<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Entities.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Fri Sep 6 2019 16:18:01 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/db6/a00074.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">Entities.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d6/db8/a00158.php">C++/Stone.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../de/d76/a00134.php">C++/Plant.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../df/d98/a00107.php">C++/Mushroom.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../dd/dad/a00005.php">C++/Ant.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Entities.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/da5/a00075.png" border="0" usemap="#Entities_8hpp" alt=""/></div>
<map name="Entities_8hpp" id="Entities_8hpp">
<area shape="rect" id="node2" href="../../d6/db8/a00158.php" title="C++/Stone.hpp" alt="" coords="523,80,634,107"/>
<area shape="rect" id="node85" href="../../de/d76/a00134.php" title="C++/Plant.hpp" alt="" coords="659,80,765,107"/>
<area shape="rect" id="node88" href="../../df/d98/a00107.php" title="C++/Mushroom.hpp" alt="" coords="789,80,928,107"/>
<area shape="rect" id="node89" href="../../dd/dad/a00005.php" title="C++/Ant.hpp" alt="" coords="953,80,1050,107"/>
<area shape="rect" id="node3" href="../../d3/d00/a00113.php" title="C++/Object.hpp" alt="" coords="585,229,700,256"/>
<area shape="rect" id="node4" href="../../d9/d2e/a00056.php" title="C++/Contraption.hpp" alt="" coords="624,379,768,405"/>
<area shape="rect" id="node5" href="../../d4/d8c/a00035.php" title="C++/C++.hpp" alt="" coords="645,453,747,480"/>
<area shape="rect" id="node6" href="../../df/d03/a00062.php" title="C++/cryptage.hpp" alt="" coords="494,528,621,555"/>
<area shape="rect" id="node83" href="../../db/dd9/a00179.php" title="C++/Tree.hpp" alt="" coords="645,528,747,555"/>
<area shape="rect" id="node84" href="../../d4/d3a/a00101.php" title="C++/Map.hpp" alt="" coords="771,528,874,555"/>
<area shape="rect" id="node7" href="../../d0/d89/a00071.php" title="C++/defines.hpp" alt="" coords="637,603,755,629"/>
<area shape="rect" id="node8" href="../../d5/de9/a00176.php" title="C++/Timer.hpp" alt="" coords="295,677,406,704"/>
<area shape="rect" id="node69" href="../../d4/dee/a00008.php" title="C++/Args.hpp" alt="" coords="431,677,535,704"/>
<area shape="rect" id="node70" href="../../da/d24/a00068.php" title="C++/DateTime.hpp" alt="" coords="505,901,639,928"/>
<area shape="rect" id="node73" href="../../d5/df9/a00044.php" title="C++/Clock.hpp" alt="" coords="610,827,721,853"/>
<area shape="rect" id="node74" href="../../dc/dee/a00053.php" title="C++/ConsoleTable.hpp" alt="" coords="676,752,833,779"/>
<area shape="rect" id="node75" href="../../da/d1e/a00149.php" title="C++/Referenced.hpp" alt="" coords="796,827,940,853"/>
<area shape="rect" id="node76" href="../../df/dc8/a00122.php" title="C++/PathfindingAlgorithms.hpp" alt="" coords="919,677,1123,704"/>
<area shape="rect" id="node82" href="../../d9/d77/a00095.php" title="C++/IOConfig.hpp" alt="" coords="1147,901,1277,928"/>
<area shape="rect" id="node9" href="../../dc/de6/a00167.php" title="C++/Threadable.hpp" alt="" coords="325,752,467,779"/>
<area shape="rect" id="node10" href="../../d1/dc1/a00092.php" title="C++/includes.hpp" alt="" coords="696,1051,821,1077"/>
<area shape="rect" id="node11" href="../../d7/d3f/a00173.php" title="C++/timeFunctions.hpp" alt="" coords="289,1125,447,1152"/>
<area shape="rect" id="node63" href="../../d4/d81/a00110.php" title="C++/NotCopyable.hpp" alt="" coords="471,1125,625,1152"/>
<area shape="rect" id="node13" href="../../d6/d7d/a00161.php" title="C++/string.hpp" alt="" coords="367,1200,476,1227"/>
<area shape="rect" id="node15" href="../../db/ddf/a00164.php" title="C++/system.hpp" alt="" coords="293,1275,413,1301"/>
<area shape="rect" id="node60" href="../../d7/d9a/a00152.php" title="C++/RNG.hpp" alt="" coords="437,1275,544,1301"/>
<area shape="rect" id="node62" href="../../d1/d44/a00098.php" title="C++/macro.hpp" alt="" coords="569,1275,682,1301"/>
<area shape="rect" id="node16" href="../../da/dec/a00080.php" title="C++/errors.hpp" alt="" coords="298,1349,409,1376"/>
<area shape="rect" id="node17" href="../../d5/de0/a00050.php" title="C++/console.hpp" alt="" coords="224,1424,347,1451"/>
<area shape="rect" id="node58" href="../../d2/d1f/a00083.php" title="C++/files.hpp" alt="" coords="371,1424,472,1451"/>
<area shape="rect" id="node18" href="../../d3/d8b/a00059.php" title="C++/convert.hpp" alt="" coords="235,1499,355,1525"/>
<area shape="rect" id="node20" href="../../da/d45/a00011.php" title="C++/array.hpp" alt="" coords="301,1573,408,1600"/>
<area shape="rect" id="node22" href="../../dd/d32/a00041.php" title="C++/check.hpp" alt="" coords="299,1648,411,1675"/>
<area shape="rect" id="node57" href="../../d3/df8/a00155.php" title="C++/sorting.hpp" alt="" coords="505,1648,621,1675"/>
<area shape="rect" id="node26" href="../../d2/de7/a00014.php" title="C++/arraysIncludes.hpp" alt="" coords="517,1723,680,1749"/>
<area shape="rect" id="node55" href="../../d6/d2d/a00047.php" title="C++/collides.hpp" alt="" coords="371,1723,493,1749"/>
<area shape="rect" id="node33" href="../../d7/dce/a00143.php" title="C++/pointers.hpp" alt="" coords="481,1872,604,1899"/>
<area shape="rect" id="node36" href="../../d7/d25/a00182.php" title="C++/types.hpp" alt="" coords="596,1947,705,1973"/>
<area shape="rect" id="node38" href="../../db/db2/a00020.php" title="Big.hpp" alt="" coords="560,2021,627,2048"/>
<area shape="rect" id="node53" href="../../d9/db6/a00146.php" title="PureVirtual.hpp" alt="" coords="651,2021,762,2048"/>
<area shape="rect" id="node54" href="../../de/df3/a00185.php" title="UsefullDefines.hpp" alt="" coords="787,2021,920,2048"/>
<area shape="rect" id="node49" href="../../d6/d5b/a00026.php" title="C++/Big_Constructor.hpp" alt="" coords="887,2096,1057,2123"/>
<area shape="rect" id="node50" href="../../dc/d87/a00032.php" title="C++/Big_Operator.hpp" alt="" coords="1082,2096,1235,2123"/>
<area shape="rect" id="node51" href="../../d3/d52/a00023.php" title="C++/Big_Comparison.hpp" alt="" coords="1260,2096,1433,2123"/>
<area shape="rect" id="node52" href="../../d5/d16/a00029.php" title="C++/Big_Maths.hpp" alt="" coords="1457,2096,1596,2123"/>
<area shape="rect" id="node56" href="../../d0/dc2/a00104.php" title="C++/maths.hpp" alt="" coords="195,1797,309,1824"/>
<area shape="rect" id="node71" href="../../de/de1/a00065.php" title="C++/Date.hpp" alt="" coords="565,976,670,1003"/>
<area shape="rect" id="node72" href="../../d5/dcb/a00170.php" title="C++/Time.hpp" alt="" coords="433,976,540,1003"/>
<area shape="rect" id="node77" href="../../dc/dfe/a00125.php" title="C++/PathfindingDijkstra.hpp" alt="" coords="939,752,1125,779"/>
<area shape="rect" id="node78" href="../../df/d6a/a00119.php" title="C++/Pathfinding.hpp" alt="" coords="965,827,1107,853"/>
<area shape="rect" id="node79" href="../../d7/d06/a00131.php" title="C++/PathfindingProblem.hpp" alt="" coords="933,901,1123,928"/>
<area shape="rect" id="node80" href="../../d1/d88/a00128.php" title="C++/PathfindingException.hpp" alt="" coords="975,976,1175,1003"/>
<area shape="rect" id="node81" href="../../d4/d3e/a00116.php" title="C++/Path.hpp" alt="" coords="847,976,951,1003"/>
<area shape="rect" id="node86" href="../../da/d15/a00188.php" title="C++/Vegetal.hpp" alt="" coords="687,155,809,181"/>
<area shape="rect" id="node87" href="../../d1/d09/a00077.php" title="C++/Entity.hpp" alt="" coords="693,304,803,331"/>
<area shape="rect" id="node90" href="../../d7/d46/a00002.php" title="C++/Animal.hpp" alt="" coords="905,155,1023,181"/>
<area shape="rect" id="node91" href="../../da/d2a/a00086.php" title="C++/Hostile.hpp" alt="" coords="845,229,963,256"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../db/df8/a00076.png" border="0" usemap="#Entities_8hppdep" alt=""/></div>
<map name="Entities_8hppdep" id="Entities_8hppdep">
<area shape="rect" id="node2" href="../../d5/db1/a00140.php" title="PlayerAbstraction.hpp" alt="" coords="5,80,156,107"/>
<area shape="rect" id="node3" href="../../d2/df5/a00137.php" title="Player.hpp" alt="" coords="39,155,123,181"/>
<area shape="rect" id="node4" href="../../d8/d41/a00038.php" title="C++Entities.hpp" alt="" coords="22,229,139,256"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:d7/ded/a00196"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/ded/a00196.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>June, 12 2018 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../db/db6/a00074.php">Entities.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
