<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: array.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Apr 28 2019 10:54:56 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d9/da5/a00075.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">array.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;stdexcept&gt;</code><br />
<code>#include &quot;<a class="el" href="../../df/d13/a00085.php">C++/check.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../da/d72/a00124.php">C++/sorting.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for array.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/db2/a00151.png" border="0" usemap="#array_8hpp" alt=""/></div>
<map name="array_8hpp" id="array_8hpp">
<area shape="rect" id="node3" href="../../df/d13/a00085.php" title="C++/check.hpp" alt="" coords="319,80,431,107"/>
<area shape="rect" id="node38" href="../../da/d72/a00124.php" title="C++/sorting.hpp" alt="" coords="469,80,585,107"/>
<area shape="rect" id="node7" href="../../db/df8/a00076.php" title="C++/arraysIncludes.hpp" alt="" coords="516,155,679,181"/>
<area shape="rect" id="node36" href="../../d1/d1e/a00087.php" title="C++/collides.hpp" alt="" coords="370,155,491,181"/>
<area shape="rect" id="node14" href="../../d4/d98/a00120.php" title="C++/pointers.hpp" alt="" coords="480,304,603,331"/>
<area shape="rect" id="node17" href="../../d0/de8/a00133.php" title="C++/types.hpp" alt="" coords="595,379,704,405"/>
<area shape="rect" id="node19" href="../../d9/da4/a00078.php" title="Big.hpp" alt="" coords="560,453,627,480"/>
<area shape="rect" id="node34" href="../../d8/dfa/a00121.php" title="PureVirtual.hpp" alt="" coords="651,453,762,480"/>
<area shape="rect" id="node35" href="../../de/d76/a00134.php" title="UsefullDefines.hpp" alt="" coords="787,453,920,480"/>
<area shape="rect" id="node30" href="../../da/dec/a00080.php" title="C++/Big_Constructor.hpp" alt="" coords="887,528,1057,555"/>
<area shape="rect" id="node31" href="../../d4/d63/a00082.php" title="C++/Big_Operator.hpp" alt="" coords="1082,528,1235,555"/>
<area shape="rect" id="node32" href="../../d1/d51/a00079.php" title="C++/Big_Comparison.hpp" alt="" coords="1260,528,1433,555"/>
<area shape="rect" id="node33" href="../../d8/d53/a00081.php" title="C++/Big_Maths.hpp" alt="" coords="1457,528,1596,555"/>
<area shape="rect" id="node37" href="../../df/d98/a00107.php" title="C++/maths.hpp" alt="" coords="194,229,307,256"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/d9a/a00152.png" border="0" usemap="#array_8hppdep" alt=""/></div>
<map name="array_8hppdep" id="array_8hppdep">
<area shape="rect" id="node2" href="../../da/d82/a00091.php" title="convert.hpp" alt="" coords="303,80,394,107"/>
<area shape="rect" id="node3" href="../../db/ddf/a00088.php" title="console.hpp" alt="" coords="251,155,343,181"/>
<area shape="rect" id="node46" href="../../da/d74/a00099.php" title="files.hpp" alt="" coords="367,155,437,181"/>
<area shape="rect" id="node4" href="../../d1/d44/a00098.php" title="errors.hpp" alt="" coords="309,229,389,256"/>
<area shape="rect" id="node5" href="../../df/dcd/a00127.php" title="system.hpp" alt="" coords="303,304,394,331"/>
<area shape="rect" id="node6" href="../../d7/d12/a00126.php" title="string.hpp" alt="" coords="309,379,388,405"/>
<area shape="rect" id="node7" href="../../d6/db3/a00130.php" title="timeFunctions.hpp" alt="" coords="284,453,413,480"/>
<area shape="rect" id="node8" href="../../d9/dcc/a00102.php" title="includes.hpp" alt="" coords="301,528,396,555"/>
<area shape="rect" id="node9" href="../../da/d2a/a00086.php" title="Clock.hpp" alt="" coords="5,752,87,779"/>
<area shape="rect" id="node30" href="../../db/dab/a00089.php" title="ConsoleTable.hpp" alt="" coords="56,677,183,704"/>
<area shape="rect" id="node31" href="../../d4/d7d/a00093.php" title="Date.hpp" alt="" coords="135,603,210,629"/>
<area shape="rect" id="node33" href="../../d5/d1e/a00103.php" title="IOConfig.hpp" alt="" coords="297,752,395,779"/>
<area shape="rect" id="node34" href="../../dd/d6d/a00111.php" title="Path.hpp" alt="" coords="386,603,461,629"/>
<area shape="rect" id="node39" href="../../d2/da3/a00115.php" title="PathfindingException.hpp" alt="" coords="485,603,655,629"/>
<area shape="rect" id="node40" href="../../df/dc8/a00122.php" title="Referenced.hpp" alt="" coords="549,827,663,853"/>
<area shape="rect" id="node41" href="../../d1/d88/a00128.php" title="Threadable.hpp" alt="" coords="688,827,799,853"/>
<area shape="rect" id="node45" href="../../d9/d47/a00129.php" title="Time.hpp" alt="" coords="235,603,311,629"/>
<area shape="rect" id="node10" href="../../d9/d77/a00095.php" title="defines.hpp" alt="" coords="401,976,491,1003"/>
<area shape="rect" id="node11" href="../../d1/dc1/a00092.php" title="cryptage.hpp" alt="" coords="288,1051,385,1077"/>
<area shape="rect" id="node28" href="../../d7/d70/a00106.php" title="Map.hpp" alt="" coords="410,1051,482,1077"/>
<area shape="rect" id="node29" href="../../d5/deb/a00132.php" title="Tree.hpp" alt="" coords="507,1051,580,1077"/>
<area shape="rect" id="node12" href="../../d2/d1f/a00083.php" title="C++.hpp" alt="" coords="409,1125,483,1152"/>
<area shape="rect" id="node13" href="../../d9/dec/a00090.php" title="Contraption.hpp" alt="" coords="342,1200,457,1227"/>
<area shape="rect" id="node27" href="../../d4/d3a/a00101.php" title="Identifier.hpp" alt="" coords="441,1573,539,1600"/>
<area shape="rect" id="node14" href="../../d1/d84/a00097.php" title="Entity.hpp" alt="" coords="232,1275,313,1301"/>
<area shape="rect" id="node25" href="../../d4/d81/a00110.php" title="Object.hpp" alt="" coords="365,1275,450,1301"/>
<area shape="rect" id="node15" href="../../d0/d61/a00100.php" title="Hostile.hpp" alt="" coords="121,1349,209,1376"/>
<area shape="rect" id="node22" href="../../d5/d5b/a00135.php" title="Vegetal.hpp" alt="" coords="227,1424,318,1451"/>
<area shape="rect" id="node16" href="../../d6/d2c/a00072.php" title="Animal.hpp" alt="" coords="105,1424,192,1451"/>
<area shape="rect" id="node17" href="../../d1/d6e/a00073.php" title="Ant.hpp" alt="" coords="105,1499,171,1525"/>
<area shape="rect" id="node18" href="../../d9/df8/a00096.php" title="Entities.hpp" alt="" coords="322,1573,413,1600"/>
<area shape="rect" id="node19" href="../../df/d6a/a00119.php" title="PlayerAbstraction.hpp" alt="" coords="296,1648,447,1675"/>
<area shape="rect" id="node20" href="../../d8/d87/a00118.php" title="Player.hpp" alt="" coords="387,1723,471,1749"/>
<area shape="rect" id="node21" href="../../df/d5d/a00084.php" title="C++Entities.hpp" alt="" coords="370,1797,487,1824"/>
<area shape="rect" id="node23" href="../../d1/dd6/a00108.php" title="Mushroom.hpp" alt="" coords="196,1499,304,1525"/>
<area shape="rect" id="node24" href="../../d9/d4b/a00117.php" title="Plant.hpp" alt="" coords="329,1499,406,1525"/>
<area shape="rect" id="node26" href="../../dc/dfe/a00125.php" title="Stone.hpp" alt="" coords="371,1349,452,1376"/>
<area shape="rect" id="node32" href="../../dc/d54/a00094.php" title="DateTime.hpp" alt="" coords="207,677,311,704"/>
<area shape="rect" id="node35" href="../../d4/d3e/a00116.php" title="PathfindingProblem.hpp" alt="" coords="395,677,555,704"/>
<area shape="rect" id="node36" href="../../db/d57/a00112.php" title="Pathfinding.hpp" alt="" coords="419,752,531,779"/>
<area shape="rect" id="node37" href="../../d8/d17/a00114.php" title="PathfindingDijkstra.hpp" alt="" coords="367,827,525,853"/>
<area shape="rect" id="node38" href="../../d3/d00/a00113.php" title="PathfindingAlgorithms.hpp" alt="" coords="359,901,533,928"/>
<area shape="rect" id="node42" href="../../db/db6/a00074.php" title="Args.hpp" alt="" coords="609,901,683,928"/>
<area shape="rect" id="node43" href="../../d1/d09/a00077.php" title="bdd.hpp" alt="" coords="708,901,776,928"/>
<area shape="rect" id="node44" href="../../d7/d06/a00131.php" title="Timer.hpp" alt="" coords="801,901,881,928"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/de8/a00061.php">mcd::stack&lt; T, Container &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">An implementation of std::stack.  <a href="../../d4/de8/a00061.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d5f/a00064.php">mcd::t_stack&lt; T, Container &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">An thread-safe implementation of stack.  <a href="../../df/d5f/a00064.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d6d/a00055.php">mcd::queue&lt; T, Container &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">An implementation of std::queue.  <a href="../../d4/d6d/a00055.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d6f/a00063.php">mcd::t_queue&lt; T, Container &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">An thread-safe implementation of queue.  <a href="../../d1/d6f/a00063.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:dd/d1b/a00015"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:ad688e3c0cf0c670ae196d83a4c6dd0d6"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:ad688e3c0cf0c670ae196d83a4c6dd0d6"><td class="memTemplItemLeft" align="right" valign="top">std::string&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#ad688e3c0cf0c670ae196d83a4c6dd0d6">mcd::implode</a> (std::vector&lt; T &gt; a, std::string glue=&quot;&quot;)</td></tr>
<tr class="memdesc:ad688e3c0cf0c670ae196d83a4c6dd0d6"><td class="mdescLeft">&#160;</td><td class="mdescRight">Stick the <em>a</em> vector with the <em>glue</em> given.  <a href="../../dd/d1b/a00015.php#ad688e3c0cf0c670ae196d83a4c6dd0d6">More...</a><br /></td></tr>
<tr class="separator:ad688e3c0cf0c670ae196d83a4c6dd0d6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a49514e6c6c7518d6207a0f707ec92529"><td class="memTemplParams" colspan="2">template&lt;typename Array &gt; </td></tr>
<tr class="memitem:a49514e6c6c7518d6207a0f707ec92529"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a49514e6c6c7518d6207a0f707ec92529">mcd::print_r</a> (Array a)</td></tr>
<tr class="memdesc:a49514e6c6c7518d6207a0f707ec92529"><td class="mdescLeft">&#160;</td><td class="mdescRight">Print the content of an array.  <a href="../../dd/d1b/a00015.php#a49514e6c6c7518d6207a0f707ec92529">More...</a><br /></td></tr>
<tr class="separator:a49514e6c6c7518d6207a0f707ec92529"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab06f1dc4b0034eb8041c40a16b70e4ca"><td class="memTemplParams" colspan="2">template&lt;typename V &gt; </td></tr>
<tr class="memitem:ab06f1dc4b0034eb8041c40a16b70e4ca"><td class="memTemplItemLeft" align="right" valign="top">std::vector&lt; V &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#ab06f1dc4b0034eb8041c40a16b70e4ca">mcd::rewrite</a> (std::vector&lt; V &gt; table, unsigned index)</td></tr>
<tr class="memdesc:ab06f1dc4b0034eb8041c40a16b70e4ca"><td class="mdescLeft">&#160;</td><td class="mdescRight">Rewrite a vector array without the value at the given index.  <a href="../../dd/d1b/a00015.php#ab06f1dc4b0034eb8041c40a16b70e4ca">More...</a><br /></td></tr>
<tr class="separator:ab06f1dc4b0034eb8041c40a16b70e4ca"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3ac7c03f689e82ab37f28905b06cedbd"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:a3ac7c03f689e82ab37f28905b06cedbd"><td class="memTemplItemLeft" align="right" valign="top">bool&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a3ac7c03f689e82ab37f28905b06cedbd">mcd::contains</a> (std::vector&lt; T &gt; table, T value)</td></tr>
<tr class="memdesc:a3ac7c03f689e82ab37f28905b06cedbd"><td class="mdescLeft">&#160;</td><td class="mdescRight">Verify if a vector contains or not something.  <a href="../../dd/d1b/a00015.php#a3ac7c03f689e82ab37f28905b06cedbd">More...</a><br /></td></tr>
<tr class="separator:a3ac7c03f689e82ab37f28905b06cedbd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a95b30a0f37ef4accc8c762eee75bcc12"><td class="memTemplParams" colspan="2">template&lt;typename Something &gt; </td></tr>
<tr class="memitem:a95b30a0f37ef4accc8c762eee75bcc12"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a95b30a0f37ef4accc8c762eee75bcc12">mcd::print_all</a> (Something data, bool change=false)</td></tr>
<tr class="memdesc:a95b30a0f37ef4accc8c762eee75bcc12"><td class="mdescLeft">&#160;</td><td class="mdescRight">Prints approximately everything.  <a href="../../dd/d1b/a00015.php#a95b30a0f37ef4accc8c762eee75bcc12">More...</a><br /></td></tr>
<tr class="separator:a95b30a0f37ef4accc8c762eee75bcc12"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2e20a60d52caf65d9d57c170efc7d56a"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a2e20a60d52caf65d9d57c170efc7d56a"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a2e20a60d52caf65d9d57c170efc7d56a">mcd::operator+=</a> (std::vector&lt; T &gt; &amp;a, const std::vector&lt; T &gt; &amp;b)</td></tr>
<tr class="separator:a2e20a60d52caf65d9d57c170efc7d56a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aea330903a85d1247751d666e798ead28"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:aea330903a85d1247751d666e798ead28"><td class="memTemplItemLeft" align="right" valign="top">std::vector&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#aea330903a85d1247751d666e798ead28">mcd::operator+</a> (const std::vector&lt; T &gt; &amp;a, const std::vector&lt; T &gt; &amp;b)</td></tr>
<tr class="separator:aea330903a85d1247751d666e798ead28"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a50233faf9e0e108078af975455fad0b9"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a50233faf9e0e108078af975455fad0b9"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a50233faf9e0e108078af975455fad0b9">mcd::operator-=</a> (std::vector&lt; T &gt; &amp;a, const std::vector&lt; T &gt; &amp;b)</td></tr>
<tr class="separator:a50233faf9e0e108078af975455fad0b9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a643c3473b3bce61f2ac50e63b8003994"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a643c3473b3bce61f2ac50e63b8003994"><td class="memTemplItemLeft" align="right" valign="top">std::vector&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a643c3473b3bce61f2ac50e63b8003994">mcd::operator-</a> (const std::vector&lt; T &gt; &amp;a, const std::vector&lt; T &gt; &amp;b)</td></tr>
<tr class="separator:a643c3473b3bce61f2ac50e63b8003994"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2e6ec1508e48530c9ea83c090cfe9ea1"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a2e6ec1508e48530c9ea83c090cfe9ea1"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a2e6ec1508e48530c9ea83c090cfe9ea1">mcd::operator%=</a> (std::vector&lt; T &gt; &amp;a, const std::vector&lt; T &gt; &amp;b)</td></tr>
<tr class="separator:a2e6ec1508e48530c9ea83c090cfe9ea1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ade36d3312ff7c93578e529d00411c67a"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:ade36d3312ff7c93578e529d00411c67a"><td class="memTemplItemLeft" align="right" valign="top">std::vector&lt; T &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#ade36d3312ff7c93578e529d00411c67a">mcd::operator%</a> (const std::vector&lt; T &gt; &amp;a, const std::vector&lt; T &gt; &amp;b)</td></tr>
<tr class="separator:ade36d3312ff7c93578e529d00411c67a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aad6be0710fa6c480619505eae0afd547"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:aad6be0710fa6c480619505eae0afd547"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#aad6be0710fa6c480619505eae0afd547">mcd::pop</a> (std::vector&lt; T &gt; &amp;a, size_t pos=0)</td></tr>
<tr class="separator:aad6be0710fa6c480619505eae0afd547"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af1c42a8b9412d2afa3b486c5e629f752"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#af1c42a8b9412d2afa3b486c5e629f752">mcd::array2Dto1D</a> (size_t x, size_t y, size_t maxX)</td></tr>
<tr class="separator:af1c42a8b9412d2afa3b486c5e629f752"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a040a2aa0625adc9f13e6568d906a20a2"><td class="memItemLeft" align="right" valign="top">std::pair&lt; size_t, size_t &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a040a2aa0625adc9f13e6568d906a20a2">mcd::array1Dto2D</a> (size_t index, size_t maxX)</td></tr>
<tr class="separator:a040a2aa0625adc9f13e6568d906a20a2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2539eedc8c5dcf1f8f7801eeb919de42"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a2539eedc8c5dcf1f8f7801eeb919de42">mcd::array2Dto1D</a> (Point pt, size_t maxX)</td></tr>
<tr class="separator:a2539eedc8c5dcf1f8f7801eeb919de42"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : April, 24 2019 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d9/da5/a00075.php">array.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
