#!/bin/bash

function core {
	files=`grep -Enir "(\(.*)std::string (.*\)(;|\{| *)$)" | tr -s ' ' | cut -d ':' -f 1 | sort -u`

	for file in $files
	do
		lines=`grep -Enir "(\(.*)std::string (.*\)(;|\{| *)$)" | grep "$file" | tr -s ' ' | cut -d ':' -f 3-`

		grep -Enir "(\(.*)std::string (.*\)(;|\{| *)$)" | grep "$file" | tr -s ' ' | tr -d '\t' | cut -d ':' -f 3- | while IFS="" read -r line
		do
			sed -i "s/\((.*\)\(const \)?std::string \(.*)\({\|;\| *\)\)/\1const std::string\& \3/g" $file
		done
	done
}

cd src

core src

cd ..
cd inc

core inc

cd ..

exit 0
