<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: lowDefines.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.1.1</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Fri Nov 13 2020 12:37:29 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('d7/d06/a00131.php','../../'); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#define-members">Macros</a>  </div>
  <div class="headertitle">
<div class="title">lowDefines.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d5/de9/a00176.php">OsDetection.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for lowDefines.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/deb/a00132.png" border="0" usemap="#alowDefines_8hpp" alt=""/></div>
<map name="lowDefines_8hpp" id="lowDefines_8hpp">
<area shape="rect" title=" " alt="" coords="377,5,489,32"/>
<area shape="rect" href="../../d5/de9/a00176.php" title=" " alt="" coords="373,80,493,107"/>
<area shape="rect" title=" " alt="" coords="342,155,410,181"/>
<area shape="rect" href="../../de/d76/a00134.php" title=" " alt="" coords="434,155,550,181"/>
<area shape="rect" title=" " alt="" coords="5,229,80,256"/>
<area shape="rect" title=" " alt="" coords="104,229,163,256"/>
<area shape="rect" title=" " alt="" coords="187,229,266,256"/>
<area shape="rect" title=" " alt="" coords="291,229,363,256"/>
<area shape="rect" title=" " alt="" coords="387,229,434,256"/>
<area shape="rect" title=" " alt="" coords="458,229,526,256"/>
<area shape="rect" title=" " alt="" coords="550,229,605,256"/>
<area shape="rect" title=" " alt="" coords="629,229,699,256"/>
<area shape="rect" title=" " alt="" coords="723,229,778,256"/>
<area shape="rect" title=" " alt="" coords="803,229,856,256"/>
<area shape="rect" title=" " alt="" coords="880,229,939,256"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d0/de8/a00133.png" border="0" usemap="#alowDefines_8hppdep" alt=""/></div>
<map name="lowDefines_8hppdep" id="lowDefines_8hppdep">
<area shape="rect" title=" " alt="" coords="330,5,442,32"/>
<area shape="rect" href="../../d3/d52/a00023.php" title=" " alt="" coords="306,80,373,107"/>
<area shape="rect" href="../../dd/dd7/a00248.php" title=" " alt="" coords="397,80,471,107"/>
<area shape="rect" href="../../d3/d1a/a00251.php" title=" " alt="" coords="347,155,425,181"/>
<area shape="rect" href="../../d5/df1/a00206.php" title=" " alt="" coords="339,229,433,256"/>
<area shape="rect" href="../../d2/de7/a00014.php" title=" " alt="" coords="255,304,387,331"/>
<area shape="rect" href="../../d8/d41/a00038.php" title=" " alt="" coords="411,304,494,331"/>
<area shape="rect" href="../../d9/d39/a00257.php" title=" " alt="" coords="279,603,362,629"/>
<area shape="rect" href="../../dc/dee/a00053.php" title=" " alt="" coords="389,677,471,704"/>
<area shape="rect" href="../../dc/d9a/a00218.php" title=" " alt="" coords="277,677,364,704"/>
<area shape="rect" href="../../da/d45/a00011.php" title=" " alt="" coords="338,752,413,779"/>
<area shape="rect" href="../../db/db6/a00074.php" title=" " alt="" coords="330,827,421,853"/>
<area shape="rect" href="../../de/de1/a00065.php" title=" " alt="" coords="277,901,369,928"/>
<area shape="rect" href="../../d4/d3a/a00101.php" title=" " alt="" coords="393,901,464,928"/>
<area shape="rect" href="../../d9/d77/a00095.php" title=" " alt="" coords="335,976,415,1003"/>
<area shape="rect" href="../../d1/da8/a00230.php" title=" " alt="" coords="330,1051,421,1077"/>
<area shape="rect" href="../../d5/ddf/a00224.php" title=" " alt="" coords="336,1125,415,1152"/>
<area shape="rect" href="../../d9/d01/a00227.php" title="Used to replace strptime function when compiling for Windows." alt="" coords="335,1200,415,1227"/>
<area shape="rect" href="../../d2/dc8/a00242.php" title=" " alt="" coords="311,1275,440,1301"/>
<area shape="rect" href="../../d4/d3e/a00116.php" title=" " alt="" coords="328,1349,423,1376"/>
<area shape="rect" href="../../d3/d8b/a00059.php" title=" " alt="" coords="5,1573,87,1600"/>
<area shape="rect" href="../../da/d24/a00068.php" title=" " alt="" coords="120,1648,247,1675"/>
<area shape="rect" href="../../da/dec/a00080.php" title=" " alt="" coords="162,1424,237,1451"/>
<area shape="rect" href="../../df/d6a/a00119.php" title=" " alt="" coords="318,1499,417,1525"/>
<area shape="rect" href="../../db/dd9/a00179.php" title=" " alt="" coords="413,1424,487,1451"/>
<area shape="rect" href="../../d9/dd0/a00191.php" title=" " alt="" coords="511,1424,682,1451"/>
<area shape="rect" href="../../dd/dc1/a00212.php" title=" " alt="" coords="586,1573,701,1600"/>
<area shape="rect" href="../../d7/d40/a00236.php" title=" " alt="" coords="715,1723,825,1749"/>
<area shape="rect" href="../../d0/d27/a00239.php" title=" " alt="" coords="261,1424,337,1451"/>
<area shape="rect" href="../../da/d2a/a00086.php" title=" " alt="" coords="369,1872,459,1899"/>
<area shape="rect" href="../../db/db2/a00020.php" title=" " alt="" coords="217,1947,377,1973"/>
<area shape="rect" href="../../d1/d09/a00077.php" title=" " alt="" coords="364,2021,461,2048"/>
<area shape="rect" href="../../dc/dfe/a00125.php" title=" " alt="" coords="454,1947,587,1973"/>
<area shape="rect" href="../../d4/d51/a00017.php" title=" " alt="" coords="254,2021,339,2048"/>
<area shape="rect" href="../../d6/d2d/a00047.php" title=" " alt="" coords="369,2096,456,2123"/>
<area shape="rect" href="../../df/d98/a00107.php" title=" " alt="" coords="271,2171,349,2197"/>
<area shape="rect" href="../../d1/d88/a00128.php" title=" " alt="" coords="370,2245,455,2272"/>
<area shape="rect" href="../../d6/de1/a00233.php" title=" " alt="" coords="453,2320,525,2347"/>
<area shape="rect" href="../../d9/d2e/a00056.php" title=" " alt="" coords="221,2245,346,2272"/>
<area shape="rect" href="../../d5/de0/a00050.php" title=" " alt="" coords="276,2320,347,2347"/>
<area shape="rect" href="../../dd/d32/a00041.php" title=" " alt="" coords="376,2395,449,2421"/>
<area shape="rect" href="../../d0/d89/a00071.php" title=" " alt="" coords="309,2469,423,2496"/>
<area shape="rect" href="../../d3/d00/a00113.php" title=" " alt="" coords="407,2843,503,2869"/>
<area shape="rect" href="../../d1/dc1/a00092.php" title=" " alt="" coords="215,2544,293,2571"/>
<area shape="rect" href="../../d7/d3f/a00173.php" title=" " alt="" coords="331,2544,417,2571"/>
<area shape="rect" href="../../d4/d81/a00110.php" title=" " alt="" coords="99,2619,187,2645"/>
<area shape="rect" href="../../dd/dd7/a00260.php" title=" " alt="" coords="209,2693,299,2720"/>
<area shape="rect" href="../../d7/d46/a00002.php" title=" " alt="" coords="69,2693,156,2720"/>
<area shape="rect" href="../../dd/dad/a00005.php" title=" " alt="" coords="71,2768,138,2795"/>
<area shape="rect" href="../../db/dab/a00089.php" title=" " alt="" coords="289,2843,379,2869"/>
<area shape="rect" href="../../de/d79/a00203.php" title=" " alt="" coords="260,2917,411,2944"/>
<area shape="rect" href="../../d3/db1/a00200.php" title=" " alt="" coords="350,2992,433,3019"/>
<area shape="rect" href="../../d5/df9/a00044.php" title=" " alt="" coords="333,3067,450,3093"/>
<area shape="rect" href="../../db/ddf/a00164.php" title=" " alt="" coords="163,2768,271,2795"/>
<area shape="rect" href="../../de/db1/a00197.php" title=" " alt="" coords="295,2768,373,2795"/>
<area shape="rect" href="../../dd/d52/a00221.php" title=" " alt="" coords="341,2619,423,2645"/>
<area shape="rect" href="../../df/dc8/a00122.php" title=" " alt="" coords="486,2021,561,2048"/>
<area shape="rect" href="../../d2/d1f/a00083.php" title=" " alt="" coords="190,1499,294,1525"/>
<area shape="rect" href="../../dc/d57/a00194.php" title=" " alt="" coords="441,1499,601,1525"/>
<area shape="rect" href="../../d7/d25/a00182.php" title=" " alt="" coords="442,1573,554,1600"/>
<area shape="rect" href="../../da/d15/a00188.php" title=" " alt="" coords="403,1648,561,1675"/>
<area shape="rect" href="../../de/df3/a00185.php" title=" " alt="" coords="389,1723,564,1749"/>
<area shape="rect" href="../../d5/db1/a00140.php" title=" " alt="" coords="415,1797,487,1824"/>
<area shape="rect" href="../../d4/dee/a00008.php" title=" " alt="" coords="639,1797,714,1824"/>
<area shape="rect" href="../../d6/d22/a00245.php" title=" " alt="" coords="739,1797,817,1824"/>
<area shape="rect" href="../../d7/dce/a00143.php" title=" " alt="" coords="411,379,494,405"/>
<area shape="rect" href="../../d0/dc2/a00104.php" title=" " alt="" coords="372,453,467,480"/>
<area shape="rect" href="../../d6/d7d/a00161.php" title=" " alt="" coords="491,453,633,480"/>
<area shape="rect" href="../../d9/db6/a00146.php" title=" " alt="" coords="390,528,473,555"/>
<area shape="rect" href="../../df/d03/a00062.php" title=" " alt="" coords="386,603,477,629"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:db/d12/a00268"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="define-members"></a>
Macros</h2></td></tr>
<tr class="memitem:a983517eb99d86ddbcbe73c34d18fdeb5"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d06/a00131.php#a983517eb99d86ddbcbe73c34d18fdeb5">AUTO_OPERATOR_GREATER</a>(Type)</td></tr>
<tr class="memdesc:a983517eb99d86ddbcbe73c34d18fdeb5"><td class="mdescLeft">&#160;</td><td class="mdescRight">A define to add operator &gt; using == and &lt;.  <a href="../../d7/d06/a00131.php#a983517eb99d86ddbcbe73c34d18fdeb5">More...</a><br /></td></tr>
<tr class="separator:a983517eb99d86ddbcbe73c34d18fdeb5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaf14a4c6705e04e70fe68fe38ea04aec"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d06/a00131.php#aaf14a4c6705e04e70fe68fe38ea04aec">AUTO_OPERATOR_GREATER_EQ</a>(Type)&#160;&#160;&#160;    friend inline bool operator&gt;=(const Type&amp; a, const Type&amp; b) noexcept { return !(a &lt; b); }</td></tr>
<tr class="memdesc:aaf14a4c6705e04e70fe68fe38ea04aec"><td class="mdescLeft">&#160;</td><td class="mdescRight">A define to add operator &gt;= using &lt;.  <a href="../../d7/d06/a00131.php#aaf14a4c6705e04e70fe68fe38ea04aec">More...</a><br /></td></tr>
<tr class="separator:aaf14a4c6705e04e70fe68fe38ea04aec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adcad71ce3a6972ceafd30f790ee5a332"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d06/a00131.php#adcad71ce3a6972ceafd30f790ee5a332">AUTO_OPERATOR_LESS_EQ</a>(Type)&#160;&#160;&#160;    friend inline bool operator&lt;=(const Type&amp; a, const Type&amp; b) noexcept { return a == b || a &lt; b; }</td></tr>
<tr class="memdesc:adcad71ce3a6972ceafd30f790ee5a332"><td class="mdescLeft">&#160;</td><td class="mdescRight">A define to add operator &lt;= using == and &lt;.  <a href="../../d7/d06/a00131.php#adcad71ce3a6972ceafd30f790ee5a332">More...</a><br /></td></tr>
<tr class="separator:adcad71ce3a6972ceafd30f790ee5a332"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acdc796107ba68a6a3ce4567f35e7b57e"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d06/a00131.php#acdc796107ba68a6a3ce4567f35e7b57e">AUTO_OPERATOR_DIFF</a>(Type)&#160;&#160;&#160;    friend inline bool operator!=(const Type&amp; a, const Type&amp; b) noexcept { return !(a == b); }</td></tr>
<tr class="memdesc:acdc796107ba68a6a3ce4567f35e7b57e"><td class="mdescLeft">&#160;</td><td class="mdescRight">A define to add operator != using ==.  <a href="../../d7/d06/a00131.php#acdc796107ba68a6a3ce4567f35e7b57e">More...</a><br /></td></tr>
<tr class="separator:acdc796107ba68a6a3ce4567f35e7b57e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abe33bfc662fbc270e952c288fd8a7991"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d06/a00131.php#abe33bfc662fbc270e952c288fd8a7991">AUTO_OPERATORS</a>(Type)</td></tr>
<tr class="memdesc:abe33bfc662fbc270e952c288fd8a7991"><td class="mdescLeft">&#160;</td><td class="mdescRight">A define to add operators &lt;=, &gt;, &gt;=, and != when == and &lt; are defined.  <a href="../../d7/d06/a00131.php#abe33bfc662fbc270e952c288fd8a7991">More...</a><br /></td></tr>
<tr class="separator:abe33bfc662fbc270e952c288fd8a7991"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8002d97e9fbabb78da501b4b5a9d188a"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d06/a00131.php#a8002d97e9fbabb78da501b4b5a9d188a">try_catch</a>(Instruction,  Exception)</td></tr>
<tr class="separator:a8002d97e9fbabb78da501b4b5a9d188a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adf3d20aa957d03b79d774e80ab0507ed"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/d06/a00131.php#adf3d20aa957d03b79d774e80ab0507ed">GENERATE_ITERATORS</a>(ArrayType,  ArrayMember)</td></tr>
<tr class="memdesc:adf3d20aa957d03b79d774e80ab0507ed"><td class="mdescLeft">&#160;</td><td class="mdescRight">A define to generate begin, cebgin, end, and cend iterators.  <a href="../../d7/d06/a00131.php#adf3d20aa957d03b79d774e80ab0507ed">More...</a><br /></td></tr>
<tr class="separator:adf3d20aa957d03b79d774e80ab0507ed"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Created : Sunday October, 25 2020 18:40:52 </dd>
<dd>
Last modification : November, 01 2020 </dd></dl>
</div><h2 class="groupheader">Macro Definition Documentation</h2>
<a id="acdc796107ba68a6a3ce4567f35e7b57e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acdc796107ba68a6a3ce4567f35e7b57e">&#9670;&nbsp;</a></span>AUTO_OPERATOR_DIFF</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define AUTO_OPERATOR_DIFF</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname">Type</td><td>)</td>
          <td>&#160;&#160;&#160;    friend inline bool operator!=(const Type&amp; a, const Type&amp; b) noexcept { return !(a == b); }</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>A define to add operator != using ==. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">Type</td><td>The type of the object to test </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a983517eb99d86ddbcbe73c34d18fdeb5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a983517eb99d86ddbcbe73c34d18fdeb5">&#9670;&nbsp;</a></span>AUTO_OPERATOR_GREATER</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define AUTO_OPERATOR_GREATER</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname">Type</td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Value:</b><div class="fragment"><div class="line">    <span class="keyword">friend</span> <span class="keyword">inline</span> <span class="keywordtype">bool</span> <a class="code" href="../../db/d12/a00268.php#ae8c157fea2d3cba9a23a3ff2878cc08e">operator&gt;</a>(<span class="keyword">const</span> Type&amp; a, <span class="keyword">const</span> Type&amp; b) noexcept {                          \</div>
<div class="line">        return !(a &lt; b) &amp;&amp; !(a == b);                                                              \</div>
<div class="line">    }</div>
</div><!-- fragment -->
<p>A define to add operator &gt; using == and &lt;. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">Type</td><td>The type of the object to test </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="aaf14a4c6705e04e70fe68fe38ea04aec"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aaf14a4c6705e04e70fe68fe38ea04aec">&#9670;&nbsp;</a></span>AUTO_OPERATOR_GREATER_EQ</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define AUTO_OPERATOR_GREATER_EQ</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname">Type</td><td>)</td>
          <td>&#160;&#160;&#160;    friend inline bool operator&gt;=(const Type&amp; a, const Type&amp; b) noexcept { return !(a &lt; b); }</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>A define to add operator &gt;= using &lt;. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">Type</td><td>The type of the object to test </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="adcad71ce3a6972ceafd30f790ee5a332"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adcad71ce3a6972ceafd30f790ee5a332">&#9670;&nbsp;</a></span>AUTO_OPERATOR_LESS_EQ</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define AUTO_OPERATOR_LESS_EQ</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname">Type</td><td>)</td>
          <td>&#160;&#160;&#160;    friend inline bool operator&lt;=(const Type&amp; a, const Type&amp; b) noexcept { return a == b || a &lt; b; }</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>A define to add operator &lt;= using == and &lt;. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">Type</td><td>The type of the object to test </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="abe33bfc662fbc270e952c288fd8a7991"></a>
<h2 class="memtitle"><span class="permalink"><a href="#abe33bfc662fbc270e952c288fd8a7991">&#9670;&nbsp;</a></span>AUTO_OPERATORS</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define AUTO_OPERATORS</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname">Type</td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Value:</b><div class="fragment"><div class="line">    <a class="code" href="../../d7/d06/a00131.php#a983517eb99d86ddbcbe73c34d18fdeb5">AUTO_OPERATOR_GREATER</a>(Type)                                                                    \</div>
<div class="line">    AUTO_OPERATOR_GREATER_EQ(Type)                                                                 \</div>
<div class="line">    AUTO_OPERATOR_LESS_EQ(Type)                                                                    \</div>
<div class="line">    AUTO_OPERATOR_DIFF(Type)</div>
</div><!-- fragment -->
<p>A define to add operators &lt;=, &gt;, &gt;=, and != when == and &lt; are defined. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">Type</td><td>The type of the object to test </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="adf3d20aa957d03b79d774e80ab0507ed"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adf3d20aa957d03b79d774e80ab0507ed">&#9670;&nbsp;</a></span>GENERATE_ITERATORS</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define GENERATE_ITERATORS</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname">ArrayType, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname">ArrayMember&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Value:</b><div class="fragment"><div class="line">    <span class="keyword">typename</span> ArrayType::iterator       begin() { <span class="keywordflow">return</span> ArrayMember.begin(); }                     \</div>
<div class="line">    typename ArrayType::const_iterator begin()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> ArrayMember.begin(); }               \</div>
<div class="line">    typename ArrayType::const_iterator cbegin()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> begin(); }                          \</div>
<div class="line">                                                                                                   \</div>
<div class="line">    typename ArrayType::iterator       end() { <span class="keywordflow">return</span> ArrayMember.end(); }                         \</div>
<div class="line">    typename ArrayType::const_iterator end()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> ArrayMember.end(); }                   \</div>
<div class="line">    typename ArrayType::const_iterator cend()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> end(); }</div>
</div><!-- fragment -->
<p>A define to generate begin, cebgin, end, and cend iterators. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">ArrayType</td><td>The type of the array to create iterators for </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">ArrayMember</td><td>The name of the member variable to create iterators for </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a8002d97e9fbabb78da501b4b5a9d188a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8002d97e9fbabb78da501b4b5a9d188a">&#9670;&nbsp;</a></span>try_catch</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define try_catch</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname">Instruction, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname">Exception&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Value:</b><div class="fragment"><div class="line">    <span class="keywordflow">try</span> {                                                                                          \</div>
<div class="line">        Instruction;                                                                               \</div>
<div class="line">    } <span class="keywordflow">catch</span> (<span class="keyword">const</span> Exception&amp; exception) { exception.what(); }</div>
</div><!-- fragment -->
</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<div class="ttc" id="aa00131_php_a983517eb99d86ddbcbe73c34d18fdeb5"><div class="ttname"><a href="../../d7/d06/a00131.php#a983517eb99d86ddbcbe73c34d18fdeb5">AUTO_OPERATOR_GREATER</a></div><div class="ttdeci">#define AUTO_OPERATOR_GREATER(Type)</div><div class="ttdoc">A define to add operator &gt; using == and &lt;.</div><div class="ttdef"><b>Definition:</b> lowDefines.hpp:20</div></div>
<div class="ttc" id="aa00268_php_ae8c157fea2d3cba9a23a3ff2878cc08e"><div class="ttname"><a href="../../db/d12/a00268.php#ae8c157fea2d3cba9a23a3ff2878cc08e">mcd::operator&gt;</a></div><div class="ttdeci">bool operator&gt;(const trio&lt; T, U, V &gt; &amp;a, const trio&lt; T, U, V &gt; &amp;b)</div><div class="ttdef"><b>Definition:</b> types.hpp:46</div></div>
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../dir_220287e732b97f08f66e5f221c69df74.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_75b0389167f46f79a101ef8c4434cec4.php">C++</a></li><li class="navelem"><a class="el" href="../../d7/d06/a00131.php">lowDefines.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
