<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: mcd::Player&lt; PlayerParent &gt; Class Template Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Apr 28 2019 10:55:03 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d2/d79/a00051.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="../../df/df1/a00340.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">mcd::Player&lt; PlayerParent &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A player that can be a child from any class.  
 <a href="../../d2/d79/a00051.php#details">More...</a></p>

<p><code>#include &lt;Player.hpp&gt;</code></p>
<div class="dynheader">
Inheritance diagram for mcd::Player&lt; PlayerParent &gt;:</div>
<div class="dyncontent">
<div class="center"><img src="../../d3/d93/a00341.png" border="0" usemap="#mcd_1_1Player_3_01PlayerParent_01_4_inherit__map" alt="Inheritance graph"/></div>
<map name="mcd_1_1Player_3_01PlayerParent_01_4_inherit__map" id="mcd_1_1Player_3_01PlayerParent_01_4_inherit__map">
<area shape="rect" id="node2" href="../../d1/d84/a00052.php" title="A player that can be a child from any class. " alt="" coords="5,80,164,121"/>
<area shape="rect" id="node4" href="../../dc/de2/a00024.php" title="A class to store some identify datas. " alt="" coords="188,87,293,114"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for mcd::Player&lt; PlayerParent &gt;:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/d45/a00342.png" border="0" usemap="#mcd_1_1Player_3_01PlayerParent_01_4_coll__map" alt="Collaboration graph"/></div>
<map name="mcd_1_1Player_3_01PlayerParent_01_4_coll__map" id="mcd_1_1Player_3_01PlayerParent_01_4_coll__map">
<area shape="rect" id="node2" href="../../d1/d84/a00052.php" title="A player that can be a child from any class. " alt="" coords="5,200,164,241"/>
<area shape="rect" id="node4" title="STL class. " alt="" coords="179,96,259,123"/>
<area shape="rect" id="node6" href="../../dc/de2/a00024.php" title="A class to store some identify datas. " alt="" coords="188,207,293,234"/>
<area shape="rect" id="node5" title="STL class. " alt="" coords="156,5,283,47"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aa2e12089a072fbc695087df2b474af5c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#aa2e12089a072fbc695087df2b474af5c">Player</a> (<a class="el" href="../../d3/de7/a00039.php">Map</a> *map=nullptr, <a class="el" href="../../dc/dee/a00053.php">Point</a> pt={0, 0, 0}, <a class="el" href="../../dd/d1b/a00015.php#d4/ddd/a00138">ContraptionAttr</a> attr={0, 0, 0})</td></tr>
<tr class="memdesc:aa2e12089a072fbc695087df2b474af5c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructor of the class.  <a href="#aa2e12089a072fbc695087df2b474af5c">More...</a><br /></td></tr>
<tr class="separator:aa2e12089a072fbc695087df2b474af5c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a73fba351baf5641e985c76c0de4fe097"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#a73fba351baf5641e985c76c0de4fe097">~Player</a> ()</td></tr>
<tr class="memdesc:a73fba351baf5641e985c76c0de4fe097"><td class="mdescLeft">&#160;</td><td class="mdescRight">Virtual destructor.  <a href="#a73fba351baf5641e985c76c0de4fe097">More...</a><br /></td></tr>
<tr class="separator:a73fba351baf5641e985c76c0de4fe097"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae0258dbfcdecaaa58390125aac118fe8"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#ae0258dbfcdecaaa58390125aac118fe8">printInfos</a> (std::ostream &amp;stream) const override</td></tr>
<tr class="memdesc:ae0258dbfcdecaaa58390125aac118fe8"><td class="mdescLeft">&#160;</td><td class="mdescRight">Print the infos in the instance of the class in <em>stream</em>.  <a href="#ae0258dbfcdecaaa58390125aac118fe8">More...</a><br /></td></tr>
<tr class="separator:ae0258dbfcdecaaa58390125aac118fe8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00052"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00052')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../d1/d84/a00052.php">mcd::PlayerAbstraction&lt; PlayerParent &gt;</a></td></tr>
<tr class="memitem:acd7472274e5fd10845893208d604617f inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#acd7472274e5fd10845893208d604617f">PlayerAbstraction</a> (<a class="el" href="../../d3/de7/a00039.php">Map</a> *map=nullptr, <a class="el" href="../../dc/dee/a00053.php">Point</a> pt={0, 0, 0}, <a class="el" href="../../dd/d1b/a00015.php#d4/ddd/a00138">ContraptionAttr</a> attr={0, 0, 0})</td></tr>
<tr class="memdesc:acd7472274e5fd10845893208d604617f inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructor of the class.  <a href="#acd7472274e5fd10845893208d604617f">More...</a><br /></td></tr>
<tr class="separator:acd7472274e5fd10845893208d604617f inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abde0c45c79e9cb030711f77d73fdc5a8 inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#abde0c45c79e9cb030711f77d73fdc5a8">~PlayerAbstraction</a> ()</td></tr>
<tr class="memdesc:abde0c45c79e9cb030711f77d73fdc5a8 inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Virtual destructor.  <a href="#abde0c45c79e9cb030711f77d73fdc5a8">More...</a><br /></td></tr>
<tr class="separator:abde0c45c79e9cb030711f77d73fdc5a8 inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a42c70de66bff8acacb5f3fe9b1d68b66 inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a42c70de66bff8acacb5f3fe9b1d68b66">setMail</a> (const std::string mail)</td></tr>
<tr class="memdesc:a42c70de66bff8acacb5f3fe9b1d68b66 inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the <a class="el" href="../../d2/d79/a00051.php" title="A player that can be a child from any class. ">Player</a>'smail.  <a href="#a42c70de66bff8acacb5f3fe9b1d68b66">More...</a><br /></td></tr>
<tr class="separator:a42c70de66bff8acacb5f3fe9b1d68b66 inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afd43768fd6e0cef44f01eda62c12709d inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#afd43768fd6e0cef44f01eda62c12709d">setExperience</a> (const <a class="el" href="../../dd/d1b/a00015.php#adda27badcbfcfc854854c6ab094cf34e">double64_t</a> experience)</td></tr>
<tr class="memdesc:afd43768fd6e0cef44f01eda62c12709d inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the <a class="el" href="../../d2/d79/a00051.php" title="A player that can be a child from any class. ">Player</a>'s experience.  <a href="#afd43768fd6e0cef44f01eda62c12709d">More...</a><br /></td></tr>
<tr class="separator:afd43768fd6e0cef44f01eda62c12709d inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a359eee2f7927489351f40177a5da91fe inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a359eee2f7927489351f40177a5da91fe">setExperienceMax</a> (const <a class="el" href="../../dd/d1b/a00015.php#adda27badcbfcfc854854c6ab094cf34e">double64_t</a> experienceMax)</td></tr>
<tr class="memdesc:a359eee2f7927489351f40177a5da91fe inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the <a class="el" href="../../d2/d79/a00051.php" title="A player that can be a child from any class. ">Player</a>'s max experience.  <a href="#a359eee2f7927489351f40177a5da91fe">More...</a><br /></td></tr>
<tr class="separator:a359eee2f7927489351f40177a5da91fe inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab5589f9ae6f9afe7494033ec6eaf4209 inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#ab5589f9ae6f9afe7494033ec6eaf4209">getMail</a> () const </td></tr>
<tr class="separator:ab5589f9ae6f9afe7494033ec6eaf4209 inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afe9cdb253793b68847989ece8d32dbbe inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../dd/d1b/a00015.php#adda27badcbfcfc854854c6ab094cf34e">double64_t</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#afe9cdb253793b68847989ece8d32dbbe">getExperience</a> () const </td></tr>
<tr class="separator:afe9cdb253793b68847989ece8d32dbbe inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a34efa55330f4178da4512e28545c0f50 inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../dd/d1b/a00015.php#adda27badcbfcfc854854c6ab094cf34e">double64_t</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a34efa55330f4178da4512e28545c0f50">getExperienceMax</a> () const </td></tr>
<tr class="separator:a34efa55330f4178da4512e28545c0f50 inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a57f10ce6fa33a36671c750dd68dc1a13 inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a57f10ce6fa33a36671c750dd68dc1a13">pause</a> ()</td></tr>
<tr class="memdesc:a57f10ce6fa33a36671c750dd68dc1a13 inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Pause the player.  <a href="#a57f10ce6fa33a36671c750dd68dc1a13">More...</a><br /></td></tr>
<tr class="separator:a57f10ce6fa33a36671c750dd68dc1a13 inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4670bc4130ffbdd8fd198ab020a7ffe3 inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a4670bc4130ffbdd8fd198ab020a7ffe3">resume</a> ()</td></tr>
<tr class="memdesc:a4670bc4130ffbdd8fd198ab020a7ffe3 inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Resume the player.  <a href="#a4670bc4130ffbdd8fd198ab020a7ffe3">More...</a><br /></td></tr>
<tr class="separator:a4670bc4130ffbdd8fd198ab020a7ffe3 inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a548c47ffd2ac76ffe19f6f7f25b941a8 inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a548c47ffd2ac76ffe19f6f7f25b941a8">isPaused</a> () const </td></tr>
<tr class="memdesc:a548c47ffd2ac76ffe19f6f7f25b941a8 inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Verify if the player is paused.  <a href="#a548c47ffd2ac76ffe19f6f7f25b941a8">More...</a><br /></td></tr>
<tr class="separator:a548c47ffd2ac76ffe19f6f7f25b941a8 inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7582710c11a7b92d9912f414a5296975 inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a7582710c11a7b92d9912f414a5296975">lost</a> ()</td></tr>
<tr class="memdesc:a7582710c11a7b92d9912f414a5296975 inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Lost the focus.  <a href="#a7582710c11a7b92d9912f414a5296975">More...</a><br /></td></tr>
<tr class="separator:a7582710c11a7b92d9912f414a5296975 inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac4a98e2f186ed9702f90362a158a9f2f inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#ac4a98e2f186ed9702f90362a158a9f2f">retreive</a> ()</td></tr>
<tr class="memdesc:ac4a98e2f186ed9702f90362a158a9f2f inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Regain the focus.  <a href="#ac4a98e2f186ed9702f90362a158a9f2f">More...</a><br /></td></tr>
<tr class="separator:ac4a98e2f186ed9702f90362a158a9f2f inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a98e4c4a2c86689dfc2a2a5926bfe26cc inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a98e4c4a2c86689dfc2a2a5926bfe26cc">isLost</a> () const </td></tr>
<tr class="memdesc:a98e4c4a2c86689dfc2a2a5926bfe26cc inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Verify if it has the focus.  <a href="#a98e4c4a2c86689dfc2a2a5926bfe26cc">More...</a><br /></td></tr>
<tr class="separator:a98e4c4a2c86689dfc2a2a5926bfe26cc inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acd5a72be6d18b5cceda1ec825b307d7c inherit pub_methods_a00052"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#acd5a72be6d18b5cceda1ec825b307d7c">isInit</a> () const </td></tr>
<tr class="memdesc:acd5a72be6d18b5cceda1ec825b307d7c inherit pub_methods_a00052"><td class="mdescLeft">&#160;</td><td class="mdescRight">Verify if the player is initialized.  <a href="#acd5a72be6d18b5cceda1ec825b307d7c">More...</a><br /></td></tr>
<tr class="separator:acd5a72be6d18b5cceda1ec825b307d7c inherit pub_methods_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00024"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00024')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../dc/de2/a00024.php">mcd::Identifier</a></td></tr>
<tr class="memitem:a1496891d2323d1023ebfd086b84faf8d inherit pub_methods_a00024"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a1496891d2323d1023ebfd086b84faf8d">Identifier</a> ()</td></tr>
<tr class="separator:a1496891d2323d1023ebfd086b84faf8d inherit pub_methods_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a87dbdb0f9b391d6a78d61463e8823628 inherit pub_methods_a00024"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a87dbdb0f9b391d6a78d61463e8823628">~Identifier</a> ()</td></tr>
<tr class="separator:a87dbdb0f9b391d6a78d61463e8823628 inherit pub_methods_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8e39d490b0b94678150e8c2b1d156e51 inherit pub_methods_a00024"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a8e39d490b0b94678150e8c2b1d156e51">setUsername</a> (std::string username)</td></tr>
<tr class="memdesc:a8e39d490b0b94678150e8c2b1d156e51 inherit pub_methods_a00024"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the <a class="el" href="../../d2/d79/a00051.php" title="A player that can be a child from any class. ">Player</a>'s username.  <a href="#a8e39d490b0b94678150e8c2b1d156e51">More...</a><br /></td></tr>
<tr class="separator:a8e39d490b0b94678150e8c2b1d156e51 inherit pub_methods_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a53d4547cb792d88243c6448849fc40f3 inherit pub_methods_a00024"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a53d4547cb792d88243c6448849fc40f3">setPassword</a> (std::string password)</td></tr>
<tr class="memdesc:a53d4547cb792d88243c6448849fc40f3 inherit pub_methods_a00024"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the <a class="el" href="../../d2/d79/a00051.php" title="A player that can be a child from any class. ">Player</a>'s password.  <a href="#a53d4547cb792d88243c6448849fc40f3">More...</a><br /></td></tr>
<tr class="separator:a53d4547cb792d88243c6448849fc40f3 inherit pub_methods_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a593e0be0e4c8e17b22507e7f7d933ded inherit pub_methods_a00024"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a593e0be0e4c8e17b22507e7f7d933ded">setId</a> (size_t id)</td></tr>
<tr class="memdesc:a593e0be0e4c8e17b22507e7f7d933ded inherit pub_methods_a00024"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the <a class="el" href="../../d2/d79/a00051.php" title="A player that can be a child from any class. ">Player</a>'s id.  <a href="#a593e0be0e4c8e17b22507e7f7d933ded">More...</a><br /></td></tr>
<tr class="separator:a593e0be0e4c8e17b22507e7f7d933ded inherit pub_methods_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a893b6b3a2b60064110ec14b81433033f inherit pub_methods_a00024"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a893b6b3a2b60064110ec14b81433033f">getUsername</a> () const </td></tr>
<tr class="separator:a893b6b3a2b60064110ec14b81433033f inherit pub_methods_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0415f38f13d2074e9aedc7d8197d590c inherit pub_methods_a00024"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a0415f38f13d2074e9aedc7d8197d590c">getPassword</a> () const </td></tr>
<tr class="separator:a0415f38f13d2074e9aedc7d8197d590c inherit pub_methods_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a923c285a36a65601bfcf303498e0d2b5 inherit pub_methods_a00024"><td class="memItemLeft" align="right" valign="top">virtual size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a923c285a36a65601bfcf303498e0d2b5">getId</a> () const </td></tr>
<tr class="separator:a923c285a36a65601bfcf303498e0d2b5 inherit pub_methods_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pro_attribs_a00052"><td colspan="2" onclick="javascript:toggleInherit('pro_attribs_a00052')"><img src="../../closed.png" alt="-"/>&#160;Protected Attributes inherited from <a class="el" href="../../d1/d84/a00052.php">mcd::PlayerAbstraction&lt; PlayerParent &gt;</a></td></tr>
<tr class="memitem:abffa7d0ae3461370c932f0732367c93b inherit pro_attribs_a00052"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#abffa7d0ae3461370c932f0732367c93b">_init</a></td></tr>
<tr class="separator:abffa7d0ae3461370c932f0732367c93b inherit pro_attribs_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a005074efa352510f2dc316404195946c inherit pro_attribs_a00052"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a005074efa352510f2dc316404195946c">_paused</a></td></tr>
<tr class="separator:a005074efa352510f2dc316404195946c inherit pro_attribs_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aee72e21c73d5bbf23c831514cd6cd58b inherit pro_attribs_a00052"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#aee72e21c73d5bbf23c831514cd6cd58b">_losted</a></td></tr>
<tr class="separator:aee72e21c73d5bbf23c831514cd6cd58b inherit pro_attribs_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad9199142db686c7745b21429e7061823 inherit pro_attribs_a00052"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#ad9199142db686c7745b21429e7061823">_mail</a></td></tr>
<tr class="separator:ad9199142db686c7745b21429e7061823 inherit pro_attribs_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae561b7817c64610317799205afa306cd inherit pro_attribs_a00052"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../dd/d1b/a00015.php#adda27badcbfcfc854854c6ab094cf34e">double64_t</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#ae561b7817c64610317799205afa306cd">_experience</a></td></tr>
<tr class="separator:ae561b7817c64610317799205afa306cd inherit pro_attribs_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3800d1590d75f762d41be6349556707d inherit pro_attribs_a00052"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../dd/d1b/a00015.php#adda27badcbfcfc854854c6ab094cf34e">double64_t</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d84/a00052.php#a3800d1590d75f762d41be6349556707d">_experienceMax</a></td></tr>
<tr class="separator:a3800d1590d75f762d41be6349556707d inherit pro_attribs_a00052"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_attribs_a00024"><td colspan="2" onclick="javascript:toggleInherit('pro_attribs_a00024')"><img src="../../closed.png" alt="-"/>&#160;Protected Attributes inherited from <a class="el" href="../../dc/de2/a00024.php">mcd::Identifier</a></td></tr>
<tr class="memitem:a4a002c57b507ef0c744135eacfb82b6f inherit pro_attribs_a00024"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a4a002c57b507ef0c744135eacfb82b6f">_username</a></td></tr>
<tr class="separator:a4a002c57b507ef0c744135eacfb82b6f inherit pro_attribs_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a95d479399de1b046aff00e83210b67ea inherit pro_attribs_a00024"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a95d479399de1b046aff00e83210b67ea">_password</a></td></tr>
<tr class="separator:a95d479399de1b046aff00e83210b67ea inherit pro_attribs_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6920412818f4d8a4478771fb767a2d07 inherit pro_attribs_a00024"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/de2/a00024.php#a6920412818f4d8a4478771fb767a2d07">_id</a></td></tr>
<tr class="separator:a6920412818f4d8a4478771fb767a2d07 inherit pro_attribs_a00024"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class PlayerParent&gt;<br />
class mcd::Player&lt; PlayerParent &gt;</h3>

<p>A player that can be a child from any class. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="aa2e12089a072fbc695087df2b474af5c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class PlayerParent &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d2/d79/a00051.php">mcd::Player</a>&lt; PlayerParent &gt;::<a class="el" href="../../d2/d79/a00051.php">Player</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../d3/de7/a00039.php">Map</a> *&#160;</td>
          <td class="paramname"><em>map</em> = <code>nullptr</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../dc/dee/a00053.php">Point</a>&#160;</td>
          <td class="paramname"><em>pt</em> = <code>{0,&#160;0,&#160;0}</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="../../dd/d1b/a00015.php#d4/ddd/a00138">ContraptionAttr</a>&#160;</td>
          <td class="paramname"><em>attr</em> = <code>{0,&#160;0,&#160;0}</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Constructor of the class. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">map</td><td>The map where it is </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">pt</td><td>The position in the map </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">attr</td><td>The attributes of the object(width, height, angle) </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a73fba351baf5641e985c76c0de4fe097"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class PlayerParent &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual <a class="el" href="../../d2/d79/a00051.php">mcd::Player</a>&lt; PlayerParent &gt;::~<a class="el" href="../../d2/d79/a00051.php">Player</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Virtual destructor. </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ae0258dbfcdecaaa58390125aac118fe8"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class PlayerParent &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void <a class="el" href="../../d2/d79/a00051.php">mcd::Player</a>&lt; PlayerParent &gt;::printInfos </td>
          <td>(</td>
          <td class="paramtype">std::ostream &amp;&#160;</td>
          <td class="paramname"><em>stream</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Print the infos in the instance of the class in <em>stream</em>. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">stream</td><td>The output stream</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Reimplemented from <a class="el" href="../../d1/d84/a00052.php#ac6d60013def2f34160fda9a990cf2da5">mcd::PlayerAbstraction&lt; PlayerParent &gt;</a>.</p>

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/d79/a00051_ae0258dbfcdecaaa58390125aac118fe8_cgraph.png" border="0" usemap="#d2/d79/a00051_ae0258dbfcdecaaa58390125aac118fe8_cgraph" alt=""/></div>
<map name="d2/d79/a00051_ae0258dbfcdecaaa58390125aac118fe8_cgraph" id="d2/d79/a00051_ae0258dbfcdecaaa58390125aac118fe8_cgraph">
<area shape="rect" id="node2" href="../../d1/d84/a00052.php#ac6d60013def2f34160fda9a990cf2da5" title="Print the infos in the instance of the class in stream. " alt="" coords="208,5,367,47"/>
</map>
</div>
</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d8/d87/a00118.php">Player.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dd/d1b/a00015.php">mcd</a></li><li class="navelem"><a class="el" href="../../d2/d79/a00051.php">Player</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
