<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Member List</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Sep 18 2019 15:38:16 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/d40/a00959.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">mcd::Matrix&lt; C &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#ace95025dd985ddaa6c1ed72e8b464a0a">det</a>()</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#ae6b6255f5d5cd9a1684fcdb927978c18">enabled</a>() const</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a5e13250be50a80b7e8cab73a741b9fd5">GaussJordan</a>(Matrix&lt; D &gt; M, Matrix&lt; D &gt; &amp;I, size_t i, size_t j)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#aac5e5ab03fe97f3deb3f56b34b638638">getIdentity</a>()</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a9823b15f6575c9007b734e505ea772b5">i</a>() const</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#af0390771523fc535079faa2a7b7c29ce">inverted</a>()</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a3885a9068844517cbbd58cfed57eb5c4">isSquare</a>() const</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#adc00ecac929d1e153082d6a61879d4e2">j</a>() const</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a222bcb9024bd8d24b105f9d6be5dd391">Matrix</a>()</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a4f2cef0c1ab7ebbbecbe0dc22de5eeeb">Matrix</a>(const std::vector&lt; std::vector&lt; C &gt;&gt; &amp;datas)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a5cfebad51878a28020f44f6aacc6f29a">Matrix</a>(std::array&lt; std::array&lt; C, M &gt;, N &gt; &amp;datas)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a8919e7b6753c1f480d89106a0e993d57">Matrix</a>()</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a13b069e43b69c428da1868baa888f8a7">Matrix</a>(const std::vector&lt; std::vector&lt; C &gt;&gt; &amp;datas)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a5cfebad51878a28020f44f6aacc6f29a">Matrix</a>(std::array&lt; std::array&lt; C, M &gt;, N &gt; &amp;datas)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a895533c348847ed307cafe3d85c8ebf9">operator()</a>(size_t i, size_t j) const</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#ab2e5889d3ce0c0a97ec6f7c35b424f23">operator()</a>(size_t i, size_t j)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a61b1b866f822f492dd94f0178de09f0e">operator*</a>(const D &amp;a)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a37a33064fb7f3599b1e3127d13cd87f9">operator*</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#ab1a6b452f2b1878dbe72e1825f8dca12">operator*</a>(const D &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a37a33064fb7f3599b1e3127d13cd87f9">operator*</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a309672571879a0b44bf9c91b26b51a21">operator*=</a>(const D &amp;a)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a035e71a534c66ed739cdafccb5abc09b">operator*=</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a743ecbf9bc1defaa0d556a84f328906b">operator*=</a>(const D &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a035e71a534c66ed739cdafccb5abc09b">operator*=</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#ac2adb934f2c26b12d6b5f5981c0e4d7a">operator+</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#ac2adb934f2c26b12d6b5f5981c0e4d7a">operator+</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#ab65365129992bf5a53b62e3bd3955135">operator+=</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#ab65365129992bf5a53b62e3bd3955135">operator+=</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a0e53fd790079347de2d5d5e132a4c37b">operator-</a>()</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a3dc00dacaac8d2884d41d0f1057a098b">operator-</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#acff8e20e80d55f14e4ef611dc1c9b8ce">operator-</a>()</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a3dc00dacaac8d2884d41d0f1057a098b">operator-</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a8c4a74722881f5fdb1a1135b36808f47">operator-=</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a8c4a74722881f5fdb1a1135b36808f47">operator-=</a>(const Matrix&lt; D &gt; &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#aead70f5313e4a9a9c39321d41c2c3d10">operator/</a>(const D &amp;a)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a116e84cdee4fae72b8cdaabcc4f749ad">operator/</a>(const D &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a8f1be652fdf748cc826d30cbb96745f0">operator/=</a>(const D &amp;a)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#ad60adce66964625f49ed954456ef08af">operator/=</a>(const D &amp;A)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a9a3710d279e209fbff51b625690ef630">operator&lt;&lt;</a>(std::ostream &amp;os, const Matrix&lt; D &gt; &amp;M)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#adbfa246182cc089300f95cf1610a99ef">tos</a>(T value)</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/d40/a00959.php#a942e3d418da2bacad3193d82411e2cfc">transposed</a>()</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/d40/a00959.php#a87e5bc598036e554e7fac18328bbb47b">~Matrix</a>()</td><td class="entry"><a class="el" href="../../db/d40/a00959.php">mcd::Matrix&lt; C &gt;</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
