<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: files.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.1.1</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Nov 15 2020 11:00:16 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('d4/d3a/a00101.php','../../'); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">files.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../db/db6/a00074.php">convert.hpp</a>&quot;</code><br />
<code>#include &lt;fstream&gt;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for files.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/dcc/a00102.png" border="0" usemap="#afiles_8hpp" alt=""/></div>
<map name="files_8hpp" id="files_8hpp">
<area shape="rect" title=" " alt="" coords="791,5,861,32"/>
<area shape="rect" href="../../db/db6/a00074.php" title=" " alt="" coords="730,80,821,107"/>
<area shape="rect" title=" " alt="" coords="845,80,911,107"/>
<area shape="rect" title=" " alt="" coords="683,155,766,181"/>
<area shape="rect" href="../../da/d45/a00011.php" title=" " alt="" coords="790,155,865,181"/>
<area shape="rect" href="../../dc/dee/a00053.php" title=" " alt="" coords="841,229,923,256"/>
<area shape="rect" href="../../dc/d9a/a00218.php" title=" " alt="" coords="729,229,816,256"/>
<area shape="rect" href="../../df/d03/a00062.php" title=" " alt="" coords="1034,304,1125,331"/>
<area shape="rect" href="../../d9/d39/a00257.php" title=" " alt="" coords="731,304,814,331"/>
<area shape="rect" title=" " alt="" coords="845,304,906,331"/>
<area shape="rect" title=" " alt="" coords="930,304,999,331"/>
<area shape="rect" href="../../d9/db6/a00146.php" title=" " alt="" coords="1043,379,1126,405"/>
<area shape="rect" href="../../d0/dc2/a00104.php" title=" " alt="" coords="1180,453,1275,480"/>
<area shape="rect" href="../../d6/d7d/a00161.php" title=" " alt="" coords="1014,453,1155,480"/>
<area shape="rect" href="../../d7/dce/a00143.php" title=" " alt="" coords="1065,528,1147,555"/>
<area shape="rect" title=" " alt="" coords="1194,528,1261,555"/>
<area shape="rect" href="../../d8/d41/a00038.php" title=" " alt="" coords="1062,603,1145,629"/>
<area shape="rect" href="../../d5/df1/a00206.php" title=" " alt="" coords="701,677,794,704"/>
<area shape="rect" href="../../d3/d1a/a00251.php" title=" " alt="" coords="615,752,693,779"/>
<area shape="rect" title=" " alt="" coords="718,752,777,779"/>
<area shape="rect" title=" " alt="" coords="801,752,859,779"/>
<area shape="rect" href="../../d3/d52/a00023.php" title=" " alt="" coords="371,827,438,853"/>
<area shape="rect" href="../../d3/de5/a00209.php" title=" " alt="" coords="483,827,593,853"/>
<area shape="rect" href="../../dd/dd7/a00248.php" title=" " alt="" coords="617,827,691,853"/>
<area shape="rect" href="../../d7/d03/a00254.php" title=" " alt="" coords="715,827,849,853"/>
<area shape="rect" title=" " alt="" coords="873,827,941,853"/>
<area shape="rect" href="../../d7/d06/a00131.php" title=" " alt="" coords="618,901,730,928"/>
<area shape="rect" href="../../d6/d5b/a00026.php" title=" " alt="" coords="451,901,593,928"/>
<area shape="rect" href="../../d5/d16/a00029.php" title=" " alt="" coords="5,901,145,928"/>
<area shape="rect" href="../../dc/d87/a00032.php" title=" " alt="" coords="170,901,279,928"/>
<area shape="rect" href="../../d4/d8c/a00035.php" title=" " alt="" coords="303,901,426,928"/>
<area shape="rect" href="../../d5/de9/a00176.php" title=" " alt="" coords="614,976,734,1003"/>
<area shape="rect" title=" " alt="" coords="583,1051,651,1077"/>
<area shape="rect" href="../../de/d76/a00134.php" title=" " alt="" coords="675,1051,791,1077"/>
<area shape="rect" title=" " alt="" coords="246,1125,321,1152"/>
<area shape="rect" title=" " alt="" coords="345,1125,403,1152"/>
<area shape="rect" title=" " alt="" coords="428,1125,507,1152"/>
<area shape="rect" title=" " alt="" coords="531,1125,603,1152"/>
<area shape="rect" title=" " alt="" coords="628,1125,675,1152"/>
<area shape="rect" title=" " alt="" coords="699,1125,767,1152"/>
<area shape="rect" title=" " alt="" coords="791,1125,845,1152"/>
<area shape="rect" title=" " alt="" coords="870,1125,939,1152"/>
<area shape="rect" title=" " alt="" coords="964,1125,1019,1152"/>
<area shape="rect" title=" " alt="" coords="1043,1125,1097,1152"/>
<area shape="rect" title=" " alt="" coords="1121,1125,1179,1152"/>
<area shape="rect" href="../../d1/d44/a00098.php" title=" " alt="" coords="937,528,1040,555"/>
<area shape="rect" title=" " alt="" coords="953,603,1032,629"/>
<area shape="rect" title=" " alt="" coords="851,603,929,629"/>
<area shape="rect" href="../../d2/de7/a00014.php" title=" " alt="" coords="700,379,832,405"/>
<area shape="rect" title=" " alt="" coords="449,453,560,480"/>
<area shape="rect" title=" " alt="" coords="585,453,689,480"/>
<area shape="rect" title=" " alt="" coords="713,453,763,480"/>
<area shape="rect" title=" " alt="" coords="788,453,845,480"/>
<area shape="rect" title=" " alt="" coords="870,453,910,480"/>
<area shape="rect" title=" " alt="" coords="935,453,989,480"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/d1e/a00103.png" border="0" usemap="#afiles_8hppdep" alt=""/></div>
<map name="files_8hppdep" id="files_8hppdep">
<area shape="rect" title=" " alt="" coords="340,5,411,32"/>
<area shape="rect" href="../../d9/d77/a00095.php" title=" " alt="" coords="335,80,415,107"/>
<area shape="rect" href="../../d1/da8/a00230.php" title=" " alt="" coords="330,155,421,181"/>
<area shape="rect" href="../../d5/ddf/a00224.php" title=" " alt="" coords="336,229,415,256"/>
<area shape="rect" href="../../d9/d01/a00227.php" title="Used to replace strptime function when compiling for Windows." alt="" coords="335,304,415,331"/>
<area shape="rect" href="../../d2/dc8/a00242.php" title=" " alt="" coords="311,379,440,405"/>
<area shape="rect" href="../../d4/d3e/a00116.php" title=" " alt="" coords="328,453,423,480"/>
<area shape="rect" href="../../d3/d8b/a00059.php" title=" " alt="" coords="5,677,87,704"/>
<area shape="rect" href="../../da/d24/a00068.php" title=" " alt="" coords="116,752,243,779"/>
<area shape="rect" href="../../da/dec/a00080.php" title=" " alt="" coords="162,528,237,555"/>
<area shape="rect" href="../../df/d6a/a00119.php" title=" " alt="" coords="318,603,417,629"/>
<area shape="rect" href="../../db/dd9/a00179.php" title=" " alt="" coords="413,528,487,555"/>
<area shape="rect" href="../../d9/dd0/a00191.php" title=" " alt="" coords="511,528,682,555"/>
<area shape="rect" href="../../dd/dc1/a00212.php" title=" " alt="" coords="610,677,725,704"/>
<area shape="rect" href="../../d7/d40/a00236.php" title=" " alt="" coords="715,827,825,853"/>
<area shape="rect" href="../../d0/d27/a00239.php" title=" " alt="" coords="261,528,337,555"/>
<area shape="rect" href="../../da/d2a/a00086.php" title=" " alt="" coords="369,976,459,1003"/>
<area shape="rect" href="../../db/db2/a00020.php" title=" " alt="" coords="217,1051,377,1077"/>
<area shape="rect" href="../../d1/d09/a00077.php" title=" " alt="" coords="364,1125,461,1152"/>
<area shape="rect" href="../../dc/dfe/a00125.php" title=" " alt="" coords="454,1051,587,1077"/>
<area shape="rect" href="../../d4/d51/a00017.php" title=" " alt="" coords="254,1125,339,1152"/>
<area shape="rect" href="../../d6/d2d/a00047.php" title=" " alt="" coords="369,1200,456,1227"/>
<area shape="rect" href="../../df/d98/a00107.php" title=" " alt="" coords="271,1275,349,1301"/>
<area shape="rect" href="../../d1/d88/a00128.php" title=" " alt="" coords="370,1349,455,1376"/>
<area shape="rect" href="../../d6/de1/a00233.php" title=" " alt="" coords="453,1424,525,1451"/>
<area shape="rect" href="../../d9/d2e/a00056.php" title=" " alt="" coords="221,1349,346,1376"/>
<area shape="rect" href="../../d5/de0/a00050.php" title=" " alt="" coords="276,1424,347,1451"/>
<area shape="rect" href="../../dd/d32/a00041.php" title=" " alt="" coords="376,1499,449,1525"/>
<area shape="rect" href="../../d0/d89/a00071.php" title=" " alt="" coords="309,1573,423,1600"/>
<area shape="rect" href="../../d3/d00/a00113.php" title=" " alt="" coords="407,1947,503,1973"/>
<area shape="rect" href="../../d1/dc1/a00092.php" title=" " alt="" coords="215,1648,293,1675"/>
<area shape="rect" href="../../d7/d3f/a00173.php" title=" " alt="" coords="331,1648,417,1675"/>
<area shape="rect" href="../../d4/d81/a00110.php" title=" " alt="" coords="99,1723,187,1749"/>
<area shape="rect" href="../../dd/dd7/a00260.php" title=" " alt="" coords="209,1797,299,1824"/>
<area shape="rect" href="../../d7/d46/a00002.php" title=" " alt="" coords="69,1797,156,1824"/>
<area shape="rect" href="../../dd/dad/a00005.php" title=" " alt="" coords="71,1872,138,1899"/>
<area shape="rect" href="../../db/dab/a00089.php" title=" " alt="" coords="289,1947,379,1973"/>
<area shape="rect" href="../../de/d79/a00203.php" title=" " alt="" coords="260,2021,411,2048"/>
<area shape="rect" href="../../d3/db1/a00200.php" title=" " alt="" coords="350,2096,433,2123"/>
<area shape="rect" href="../../d5/df9/a00044.php" title=" " alt="" coords="333,2171,450,2197"/>
<area shape="rect" href="../../db/ddf/a00164.php" title=" " alt="" coords="163,1872,271,1899"/>
<area shape="rect" href="../../de/db1/a00197.php" title=" " alt="" coords="295,1872,373,1899"/>
<area shape="rect" href="../../dd/d52/a00221.php" title=" " alt="" coords="341,1723,423,1749"/>
<area shape="rect" href="../../df/dc8/a00122.php" title=" " alt="" coords="486,1125,561,1152"/>
<area shape="rect" href="../../d2/d1f/a00083.php" title=" " alt="" coords="190,603,294,629"/>
<area shape="rect" href="../../dc/d57/a00194.php" title=" " alt="" coords="441,603,601,629"/>
<area shape="rect" href="../../d7/d25/a00182.php" title=" " alt="" coords="445,677,557,704"/>
<area shape="rect" href="../../da/d15/a00188.php" title=" " alt="" coords="402,752,559,779"/>
<area shape="rect" href="../../de/df3/a00185.php" title=" " alt="" coords="389,827,564,853"/>
<area shape="rect" href="../../d5/db1/a00140.php" title=" " alt="" coords="415,901,487,928"/>
<area shape="rect" href="../../d4/dee/a00008.php" title=" " alt="" coords="639,901,714,928"/>
<area shape="rect" href="../../d6/d22/a00245.php" title=" " alt="" coords="739,901,817,928"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:db/d12/a00268"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:aada88379a63c49987a295485391aa192"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php#aada88379a63c49987a295485391aa192">mcd::fileFormat</a> (std::string &amp;line)</td></tr>
<tr class="memdesc:aada88379a63c49987a295485391aa192"><td class="mdescLeft">&#160;</td><td class="mdescRight">Format a given <em>line</em> for files.  <a href="../../db/d12/a00268.php#aada88379a63c49987a295485391aa192">More...</a><br /></td></tr>
<tr class="separator:aada88379a63c49987a295485391aa192"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae44c2e346da18a7424d97535fb654448"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php#ae44c2e346da18a7424d97535fb654448">mcd::fileExists</a> (const std::string &amp;path)</td></tr>
<tr class="memdesc:ae44c2e346da18a7424d97535fb654448"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return true if the file exists.  <a href="../../db/d12/a00268.php#ae44c2e346da18a7424d97535fb654448">More...</a><br /></td></tr>
<tr class="separator:ae44c2e346da18a7424d97535fb654448"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a97dfa91f19b9e2175dddbf65285663a2"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php#a97dfa91f19b9e2175dddbf65285663a2">mcd::getFileSize</a> (const std::string &amp;path)</td></tr>
<tr class="memdesc:a97dfa91f19b9e2175dddbf65285663a2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the file size.  <a href="../../db/d12/a00268.php#a97dfa91f19b9e2175dddbf65285663a2">More...</a><br /></td></tr>
<tr class="separator:a97dfa91f19b9e2175dddbf65285663a2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7fa98622f290e9789bf929fb66ee3a4c"><td class="memItemLeft" align="right" valign="top">std::vector&lt; std::string &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php#a7fa98622f290e9789bf929fb66ee3a4c">mcd::getlines</a> (std::ifstream &amp;input)</td></tr>
<tr class="memdesc:a7fa98622f290e9789bf929fb66ee3a4c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get all the lines in a given file.  <a href="../../db/d12/a00268.php#a7fa98622f290e9789bf929fb66ee3a4c">More...</a><br /></td></tr>
<tr class="separator:a7fa98622f290e9789bf929fb66ee3a4c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a08a1c8da74e7ca2634c1a2a4f4a3ac9d"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php#a08a1c8da74e7ca2634c1a2a4f4a3ac9d">mcd::setlines</a> (std::ofstream &amp;output, const std::vector&lt; std::string &gt; &amp;lines)</td></tr>
<tr class="memdesc:a08a1c8da74e7ca2634c1a2a4f4a3ac9d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Write all the lines in a given file.  <a href="../../db/d12/a00268.php#a08a1c8da74e7ca2634c1a2a4f4a3ac9d">More...</a><br /></td></tr>
<tr class="separator:a08a1c8da74e7ca2634c1a2a4f4a3ac9d"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a8860bcba5ad1fad5c14e9f8a69b8bc51"><td class="memItemLeft" align="right" valign="top">std::ifstream&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php#a8860bcba5ad1fad5c14e9f8a69b8bc51">mcd::reader</a></td></tr>
<tr class="memdesc:a8860bcba5ad1fad5c14e9f8a69b8bc51"><td class="mdescLeft">&#160;</td><td class="mdescRight">Define a global file reader.  <a href="../../db/d12/a00268.php#a8860bcba5ad1fad5c14e9f8a69b8bc51">More...</a><br /></td></tr>
<tr class="separator:a8860bcba5ad1fad5c14e9f8a69b8bc51"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9826cf077a919365508fb2a7d7aae4c2"><td class="memItemLeft" align="right" valign="top">std::ofstream&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php#a9826cf077a919365508fb2a7d7aae4c2">mcd::writer</a></td></tr>
<tr class="memdesc:a9826cf077a919365508fb2a7d7aae4c2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Define a global file writer.  <a href="../../db/d12/a00268.php#a9826cf077a919365508fb2a7d7aae4c2">More...</a><br /></td></tr>
<tr class="separator:a9826cf077a919365508fb2a7d7aae4c2"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : August, 19 2018 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../dir_220287e732b97f08f66e5f221c69df74.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_75b0389167f46f79a101ef8c4434cec4.php">C++</a></li><li class="navelem"><a class="el" href="../../d4/d3a/a00101.php">files.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
