<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: Gene.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.2.3</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Tue Nov 17 2020 15:27:34 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('df/d98/a00107.php','../../'); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a> &#124;
<a href="#typedef-members">Typedefs</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">Gene.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d6/d2d/a00047.php">C++lib.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Gene.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/dd6/a00108.png" border="0" usemap="#aGene_8hpp" alt=""/></div>
<map name="Gene_8hpp" id="Gene_8hpp">
<area shape="rect" title=" " alt="" coords="785,5,864,32"/>
<area shape="rect" href="../../d6/d2d/a00047.php" title=" " alt="" coords="781,80,868,107"/>
<area shape="rect" href="../../d4/d51/a00017.php" title=" " alt="" coords="645,155,730,181"/>
<area shape="rect" href="../../df/dc8/a00122.php" title=" " alt="" coords="787,155,862,181"/>
<area shape="rect" href="../../d1/d09/a00077.php" title=" " alt="" coords="916,229,1013,256"/>
<area shape="rect" href="../../db/db2/a00020.php" title=" " alt="" coords="574,229,734,256"/>
<area shape="rect" href="../../da/d2a/a00086.php" title=" " alt="" coords="780,304,869,331"/>
<area shape="rect" href="../../d6/d22/a00245.php" title=" " alt="" coords="533,379,612,405"/>
<area shape="rect" href="../../d4/dee/a00008.php" title=" " alt="" coords="637,379,711,405"/>
<area shape="rect" href="../../d3/d8b/a00059.php" title=" " alt="" coords="655,528,736,555"/>
<area shape="rect" href="../../da/d24/a00068.php" title=" " alt="" coords="683,603,809,629"/>
<area shape="rect" href="../../d2/d1f/a00083.php" title=" " alt="" coords="798,677,902,704"/>
<area shape="rect" href="../../df/d6a/a00119.php" title=" " alt="" coords="887,453,986,480"/>
<area shape="rect" href="../../d5/db1/a00140.php" title=" " alt="" coords="1018,379,1090,405"/>
<area shape="rect" href="../../dd/dc1/a00212.php" title=" " alt="" coords="1215,528,1330,555"/>
<area shape="rect" href="../../d7/d40/a00236.php" title=" " alt="" coords="536,453,647,480"/>
<area shape="rect" href="../../d4/d3e/a00116.php" title=" " alt="" coords="821,827,916,853"/>
<area shape="rect" href="../../dc/de6/a00167.php" title=" " alt="" coords="341,901,463,928"/>
<area shape="rect" href="../../d5/dcb/a00170.php" title=" " alt="" coords="488,901,623,928"/>
<area shape="rect" href="../../d2/dc8/a00242.php" title=" " alt="" coords="647,901,776,928"/>
<area shape="rect" title=" " alt="" coords="801,901,862,928"/>
<area shape="rect" title=" " alt="" coords="887,901,925,928"/>
<area shape="rect" title=" " alt="" coords="949,901,1012,928"/>
<area shape="rect" title=" " alt="" coords="1037,901,1090,928"/>
<area shape="rect" title=" " alt="" coords="1114,901,1165,928"/>
<area shape="rect" href="../../d9/d01/a00227.php" title="Used to replace strptime function when compiling for Windows." alt="" coords="625,976,705,1003"/>
<area shape="rect" title=" " alt="" coords="729,976,784,1003"/>
<area shape="rect" href="../../d5/ddf/a00224.php" title=" " alt="" coords="610,1051,719,1077"/>
<area shape="rect" title=" " alt="" coords="494,1125,550,1152"/>
<area shape="rect" href="../../d3/dd5/a00215.php" title=" " alt="" coords="574,1125,651,1152"/>
<area shape="rect" href="../../d2/df5/a00137.php" title=" " alt="" coords="675,1125,758,1152"/>
<area shape="rect" href="../../d1/da8/a00230.php" title=" " alt="" coords="782,1125,873,1152"/>
<area shape="rect" title=" " alt="" coords="580,1200,645,1227"/>
<area shape="rect" href="../../d9/d77/a00095.php" title=" " alt="" coords="787,1200,867,1227"/>
<area shape="rect" href="../../de/de1/a00065.php" title=" " alt="" coords="728,1275,820,1301"/>
<area shape="rect" href="../../d4/d3a/a00101.php" title=" " alt="" coords="844,1275,915,1301"/>
<area shape="rect" href="../../db/db6/a00074.php" title=" " alt="" coords="730,1349,821,1376"/>
<area shape="rect" title=" " alt="" coords="683,1424,766,1451"/>
<area shape="rect" href="../../da/d45/a00011.php" title=" " alt="" coords="790,1424,865,1451"/>
<area shape="rect" href="../../dc/dee/a00053.php" title=" " alt="" coords="841,1499,923,1525"/>
<area shape="rect" href="../../dc/d9a/a00218.php" title=" " alt="" coords="729,1499,816,1525"/>
<area shape="rect" href="../../df/d03/a00062.php" title=" " alt="" coords="1034,1573,1125,1600"/>
<area shape="rect" href="../../d9/d39/a00257.php" title=" " alt="" coords="731,1573,814,1600"/>
<area shape="rect" title=" " alt="" coords="845,1573,906,1600"/>
<area shape="rect" title=" " alt="" coords="930,1573,999,1600"/>
<area shape="rect" href="../../d9/db6/a00146.php" title=" " alt="" coords="1043,1648,1126,1675"/>
<area shape="rect" href="../../d0/dc2/a00104.php" title=" " alt="" coords="1180,1723,1275,1749"/>
<area shape="rect" href="../../d6/d7d/a00161.php" title=" " alt="" coords="1014,1723,1155,1749"/>
<area shape="rect" href="../../d7/dce/a00143.php" title=" " alt="" coords="1065,1797,1147,1824"/>
<area shape="rect" title=" " alt="" coords="1194,1797,1261,1824"/>
<area shape="rect" href="../../d8/d41/a00038.php" title=" " alt="" coords="1062,1872,1145,1899"/>
<area shape="rect" href="../../d5/df1/a00206.php" title=" " alt="" coords="701,1947,794,1973"/>
<area shape="rect" href="../../d3/d1a/a00251.php" title=" " alt="" coords="615,2021,693,2048"/>
<area shape="rect" title=" " alt="" coords="718,2021,777,2048"/>
<area shape="rect" title=" " alt="" coords="801,2021,859,2048"/>
<area shape="rect" href="../../d3/d52/a00023.php" title=" " alt="" coords="371,2096,438,2123"/>
<area shape="rect" href="../../d3/de5/a00209.php" title=" " alt="" coords="483,2096,593,2123"/>
<area shape="rect" href="../../dd/dd7/a00248.php" title=" " alt="" coords="617,2096,691,2123"/>
<area shape="rect" href="../../d7/d03/a00254.php" title=" " alt="" coords="715,2096,849,2123"/>
<area shape="rect" title=" " alt="" coords="873,2096,941,2123"/>
<area shape="rect" href="../../d7/d06/a00131.php" title=" " alt="" coords="618,2171,730,2197"/>
<area shape="rect" href="../../d6/d5b/a00026.php" title=" " alt="" coords="451,2171,593,2197"/>
<area shape="rect" href="../../d5/d16/a00029.php" title=" " alt="" coords="5,2171,145,2197"/>
<area shape="rect" href="../../dc/d87/a00032.php" title=" " alt="" coords="170,2171,279,2197"/>
<area shape="rect" href="../../d4/d8c/a00035.php" title=" " alt="" coords="303,2171,426,2197"/>
<area shape="rect" href="../../d5/de9/a00176.php" title=" " alt="" coords="614,2245,734,2272"/>
<area shape="rect" title=" " alt="" coords="583,2320,651,2347"/>
<area shape="rect" href="../../de/d76/a00134.php" title=" " alt="" coords="675,2320,791,2347"/>
<area shape="rect" title=" " alt="" coords="246,2395,321,2421"/>
<area shape="rect" title=" " alt="" coords="345,2395,403,2421"/>
<area shape="rect" title=" " alt="" coords="428,2395,507,2421"/>
<area shape="rect" title=" " alt="" coords="531,2395,603,2421"/>
<area shape="rect" title=" " alt="" coords="628,2395,675,2421"/>
<area shape="rect" title=" " alt="" coords="699,2395,767,2421"/>
<area shape="rect" title=" " alt="" coords="791,2395,845,2421"/>
<area shape="rect" title=" " alt="" coords="870,2395,939,2421"/>
<area shape="rect" title=" " alt="" coords="964,2395,1019,2421"/>
<area shape="rect" title=" " alt="" coords="1043,2395,1097,2421"/>
<area shape="rect" title=" " alt="" coords="1121,2395,1179,2421"/>
<area shape="rect" href="../../d1/d44/a00098.php" title=" " alt="" coords="937,1797,1040,1824"/>
<area shape="rect" title=" " alt="" coords="955,1872,1033,1899"/>
<area shape="rect" title=" " alt="" coords="852,1872,931,1899"/>
<area shape="rect" href="../../d2/de7/a00014.php" title=" " alt="" coords="679,1648,811,1675"/>
<area shape="rect" title=" " alt="" coords="449,1723,560,1749"/>
<area shape="rect" title=" " alt="" coords="585,1723,689,1749"/>
<area shape="rect" title=" " alt="" coords="713,1723,763,1749"/>
<area shape="rect" title=" " alt="" coords="788,1723,845,1749"/>
<area shape="rect" title=" " alt="" coords="870,1723,910,1749"/>
<area shape="rect" title=" " alt="" coords="935,1723,989,1749"/>
<area shape="rect" title=" " alt="" coords="846,1349,913,1376"/>
<area shape="rect" href="../../da/dec/a00080.php" title=" " alt="" coords="831,752,906,779"/>
<area shape="rect" href="../../d0/d27/a00239.php" title=" " alt="" coords="731,752,807,779"/>
<area shape="rect" href="../../de/df3/a00185.php" title=" " alt="" coords="1011,453,1185,480"/>
<area shape="rect" href="../../da/d15/a00188.php" title=" " alt="" coords="1019,528,1177,555"/>
<area shape="rect" href="../../d7/d25/a00182.php" title=" " alt="" coords="1042,603,1154,629"/>
<area shape="rect" href="../../dc/d57/a00194.php" title=" " alt="" coords="1018,677,1178,704"/>
<area shape="rect" href="../../db/dd9/a00179.php" title=" " alt="" coords="1175,752,1250,779"/>
<area shape="rect" href="../../d9/dd0/a00191.php" title=" " alt="" coords="981,752,1151,779"/>
<area shape="rect" href="../../dc/dfe/a00125.php" title=" " alt="" coords="758,229,891,256"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/d42/a00109.png" border="0" usemap="#aGene_8hppdep" alt=""/></div>
<map name="Gene_8hppdep" id="Gene_8hppdep">
<area shape="rect" title=" " alt="" coords="307,5,386,32"/>
<area shape="rect" href="../../d9/d2e/a00056.php" title=" " alt="" coords="284,80,409,107"/>
<area shape="rect" href="../../d5/de0/a00050.php" title=" " alt="" coords="311,155,382,181"/>
<area shape="rect" href="../../dd/d32/a00041.php" title=" " alt="" coords="310,229,383,256"/>
<area shape="rect" href="../../d0/d89/a00071.php" title=" " alt="" coords="243,304,357,331"/>
<area shape="rect" href="../../d3/d00/a00113.php" title=" " alt="" coords="341,677,437,704"/>
<area shape="rect" href="../../d1/dc1/a00092.php" title=" " alt="" coords="134,379,213,405"/>
<area shape="rect" href="../../d7/d3f/a00173.php" title=" " alt="" coords="265,379,351,405"/>
<area shape="rect" href="../../d4/d81/a00110.php" title=" " alt="" coords="32,453,120,480"/>
<area shape="rect" href="../../dd/dd7/a00260.php" title=" " alt="" coords="128,528,219,555"/>
<area shape="rect" href="../../d7/d46/a00002.php" title=" " alt="" coords="6,528,93,555"/>
<area shape="rect" href="../../dd/dad/a00005.php" title=" " alt="" coords="5,603,72,629"/>
<area shape="rect" href="../../db/dab/a00089.php" title=" " alt="" coords="223,677,313,704"/>
<area shape="rect" href="../../de/d79/a00203.php" title=" " alt="" coords="194,752,345,779"/>
<area shape="rect" href="../../d3/db1/a00200.php" title=" " alt="" coords="284,827,367,853"/>
<area shape="rect" href="../../d5/df9/a00044.php" title=" " alt="" coords="267,901,384,928"/>
<area shape="rect" href="../../db/ddf/a00164.php" title=" " alt="" coords="97,603,205,629"/>
<area shape="rect" href="../../de/db1/a00197.php" title=" " alt="" coords="229,603,307,629"/>
<area shape="rect" href="../../dd/d52/a00221.php" title=" " alt="" coords="271,453,353,480"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d8/d38/a01299.php">mcd::natural::Gene</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A gene that represent a caracteristic.  <a href="../../d8/d38/a01299.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:db/d12/a00268"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:dd/d86/a00271"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d86/a00271.php">mcd::natural</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="typedef-members"></a>
Typedefs</h2></td></tr>
<tr class="memitem:aed19377fb7721df1a451d93af0c19950"><td class="memItemLeft" align="right" valign="top">typedef std::vector&lt; Gene &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d86/a00271.php#aed19377fb7721df1a451d93af0c19950">mcd::natural::Genes</a></td></tr>
<tr class="separator:aed19377fb7721df1a451d93af0c19950"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a81eb139ff8493e715a8efce3fda3155f"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d86/a00271.php#a81eb139ff8493e715a8efce3fda3155f">mcd::natural::transfer</a> (const Genes &amp;in, Genes &amp;out)</td></tr>
<tr class="memdesc:a81eb139ff8493e715a8efce3fda3155f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Transfer a vector of <a class="el" href="../../d8/d38/a01299.php" title="A gene that represent a caracteristic.">Gene</a> into another one, using the copy method.  <a href="../../dd/d86/a00271.php#a81eb139ff8493e715a8efce3fda3155f">More...</a><br /></td></tr>
<tr class="separator:a81eb139ff8493e715a8efce3fda3155f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Created : Tuesday November, 27 2018 15:12:24 </dd>
<dd>
Last modification : October, 28 2020 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../dir_220287e732b97f08f66e5f221c69df74.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_75b0389167f46f79a101ef8c4434cec4.php">C++</a></li><li class="navelem"><a class="el" href="../../df/d98/a00107.php">Gene.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
