<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: mcd::t_queue&lt; T, Container &gt; Class Template Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Apr 28 2019 10:55:04 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d1/d6f/a00063.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="../../d6/d80/a00371.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">mcd::t_queue&lt; T, Container &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>An thread-safe implementation of queue.  
 <a href="../../d1/d6f/a00063.php#details">More...</a></p>

<p><code>#include &lt;array.hpp&gt;</code></p>
<div class="dynheader">
Inheritance diagram for mcd::t_queue&lt; T, Container &gt;:</div>
<div class="dyncontent">
<div class="center"><img src="../../db/d7e/a00372.png" border="0" usemap="#mcd_1_1t__queue_3_01T_00_01Container_01_4_inherit__map" alt="Inheritance graph"/></div>
<map name="mcd_1_1t__queue_3_01T_00_01Container_01_4_inherit__map" id="mcd_1_1t__queue_3_01T_00_01Container_01_4_inherit__map">
<area shape="rect" id="node2" href="../../d4/d6d/a00055.php" title="An implementation of std::queue. " alt="" coords="11,80,197,107"/>
<area shape="rect" id="node3" title="STL class. " alt="" coords="15,5,193,32"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for mcd::t_queue&lt; T, Container &gt;:</div>
<div class="dyncontent">
<div class="center"><img src="../../dc/de3/a00373.png" border="0" usemap="#mcd_1_1t__queue_3_01T_00_01Container_01_4_coll__map" alt="Collaboration graph"/></div>
<map name="mcd_1_1t__queue_3_01T_00_01Container_01_4_coll__map" id="mcd_1_1t__queue_3_01T_00_01Container_01_4_coll__map">
<area shape="rect" id="node2" href="../../d4/d6d/a00055.php" title="An implementation of std::queue. " alt="" coords="11,171,197,197"/>
<area shape="rect" id="node3" title="STL class. " alt="" coords="15,95,193,121"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a6113ab263c40412573cb17961892e4eb"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d6f/a00063.php#a6113ab263c40412573cb17961892e4eb">t_queue</a> ()</td></tr>
<tr class="separator:a6113ab263c40412573cb17961892e4eb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7108e587ce260901f5fdac365db13fab"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d6f/a00063.php#a7108e587ce260901f5fdac365db13fab">push</a> (const T &amp;value)</td></tr>
<tr class="separator:a7108e587ce260901f5fdac365db13fab"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7ccba4c88decd735670f069077bce0b0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d6f/a00063.php#a7ccba4c88decd735670f069077bce0b0">push</a> (T &amp;&amp;value)</td></tr>
<tr class="separator:a7ccba4c88decd735670f069077bce0b0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00055"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00055')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../d4/d6d/a00055.php">mcd::queue&lt; T, Container &gt;</a></td></tr>
<tr class="memitem:a0566f226253ef02ac813bad965f647b9 inherit pub_methods_a00055"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d6d/a00055.php#a0566f226253ef02ac813bad965f647b9">queue</a> ()</td></tr>
<tr class="separator:a0566f226253ef02ac813bad965f647b9 inherit pub_methods_a00055"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9c9c5803f41517e0b1b8d75441cd4b09 inherit pub_methods_a00055"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d6d/a00055.php#a9c9c5803f41517e0b1b8d75441cd4b09">pop</a> ()</td></tr>
<tr class="memdesc:a9c9c5803f41517e0b1b8d75441cd4b09 inherit pub_methods_a00055"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the first element of the queue and erase it from the queue.  <a href="#a9c9c5803f41517e0b1b8d75441cd4b09">More...</a><br /></td></tr>
<tr class="separator:a9c9c5803f41517e0b1b8d75441cd4b09 inherit pub_methods_a00055"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a148295001e6effa1aa1217af766e021f inherit pub_methods_a00055"><td class="memItemLeft" align="right" valign="top">T&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d6d/a00055.php#a148295001e6effa1aa1217af766e021f">get</a> ()</td></tr>
<tr class="memdesc:a148295001e6effa1aa1217af766e021f inherit pub_methods_a00055"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the first element of the queue and erase it from the queue.  <a href="#a148295001e6effa1aa1217af766e021f">More...</a><br /></td></tr>
<tr class="separator:a148295001e6effa1aa1217af766e021f inherit pub_methods_a00055"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T, class Container = std::deque&lt;T&gt;&gt;<br />
class mcd::t_queue&lt; T, Container &gt;</h3>

<p>An thread-safe implementation of queue. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a6113ab263c40412573cb17961892e4eb"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Container  = std::deque&lt;T&gt;&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d1/d6f/a00063.php">mcd::t_queue</a>&lt; T, Container &gt;::<a class="el" href="../../d1/d6f/a00063.php">t_queue</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d6f/a00063_a6113ab263c40412573cb17961892e4eb_cgraph.png" border="0" usemap="#d1/d6f/a00063_a6113ab263c40412573cb17961892e4eb_cgraph" alt=""/></div>
<map name="d1/d6f/a00063_a6113ab263c40412573cb17961892e4eb_cgraph" id="d1/d6f/a00063_a6113ab263c40412573cb17961892e4eb_cgraph">
<area shape="rect" id="node2" href="../../dd/d1b/a00015.php#aad6be0710fa6c480619505eae0afd547" title="mcd::pop" alt="" coords="208,5,284,32"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a7108e587ce260901f5fdac365db13fab"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Container  = std::deque&lt;T&gt;&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="../../d1/d6f/a00063.php">mcd::t_queue</a>&lt; T, Container &gt;::push </td>
          <td>(</td>
          <td class="paramtype">const T &amp;&#160;</td>
          <td class="paramname"><em>value</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a7ccba4c88decd735670f069077bce0b0"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class Container  = std::deque&lt;T&gt;&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="../../d1/d6f/a00063.php">mcd::t_queue</a>&lt; T, Container &gt;::push </td>
          <td>(</td>
          <td class="paramtype">T &amp;&amp;&#160;</td>
          <td class="paramname"><em>value</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d9/da5/a00075.php">array.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dd/d1b/a00015.php">mcd</a></li><li class="navelem"><a class="el" href="../../d1/d6f/a00063.php">t_queue</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
