<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: Clock.hpp Source File</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Aug 8 2018 09:57:28 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('da/dec/a00080_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Clock.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../da/dec/a00080.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="preprocessor">#ifndef HEADER_CPP_CLOCK</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#define HEADER_CPP_CLOCK</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d9/d77/a00095.php">C++/includes.hpp</a>&quot;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno"><a class="line" href="../../da/da0/a00009.php">   17</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../da/da0/a00009.php">Clock</a> {</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;        <span class="comment">/* Constructor */</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;        <a class="code" href="../../da/da0/a00009.php#adbc370eb6b5f8d01645cf440188160a8">Clock</a>();</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;        <span class="comment">/* Getters */</span></div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;        <a class="code" href="../../dc/dee/a00053.php#a2bf7d302208fe9b09381557fd448e273">double64_t</a> <a class="code" href="../../da/da0/a00009.php#a0a6d71902fea97071c6c4787d75de99e">getElapsed</a>();</div><div class="line"><a name="l00032"></a><span class="lineno"><a class="line" href="../../da/da0/a00009.php#af030d200b960fa7c669df1f55a8cfc68">   32</a></span>&#160;        <a class="code" href="../../dc/dee/a00053.php#a2bf7d302208fe9b09381557fd448e273">double64_t</a> <a class="code" href="../../da/da0/a00009.php#af030d200b960fa7c669df1f55a8cfc68">getStart</a>()<span class="keyword">const </span>{ <span class="keywordflow">return</span> <a class="code" href="../../da/da0/a00009.php#ae16d2f7932e475086f21cc234c347a2c">m_start</a>.time_since_epoch().count(); }</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;        <span class="comment">/* Others */</span></div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/da0/a00009.php#a8a050959dcff11c85d695989e9099a8c">start</a>();</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/da0/a00009.php#a775bf97123b58c768571868341d28b08">restart</a>();</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;    <span class="keyword">protected</span>:</div><div class="line"><a name="l00045"></a><span class="lineno"><a class="line" href="../../da/da0/a00009.php#ae16d2f7932e475086f21cc234c347a2c">   45</a></span>&#160;        std::chrono::high_resolution_clock::time_point <a class="code" href="../../da/da0/a00009.php#ae16d2f7932e475086f21cc234c347a2c">m_start</a>;</div><div class="line"><a name="l00046"></a><span class="lineno"><a class="line" href="../../da/da0/a00009.php#aed945651f59f21f56df523af2719597e">   46</a></span>&#160;        <span class="keywordtype">bool</span> <a class="code" href="../../da/da0/a00009.php#aed945651f59f21f56df523af2719597e">started</a>;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;};</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;<span class="preprocessor">#endif //HEADER_CPP_CLOCK</span></div><div class="ttc" id="a00009_php_af030d200b960fa7c669df1f55a8cfc68"><div class="ttname"><a href="../../da/da0/a00009.php#af030d200b960fa7c669df1f55a8cfc68">Clock::getStart</a></div><div class="ttdeci">double64_t getStart() const </div><div class="ttdoc">Get the time start. </div><div class="ttdef"><b>Definition:</b> Clock.hpp:32</div></div>
<div class="ttc" id="a00009_php_a775bf97123b58c768571868341d28b08"><div class="ttname"><a href="../../da/da0/a00009.php#a775bf97123b58c768571868341d28b08">Clock::restart</a></div><div class="ttdeci">void restart()</div></div>
<div class="ttc" id="a00095_php"><div class="ttname"><a href="../../d9/d77/a00095.php">includes.hpp</a></div></div>
<div class="ttc" id="a00009_php_ae16d2f7932e475086f21cc234c347a2c"><div class="ttname"><a href="../../da/da0/a00009.php#ae16d2f7932e475086f21cc234c347a2c">Clock::m_start</a></div><div class="ttdeci">std::chrono::high_resolution_clock::time_point m_start</div><div class="ttdef"><b>Definition:</b> Clock.hpp:45</div></div>
<div class="ttc" id="a00053_php_a2bf7d302208fe9b09381557fd448e273"><div class="ttname"><a href="../../dc/dee/a00053.php#a2bf7d302208fe9b09381557fd448e273">double64_t</a></div><div class="ttdeci">long double double64_t</div><div class="ttdef"><b>Definition:</b> types.hpp:16</div></div>
<div class="ttc" id="a00009_php_adbc370eb6b5f8d01645cf440188160a8"><div class="ttname"><a href="../../da/da0/a00009.php#adbc370eb6b5f8d01645cf440188160a8">Clock::Clock</a></div><div class="ttdeci">Clock()</div></div>
<div class="ttc" id="a00009_php_aed945651f59f21f56df523af2719597e"><div class="ttname"><a href="../../da/da0/a00009.php#aed945651f59f21f56df523af2719597e">Clock::started</a></div><div class="ttdeci">bool started</div><div class="ttdef"><b>Definition:</b> Clock.hpp:46</div></div>
<div class="ttc" id="a00009_php_a0a6d71902fea97071c6c4787d75de99e"><div class="ttname"><a href="../../da/da0/a00009.php#a0a6d71902fea97071c6c4787d75de99e">Clock::getElapsed</a></div><div class="ttdeci">double64_t getElapsed()</div><div class="ttdoc">Get time elapsed. </div></div>
<div class="ttc" id="a00009_php"><div class="ttname"><a href="../../da/da0/a00009.php">Clock</a></div><div class="ttdoc">A clock to measure the elapsed time. </div><div class="ttdef"><b>Definition:</b> Clock.hpp:17</div></div>
<div class="ttc" id="a00009_php_a8a050959dcff11c85d695989e9099a8c"><div class="ttname"><a href="../../da/da0/a00009.php#a8a050959dcff11c85d695989e9099a8c">Clock::start</a></div><div class="ttdeci">void start()</div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../dir_220287e732b97f08f66e5f221c69df74.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_75b0389167f46f79a101ef8c4434cec4.php">C++</a></li><li class="navelem"><a class="el" href="../../da/dec/a00080.php">Clock.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
