<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: errors.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Dec 1 2019 13:57:10 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/dab/a00089.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#define-members">Macros</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">errors.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d3/d8b/a00059.php">C++/console.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/dc1/a00092.php">C++/files.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for errors.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/dec/a00090.png" border="0" usemap="#errors_8hpp" alt=""/></div>
<map name="errors_8hpp" id="errors_8hpp">
<area shape="rect" id="node2" href="../../d3/d8b/a00059.php" title="C++/console.hpp" alt="" coords="515,80,637,107"/>
<area shape="rect" id="node52" href="../../d1/dc1/a00092.php" title="C++/files.hpp" alt="" coords="661,80,763,107"/>
<area shape="rect" id="node3" href="../../da/d24/a00068.php" title="C++/convert.hpp" alt="" coords="525,155,645,181"/>
<area shape="rect" id="node5" href="../../da/d45/a00011.php" title="C++/array.hpp" alt="" coords="592,229,699,256"/>
<area shape="rect" id="node7" href="../../d5/de0/a00050.php" title="C++/check.hpp" alt="" coords="589,304,701,331"/>
<area shape="rect" id="node51" href="../../dc/d57/a00194.php" title="C++/sorting.hpp" alt="" coords="727,304,843,331"/>
<area shape="rect" id="node10" href="../../d6/de1/a00233.php" title="C++/vector.hpp" alt="" coords="730,379,843,405"/>
<area shape="rect" id="node45" href="../../d9/d2e/a00056.php" title="C++/collides.hpp" alt="" coords="585,379,706,405"/>
<area shape="rect" id="node11" href="../../d2/de7/a00014.php" title="C++/arraysIncludes.hpp" alt="" coords="751,453,913,480"/>
<area shape="rect" id="node18" href="../../d7/d25/a00182.php" title="C++/pointers.hpp" alt="" coords="713,752,836,779"/>
<area shape="rect" id="node19" href="../../d9/d01/a00227.php" title="C++/types.hpp" alt="" coords="612,827,721,853"/>
<area shape="rect" id="node21" href="../../d3/d52/a00023.php" title="Big.hpp" alt="" coords="633,901,700,928"/>
<area shape="rect" id="node40" href="../../d5/ddf/a00224.php" title="C++/Tree.hpp" alt="" coords="506,901,609,928"/>
<area shape="rect" id="node41" href="../../de/df3/a00185.php" title="PureVirtual.hpp" alt="" coords="725,901,835,928"/>
<area shape="rect" id="node42" href="../../d1/da8/a00230.php" title="UsefullDefines.hpp" alt="" coords="860,901,993,928"/>
<area shape="rect" id="node22" href="../../d7/d9a/a00152.php" title="C++/OsDetection.hpp" alt="" coords="322,976,473,1003"/>
<area shape="rect" id="node36" href="../../d5/d16/a00029.php" title="C++/Big_Constructor.hpp" alt="" coords="1035,976,1205,1003"/>
<area shape="rect" id="node37" href="../../d4/d8c/a00035.php" title="C++/Big_Operator.hpp" alt="" coords="497,976,650,1003"/>
<area shape="rect" id="node38" href="../../d6/d5b/a00026.php" title="C++/Big_Comparison.hpp" alt="" coords="675,976,848,1003"/>
<area shape="rect" id="node39" href="../../dc/d87/a00032.php" title="C++/Big_Maths.hpp" alt="" coords="872,976,1011,1003"/>
<area shape="rect" id="node24" href="../../d3/d00/a00113.php" title="C++/lowIncludes.hpp" alt="" coords="391,1051,537,1077"/>
<area shape="rect" id="node46" href="../../dc/dfe/a00125.php" title="C++/Matrix.hpp" alt="" coords="543,453,657,480"/>
<area shape="rect" id="node47" href="../../d9/d77/a00095.php" title="C++/Fraction.hpp" alt="" coords="419,528,543,555"/>
<area shape="rect" id="node48" href="../../df/dc8/a00122.php" title="C++/maths.hpp" alt="" coords="425,603,538,629"/>
<area shape="rect" id="node49" href="../../d8/d41/a00038.php" title="C++/Binary.hpp" alt="" coords="671,677,785,704"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d82/a00091.png" border="0" usemap="#errors_8hppdep" alt=""/></div>
<map name="errors_8hppdep" id="errors_8hppdep">
<area shape="rect" id="node2" href="../../d5/df1/a00206.php" title="system.hpp" alt="" coords="330,80,421,107"/>
<area shape="rect" id="node3" href="../../d3/db1/a00200.php" title="string.hpp" alt="" coords="336,155,415,181"/>
<area shape="rect" id="node4" href="../../de/d79/a00203.php" title="Used to replace strptime function when compiling for Windows. " alt="" coords="335,229,415,256"/>
<area shape="rect" id="node5" href="../../dc/d9a/a00218.php" title="timeFunctions.hpp" alt="" coords="311,304,440,331"/>
<area shape="rect" id="node6" href="../../d0/dc2/a00104.php" title="includes.hpp" alt="" coords="328,379,423,405"/>
<area shape="rect" id="node7" href="../../dc/dee/a00053.php" title="Clock.hpp" alt="" coords="5,603,87,629"/>
<area shape="rect" id="node31" href="../../df/d03/a00062.php" title="ConsoleTable.hpp" alt="" coords="116,677,243,704"/>
<area shape="rect" id="node32" href="../../db/db6/a00074.php" title="Date.hpp" alt="" coords="162,453,237,480"/>
<area shape="rect" id="node34" href="../../df/d98/a00107.php" title="IOConfig.hpp" alt="" coords="318,528,417,555"/>
<area shape="rect" id="node35" href="../../d3/df8/a00155.php" title="Path.hpp" alt="" coords="413,453,487,480"/>
<area shape="rect" id="node41" href="../../dc/de6/a00167.php" title="PathfindingException.hpp" alt="" coords="511,453,682,480"/>
<area shape="rect" id="node42" href="../../da/d15/a00188.php" title="Referenced.hpp" alt="" coords="605,603,719,629"/>
<area shape="rect" id="node43" href="../../dd/dc1/a00212.php" title="Threadable.hpp" alt="" coords="715,752,825,779"/>
<area shape="rect" id="node46" href="../../d3/dd5/a00215.php" title="Time.hpp" alt="" coords="261,453,337,480"/>
<area shape="rect" id="node8" href="../../da/dec/a00080.php" title="defines.hpp" alt="" coords="356,901,445,928"/>
<area shape="rect" id="node9" href="../../db/db2/a00020.php" title="AssertionException.hpp" alt="" coords="262,976,422,1003"/>
<area shape="rect" id="node30" href="../../d0/d89/a00071.php" title="cryptage.hpp" alt="" coords="409,1051,507,1077"/>
<area shape="rect" id="node10" href="../../d4/d51/a00017.php" title="Assert.hpp" alt="" coords="299,1051,385,1077"/>
<area shape="rect" id="node11" href="../../d6/d2d/a00047.php" title="C++lib.hpp" alt="" coords="356,1125,443,1152"/>
<area shape="rect" id="node12" href="../../d4/d81/a00110.php" title="Logger.hpp" alt="" coords="304,1200,391,1227"/>
<area shape="rect" id="node29" href="../../d3/de5/a00209.php" title="Test.hpp" alt="" coords="415,1200,488,1227"/>
<area shape="rect" id="node13" href="../../dd/d32/a00041.php" title="C++.hpp" alt="" coords="363,1275,436,1301"/>
<area shape="rect" id="node14" href="../../de/de1/a00065.php" title="Contraption.hpp" alt="" coords="295,1349,410,1376"/>
<area shape="rect" id="node28" href="../../d4/d3a/a00101.php" title="Identifier.hpp" alt="" coords="395,1723,492,1749"/>
<area shape="rect" id="node15" href="../../da/d2a/a00086.php" title="Entity.hpp" alt="" coords="199,1424,280,1451"/>
<area shape="rect" id="node26" href="../../da/d1e/a00149.php" title="Object.hpp" alt="" coords="318,1424,403,1451"/>
<area shape="rect" id="node16" href="../../d1/d44/a00098.php" title="Hostile.hpp" alt="" coords="85,1499,173,1525"/>
<area shape="rect" id="node23" href="../../d7/d40/a00236.php" title="Vegetal.hpp" alt="" coords="194,1573,285,1600"/>
<area shape="rect" id="node17" href="../../d7/d46/a00002.php" title="Animal.hpp" alt="" coords="56,1573,143,1600"/>
<area shape="rect" id="node18" href="../../dd/dad/a00005.php" title="Ant.hpp" alt="" coords="58,1648,125,1675"/>
<area shape="rect" id="node19" href="../../d2/d1f/a00083.php" title="Entities.hpp" alt="" coords="275,1723,366,1749"/>
<area shape="rect" id="node20" href="../../db/dd9/a00179.php" title="PlayerAbstraction.hpp" alt="" coords="248,1797,399,1824"/>
<area shape="rect" id="node21" href="../../d5/de9/a00176.php" title="Player.hpp" alt="" coords="337,1872,421,1899"/>
<area shape="rect" id="node22" href="../../d5/df9/a00044.php" title="C++Entities.hpp" alt="" coords="321,1947,438,1973"/>
<area shape="rect" id="node24" href="../../d5/db1/a00140.php" title="Mushroom.hpp" alt="" coords="149,1648,257,1675"/>
<area shape="rect" id="node25" href="../../d7/d3f/a00173.php" title="Plant.hpp" alt="" coords="282,1648,359,1675"/>
<area shape="rect" id="node27" href="../../de/db1/a00197.php" title="Stone.hpp" alt="" coords="328,1499,409,1525"/>
<area shape="rect" id="node33" href="../../d1/d09/a00077.php" title="DateTime.hpp" alt="" coords="190,528,294,555"/>
<area shape="rect" id="node36" href="../../d5/dcb/a00170.php" title="PathfindingProblem.hpp" alt="" coords="441,528,601,555"/>
<area shape="rect" id="node37" href="../../d6/db8/a00158.php" title="Pathfinding.hpp" alt="" coords="438,603,550,629"/>
<area shape="rect" id="node38" href="../../db/ddf/a00164.php" title="PathfindingDijkstra.hpp" alt="" coords="402,677,559,704"/>
<area shape="rect" id="node39" href="../../d6/d7d/a00161.php" title="PathfindingAlgorithms.hpp" alt="" coords="389,752,564,779"/>
<area shape="rect" id="node40" href="../../df/d6a/a00119.php" title="Map.hpp" alt="" coords="415,827,487,853"/>
<area shape="rect" id="node44" href="../../d4/dee/a00008.php" title="Args.hpp" alt="" coords="639,827,714,853"/>
<area shape="rect" id="node45" href="../../dd/d52/a00221.php" title="Timer.hpp" alt="" coords="738,827,818,853"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:d6/d08/a00244"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d08/a00244.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="define-members"></a>
Macros</h2></td></tr>
<tr class="memitem:a08ee21f84a6b44ca59d7f045b55d6bfc"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>&#160;&#160;&#160;__LINE__</td></tr>
<tr class="memdesc:a08ee21f84a6b44ca59d7f045b55d6bfc"><td class="mdescLeft">&#160;</td><td class="mdescRight">Define to do an alias of <b>LINE</b>  <a href="#a08ee21f84a6b44ca59d7f045b55d6bfc">More...</a><br /></td></tr>
<tr class="separator:a08ee21f84a6b44ca59d7f045b55d6bfc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6743e67ef3323372193a9936858a6fb8"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/dab/a00089.php#a6743e67ef3323372193a9936858a6fb8">debug_dlog</a>()&#160;&#160;&#160;<a class="el" href="../../db/dab/a00089.php#a33a5e22684c459c3d752ddee8f5e0915">debug_ilog</a>()</td></tr>
<tr class="separator:a6743e67ef3323372193a9936858a6fb8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a33a5e22684c459c3d752ddee8f5e0915"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/dab/a00089.php#a33a5e22684c459c3d752ddee8f5e0915">debug_ilog</a>()&#160;&#160;&#160;info_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__)</td></tr>
<tr class="separator:a33a5e22684c459c3d752ddee8f5e0915"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abfef935e08c6c7f3d9247920b01659b1"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/dab/a00089.php#abfef935e08c6c7f3d9247920b01659b1">debug_elog</a>()&#160;&#160;&#160;error_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__)</td></tr>
<tr class="separator:abfef935e08c6c7f3d9247920b01659b1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acaeb75ef78e20ba74be61d159e670373"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/dab/a00089.php#acaeb75ef78e20ba74be61d159e670373">debug_wlog</a>()&#160;&#160;&#160;warning_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__)</td></tr>
<tr class="separator:acaeb75ef78e20ba74be61d159e670373"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a54252dbab5b5524cae2163d7c4bbf456"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/dab/a00089.php#a54252dbab5b5524cae2163d7c4bbf456">debug_dlogs</a>(...)&#160;&#160;&#160;<a class="el" href="../../db/dab/a00089.php#a03901e920751bab486efba87b39f2707">debug_ilogs</a>( __VA_ARGS__)</td></tr>
<tr class="separator:a54252dbab5b5524cae2163d7c4bbf456"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a03901e920751bab486efba87b39f2707"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/dab/a00089.php#a03901e920751bab486efba87b39f2707">debug_ilogs</a>(...)&#160;&#160;&#160;info_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__, __VA_ARGS__)</td></tr>
<tr class="separator:a03901e920751bab486efba87b39f2707"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adadf91083b9bc12bba2cf639e5b7aa21"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/dab/a00089.php#adadf91083b9bc12bba2cf639e5b7aa21">debug_elogs</a>(...)&#160;&#160;&#160;error_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__, __VA_ARGS__)</td></tr>
<tr class="separator:adadf91083b9bc12bba2cf639e5b7aa21"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a05518c3c201982924254d7df8cc2d910"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/dab/a00089.php#a05518c3c201982924254d7df8cc2d910">debug_wlogs</a>(...)&#160;&#160;&#160;warning_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__, __VA_ARGS__)</td></tr>
<tr class="separator:a05518c3c201982924254d7df8cc2d910"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a1a14f66f0c6eba0c77338364977658e1"><td class="memTemplParams" colspan="2">template&lt;class T , class ... Args&gt; </td></tr>
<tr class="memitem:a1a14f66f0c6eba0c77338364977658e1"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d6/d08/a00244.php#a1a14f66f0c6eba0c77338364977658e1">mcd::error_log</a> (size_t line, T in, Args... args)</td></tr>
<tr class="memdesc:a1a14f66f0c6eba0c77338364977658e1"><td class="mdescLeft">&#160;</td><td class="mdescRight">Print the given text like an error.  <a href="../../d6/d08/a00244.php#a1a14f66f0c6eba0c77338364977658e1">More...</a><br /></td></tr>
<tr class="separator:a1a14f66f0c6eba0c77338364977658e1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac625de83fcace96567aecd1363297776"><td class="memTemplParams" colspan="2">template&lt;class T , class ... Args&gt; </td></tr>
<tr class="memitem:ac625de83fcace96567aecd1363297776"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d6/d08/a00244.php#ac625de83fcace96567aecd1363297776">mcd::warning_log</a> (size_t line, T in, Args... args)</td></tr>
<tr class="memdesc:ac625de83fcace96567aecd1363297776"><td class="mdescLeft">&#160;</td><td class="mdescRight">Print the given text like a warning.  <a href="../../d6/d08/a00244.php#ac625de83fcace96567aecd1363297776">More...</a><br /></td></tr>
<tr class="separator:ac625de83fcace96567aecd1363297776"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af0b4fd6390d33edc9719d42b26f6e29f"><td class="memTemplParams" colspan="2">template&lt;class T , class ... Args&gt; </td></tr>
<tr class="memitem:af0b4fd6390d33edc9719d42b26f6e29f"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="../../d6/d08/a00244.php#af0b4fd6390d33edc9719d42b26f6e29f">mcd::info_log</a> (size_t line, T in, Args... args)</td></tr>
<tr class="memdesc:af0b4fd6390d33edc9719d42b26f6e29f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Print the given text like an information.  <a href="../../d6/d08/a00244.php#af0b4fd6390d33edc9719d42b26f6e29f">More...</a><br /></td></tr>
<tr class="separator:af0b4fd6390d33edc9719d42b26f6e29f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>November, 09 2019 </dd></dl>
</div><h2 class="groupheader">Macro Definition Documentation</h2>
<a id="a6743e67ef3323372193a9936858a6fb8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a6743e67ef3323372193a9936858a6fb8">&#9670;&nbsp;</a></span>debug_dlog</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define debug_dlog</td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td>&#160;&#160;&#160;<a class="el" href="../../db/dab/a00089.php#a33a5e22684c459c3d752ddee8f5e0915">debug_ilog</a>()</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a54252dbab5b5524cae2163d7c4bbf456"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a54252dbab5b5524cae2163d7c4bbf456">&#9670;&nbsp;</a></span>debug_dlogs</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define debug_dlogs</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>...</em></td><td>)</td>
          <td>&#160;&#160;&#160;<a class="el" href="../../db/dab/a00089.php#a03901e920751bab486efba87b39f2707">debug_ilogs</a>( __VA_ARGS__)</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="abfef935e08c6c7f3d9247920b01659b1"></a>
<h2 class="memtitle"><span class="permalink"><a href="#abfef935e08c6c7f3d9247920b01659b1">&#9670;&nbsp;</a></span>debug_elog</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define debug_elog</td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td>&#160;&#160;&#160;error_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__)</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="adadf91083b9bc12bba2cf639e5b7aa21"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adadf91083b9bc12bba2cf639e5b7aa21">&#9670;&nbsp;</a></span>debug_elogs</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define debug_elogs</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>...</em></td><td>)</td>
          <td>&#160;&#160;&#160;error_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__, __VA_ARGS__)</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a33a5e22684c459c3d752ddee8f5e0915"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a33a5e22684c459c3d752ddee8f5e0915">&#9670;&nbsp;</a></span>debug_ilog</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define debug_ilog</td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td>&#160;&#160;&#160;info_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__)</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a03901e920751bab486efba87b39f2707"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a03901e920751bab486efba87b39f2707">&#9670;&nbsp;</a></span>debug_ilogs</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define debug_ilogs</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>...</em></td><td>)</td>
          <td>&#160;&#160;&#160;info_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__, __VA_ARGS__)</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="acaeb75ef78e20ba74be61d159e670373"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acaeb75ef78e20ba74be61d159e670373">&#9670;&nbsp;</a></span>debug_wlog</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define debug_wlog</td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td>&#160;&#160;&#160;warning_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__)</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a05518c3c201982924254d7df8cc2d910"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a05518c3c201982924254d7df8cc2d910">&#9670;&nbsp;</a></span>debug_wlogs</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define debug_wlogs</td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>...</em></td><td>)</td>
          <td>&#160;&#160;&#160;warning_log(<a class="el" href="../../db/dab/a00089.php#a08ee21f84a6b44ca59d7f045b55d6bfc">line_number</a>, __FILE__, __VA_ARGS__)</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a08ee21f84a6b44ca59d7f045b55d6bfc"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a08ee21f84a6b44ca59d7f045b55d6bfc">&#9670;&nbsp;</a></span>line_number</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define line_number&#160;&#160;&#160;__LINE__</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Define to do an alias of <b>LINE</b> </p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../db/dab/a00089.php">errors.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
