<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: Member List</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Thu Aug 9 2018 09:14:33 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d2/de7/a00014.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Contraption Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../d2/de7/a00014.php">Contraption</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a6cbb52b9ef8ee0ffba677c79290da3a5">addPosition</a>(double64_t x, double64_t y, double64_t z=0)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#ac80a221d48732cc349d5ccef1e4ad319">Contraption</a>(Map *map=nullptr, Point pt={0, 0, 0}, ContraptionAttr attr={0, 0, 0})</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a8078072bd826e3494d66a82ebf21754e">getA</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a9993ab6cac0ce33ea91485965572cba9">getAttributes</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a9719243bd6cfcc7b4aaea3aa1623d6c9">getH</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a3b6d4a5f2d520dfa5e58afe5b421a126">getLevel</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a3ca9a1e5aff93640d295576af62b7202">getMap</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#abc9cc2cd7e06c45e4c0edf96f405bae2">getPosition</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#ad4558d52105c2ad89f7eef6ead603286">getRelativeZ</a>(Contraption &amp;obj)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a797f24e736a2d9fb49324219ce5ff493">getW</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a8e37d9aa83c5a7074a73b0629c92bca9">getX</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a384fbc78faf68407ed47efc23608801d">getY</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a9718691fe70bd1855414ccf74a23f995">getZ</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a763a20bdd6cf99e565f2516d1c4bb161">operator&lt;&lt;</a>(std::ostream &amp;stream, Contraption const &amp;in)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a6dedcd33d891a22ae7d6ce4d7e1d6a37">printInfos</a>(std::ostream &amp;stream) const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#aac3b312b278f4e56cd4806ec3b8b1760">sender</a>(std::string, vector_str)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#adc32e0091645e3ff58587b3915680d81">setA</a>(double64_t angle)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a3e221cb1cdd414d2d06492b575ec7120">setAttributes</a>(ContraptionAttr attr)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a6f32609c67a5031667bca0160cc3c4b0">setAttributes</a>(double64_t w, double64_t h, double64_t angle=0)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a7efde486fe106d3878755b9db1127d88">setH</a>(double64_t h)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#ae9131d3133c67c22f8692d4bd806187e">setLevel</a>(size_t level)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a0d88e87317d6f003471fcf52808a4a25">setMap</a>(Map *map)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a05facc668dcb27c1bab72118aa5bafe7">setPosition</a>(Point pt)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a4bfbd30624b084959f42291f2702a723">setPosition</a>(double64_t x, double64_t y, double64_t z=0)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a1102b32324b755d0fa4ed68a4fbbff72">setW</a>(double64_t w)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a33238305b6740a899553d139d2c6f522">setX</a>(double64_t x)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a42e1a00e1ad5acaa84121a8e86cd4d02">setY</a>(double64_t y)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#ad6f7d1d6ad29714e30947ca89a4812a0">setZ</a>(double64_t z)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#ab69fdcd66f63e0a038a4006d43ecb9b6">turnLeft</a>()</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a20f271c846ea0c8bc96c618616a260ba">turnRight</a>()</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#acfdea93e7835722a3b211ba2b8dd1463">~Contraption</a>()</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
