<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: NotCopyable.hpp Source File</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Aug 8 2018 09:57:28 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d0/d61/a00100_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">NotCopyable.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d0/d61/a00100.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#ifndef HEADER_CPP_NOT_COPYABLE</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">#define HEADER_CPP_NOT_COPYABLE</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00016"></a><span class="lineno"><a class="line" href="../../dd/d32/a00041.php">   16</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../dd/d32/a00041.php">NotCopyable</a> {</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;    <span class="comment">/* Usefull or required defines */</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;        </div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;    <span class="comment">/* Members of NotCopyable */</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;        <span class="comment">/* Internal enums of NotCopyable */</span></div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;            </div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <span class="comment">/* Constructors &amp; Destructor of NotCopyable */</span></div><div class="line"><a name="l00025"></a><span class="lineno"><a class="line" href="../../dd/d32/a00041.php#a87c521041c0abcb674e5a86cf80b166a">   25</a></span>&#160;            <a class="code" href="../../dd/d32/a00041.php#a87c521041c0abcb674e5a86cf80b166a">NotCopyable</a>(){}</div><div class="line"><a name="l00026"></a><span class="lineno"><a class="line" href="../../dd/d32/a00041.php#ae53078d7e98da1578717f862f9166996">   26</a></span>&#160;            <span class="keyword">virtual</span> <a class="code" href="../../dd/d32/a00041.php#ae53078d7e98da1578717f862f9166996">~NotCopyable</a>(){}</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;        <span class="comment">/* Getters of NotCopyable */</span></div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;            </div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;        <span class="comment">/* Setters of NotCopyable */</span></div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;            </div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;        <span class="comment">/* Statics of NotCopyable */</span></div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;            </div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;        <span class="comment">/* Operators of NotCopyable */</span></div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;            </div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;        <span class="comment">/* Friends of NotCopyable */</span></div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;            </div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;        <span class="comment">/* Others members of NotCopyable */</span></div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;            </div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;    <span class="keyword">protected</span>:</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;        <span class="comment">/* Getters of NotCopyable */</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;            </div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;        <span class="comment">/* Setters of NotCopyable */</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;            </div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;        <span class="comment">/* Statics of NotCopyable */</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;            </div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;        <span class="comment">/* Friends of NotCopyable */</span></div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;            </div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;        <span class="comment">/* Others members of NotCopyable */</span></div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;            </div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;            <a class="code" href="../../dd/d32/a00041.php#a87c521041c0abcb674e5a86cf80b166a">NotCopyable</a>(<span class="keyword">const</span> <a class="code" href="../../dd/d32/a00041.php">NotCopyable</a>&amp;){}</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;            <a class="code" href="../../dd/d32/a00041.php#a87c521041c0abcb674e5a86cf80b166a">NotCopyable</a>(<span class="keyword">const</span> <a class="code" href="../../dd/d32/a00041.php">NotCopyable</a>&amp;&amp;){}</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;            <a class="code" href="../../dd/d32/a00041.php">NotCopyable</a>&amp; operator=(<span class="keyword">const</span> <a class="code" href="../../dd/d32/a00041.php">NotCopyable</a>&amp;) noexcept { <span class="keywordflow">return</span> *<span class="keyword">this</span>; }</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;            <a class="code" href="../../dd/d32/a00041.php">NotCopyable</a>&amp; operator=(<span class="keyword">const</span> <a class="code" href="../../dd/d32/a00041.php">NotCopyable</a>&amp;&amp;) noexcept { <span class="keywordflow">return</span> *<span class="keyword">this</span>; }</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;    <span class="comment">/* Atttributes of NotCopyable */</span></div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;        <span class="comment">/* Global */</span></div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;            </div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;        <span class="comment">/* Local */</span></div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;            </div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;    <span class="keyword">protected</span>:</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;        <span class="comment">/* Global */</span></div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;            </div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;        <span class="comment">/* Local */</span></div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;            </div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;        <span class="comment">/* Global */</span></div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;            </div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;        <span class="comment">/* Local */</span></div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;            </div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;};</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;<span class="preprocessor">#endif //HEADER_CPP_NOT_COPYABLE</span></div><div class="ttc" id="a00041_php_a87c521041c0abcb674e5a86cf80b166a"><div class="ttname"><a href="../../dd/d32/a00041.php#a87c521041c0abcb674e5a86cf80b166a">NotCopyable::NotCopyable</a></div><div class="ttdeci">NotCopyable()</div><div class="ttdoc">The constructor of the class. </div><div class="ttdef"><b>Definition:</b> NotCopyable.hpp:25</div></div>
<div class="ttc" id="a00041_php"><div class="ttname"><a href="../../dd/d32/a00041.php">NotCopyable</a></div><div class="ttdoc">A class to let some other not to be copyable. </div><div class="ttdef"><b>Definition:</b> NotCopyable.hpp:16</div></div>
<div class="ttc" id="a00041_php_ae53078d7e98da1578717f862f9166996"><div class="ttname"><a href="../../dd/d32/a00041.php#ae53078d7e98da1578717f862f9166996">NotCopyable::~NotCopyable</a></div><div class="ttdeci">virtual ~NotCopyable()</div><div class="ttdef"><b>Definition:</b> NotCopyable.hpp:26</div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../dir_220287e732b97f08f66e5f221c69df74.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_75b0389167f46f79a101ef8c4434cec4.php">C++</a></li><li class="navelem"><a class="el" href="../../d0/d61/a00100.php">NotCopyable.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
