<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: Member List</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Thu Aug 9 2018 09:14:33 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('de/d5e/a00007.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Big Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../de/d5e/a00007.php">Big</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#ab9960634344b0e7683f0a43866efdfb7">Big</a>(T val)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#af5137ca3a645f0385386562e230f3651">Big</a>(std::string val)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a9e3d0d8c5f1729e3fbb3996b4c3c589d">Big</a>()</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#ae380a9622d1011d5f9fb550146ec00aa">Big</a>(const Big &amp;other)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a422ae51cf459d75650c428ce4e98404e">Big</a>(const Big &amp;&amp;other)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a2ed0b910c5ed7ec9875836082c63baa8">mod</a>(const Big &amp;a, const Big &amp;b)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aa3f0bc97d7c74a25af25962aa2bec33f">nroot</a>(const Big &amp;a, uint64_t exp)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a03872cd0c9c90225059aa7c04a87417f">operator std::string</a>() const noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aaeca4e372966fe2b3b857d52880ca210">operator!</a>(const Big &amp;a) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#ad9c55799e64051a79feb72642bacc2bd">operator!=</a>(const Big &amp;a, const Big &amp;b) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a8082f5075921a15bedfa304ddc5f0bfa">operator%</a>(const Big &amp;a, const Big &amp;b)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a4c54efc3d3e0678e3c5df17582dd3474">operator%=</a>(const Big &amp;other)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aef65b2815526a32f3da7094648cb5ef7">operator*</a>(const Big &amp;a, const Big &amp;b) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#ab6efe526ce133c1d8faab4c6c1030a20">operator*=</a>(const Big &amp;other) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#ad475b8459ee2ea450eecbc0b2a49f221">operator+</a>(const Big &amp;in) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a4097440072b14b44b9f362be9bc7faa0">operator+</a>(const Big &amp;a, const Big &amp;b) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aa74d80c3933bcb0736cd466c4e040daa">operator++</a>(Big &amp;in) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aa3a36b3d1c1231ff86d60627588ff841">operator++</a>(Big &amp;in, int) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#af62222b4c7617f3e083faa9791c4358d">operator+=</a>(const Big &amp;other) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a8d411571b65ece2daacc12f0293850e8">operator-</a>(const Big &amp;in) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aa7b2588e5feb48f5dd51983be1ee0457">operator-</a>(const Big &amp;a, const Big &amp;b) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#ac81326310b387979cb8976c802059fda">operator--</a>(Big &amp;in) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aa6f2c60de8962b9f45a79b656ee2ca51">operator--</a>(Big &amp;in, int) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a95b72b322bdd5d6de45c3b4f9e587d4a">operator-=</a>(const Big &amp;other) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aa0213bc63f03a5db6ec4d081b9320a96">operator/</a>(const Big &amp;a, const Big &amp;b)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#ae9d4bb05ec679184419914b8e2de13f6">operator/=</a>(const Big &amp;other)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a9c625348272715ed4dad2c1420fb5bd0">operator&lt;</a>(const Big &amp;a, const Big &amp;b) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a6d1ae6342e0dd6f689535b21fd46a023">operator&lt;&lt;</a>(std::ostream &amp;os, const Big &amp;other) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a74e55e1a85a44b255d0f8e1158e02658">operator&lt;=</a>(const Big &amp;a, const Big &amp;b) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a4955126f4af91d3a66e615eb4d183df4">operator=</a>(const Big &amp;other) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a62ce1f9d71b177e39a6f607ccdb9ecc4">operator=</a>(const Big &amp;&amp;other) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a5eed09966f2142f9d979e7be4643c06a">operator==</a>(const Big &amp;a, const Big &amp;b) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#ac75c3d550acaece7444e1d3373e0ced6">operator&gt;</a>(const Big &amp;a, const Big &amp;b) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#adf83d734f0c4b777bb675bf327996987">operator&gt;=</a>(const Big &amp;a, const Big &amp;b) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a91ce80d3959e1d2a891e58c940c8631b">operator&gt;&gt;</a>(std::istream &amp;is, Big &amp;other) noexcept</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aa6a7af66a5c239b2b46979e998c43679">pgcd</a>(const Big &amp;a, const Big &amp;b)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a9d40406ec9457a1565a2b0c60585ae9b">pow</a>(const Big &amp;a, const Big &amp;exp)</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">friend</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a90940d0adee92ed5b045d685acedbee1">prime</a>() const </td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../de/d5e/a00007.php#aef4befbad12a6f89a500349b0f3f0fe7">size</a>() const </td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../de/d5e/a00007.php#a1cbc94bd3fe5f63ea23c9d4feef6bc82">~Big</a>()</td><td class="entry"><a class="el" href="../../de/d5e/a00007.php">Big</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
