<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: mcd::console::SetPrecision Class Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.3.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 18 2020 14:47:42 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('d8/db0/a01243.php','../../'); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#friends">Friends</a> &#124;
<a href="../../d5/d6e/a01240.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">mcd::console::SetPrecision Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Change the precision of a std::ostream and save the default value.  
 <a href="../../d8/db0/a01243.php#details">More...</a></p>

<p><code>#include &lt;console.hpp&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a75f2e148d3eb7a84c8d499367c0eae7a"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d8/db0/a01243.php#a75f2e148d3eb7a84c8d499367c0eae7a">SetPrecision</a> ()</td></tr>
<tr class="memdesc:a75f2e148d3eb7a84c8d499367c0eae7a"><td class="mdescLeft">&#160;</td><td class="mdescRight">Construct a <a class="el" href="../../d8/db0/a01243.php" title="Change the precision of a std::ostream and save the default value.">SetPrecision</a> object and save the default value of std::cout.  <a href="../../d8/db0/a01243.php#a75f2e148d3eb7a84c8d499367c0eae7a">More...</a><br /></td></tr>
<tr class="separator:a75f2e148d3eb7a84c8d499367c0eae7a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ace1afba2de5729ff45bcd7386e6c53a8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d8/db0/a01243.php#ace1afba2de5729ff45bcd7386e6c53a8">~SetPrecision</a> ()</td></tr>
<tr class="separator:ace1afba2de5729ff45bcd7386e6c53a8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af082d3196dd332150a4ecf0db312c20e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../d8/db0/a01243.php">SetPrecision</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d8/db0/a01243.php#af082d3196dd332150a4ecf0db312c20e">operator()</a> ()</td></tr>
<tr class="memdesc:af082d3196dd332150a4ecf0db312c20e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Reset the precision to the default value.  <a href="../../d8/db0/a01243.php#af082d3196dd332150a4ecf0db312c20e">More...</a><br /></td></tr>
<tr class="separator:af082d3196dd332150a4ecf0db312c20e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a87819cdb250da9a9e9428b143c8201b6"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../d8/db0/a01243.php">SetPrecision</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d8/db0/a01243.php#a87819cdb250da9a9e9428b143c8201b6">operator()</a> (std::streamsize value)</td></tr>
<tr class="memdesc:a87819cdb250da9a9e9428b143c8201b6"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the precision to value.  <a href="../../d8/db0/a01243.php#a87819cdb250da9a9e9428b143c8201b6">More...</a><br /></td></tr>
<tr class="separator:a87819cdb250da9a9e9428b143c8201b6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="friends"></a>
Friends</h2></td></tr>
<tr class="memitem:a5a120231654267de5f32512a83c99521"><td class="memItemLeft" align="right" valign="top">std::ostream &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d8/db0/a01243.php#a5a120231654267de5f32512a83c99521">operator&lt;&lt;</a> (std::ostream &amp;os, const <a class="el" href="../../d8/db0/a01243.php">SetPrecision</a> &amp;other)</td></tr>
<tr class="separator:a5a120231654267de5f32512a83c99521"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Change the precision of a std::ostream and save the default value. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a75f2e148d3eb7a84c8d499367c0eae7a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a75f2e148d3eb7a84c8d499367c0eae7a">&#9670;&nbsp;</a></span>SetPrecision()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">mcd::console::SetPrecision::SetPrecision </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Construct a <a class="el" href="../../d8/db0/a01243.php" title="Change the precision of a std::ostream and save the default value.">SetPrecision</a> object and save the default value of std::cout. </p>

</div>
</div>
<a id="ace1afba2de5729ff45bcd7386e6c53a8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ace1afba2de5729ff45bcd7386e6c53a8">&#9670;&nbsp;</a></span>~SetPrecision()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">mcd::console::SetPrecision::~SetPrecision </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="af082d3196dd332150a4ecf0db312c20e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af082d3196dd332150a4ecf0db312c20e">&#9670;&nbsp;</a></span>operator()() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d8/db0/a01243.php">SetPrecision</a>&amp; mcd::console::SetPrecision::operator() </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Reset the precision to the default value. </p>

</div>
</div>
<a id="a87819cdb250da9a9e9428b143c8201b6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a87819cdb250da9a9e9428b143c8201b6">&#9670;&nbsp;</a></span>operator()() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../d8/db0/a01243.php">SetPrecision</a>&amp; mcd::console::SetPrecision::operator() </td>
          <td>(</td>
          <td class="paramtype">std::streamsize&#160;</td>
          <td class="paramname"><em>value</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the precision to value. </p>

</div>
</div>
<h2 class="groupheader">Friends And Related Function Documentation</h2>
<a id="a5a120231654267de5f32512a83c99521"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5a120231654267de5f32512a83c99521">&#9670;&nbsp;</a></span>operator&lt;&lt;</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::ostream&amp; operator&lt;&lt; </td>
          <td>(</td>
          <td class="paramtype">std::ostream &amp;&#160;</td>
          <td class="paramname"><em>os</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="../../d8/db0/a01243.php">SetPrecision</a> &amp;&#160;</td>
          <td class="paramname"><em>other</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">friend</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../de/de1/a00065.php">console.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../db/d12/a00268.php">mcd</a></li><li class="navelem"><a class="el" href="../../d9/d2a/a00270.php">console</a></li><li class="navelem"><a class="el" href="../../d8/db0/a01243.php">SetPrecision</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
