<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Big_Comparison.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sat Nov 23 2019 16:47:47 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d6/d5b/a00026.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">Big_Comparison.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../dc/d3c/a00028.png" border="0" usemap="#Big__Comparison_8hppdep" alt=""/></div>
<map name="Big__Comparison_8hppdep" id="Big__Comparison_8hppdep">
<area shape="rect" id="node2" href="../../d3/d52/a00023.php" title="Big.hpp" alt="" coords="337,80,403,107"/>
<area shape="rect" id="node3" href="../../dd/d52/a00221.php" title="types.hpp" alt="" coords="331,155,409,181"/>
<area shape="rect" id="node4" href="../../db/dd9/a00179.php" title="pointers.hpp" alt="" coords="323,229,417,256"/>
<area shape="rect" id="node5" href="../../d2/de7/a00014.php" title="arraysIncludes.hpp" alt="" coords="239,304,371,331"/>
<area shape="rect" id="node57" href="../../d8/d41/a00038.php" title="Binary.hpp" alt="" coords="395,304,479,331"/>
<area shape="rect" id="node6" href="../../d9/d01/a00227.php" title="vector.hpp" alt="" coords="279,603,362,629"/>
<area shape="rect" id="node7" href="../../d6/d2d/a00047.php" title="check.hpp" alt="" coords="389,677,471,704"/>
<area shape="rect" id="node56" href="../../d9/dd0/a00191.php" title="sorting.hpp" alt="" coords="277,677,364,704"/>
<area shape="rect" id="node8" href="../../da/d45/a00011.php" title="array.hpp" alt="" coords="337,752,413,779"/>
<area shape="rect" id="node9" href="../../de/de1/a00065.php" title="convert.hpp" alt="" coords="330,827,421,853"/>
<area shape="rect" id="node10" href="../../d9/d2e/a00056.php" title="console.hpp" alt="" coords="277,901,369,928"/>
<area shape="rect" id="node55" href="../../db/dab/a00089.php" title="files.hpp" alt="" coords="393,901,464,928"/>
<area shape="rect" id="node11" href="../../da/d2a/a00086.php" title="errors.hpp" alt="" coords="335,976,415,1003"/>
<area shape="rect" id="node12" href="../../de/d79/a00203.php" title="system.hpp" alt="" coords="330,1051,421,1077"/>
<area shape="rect" id="node13" href="../../de/db1/a00197.php" title="string.hpp" alt="" coords="336,1125,415,1152"/>
<area shape="rect" id="node14" href="../../d3/db1/a00200.php" title="Used to replace strptime function when compiling for Windows. " alt="" coords="335,1200,415,1227"/>
<area shape="rect" id="node15" href="../../dd/dc1/a00212.php" title="timeFunctions.hpp" alt="" coords="311,1275,440,1301"/>
<area shape="rect" id="node16" href="../../d4/d3a/a00101.php" title="includes.hpp" alt="" coords="328,1349,423,1376"/>
<area shape="rect" id="node17" href="../../d5/de0/a00050.php" title="Clock.hpp" alt="" coords="5,1573,87,1600"/>
<area shape="rect" id="node39" href="../../d3/d8b/a00059.php" title="ConsoleTable.hpp" alt="" coords="120,1648,247,1675"/>
<area shape="rect" id="node40" href="../../d0/d89/a00071.php" title="Date.hpp" alt="" coords="162,1424,237,1451"/>
<area shape="rect" id="node42" href="../../d0/dc2/a00104.php" title="IOConfig.hpp" alt="" coords="318,1499,417,1525"/>
<area shape="rect" id="node43" href="../../d7/d9a/a00152.php" title="Path.hpp" alt="" coords="413,1424,487,1451"/>
<area shape="rect" id="node49" href="../../db/ddf/a00164.php" title="PathfindingException.hpp" alt="" coords="511,1424,682,1451"/>
<area shape="rect" id="node50" href="../../de/df3/a00185.php" title="Referenced.hpp" alt="" coords="586,1573,701,1600"/>
<area shape="rect" id="node51" href="../../d5/df1/a00206.php" title="Threadable.hpp" alt="" coords="715,1723,825,1749"/>
<area shape="rect" id="node54" href="../../d3/de5/a00209.php" title="Time.hpp" alt="" coords="261,1424,337,1451"/>
<area shape="rect" id="node18" href="../../d1/d09/a00077.php" title="defines.hpp" alt="" coords="369,1872,459,1899"/>
<area shape="rect" id="node19" href="../../db/db2/a00020.php" title="AssertionException.hpp" alt="" coords="217,1947,377,1973"/>
<area shape="rect" id="node37" href="../../da/d24/a00068.php" title="cryptage.hpp" alt="" coords="364,2021,461,2048"/>
<area shape="rect" id="node38" href="../../df/d98/a00107.php" title="Logger.hpp" alt="" coords="453,1947,540,1973"/>
<area shape="rect" id="node20" href="../../d4/d51/a00017.php" title="Assert.hpp" alt="" coords="254,2021,339,2048"/>
<area shape="rect" id="node21" href="../../dd/d32/a00041.php" title="C++.hpp" alt="" coords="376,2096,449,2123"/>
<area shape="rect" id="node22" href="../../df/d03/a00062.php" title="Contraption.hpp" alt="" coords="309,2171,423,2197"/>
<area shape="rect" id="node36" href="../../d1/d44/a00098.php" title="Identifier.hpp" alt="" coords="408,2544,505,2571"/>
<area shape="rect" id="node23" href="../../d2/d1f/a00083.php" title="Entity.hpp" alt="" coords="212,2245,293,2272"/>
<area shape="rect" id="node34" href="../../d9/db6/a00146.php" title="Object.hpp" alt="" coords="331,2245,417,2272"/>
<area shape="rect" id="node24" href="../../d9/d77/a00095.php" title="Hostile.hpp" alt="" coords="85,2320,173,2347"/>
<area shape="rect" id="node31" href="../../d1/da8/a00230.php" title="Vegetal.hpp" alt="" coords="207,2395,298,2421"/>
<area shape="rect" id="node25" href="../../d7/d46/a00002.php" title="Animal.hpp" alt="" coords="69,2395,156,2421"/>
<area shape="rect" id="node26" href="../../dd/dad/a00005.php" title="Ant.hpp" alt="" coords="71,2469,138,2496"/>
<area shape="rect" id="node27" href="../../da/dec/a00080.php" title="Entities.hpp" alt="" coords="289,2544,379,2571"/>
<area shape="rect" id="node28" href="../../d5/de9/a00176.php" title="PlayerAbstraction.hpp" alt="" coords="261,2619,412,2645"/>
<area shape="rect" id="node29" href="../../d7/d3f/a00173.php" title="Player.hpp" alt="" coords="351,2693,435,2720"/>
<area shape="rect" id="node30" href="../../d5/df9/a00044.php" title="C++Entities.hpp" alt="" coords="334,2768,451,2795"/>
<area shape="rect" id="node32" href="../../d2/df5/a00137.php" title="Mushroom.hpp" alt="" coords="163,2469,271,2496"/>
<area shape="rect" id="node33" href="../../d5/dcb/a00170.php" title="Plant.hpp" alt="" coords="295,2469,373,2496"/>
<area shape="rect" id="node35" href="../../dc/d57/a00194.php" title="Stone.hpp" alt="" coords="341,2320,423,2347"/>
<area shape="rect" id="node41" href="../../db/db6/a00074.php" title="DateTime.hpp" alt="" coords="190,1499,294,1525"/>
<area shape="rect" id="node44" href="../../dc/de6/a00167.php" title="PathfindingProblem.hpp" alt="" coords="441,1499,601,1525"/>
<area shape="rect" id="node45" href="../../d3/df8/a00155.php" title="Pathfinding.hpp" alt="" coords="442,1573,554,1600"/>
<area shape="rect" id="node46" href="../../d6/d7d/a00161.php" title="PathfindingDijkstra.hpp" alt="" coords="403,1648,561,1675"/>
<area shape="rect" id="node47" href="../../d6/db8/a00158.php" title="PathfindingAlgorithms.hpp" alt="" coords="389,1723,564,1749"/>
<area shape="rect" id="node48" href="../../d4/d3e/a00116.php" title="Map.hpp" alt="" coords="415,1797,487,1824"/>
<area shape="rect" id="node52" href="../../d4/dee/a00008.php" title="Args.hpp" alt="" coords="639,1797,714,1824"/>
<area shape="rect" id="node53" href="../../d3/dd5/a00215.php" title="Timer.hpp" alt="" coords="738,1797,818,1824"/>
<area shape="rect" id="node58" href="../../df/d6a/a00119.php" title="maths.hpp" alt="" coords="394,379,477,405"/>
<area shape="rect" id="node59" href="../../d1/dc1/a00092.php" title="Fraction.hpp" alt="" coords="388,453,483,480"/>
<area shape="rect" id="node60" href="../../df/dc8/a00122.php" title="Matrix.hpp" alt="" coords="391,528,474,555"/>
<area shape="rect" id="node61" href="../../dc/dee/a00053.php" title="collides.hpp" alt="" coords="387,603,478,629"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:da/d2e/a00238"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a49c8e33d55da52fabdb3f09f2fd3e5b2"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#a49c8e33d55da52fabdb3f09f2fd3e5b2">mcd::operator==</a> (const Big &amp;a, const Big &amp;b) noexcept</td></tr>
<tr class="memdesc:a49c8e33d55da52fabdb3f09f2fd3e5b2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compare two <a class="el" href="../../d8/d64/a00828.php" title="A new huge arithmetic variable. ">Big</a>.  <a href="../../da/d2e/a00238.php#a49c8e33d55da52fabdb3f09f2fd3e5b2">More...</a><br /></td></tr>
<tr class="separator:a49c8e33d55da52fabdb3f09f2fd3e5b2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a72149c6d15e16114c649ecb03aec7f81"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#a72149c6d15e16114c649ecb03aec7f81">mcd::operator&lt;</a> (const Big &amp;a, const Big &amp;b) noexcept</td></tr>
<tr class="memdesc:a72149c6d15e16114c649ecb03aec7f81"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compare two <a class="el" href="../../d8/d64/a00828.php" title="A new huge arithmetic variable. ">Big</a>.  <a href="../../da/d2e/a00238.php#a72149c6d15e16114c649ecb03aec7f81">More...</a><br /></td></tr>
<tr class="separator:a72149c6d15e16114c649ecb03aec7f81"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8106aa588d48c9fbed5e30e22fd55f76"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#a8106aa588d48c9fbed5e30e22fd55f76">mcd::operator!=</a> (const Big &amp;a, const Big &amp;b) noexcept</td></tr>
<tr class="memdesc:a8106aa588d48c9fbed5e30e22fd55f76"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compare two <a class="el" href="../../d8/d64/a00828.php" title="A new huge arithmetic variable. ">Big</a>.  <a href="../../da/d2e/a00238.php#a8106aa588d48c9fbed5e30e22fd55f76">More...</a><br /></td></tr>
<tr class="separator:a8106aa588d48c9fbed5e30e22fd55f76"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61257b7f63f915629b98d2b57933d65e"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#a61257b7f63f915629b98d2b57933d65e">mcd::operator&lt;=</a> (const Big &amp;a, const Big &amp;b) noexcept</td></tr>
<tr class="memdesc:a61257b7f63f915629b98d2b57933d65e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compare two <a class="el" href="../../d8/d64/a00828.php" title="A new huge arithmetic variable. ">Big</a>.  <a href="../../da/d2e/a00238.php#a61257b7f63f915629b98d2b57933d65e">More...</a><br /></td></tr>
<tr class="separator:a61257b7f63f915629b98d2b57933d65e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a83c8849718e8a8532282e6f1c80ceca0"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#a83c8849718e8a8532282e6f1c80ceca0">mcd::operator&gt;=</a> (const Big &amp;a, const Big &amp;b) noexcept</td></tr>
<tr class="memdesc:a83c8849718e8a8532282e6f1c80ceca0"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compare two <a class="el" href="../../d8/d64/a00828.php" title="A new huge arithmetic variable. ">Big</a>.  <a href="../../da/d2e/a00238.php#a83c8849718e8a8532282e6f1c80ceca0">More...</a><br /></td></tr>
<tr class="separator:a83c8849718e8a8532282e6f1c80ceca0"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d6/d5b/a00026.php">Big_Comparison.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
