<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: Big_Comparison.hpp Source File</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Aug 8 2018 09:57:28 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d1/d6e/a00073_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Big_Comparison.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d1/d6e/a00073.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00002"></a><span class="lineno"><a class="line" href="../../d1/d6e/a00073.php#a5eed09966f2142f9d979e7be4643c06a">    2</a></span>&#160;<span class="keyword">inline</span> <span class="keywordtype">bool</span> <a class="code" href="../../d1/d6e/a00073.php#a5eed09966f2142f9d979e7be4643c06a">operator==</a>(<span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; a, <span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; b) noexcept{</div><div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;    <span class="keywordflow">return</span> (a._val == b._val) &amp;&amp; (a._neg == b._neg);</div><div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;}</div><div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;</div><div class="line"><a name="l00007"></a><span class="lineno"><a class="line" href="../../d1/d6e/a00073.php#a9c625348272715ed4dad2c1420fb5bd0">    7</a></span>&#160;<span class="keyword">inline</span> <span class="keywordtype">bool</span> <a class="code" href="../../d1/d6e/a00073.php#a9c625348272715ed4dad2c1420fb5bd0">operator&lt;</a>(<span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; a, <span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; b) noexcept{</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;    <span class="keywordflow">return</span> (a != b) &amp;&amp; !(a &gt; b);</div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;}</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno"><a class="line" href="../../d1/d6e/a00073.php#ad9c55799e64051a79feb72642bacc2bd">   12</a></span>&#160;<span class="keyword">inline</span> <span class="keywordtype">bool</span> <a class="code" href="../../d1/d6e/a00073.php#ad9c55799e64051a79feb72642bacc2bd">operator!=</a>(<span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; a, <span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; b) noexcept {</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;    <span class="keywordflow">return</span> !(a == b);</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;}</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno"><a class="line" href="../../d1/d6e/a00073.php#a74e55e1a85a44b255d0f8e1158e02658">   17</a></span>&#160;<span class="keyword">inline</span> <span class="keywordtype">bool</span> <a class="code" href="../../d1/d6e/a00073.php#a74e55e1a85a44b255d0f8e1158e02658">operator&lt;=</a>(<span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; a, <span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; b) noexcept {</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keywordflow">return</span> (a &lt; b) || (a == b);</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;}</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno"><a class="line" href="../../d1/d6e/a00073.php#adf83d734f0c4b777bb675bf327996987">   22</a></span>&#160;<span class="keyword">inline</span> <span class="keywordtype">bool</span> <a class="code" href="../../d1/d6e/a00073.php#adf83d734f0c4b777bb675bf327996987">operator&gt;=</a>(<span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; a, <span class="keyword">const</span> <a class="code" href="../../de/d5e/a00007.php">Big</a>&amp; b) noexcept {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;    <span class="keywordflow">return</span> (a &gt; b) || (a == b);</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;}</div><div class="ttc" id="a00007_php"><div class="ttname"><a href="../../de/d5e/a00007.php">Big</a></div><div class="ttdoc">A new huge arithmetic variable. </div><div class="ttdef"><b>Definition:</b> Big.hpp:73</div></div>
<div class="ttc" id="a00073_php_adf83d734f0c4b777bb675bf327996987"><div class="ttname"><a href="../../d1/d6e/a00073.php#adf83d734f0c4b777bb675bf327996987">operator&gt;=</a></div><div class="ttdeci">bool operator&gt;=(const Big &amp;a, const Big &amp;b) noexcept</div><div class="ttdoc">Compare two Big. </div><div class="ttdef"><b>Definition:</b> Big_Comparison.hpp:22</div></div>
<div class="ttc" id="a00073_php_a5eed09966f2142f9d979e7be4643c06a"><div class="ttname"><a href="../../d1/d6e/a00073.php#a5eed09966f2142f9d979e7be4643c06a">operator==</a></div><div class="ttdeci">bool operator==(const Big &amp;a, const Big &amp;b) noexcept</div><div class="ttdoc">Compare two Big. </div><div class="ttdef"><b>Definition:</b> Big_Comparison.hpp:2</div></div>
<div class="ttc" id="a00073_php_a9c625348272715ed4dad2c1420fb5bd0"><div class="ttname"><a href="../../d1/d6e/a00073.php#a9c625348272715ed4dad2c1420fb5bd0">operator&lt;</a></div><div class="ttdeci">bool operator&lt;(const Big &amp;a, const Big &amp;b) noexcept</div><div class="ttdoc">Compare two Big. </div><div class="ttdef"><b>Definition:</b> Big_Comparison.hpp:7</div></div>
<div class="ttc" id="a00073_php_a74e55e1a85a44b255d0f8e1158e02658"><div class="ttname"><a href="../../d1/d6e/a00073.php#a74e55e1a85a44b255d0f8e1158e02658">operator&lt;=</a></div><div class="ttdeci">bool operator&lt;=(const Big &amp;a, const Big &amp;b) noexcept</div><div class="ttdoc">Compare two Big. </div><div class="ttdef"><b>Definition:</b> Big_Comparison.hpp:17</div></div>
<div class="ttc" id="a00073_php_ad9c55799e64051a79feb72642bacc2bd"><div class="ttname"><a href="../../d1/d6e/a00073.php#ad9c55799e64051a79feb72642bacc2bd">operator!=</a></div><div class="ttdeci">bool operator!=(const Big &amp;a, const Big &amp;b) noexcept</div><div class="ttdoc">Compare two Big. </div><div class="ttdef"><b>Definition:</b> Big_Comparison.hpp:12</div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../dir_220287e732b97f08f66e5f221c69df74.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_75b0389167f46f79a101ef8c4434cec4.php">C++</a></li><li class="navelem"><a class="el" href="../../d1/d6e/a00073.php">Big_Comparison.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
