<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: ConsoleTable.hpp Source File</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Aug 8 2018 09:57:28 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d2/d1f/a00083_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">ConsoleTable.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d2/d1f/a00083.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="preprocessor">#ifndef HEADER_CPP_CONSOLE_TABLE</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#define HEADER_CPP_CONSOLE_TABLE</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d9/d77/a00095.php">C++/includes.hpp</a>&quot;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno"><a class="line" href="../../d7/dd4/a00013.php">   17</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../d7/dd4/a00013.php">ConsoleTable</a>{</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;        <a class="code" href="../../d7/dd4/a00013.php#ac189683adb03344529a85cdb744a4040">ConsoleTable</a>();</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d7/dd4/a00013.php#a1394d5bfc7c064e6e195fdc1d6b78941">headers</a>(std::vector&lt;std::string&gt; h);</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;</div><div class="line"><a name="l00023"></a><span class="lineno"><a class="line" href="../../d7/dd4/a00013.php#a28df68c1cd93c9acaa39d6b70354e594">   23</a></span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d7/dd4/a00013.php#a28df68c1cd93c9acaa39d6b70354e594">lines</a>(std::vector&lt;std::vector&lt;std::string&gt;&gt; ls){</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;            <span class="keywordflow">for</span>(<span class="keyword">auto</span> l : ls){</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;                this-&gt;<a class="code" href="../../d7/dd4/a00013.php#a096796a62f1ddda4c66a65f7d1c3b3d4">line</a>(l);</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;            }</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;        }</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../d7/dd4/a00013.php#a096796a62f1ddda4c66a65f7d1c3b3d4">line</a>(std::vector&lt;std::string&gt; l);</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;        <span class="keyword">friend</span> std::ostream&amp; <a class="code" href="../../d7/dd4/a00013.php#af23c547bfa2b35d582a6922d425d02f5">operator&lt;&lt;</a>(std::ostream&amp; str, <a class="code" href="../../d7/dd4/a00013.php">ConsoleTable</a>&amp; t);</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;        std::vector&lt;std::vector&lt;std::string&gt;&gt; table;</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;        std::map&lt;std::string, std::string&gt; tableCars;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;};</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;<span class="preprocessor">#endif //HEADER_CPP_CONSOLE_TABLE</span></div><div class="ttc" id="a00095_php"><div class="ttname"><a href="../../d9/d77/a00095.php">includes.hpp</a></div></div>
<div class="ttc" id="a00013_php_a096796a62f1ddda4c66a65f7d1c3b3d4"><div class="ttname"><a href="../../d7/dd4/a00013.php#a096796a62f1ddda4c66a65f7d1c3b3d4">ConsoleTable::line</a></div><div class="ttdeci">void line(std::vector&lt; std::string &gt; l)</div></div>
<div class="ttc" id="a00013_php_af23c547bfa2b35d582a6922d425d02f5"><div class="ttname"><a href="../../d7/dd4/a00013.php#af23c547bfa2b35d582a6922d425d02f5">ConsoleTable::operator&lt;&lt;</a></div><div class="ttdeci">friend std::ostream &amp; operator&lt;&lt;(std::ostream &amp;str, ConsoleTable &amp;t)</div></div>
<div class="ttc" id="a00013_php_a28df68c1cd93c9acaa39d6b70354e594"><div class="ttname"><a href="../../d7/dd4/a00013.php#a28df68c1cd93c9acaa39d6b70354e594">ConsoleTable::lines</a></div><div class="ttdeci">void lines(std::vector&lt; std::vector&lt; std::string &gt;&gt; ls)</div><div class="ttdef"><b>Definition:</b> ConsoleTable.hpp:23</div></div>
<div class="ttc" id="a00013_php_ac189683adb03344529a85cdb744a4040"><div class="ttname"><a href="../../d7/dd4/a00013.php#ac189683adb03344529a85cdb744a4040">ConsoleTable::ConsoleTable</a></div><div class="ttdeci">ConsoleTable()</div></div>
<div class="ttc" id="a00013_php_a1394d5bfc7c064e6e195fdc1d6b78941"><div class="ttname"><a href="../../d7/dd4/a00013.php#a1394d5bfc7c064e6e195fdc1d6b78941">ConsoleTable::headers</a></div><div class="ttdeci">void headers(std::vector&lt; std::string &gt; h)</div></div>
<div class="ttc" id="a00013_php"><div class="ttname"><a href="../../d7/dd4/a00013.php">ConsoleTable</a></div><div class="ttdoc">A class to print a table in the console. </div><div class="ttdef"><b>Definition:</b> ConsoleTable.hpp:17</div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../dir_220287e732b97f08f66e5f221c69df74.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_75b0389167f46f79a101ef8c4434cec4.php">C++</a></li><li class="navelem"><a class="el" href="../../d2/d1f/a00083.php">ConsoleTable.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
