<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: console.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Fri Sep 6 2019 16:16:43 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/de0/a00050.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a> &#124;
<a href="#enum-members">Enumerations</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">console.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d3/d8b/a00059.php">C++/convert.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for console.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/d79/a00051.png" border="0" usemap="#console_8hpp" alt=""/></div>
<map name="console_8hpp" id="console_8hpp">
<area shape="rect" id="node2" href="../../d3/d8b/a00059.php" title="C++/convert.hpp" alt="" coords="235,80,355,107"/>
<area shape="rect" id="node4" href="../../da/d45/a00011.php" title="C++/array.hpp" alt="" coords="301,155,408,181"/>
<area shape="rect" id="node6" href="../../dd/d32/a00041.php" title="C++/check.hpp" alt="" coords="299,229,411,256"/>
<area shape="rect" id="node41" href="../../d3/df8/a00155.php" title="C++/sorting.hpp" alt="" coords="505,229,621,256"/>
<area shape="rect" id="node10" href="../../d2/de7/a00014.php" title="C++/arraysIncludes.hpp" alt="" coords="517,304,680,331"/>
<area shape="rect" id="node39" href="../../d6/d2d/a00047.php" title="C++/collides.hpp" alt="" coords="371,304,493,331"/>
<area shape="rect" id="node17" href="../../d7/dce/a00143.php" title="C++/pointers.hpp" alt="" coords="481,453,604,480"/>
<area shape="rect" id="node20" href="../../d7/d25/a00182.php" title="C++/types.hpp" alt="" coords="596,528,705,555"/>
<area shape="rect" id="node22" href="../../db/db2/a00020.php" title="Big.hpp" alt="" coords="560,603,627,629"/>
<area shape="rect" id="node37" href="../../d9/db6/a00146.php" title="PureVirtual.hpp" alt="" coords="651,603,762,629"/>
<area shape="rect" id="node38" href="../../de/df3/a00185.php" title="UsefullDefines.hpp" alt="" coords="787,603,920,629"/>
<area shape="rect" id="node33" href="../../d6/d5b/a00026.php" title="C++/Big_Constructor.hpp" alt="" coords="887,677,1057,704"/>
<area shape="rect" id="node34" href="../../dc/d87/a00032.php" title="C++/Big_Operator.hpp" alt="" coords="1082,677,1235,704"/>
<area shape="rect" id="node35" href="../../d3/d52/a00023.php" title="C++/Big_Comparison.hpp" alt="" coords="1260,677,1433,704"/>
<area shape="rect" id="node36" href="../../d5/d16/a00029.php" title="C++/Big_Maths.hpp" alt="" coords="1457,677,1596,704"/>
<area shape="rect" id="node40" href="../../d0/dc2/a00104.php" title="C++/maths.hpp" alt="" coords="195,379,309,405"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d84/a00052.png" border="0" usemap="#console_8hppdep" alt=""/></div>
<map name="console_8hppdep" id="console_8hppdep">
<area shape="rect" id="node2" href="../../da/dec/a00080.php" title="errors.hpp" alt="" coords="309,80,389,107"/>
<area shape="rect" id="node3" href="../../db/ddf/a00164.php" title="system.hpp" alt="" coords="303,155,394,181"/>
<area shape="rect" id="node4" href="../../d6/d7d/a00161.php" title="string.hpp" alt="" coords="309,229,388,256"/>
<area shape="rect" id="node5" href="../../d7/d3f/a00173.php" title="timeFunctions.hpp" alt="" coords="284,304,413,331"/>
<area shape="rect" id="node6" href="../../d1/dc1/a00092.php" title="includes.hpp" alt="" coords="301,379,396,405"/>
<area shape="rect" id="node7" href="../../d5/df9/a00044.php" title="Clock.hpp" alt="" coords="5,603,87,629"/>
<area shape="rect" id="node28" href="../../dc/dee/a00053.php" title="ConsoleTable.hpp" alt="" coords="56,528,183,555"/>
<area shape="rect" id="node29" href="../../de/de1/a00065.php" title="Date.hpp" alt="" coords="135,453,210,480"/>
<area shape="rect" id="node31" href="../../d9/d77/a00095.php" title="IOConfig.hpp" alt="" coords="297,603,395,629"/>
<area shape="rect" id="node32" href="../../d4/d3e/a00116.php" title="Path.hpp" alt="" coords="386,453,461,480"/>
<area shape="rect" id="node37" href="../../d1/d88/a00128.php" title="PathfindingException.hpp" alt="" coords="485,453,655,480"/>
<area shape="rect" id="node38" href="../../da/d1e/a00149.php" title="Referenced.hpp" alt="" coords="547,677,662,704"/>
<area shape="rect" id="node39" href="../../dc/de6/a00167.php" title="Threadable.hpp" alt="" coords="688,677,799,704"/>
<area shape="rect" id="node42" href="../../d5/dcb/a00170.php" title="Time.hpp" alt="" coords="235,453,311,480"/>
<area shape="rect" id="node8" href="../../d0/d89/a00071.php" title="defines.hpp" alt="" coords="336,827,425,853"/>
<area shape="rect" id="node9" href="../../df/d03/a00062.php" title="cryptage.hpp" alt="" coords="223,901,320,928"/>
<area shape="rect" id="node26" href="../../d4/d3a/a00101.php" title="Map.hpp" alt="" coords="345,901,417,928"/>
<area shape="rect" id="node27" href="../../db/dd9/a00179.php" title="Tree.hpp" alt="" coords="441,901,515,928"/>
<area shape="rect" id="node10" href="../../d4/d8c/a00035.php" title="C++.hpp" alt="" coords="344,976,417,1003"/>
<area shape="rect" id="node11" href="../../d9/d2e/a00056.php" title="Contraption.hpp" alt="" coords="277,1051,391,1077"/>
<area shape="rect" id="node25" href="../../db/dab/a00089.php" title="Identifier.hpp" alt="" coords="376,1424,473,1451"/>
<area shape="rect" id="node12" href="../../d1/d09/a00077.php" title="Entity.hpp" alt="" coords="180,1125,261,1152"/>
<area shape="rect" id="node23" href="../../d3/d00/a00113.php" title="Object.hpp" alt="" coords="299,1125,385,1152"/>
<area shape="rect" id="node13" href="../../da/d2a/a00086.php" title="Hostile.hpp" alt="" coords="66,1200,154,1227"/>
<area shape="rect" id="node20" href="../../da/d15/a00188.php" title="Vegetal.hpp" alt="" coords="175,1275,266,1301"/>
<area shape="rect" id="node14" href="../../d7/d46/a00002.php" title="Animal.hpp" alt="" coords="37,1275,124,1301"/>
<area shape="rect" id="node15" href="../../dd/dad/a00005.php" title="Ant.hpp" alt="" coords="39,1349,106,1376"/>
<area shape="rect" id="node16" href="../../db/db6/a00074.php" title="Entities.hpp" alt="" coords="257,1424,347,1451"/>
<area shape="rect" id="node17" href="../../d5/db1/a00140.php" title="PlayerAbstraction.hpp" alt="" coords="229,1499,380,1525"/>
<area shape="rect" id="node18" href="../../d2/df5/a00137.php" title="Player.hpp" alt="" coords="319,1573,403,1600"/>
<area shape="rect" id="node19" href="../../d8/d41/a00038.php" title="C++Entities.hpp" alt="" coords="302,1648,419,1675"/>
<area shape="rect" id="node21" href="../../df/d98/a00107.php" title="Mushroom.hpp" alt="" coords="131,1349,239,1376"/>
<area shape="rect" id="node22" href="../../de/d76/a00134.php" title="Plant.hpp" alt="" coords="263,1349,341,1376"/>
<area shape="rect" id="node24" href="../../d6/db8/a00158.php" title="Stone.hpp" alt="" coords="309,1200,391,1227"/>
<area shape="rect" id="node30" href="../../da/d24/a00068.php" title="DateTime.hpp" alt="" coords="207,528,311,555"/>
<area shape="rect" id="node33" href="../../d7/d06/a00131.php" title="PathfindingProblem.hpp" alt="" coords="395,528,555,555"/>
<area shape="rect" id="node34" href="../../df/d6a/a00119.php" title="Pathfinding.hpp" alt="" coords="419,603,531,629"/>
<area shape="rect" id="node35" href="../../dc/dfe/a00125.php" title="PathfindingDijkstra.hpp" alt="" coords="365,677,522,704"/>
<area shape="rect" id="node36" href="../../df/dc8/a00122.php" title="PathfindingAlgorithms.hpp" alt="" coords="356,752,531,779"/>
<area shape="rect" id="node40" href="../../d4/dee/a00008.php" title="Args.hpp" alt="" coords="606,752,681,779"/>
<area shape="rect" id="node41" href="../../d5/de9/a00176.php" title="Timer.hpp" alt="" coords="705,752,785,779"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/dcf/a00845.php">mcd::Color</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Change the text color in the console.  <a href="../../d7/dcf/a00845.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../de/d37/a00849.php">mcd::Reinit</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight"><a class="el" href="../../de/d37/a00849.php" title="Reinit the color in the console. ">Reinit</a> the color in the console.  <a href="../../de/d37/a00849.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/deb/a00853.php">mcd::Cls</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Clear the console.  <a href="../../db/deb/a00853.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d0/d82/a00857.php">mcd::ConsoleCursor</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A class to play with the cursor in the console.  <a href="../../d0/d82/a00857.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/dd5/a00861.php">mcd::ThreadEndlCout</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A class to use std::endl in <a class="el" href="../../dd/d7b/a00865.php" title="A class to use std::cout thread safe. ">ThreadCout</a>.  <a href="../../dd/dd5/a00861.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d7b/a00865.php">mcd::ThreadCout</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A class to use std::cout thread safe.  <a href="../../dd/d7b/a00865.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:d7/ded/a00196"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/ded/a00196.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="enum-members"></a>
Enumerations</h2></td></tr>
<tr class="memitem:ae124ce77f8e386663ac11e2e35e6070a"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070a">mcd::Colors</a> { <br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa4648822616bc86180727464a1e6c6312">mcd::Colors::BLACK_F</a> = 30, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa6c91c7a0d965eea06426a9d94fed419f">mcd::Colors::RED_F</a> = 31, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aac9cc84994b2dc998400606f509a5f39d">mcd::Colors::GREEN_F</a> = 32, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aac1cfbf30b4d84302148c80564f09a2f7">mcd::Colors::YELLOW_F</a> = 33, 
<br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aaaac26079ece66386f4c2cf268d474795">mcd::Colors::BLUE_F</a> = 34, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aab8176b797e421a3d45ed5a872d872591">mcd::Colors::PURPLE_F</a> = 35, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa131f0f8b48b6ef48d2d3093b20081110">mcd::Colors::CYAN_F</a> = 36, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa38ead0a9861da91e3e5aad34b7a1dbfe">mcd::Colors::GREY_F</a> = 37, 
<br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aaa86522df36b902b8e14c670dda459f1f">mcd::Colors::LIGHT_BLACK_F</a> = 90, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa889b14723d6bc4c0ac8bb1e13480ad6e">mcd::Colors::LIGHT_RED_F</a> = 91, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa9a372d70c82fc984f7c475342784fb25">mcd::Colors::LIGHT_GREEN_F</a> = 92, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa8a64c210ea569e6832792e099c006157">mcd::Colors::LIGHT_YELLOW_F</a> = 93, 
<br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa383a03eb7a3c8a6e508915b5abfd1f55">mcd::Colors::LIGHT_BLUE_F</a> = 94, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aaf7fa27f9a891a06e7aab7764b7c87744">mcd::Colors::LIGHT_PURPLE_F</a> = 95, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa1016baf606406c4b466ae02d7e8d249b">mcd::Colors::LIGHT_CYAN_F</a> = 96, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aaf0d423059b6f4ad707d65956c1a43402">mcd::Colors::LIGHT_GREY_F</a> = 97, 
<br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aabfc78599c77b7eb3c037c23f1bde963a">mcd::Colors::BLACK_B</a> = 40, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa07262f1edc5408b021950dc9a12837c7">mcd::Colors::RED_B</a> = 41, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa3bfe655ef7bb19c04ebf9a5ebabe975e">mcd::Colors::GREEN_B</a> = 42, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa62a3874ee2f47d3a664fda4a63c193a3">mcd::Colors::YELLOW_B</a> = 43, 
<br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa19995eb9ec42ffbe11647f8090e9f4fe">mcd::Colors::BLUE_B</a> = 44, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aab754547a82033c3c904e91984b530326">mcd::Colors::PURPLE_B</a> = 45, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aae0f5f8e09d8f4e0925884dd94fc3e870">mcd::Colors::CYAN_B</a> = 46, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa90bd0646259d8ab65dd352bcd1ead16e">mcd::Colors::GREY_B</a> = 47, 
<br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aadf2fe24817131afc02153bf31759d18b">mcd::Colors::LIGHT_BLACK_B</a> = 100, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa3a29105a7f33b752d0342ec1e44023af">mcd::Colors::LIGHT_RED_B</a> = 101, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa79f2fcacd6d4451c79096ed3e460e1e9">mcd::Colors::LIGHT_GREEN_B</a> = 102, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa73f0b577c984186157b9d89348faf4f3">mcd::Colors::LIGHT_YELLOW_B</a> = 103, 
<br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa77891b4842905f3aa098fae908dd5db9">mcd::Colors::LIGHT_BLUE_B</a> = 104, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa10435c0f4e6c9f1df07383e39da2064e">mcd::Colors::LIGHT_PURPLE_B</a> = 105, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa1d4b785bf14640105bb7b6e45d1d5528">mcd::Colors::LIGHT_CYAN_B</a> = 106, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aaa548ce608701dcb3a6b2146e2e6b7f73">mcd::Colors::LIGHT_GREY_B</a> = 107, 
<br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa1e23852820b9154316c7c06e2b7ba051">mcd::Colors::NORMAL</a> = 0, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa2909dd0e0336f10b6da9735b859a3d19">mcd::Colors::BOLD</a> = 1, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa8160fba05a5a291372a94bc22b55f62b">mcd::Colors::SHADOW</a> = 2, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa25093123b8943308104129e1d762f3b7">mcd::Colors::ITALIC</a> = 3, 
<br />
&#160;&#160;<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa0086c73c90c261db630b4dc8aea09bcf">mcd::Colors::UNDERLINE</a> = 4, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aaa2727ae72447eea06d4cc0ef67187280">mcd::Colors::INVERT</a> = 7, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa1e50e487f8672658546e3609404b53df">mcd::Colors::HIDE</a> = 8, 
<a class="el" href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070aa04dd53a8e6c2306e9bbf944c1d6047f2">mcd::Colors::CROSS</a> = 9
<br />
 }<tr class="memdesc:ae124ce77f8e386663ac11e2e35e6070a"><td class="mdescLeft">&#160;</td><td class="mdescRight">Colors list.  <a href="../../d7/ded/a00196.php#ae124ce77f8e386663ac11e2e35e6070a">More...</a><br /></td></tr>
</td></tr>
<tr class="separator:ae124ce77f8e386663ac11e2e35e6070a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:ad49187ab386f309e965f2f8e954c3c24"><td class="memItemLeft" align="right" valign="top">ThreadCout&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/ded/a00196.php#ad49187ab386f309e965f2f8e954c3c24">mcd::cout</a></td></tr>
<tr class="memdesc:ad49187ab386f309e965f2f8e954c3c24"><td class="mdescLeft">&#160;</td><td class="mdescRight">The thread safe version of std::cout.  <a href="../../d7/ded/a00196.php#ad49187ab386f309e965f2f8e954c3c24">More...</a><br /></td></tr>
<tr class="separator:ad49187ab386f309e965f2f8e954c3c24"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a19aa3c3882eb7a0c0d4f6479a4bbf975"><td class="memItemLeft" align="right" valign="top">ThreadEndlCout&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d7/ded/a00196.php#a19aa3c3882eb7a0c0d4f6479a4bbf975">mcd::endl</a></td></tr>
<tr class="memdesc:a19aa3c3882eb7a0c0d4f6479a4bbf975"><td class="mdescLeft">&#160;</td><td class="mdescRight">The thread safe version of std::endl.  <a href="../../d7/ded/a00196.php#a19aa3c3882eb7a0c0d4f6479a4bbf975">More...</a><br /></td></tr>
<tr class="separator:a19aa3c3882eb7a0c0d4f6479a4bbf975"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : April, 24 2019 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d5/de0/a00050.php">console.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
