<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: collides.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Wed Nov 20 2019 15:10:15 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dc/dee/a00053.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">collides.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../df/dc8/a00122.php">C++/Matrix.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for collides.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/dea/a00054.png" border="0" usemap="#collides_8hpp" alt=""/></div>
<map name="collides_8hpp" id="collides_8hpp">
<area shape="rect" id="node2" href="../../df/dc8/a00122.php" title="C++/Matrix.hpp" alt="" coords="785,80,898,107"/>
<area shape="rect" id="node3" href="../../d1/dc1/a00092.php" title="C++/Fraction.hpp" alt="" coords="779,155,903,181"/>
<area shape="rect" id="node4" href="../../df/d6a/a00119.php" title="C++/maths.hpp" alt="" coords="727,229,841,256"/>
<area shape="rect" id="node5" href="../../d8/d41/a00038.php" title="C++/Binary.hpp" alt="" coords="727,304,841,331"/>
<area shape="rect" id="node6" href="../../db/dd9/a00179.php" title="C++/pointers.hpp" alt="" coords="723,379,845,405"/>
<area shape="rect" id="node7" href="../../dd/d52/a00221.php" title="C++/types.hpp" alt="" coords="621,453,731,480"/>
<area shape="rect" id="node9" href="../../d3/d52/a00023.php" title="Big.hpp" alt="" coords="643,528,709,555"/>
<area shape="rect" id="node28" href="../../dc/d9a/a00218.php" title="C++/Tree.hpp" alt="" coords="515,528,618,555"/>
<area shape="rect" id="node29" href="../../d7/d25/a00182.php" title="PureVirtual.hpp" alt="" coords="734,528,845,555"/>
<area shape="rect" id="node30" href="../../d5/ddf/a00224.php" title="UsefullDefines.hpp" alt="" coords="869,528,1003,555"/>
<area shape="rect" id="node10" href="../../da/d1e/a00149.php" title="C++/OsDetection.hpp" alt="" coords="322,603,473,629"/>
<area shape="rect" id="node24" href="../../d5/d16/a00029.php" title="C++/Big_Constructor.hpp" alt="" coords="497,603,668,629"/>
<area shape="rect" id="node25" href="../../d4/d8c/a00035.php" title="C++/Big_Operator.hpp" alt="" coords="693,603,846,629"/>
<area shape="rect" id="node26" href="../../d6/d5b/a00026.php" title="C++/Big_Comparison.hpp" alt="" coords="871,603,1044,629"/>
<area shape="rect" id="node27" href="../../dc/d87/a00032.php" title="C++/Big_Maths.hpp" alt="" coords="1068,603,1207,629"/>
<area shape="rect" id="node12" href="../../d4/d81/a00110.php" title="C++/lowIncludes.hpp" alt="" coords="391,677,537,704"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d6d/a00055.png" border="0" usemap="#collides_8hppdep" alt=""/></div>
<map name="collides_8hppdep" id="collides_8hppdep">
<area shape="rect" id="node2" href="../../d6/d2d/a00047.php" title="check.hpp" alt="" coords="334,80,417,107"/>
<area shape="rect" id="node3" href="../../da/d45/a00011.php" title="array.hpp" alt="" coords="337,155,413,181"/>
<area shape="rect" id="node4" href="../../de/de1/a00065.php" title="convert.hpp" alt="" coords="330,229,421,256"/>
<area shape="rect" id="node5" href="../../d9/d2e/a00056.php" title="console.hpp" alt="" coords="277,304,369,331"/>
<area shape="rect" id="node50" href="../../db/dab/a00089.php" title="files.hpp" alt="" coords="393,304,464,331"/>
<area shape="rect" id="node6" href="../../da/d2a/a00086.php" title="errors.hpp" alt="" coords="335,379,415,405"/>
<area shape="rect" id="node7" href="../../de/d79/a00203.php" title="system.hpp" alt="" coords="330,453,421,480"/>
<area shape="rect" id="node8" href="../../de/db1/a00197.php" title="string.hpp" alt="" coords="336,528,415,555"/>
<area shape="rect" id="node9" href="../../d3/db1/a00200.php" title="Used to replace strptime function when compiling for Windows. " alt="" coords="335,603,415,629"/>
<area shape="rect" id="node10" href="../../dd/dc1/a00212.php" title="timeFunctions.hpp" alt="" coords="311,677,440,704"/>
<area shape="rect" id="node11" href="../../d4/d3a/a00101.php" title="includes.hpp" alt="" coords="328,752,423,779"/>
<area shape="rect" id="node12" href="../../d5/de0/a00050.php" title="Clock.hpp" alt="" coords="5,976,87,1003"/>
<area shape="rect" id="node34" href="../../d3/d8b/a00059.php" title="ConsoleTable.hpp" alt="" coords="120,1051,247,1077"/>
<area shape="rect" id="node35" href="../../d0/d89/a00071.php" title="Date.hpp" alt="" coords="162,827,237,853"/>
<area shape="rect" id="node37" href="../../d0/dc2/a00104.php" title="IOConfig.hpp" alt="" coords="318,901,417,928"/>
<area shape="rect" id="node38" href="../../d7/d9a/a00152.php" title="Path.hpp" alt="" coords="413,827,487,853"/>
<area shape="rect" id="node44" href="../../db/ddf/a00164.php" title="PathfindingException.hpp" alt="" coords="511,827,682,853"/>
<area shape="rect" id="node45" href="../../de/df3/a00185.php" title="Referenced.hpp" alt="" coords="586,976,701,1003"/>
<area shape="rect" id="node46" href="../../d5/df1/a00206.php" title="Threadable.hpp" alt="" coords="715,1125,825,1152"/>
<area shape="rect" id="node49" href="../../d3/de5/a00209.php" title="Time.hpp" alt="" coords="261,827,337,853"/>
<area shape="rect" id="node13" href="../../d1/d09/a00077.php" title="defines.hpp" alt="" coords="369,1275,459,1301"/>
<area shape="rect" id="node14" href="../../db/db2/a00020.php" title="AssertionException.hpp" alt="" coords="217,1349,377,1376"/>
<area shape="rect" id="node32" href="../../da/d24/a00068.php" title="cryptage.hpp" alt="" coords="364,1424,461,1451"/>
<area shape="rect" id="node33" href="../../df/d98/a00107.php" title="Logger.hpp" alt="" coords="453,1349,540,1376"/>
<area shape="rect" id="node15" href="../../d4/d51/a00017.php" title="Assert.hpp" alt="" coords="254,1424,339,1451"/>
<area shape="rect" id="node16" href="../../dd/d32/a00041.php" title="C++.hpp" alt="" coords="376,1499,449,1525"/>
<area shape="rect" id="node17" href="../../df/d03/a00062.php" title="Contraption.hpp" alt="" coords="309,1573,423,1600"/>
<area shape="rect" id="node31" href="../../d1/d44/a00098.php" title="Identifier.hpp" alt="" coords="408,1947,505,1973"/>
<area shape="rect" id="node18" href="../../d2/d1f/a00083.php" title="Entity.hpp" alt="" coords="212,1648,293,1675"/>
<area shape="rect" id="node29" href="../../d9/db6/a00146.php" title="Object.hpp" alt="" coords="331,1648,417,1675"/>
<area shape="rect" id="node19" href="../../d9/d77/a00095.php" title="Hostile.hpp" alt="" coords="98,1723,186,1749"/>
<area shape="rect" id="node26" href="../../d1/da8/a00230.php" title="Vegetal.hpp" alt="" coords="207,1797,298,1824"/>
<area shape="rect" id="node20" href="../../d7/d46/a00002.php" title="Animal.hpp" alt="" coords="69,1797,156,1824"/>
<area shape="rect" id="node21" href="../../dd/dad/a00005.php" title="Ant.hpp" alt="" coords="71,1872,138,1899"/>
<area shape="rect" id="node22" href="../../da/dec/a00080.php" title="Entities.hpp" alt="" coords="289,1947,379,1973"/>
<area shape="rect" id="node23" href="../../d5/de9/a00176.php" title="PlayerAbstraction.hpp" alt="" coords="261,2021,412,2048"/>
<area shape="rect" id="node24" href="../../d7/d3f/a00173.php" title="Player.hpp" alt="" coords="351,2096,435,2123"/>
<area shape="rect" id="node25" href="../../d5/df9/a00044.php" title="C++Entities.hpp" alt="" coords="334,2171,451,2197"/>
<area shape="rect" id="node27" href="../../d2/df5/a00137.php" title="Mushroom.hpp" alt="" coords="163,1872,271,1899"/>
<area shape="rect" id="node28" href="../../d5/dcb/a00170.php" title="Plant.hpp" alt="" coords="295,1872,373,1899"/>
<area shape="rect" id="node30" href="../../dc/d57/a00194.php" title="Stone.hpp" alt="" coords="341,1723,423,1749"/>
<area shape="rect" id="node36" href="../../db/db6/a00074.php" title="DateTime.hpp" alt="" coords="190,901,294,928"/>
<area shape="rect" id="node39" href="../../dc/de6/a00167.php" title="PathfindingProblem.hpp" alt="" coords="441,901,601,928"/>
<area shape="rect" id="node40" href="../../d3/df8/a00155.php" title="Pathfinding.hpp" alt="" coords="442,976,554,1003"/>
<area shape="rect" id="node41" href="../../d6/d7d/a00161.php" title="PathfindingDijkstra.hpp" alt="" coords="403,1051,561,1077"/>
<area shape="rect" id="node42" href="../../d6/db8/a00158.php" title="PathfindingAlgorithms.hpp" alt="" coords="389,1125,564,1152"/>
<area shape="rect" id="node43" href="../../d4/d3e/a00116.php" title="Map.hpp" alt="" coords="415,1200,487,1227"/>
<area shape="rect" id="node47" href="../../d4/dee/a00008.php" title="Args.hpp" alt="" coords="639,1200,714,1227"/>
<area shape="rect" id="node48" href="../../d3/dd5/a00215.php" title="Timer.hpp" alt="" coords="738,1200,818,1227"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:da/d2e/a00238"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:ace8a4328114062b56cf578ad92df821f"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#ace8a4328114062b56cf578ad92df821f">mcd::collidesC</a> (double64_t r1, double64_t x1, double64_t y1, double64_t r2, double64_t x2, double64_t y2)</td></tr>
<tr class="memdesc:ace8a4328114062b56cf578ad92df821f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute if there is a collision between two circles.  <a href="../../da/d2e/a00238.php#ace8a4328114062b56cf578ad92df821f">More...</a><br /></td></tr>
<tr class="separator:ace8a4328114062b56cf578ad92df821f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab43dbb509e6ac3b52cd7767a1fb6bdaa"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#ab43dbb509e6ac3b52cd7767a1fb6bdaa">mcd::collidesR</a> (double64_t x1, double64_t y1, double64_t w1, double64_t h1, double64_t x2, double64_t y2, double64_t w2, double64_t h2)</td></tr>
<tr class="memdesc:ab43dbb509e6ac3b52cd7767a1fb6bdaa"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute if there is a collision between two rectangles.  <a href="../../da/d2e/a00238.php#ab43dbb509e6ac3b52cd7767a1fb6bdaa">More...</a><br /></td></tr>
<tr class="separator:ab43dbb509e6ac3b52cd7767a1fb6bdaa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adbb1b1f3a194f48bab3af872f65b9757"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#adbb1b1f3a194f48bab3af872f65b9757">mcd::collidesRC</a> (double64_t rx, double64_t ry, double64_t w, double64_t h, double64_t cx, double64_t cy, double64_t r)</td></tr>
<tr class="memdesc:adbb1b1f3a194f48bab3af872f65b9757"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute if there is a collision between a rectangle and a circle.  <a href="../../da/d2e/a00238.php#adbb1b1f3a194f48bab3af872f65b9757">More...</a><br /></td></tr>
<tr class="separator:adbb1b1f3a194f48bab3af872f65b9757"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae694a8102421f25c163a0ef7a9e903e2"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#ae694a8102421f25c163a0ef7a9e903e2">mcd::collidesPC</a> (double64_t cx, double64_t cy, double64_t r, double64_t x, double64_t y)</td></tr>
<tr class="memdesc:ae694a8102421f25c163a0ef7a9e903e2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute if there is a collision between a point and a circle.  <a href="../../da/d2e/a00238.php#ae694a8102421f25c163a0ef7a9e903e2">More...</a><br /></td></tr>
<tr class="separator:ae694a8102421f25c163a0ef7a9e903e2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3c001118da32a4466802e0b378af661b"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#a3c001118da32a4466802e0b378af661b">mcd::collidesPR</a> (double64_t rx, double64_t ry, double64_t w, double64_t h, double64_t x, double64_t y)</td></tr>
<tr class="memdesc:a3c001118da32a4466802e0b378af661b"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute if there is a collision between a point and a rectangle.  <a href="../../da/d2e/a00238.php#a3c001118da32a4466802e0b378af661b">More...</a><br /></td></tr>
<tr class="separator:a3c001118da32a4466802e0b378af661b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af6f9411fa8041c4f9f81519deeba4a0a"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php#af6f9411fa8041c4f9f81519deeba4a0a">mcd::ProjectionSurSegment</a> (double64_t Cx, double64_t Cy, double64_t Ax, double64_t Ay, double64_t Bx, double64_t By)</td></tr>
<tr class="memdesc:af6f9411fa8041c4f9f81519deeba4a0a"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute if there is a collision on a segment.  <a href="../../da/d2e/a00238.php#af6f9411fa8041c4f9f81519deeba4a0a">More...</a><br /></td></tr>
<tr class="separator:af6f9411fa8041c4f9f81519deeba4a0a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : September, 17 2019 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../dc/dee/a00053.php">collides.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
