<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Player.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Thu Oct 3 2019 19:33:52 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d6/db8/a00158.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">Player.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d6/d7d/a00161.php">C++/PlayerAbstraction.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/dc1/a00092.php">C++/Identifier.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Player.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/db9/a00159.png" border="0" usemap="#Player_8hpp" alt=""/></div>
<map name="Player_8hpp" id="Player_8hpp">
<area shape="rect" id="node2" href="../../d6/d7d/a00161.php" title="C++/PlayerAbstraction.hpp" alt="" coords="827,80,1007,107"/>
<area shape="rect" id="node102" href="../../d1/dc1/a00092.php" title="C++/Identifier.hpp" alt="" coords="1029,155,1155,181"/>
<area shape="rect" id="node3" href="../../db/db6/a00074.php" title="C++/Entities.hpp" alt="" coords="847,155,969,181"/>
<area shape="rect" id="node4" href="../../db/dd9/a00179.php" title="C++/Stone.hpp" alt="" coords="981,229,1091,256"/>
<area shape="rect" id="node95" href="../../d3/df8/a00155.php" title="C++/Plant.hpp" alt="" coords="565,229,672,256"/>
<area shape="rect" id="node98" href="../../dc/dfe/a00125.php" title="C++/Mushroom.hpp" alt="" coords="696,229,835,256"/>
<area shape="rect" id="node99" href="../../dd/dad/a00005.php" title="C++/Ant.hpp" alt="" coords="859,229,957,256"/>
<area shape="rect" id="node5" href="../../de/d76/a00134.php" title="C++/Object.hpp" alt="" coords="977,379,1092,405"/>
<area shape="rect" id="node6" href="../../d9/d2e/a00056.php" title="C++/Contraption.hpp" alt="" coords="948,528,1092,555"/>
<area shape="rect" id="node7" href="../../d4/d8c/a00035.php" title="C++/C++.hpp" alt="" coords="1023,603,1126,629"/>
<area shape="rect" id="node8" href="../../df/d03/a00062.php" title="C++/cryptage.hpp" alt="" coords="873,677,999,704"/>
<area shape="rect" id="node93" href="../../de/d79/a00203.php" title="C++/Tree.hpp" alt="" coords="1023,677,1126,704"/>
<area shape="rect" id="node94" href="../../d0/dc2/a00104.php" title="C++/Map.hpp" alt="" coords="1150,677,1253,704"/>
<area shape="rect" id="node9" href="../../d0/d89/a00071.php" title="C++/defines.hpp" alt="" coords="1015,752,1134,779"/>
<area shape="rect" id="node10" href="../../d3/db1/a00200.php" title="C++/Timer.hpp" alt="" coords="674,827,785,853"/>
<area shape="rect" id="node79" href="../../d4/dee/a00008.php" title="C++/Args.hpp" alt="" coords="809,827,913,853"/>
<area shape="rect" id="node80" href="../../da/d24/a00068.php" title="C++/DateTime.hpp" alt="" coords="883,1051,1018,1077"/>
<area shape="rect" id="node83" href="../../d5/df9/a00044.php" title="C++/Clock.hpp" alt="" coords="989,976,1099,1003"/>
<area shape="rect" id="node84" href="../../dc/dee/a00053.php" title="C++/ConsoleTable.hpp" alt="" coords="1055,901,1212,928"/>
<area shape="rect" id="node85" href="../../d5/dcb/a00170.php" title="C++/Referenced.hpp" alt="" coords="1175,976,1319,1003"/>
<area shape="rect" id="node86" href="../../d7/dce/a00143.php" title="C++/PathfindingAlgorithms.hpp" alt="" coords="1298,827,1502,853"/>
<area shape="rect" id="node92" href="../../d1/d44/a00098.php" title="C++/IOConfig.hpp" alt="" coords="1526,1051,1655,1077"/>
<area shape="rect" id="node11" href="../../d9/dd0/a00191.php" title="C++/Threadable.hpp" alt="" coords="704,901,845,928"/>
<area shape="rect" id="node12" href="../../d9/d77/a00095.php" title="C++/includes.hpp" alt="" coords="1075,1200,1200,1227"/>
<area shape="rect" id="node13" href="../../de/db1/a00197.php" title="C++/timeFunctions.hpp" alt="" coords="478,1275,637,1301"/>
<area shape="rect" id="node71" href="../../d1/d88/a00128.php" title="C++/NotCopyable.hpp" alt="" coords="661,1275,814,1301"/>
<area shape="rect" id="node72" href="../../d7/d06/a00131.php" title="C++/NotInstantiable.hpp" alt="" coords="839,1275,1004,1301"/>
<area shape="rect" id="node15" href="../../de/df3/a00185.php" title="Used to replace strptime function when compiling for Windows. " alt="" coords="555,1349,666,1376"/>
<area shape="rect" id="node16" href="../../d7/d25/a00182.php" title="C++/string.hpp" alt="" coords="556,1424,665,1451"/>
<area shape="rect" id="node18" href="../../da/d15/a00188.php" title="C++/system.hpp" alt="" coords="483,1499,603,1525"/>
<area shape="rect" id="node68" href="../../d7/d3f/a00173.php" title="C++/RNG.hpp" alt="" coords="627,1499,733,1525"/>
<area shape="rect" id="node70" href="../../d4/d3a/a00101.php" title="C++/macro.hpp" alt="" coords="758,1499,871,1525"/>
<area shape="rect" id="node19" href="../../da/dec/a00080.php" title="C++/errors.hpp" alt="" coords="487,1573,598,1600"/>
<area shape="rect" id="node20" href="../../d5/de0/a00050.php" title="C++/console.hpp" alt="" coords="413,1648,536,1675"/>
<area shape="rect" id="node66" href="../../d2/d1f/a00083.php" title="C++/files.hpp" alt="" coords="560,1648,661,1675"/>
<area shape="rect" id="node21" href="../../d3/d8b/a00059.php" title="C++/convert.hpp" alt="" coords="424,1723,544,1749"/>
<area shape="rect" id="node23" href="../../da/d45/a00011.php" title="C++/array.hpp" alt="" coords="491,1797,597,1824"/>
<area shape="rect" id="node25" href="../../dd/d32/a00041.php" title="C++/check.hpp" alt="" coords="488,1872,600,1899"/>
<area shape="rect" id="node65" href="../../d5/de9/a00176.php" title="C++/sorting.hpp" alt="" coords="682,1872,798,1899"/>
<area shape="rect" id="node29" href="../../dd/dc1/a00212.php" title="C++/vector.hpp" alt="" coords="713,1947,826,1973"/>
<area shape="rect" id="node59" href="../../d6/d2d/a00047.php" title="C++/collides.hpp" alt="" coords="567,1947,689,1973"/>
<area shape="rect" id="node30" href="../../d2/de7/a00014.php" title="C++/arraysIncludes.hpp" alt="" coords="733,2021,896,2048"/>
<area shape="rect" id="node37" href="../../db/ddf/a00164.php" title="C++/pointers.hpp" alt="" coords="696,2320,819,2347"/>
<area shape="rect" id="node38" href="../../d5/df1/a00206.php" title="C++/types.hpp" alt="" coords="595,2395,704,2421"/>
<area shape="rect" id="node40" href="../../d4/d51/a00017.php" title="Big.hpp" alt="" coords="560,2469,627,2496"/>
<area shape="rect" id="node55" href="../../dc/de6/a00167.php" title="PureVirtual.hpp" alt="" coords="651,2469,762,2496"/>
<area shape="rect" id="node56" href="../../d3/de5/a00209.php" title="UsefullDefines.hpp" alt="" coords="787,2469,920,2496"/>
<area shape="rect" id="node51" href="../../d3/d52/a00023.php" title="C++/Big_Constructor.hpp" alt="" coords="887,2544,1057,2571"/>
<area shape="rect" id="node52" href="../../d5/d16/a00029.php" title="C++/Big_Operator.hpp" alt="" coords="1082,2544,1235,2571"/>
<area shape="rect" id="node53" href="../../db/db2/a00020.php" title="C++/Big_Comparison.hpp" alt="" coords="1260,2544,1433,2571"/>
<area shape="rect" id="node54" href="../../d6/d5b/a00026.php" title="C++/Big_Maths.hpp" alt="" coords="1457,2544,1596,2571"/>
<area shape="rect" id="node60" href="../../d4/d81/a00110.php" title="C++/Matrix.hpp" alt="" coords="526,2021,639,2048"/>
<area shape="rect" id="node61" href="../../da/d2a/a00086.php" title="C++/Fraction.hpp" alt="" coords="402,2096,526,2123"/>
<area shape="rect" id="node62" href="../../df/d98/a00107.php" title="C++/maths.hpp" alt="" coords="407,2171,521,2197"/>
<area shape="rect" id="node63" href="../../dc/d87/a00032.php" title="C++/Binary.hpp" alt="" coords="653,2245,768,2272"/>
<area shape="rect" id="node81" href="../../de/de1/a00065.php" title="C++/Date.hpp" alt="" coords="943,1125,1049,1152"/>
<area shape="rect" id="node82" href="../../dc/d57/a00194.php" title="C++/Time.hpp" alt="" coords="812,1125,919,1152"/>
<area shape="rect" id="node87" href="../../d9/db6/a00146.php" title="C++/PathfindingDijkstra.hpp" alt="" coords="1317,901,1504,928"/>
<area shape="rect" id="node88" href="../../d5/db1/a00140.php" title="C++/Pathfinding.hpp" alt="" coords="1343,976,1486,1003"/>
<area shape="rect" id="node89" href="../../d7/d9a/a00152.php" title="C++/PathfindingProblem.hpp" alt="" coords="1311,1051,1502,1077"/>
<area shape="rect" id="node90" href="../../da/d1e/a00149.php" title="C++/PathfindingException.hpp" alt="" coords="1353,1125,1553,1152"/>
<area shape="rect" id="node91" href="../../d2/df5/a00137.php" title="C++/Path.hpp" alt="" coords="1225,1125,1329,1152"/>
<area shape="rect" id="node96" href="../../d3/dd5/a00215.php" title="C++/Vegetal.hpp" alt="" coords="703,304,825,331"/>
<area shape="rect" id="node97" href="../../d1/d09/a00077.php" title="C++/Entity.hpp" alt="" coords="838,453,949,480"/>
<area shape="rect" id="node100" href="../../d7/d46/a00002.php" title="C++/Animal.hpp" alt="" coords="849,304,967,331"/>
<area shape="rect" id="node101" href="../../db/dab/a00089.php" title="C++/Hostile.hpp" alt="" coords="834,379,953,405"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/d38/a00160.png" border="0" usemap="#Player_8hppdep" alt=""/></div>
<map name="Player_8hppdep" id="Player_8hppdep">
<area shape="rect" id="node2" href="../../d8/d41/a00038.php" title="C++Entities.hpp" alt="" coords="5,80,123,107"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d23/a01025.php">mcd::Player&lt; PlayerParent &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A player that can be a child from any class.  <a href="../../db/d23/a01025.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:dc/d28/a00223"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d28/a00223.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : August, 17 2018 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d6/db8/a00158.php">Player.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
