<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: system.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Fri Dec 13 2019 22:15:49 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/df1/a00206.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">system.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../db/dab/a00089.php">C++/errors.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for system.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/dd2/a00207.png" border="0" usemap="#system_8hpp" alt=""/></div>
<map name="system_8hpp" id="system_8hpp">
<area shape="rect" id="node2" href="../../db/dab/a00089.php" title="C++/errors.hpp" alt="" coords="589,80,699,107"/>
<area shape="rect" id="node3" href="../../d3/d8b/a00059.php" title="C++/console.hpp" alt="" coords="515,155,637,181"/>
<area shape="rect" id="node53" href="../../d1/dc1/a00092.php" title="C++/files.hpp" alt="" coords="661,155,763,181"/>
<area shape="rect" id="node4" href="../../da/d24/a00068.php" title="C++/convert.hpp" alt="" coords="525,229,645,256"/>
<area shape="rect" id="node6" href="../../da/d45/a00011.php" title="C++/array.hpp" alt="" coords="592,304,699,331"/>
<area shape="rect" id="node8" href="../../d5/de0/a00050.php" title="C++/check.hpp" alt="" coords="589,379,701,405"/>
<area shape="rect" id="node52" href="../../dc/d57/a00194.php" title="C++/sorting.hpp" alt="" coords="727,379,843,405"/>
<area shape="rect" id="node11" href="../../d6/de1/a00233.php" title="C++/vector.hpp" alt="" coords="730,453,843,480"/>
<area shape="rect" id="node46" href="../../d9/d2e/a00056.php" title="C++/collides.hpp" alt="" coords="585,453,706,480"/>
<area shape="rect" id="node12" href="../../d2/de7/a00014.php" title="C++/arraysIncludes.hpp" alt="" coords="751,528,913,555"/>
<area shape="rect" id="node19" href="../../d7/d25/a00182.php" title="C++/pointers.hpp" alt="" coords="713,827,836,853"/>
<area shape="rect" id="node20" href="../../d9/d01/a00227.php" title="C++/types.hpp" alt="" coords="612,901,721,928"/>
<area shape="rect" id="node22" href="../../d3/d52/a00023.php" title="Big.hpp" alt="" coords="633,976,700,1003"/>
<area shape="rect" id="node41" href="../../d5/ddf/a00224.php" title="C++/Tree.hpp" alt="" coords="506,976,609,1003"/>
<area shape="rect" id="node42" href="../../de/df3/a00185.php" title="PureVirtual.hpp" alt="" coords="725,976,835,1003"/>
<area shape="rect" id="node43" href="../../d1/da8/a00230.php" title="UsefullDefines.hpp" alt="" coords="860,976,993,1003"/>
<area shape="rect" id="node23" href="../../d7/d9a/a00152.php" title="C++/OsDetection.hpp" alt="" coords="322,1051,473,1077"/>
<area shape="rect" id="node37" href="../../d5/d16/a00029.php" title="C++/Big_Constructor.hpp" alt="" coords="1035,1051,1205,1077"/>
<area shape="rect" id="node38" href="../../d4/d8c/a00035.php" title="C++/Big_Operator.hpp" alt="" coords="497,1051,650,1077"/>
<area shape="rect" id="node39" href="../../d6/d5b/a00026.php" title="C++/Big_Comparison.hpp" alt="" coords="675,1051,848,1077"/>
<area shape="rect" id="node40" href="../../dc/d87/a00032.php" title="C++/Big_Maths.hpp" alt="" coords="872,1051,1011,1077"/>
<area shape="rect" id="node25" href="../../d3/d00/a00113.php" title="C++/lowIncludes.hpp" alt="" coords="391,1125,537,1152"/>
<area shape="rect" id="node47" href="../../dc/dfe/a00125.php" title="C++/Matrix.hpp" alt="" coords="543,528,657,555"/>
<area shape="rect" id="node48" href="../../d9/d77/a00095.php" title="C++/Fraction.hpp" alt="" coords="419,603,543,629"/>
<area shape="rect" id="node49" href="../../df/dc8/a00122.php" title="C++/maths.hpp" alt="" coords="425,677,538,704"/>
<area shape="rect" id="node50" href="../../d8/d41/a00038.php" title="C++/Binary.hpp" alt="" coords="671,752,785,779"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../dc/d31/a00208.png" border="0" usemap="#system_8hppdep" alt=""/></div>
<map name="system_8hppdep" id="system_8hppdep">
<area shape="rect" id="node2" href="../../d3/db1/a00200.php" title="string.hpp" alt="" coords="336,80,415,107"/>
<area shape="rect" id="node3" href="../../de/d79/a00203.php" title="Used to replace strptime function when compiling for Windows. " alt="" coords="335,155,415,181"/>
<area shape="rect" id="node4" href="../../dc/d9a/a00218.php" title="timeFunctions.hpp" alt="" coords="311,229,440,256"/>
<area shape="rect" id="node5" href="../../d0/dc2/a00104.php" title="includes.hpp" alt="" coords="328,304,423,331"/>
<area shape="rect" id="node6" href="../../dc/dee/a00053.php" title="Clock.hpp" alt="" coords="5,528,87,555"/>
<area shape="rect" id="node30" href="../../df/d03/a00062.php" title="ConsoleTable.hpp" alt="" coords="116,603,243,629"/>
<area shape="rect" id="node31" href="../../db/db6/a00074.php" title="Date.hpp" alt="" coords="162,379,237,405"/>
<area shape="rect" id="node33" href="../../df/d98/a00107.php" title="IOConfig.hpp" alt="" coords="318,453,417,480"/>
<area shape="rect" id="node34" href="../../d3/df8/a00155.php" title="Path.hpp" alt="" coords="413,379,487,405"/>
<area shape="rect" id="node40" href="../../dc/de6/a00167.php" title="PathfindingException.hpp" alt="" coords="511,379,682,405"/>
<area shape="rect" id="node41" href="../../da/d15/a00188.php" title="Referenced.hpp" alt="" coords="605,528,719,555"/>
<area shape="rect" id="node42" href="../../dd/dc1/a00212.php" title="Threadable.hpp" alt="" coords="715,677,825,704"/>
<area shape="rect" id="node45" href="../../d3/dd5/a00215.php" title="Time.hpp" alt="" coords="261,379,337,405"/>
<area shape="rect" id="node7" href="../../da/dec/a00080.php" title="defines.hpp" alt="" coords="356,827,445,853"/>
<area shape="rect" id="node8" href="../../db/db2/a00020.php" title="AssertionException.hpp" alt="" coords="262,901,422,928"/>
<area shape="rect" id="node29" href="../../d0/d89/a00071.php" title="cryptage.hpp" alt="" coords="409,976,507,1003"/>
<area shape="rect" id="node9" href="../../d4/d51/a00017.php" title="Assert.hpp" alt="" coords="299,976,385,1003"/>
<area shape="rect" id="node10" href="../../d6/d2d/a00047.php" title="C++lib.hpp" alt="" coords="356,1051,443,1077"/>
<area shape="rect" id="node11" href="../../d4/d81/a00110.php" title="Logger.hpp" alt="" coords="304,1125,391,1152"/>
<area shape="rect" id="node28" href="../../d3/de5/a00209.php" title="Test.hpp" alt="" coords="415,1125,488,1152"/>
<area shape="rect" id="node12" href="../../dd/d32/a00041.php" title="C++.hpp" alt="" coords="363,1200,436,1227"/>
<area shape="rect" id="node13" href="../../de/de1/a00065.php" title="Contraption.hpp" alt="" coords="295,1275,410,1301"/>
<area shape="rect" id="node27" href="../../d4/d3a/a00101.php" title="Identifier.hpp" alt="" coords="395,1648,492,1675"/>
<area shape="rect" id="node14" href="../../da/d2a/a00086.php" title="Entity.hpp" alt="" coords="199,1349,280,1376"/>
<area shape="rect" id="node25" href="../../da/d1e/a00149.php" title="Object.hpp" alt="" coords="318,1349,403,1376"/>
<area shape="rect" id="node15" href="../../d1/d44/a00098.php" title="Hostile.hpp" alt="" coords="85,1424,173,1451"/>
<area shape="rect" id="node22" href="../../d7/d40/a00236.php" title="Vegetal.hpp" alt="" coords="194,1499,285,1525"/>
<area shape="rect" id="node16" href="../../d7/d46/a00002.php" title="Animal.hpp" alt="" coords="56,1499,143,1525"/>
<area shape="rect" id="node17" href="../../dd/dad/a00005.php" title="Ant.hpp" alt="" coords="58,1573,125,1600"/>
<area shape="rect" id="node18" href="../../d2/d1f/a00083.php" title="Entities.hpp" alt="" coords="275,1648,366,1675"/>
<area shape="rect" id="node19" href="../../db/dd9/a00179.php" title="PlayerAbstraction.hpp" alt="" coords="248,1723,399,1749"/>
<area shape="rect" id="node20" href="../../d5/de9/a00176.php" title="Player.hpp" alt="" coords="337,1797,421,1824"/>
<area shape="rect" id="node21" href="../../d5/df9/a00044.php" title="C++Entities.hpp" alt="" coords="321,1872,438,1899"/>
<area shape="rect" id="node23" href="../../d5/db1/a00140.php" title="Mushroom.hpp" alt="" coords="149,1573,257,1600"/>
<area shape="rect" id="node24" href="../../d7/d3f/a00173.php" title="Plant.hpp" alt="" coords="282,1573,359,1600"/>
<area shape="rect" id="node26" href="../../de/db1/a00197.php" title="Stone.hpp" alt="" coords="328,1424,409,1451"/>
<area shape="rect" id="node32" href="../../d1/d09/a00077.php" title="DateTime.hpp" alt="" coords="190,453,294,480"/>
<area shape="rect" id="node35" href="../../d5/dcb/a00170.php" title="PathfindingProblem.hpp" alt="" coords="441,453,601,480"/>
<area shape="rect" id="node36" href="../../d6/db8/a00158.php" title="Pathfinding.hpp" alt="" coords="438,528,550,555"/>
<area shape="rect" id="node37" href="../../db/ddf/a00164.php" title="PathfindingDijkstra.hpp" alt="" coords="402,603,559,629"/>
<area shape="rect" id="node38" href="../../d6/d7d/a00161.php" title="PathfindingAlgorithms.hpp" alt="" coords="389,677,564,704"/>
<area shape="rect" id="node39" href="../../df/d6a/a00119.php" title="Map.hpp" alt="" coords="415,752,487,779"/>
<area shape="rect" id="node43" href="../../d4/dee/a00008.php" title="Args.hpp" alt="" coords="639,752,714,779"/>
<area shape="rect" id="node44" href="../../dd/d52/a00221.php" title="Timer.hpp" alt="" coords="738,752,818,779"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:d6/d08/a00244"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d08/a00244.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a0d72a06346182146581ff63f2fa70580"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d08/a00244.php#a0d72a06346182146581ff63f2fa70580">mcd::exec</a> (const std::string &amp;cmd, bool force=false)</td></tr>
<tr class="memdesc:a0d72a06346182146581ff63f2fa70580"><td class="mdescLeft">&#160;</td><td class="mdescRight">Use system in an IF and say if there is an error.  <a href="../../d6/d08/a00244.php#a0d72a06346182146581ff63f2fa70580">More...</a><br /></td></tr>
<tr class="separator:a0d72a06346182146581ff63f2fa70580"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abcc09c3d97d72792032b5615d41aa1c5"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d08/a00244.php#abcc09c3d97d72792032b5615d41aa1c5">mcd::servLog</a> (const std::string &amp;str, bool server=false, const std::string &amp;name=&quot;Server&quot;)</td></tr>
<tr class="memdesc:abcc09c3d97d72792032b5615d41aa1c5"><td class="mdescLeft">&#160;</td><td class="mdescRight">Write a string in cout like in a server.  <a href="../../d6/d08/a00244.php#abcc09c3d97d72792032b5615d41aa1c5">More...</a><br /></td></tr>
<tr class="separator:abcc09c3d97d72792032b5615d41aa1c5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : April, 24 2019 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d5/df1/a00206.php">system.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
