<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: timeFunctions.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Apr 28 2019 10:55:00 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d6/db3/a00130.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">timeFunctions.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;ctime&gt;</code><br />
<code>#include &quot;<a class="el" href="../../d7/d12/a00126.php">C++/string.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for timeFunctions.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d3/d1a/a00251.png" border="0" usemap="#timeFunctions_8hpp" alt=""/></div>
<map name="timeFunctions_8hpp" id="timeFunctions_8hpp">
<area shape="rect" id="node3" href="../../d7/d12/a00126.php" title="C++/string.hpp" alt="" coords="364,80,473,107"/>
<area shape="rect" id="node5" href="../../df/dcd/a00127.php" title="C++/system.hpp" alt="" coords="291,155,411,181"/>
<area shape="rect" id="node50" href="../../de/d36/a00123.php" title="C++/RNG.hpp" alt="" coords="435,155,541,181"/>
<area shape="rect" id="node52" href="../../d0/dc2/a00104.php" title="C++/macro.hpp" alt="" coords="566,155,679,181"/>
<area shape="rect" id="node6" href="../../d1/d44/a00098.php" title="C++/errors.hpp" alt="" coords="295,229,406,256"/>
<area shape="rect" id="node7" href="../../db/ddf/a00088.php" title="C++/console.hpp" alt="" coords="221,304,344,331"/>
<area shape="rect" id="node48" href="../../da/d74/a00099.php" title="C++/files.hpp" alt="" coords="368,304,469,331"/>
<area shape="rect" id="node8" href="../../da/d82/a00091.php" title="C++/convert.hpp" alt="" coords="232,379,352,405"/>
<area shape="rect" id="node10" href="../../d9/da5/a00075.php" title="C++/array.hpp" alt="" coords="299,453,405,480"/>
<area shape="rect" id="node12" href="../../df/d13/a00085.php" title="C++/check.hpp" alt="" coords="296,528,408,555"/>
<area shape="rect" id="node47" href="../../da/d72/a00124.php" title="C++/sorting.hpp" alt="" coords="502,528,618,555"/>
<area shape="rect" id="node16" href="../../db/df8/a00076.php" title="C++/arraysIncludes.hpp" alt="" coords="515,603,677,629"/>
<area shape="rect" id="node45" href="../../d1/d1e/a00087.php" title="C++/collides.hpp" alt="" coords="369,603,490,629"/>
<area shape="rect" id="node23" href="../../d4/d98/a00120.php" title="C++/pointers.hpp" alt="" coords="480,752,603,779"/>
<area shape="rect" id="node26" href="../../d0/de8/a00133.php" title="C++/types.hpp" alt="" coords="595,827,704,853"/>
<area shape="rect" id="node28" href="../../d9/da4/a00078.php" title="Big.hpp" alt="" coords="560,901,627,928"/>
<area shape="rect" id="node43" href="../../d8/dfa/a00121.php" title="PureVirtual.hpp" alt="" coords="651,901,762,928"/>
<area shape="rect" id="node44" href="../../de/d76/a00134.php" title="UsefullDefines.hpp" alt="" coords="787,901,920,928"/>
<area shape="rect" id="node39" href="../../da/dec/a00080.php" title="C++/Big_Constructor.hpp" alt="" coords="887,976,1057,1003"/>
<area shape="rect" id="node40" href="../../d4/d63/a00082.php" title="C++/Big_Operator.hpp" alt="" coords="1082,976,1235,1003"/>
<area shape="rect" id="node41" href="../../d1/d51/a00079.php" title="C++/Big_Comparison.hpp" alt="" coords="1260,976,1433,1003"/>
<area shape="rect" id="node42" href="../../d8/d53/a00081.php" title="C++/Big_Maths.hpp" alt="" coords="1457,976,1596,1003"/>
<area shape="rect" id="node46" href="../../df/d98/a00107.php" title="C++/maths.hpp" alt="" coords="194,677,307,704"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../dc/ded/a00252.png" border="0" usemap="#timeFunctions_8hppdep" alt=""/></div>
<map name="timeFunctions_8hppdep" id="timeFunctions_8hppdep">
<area shape="rect" id="node2" href="../../d9/dcc/a00102.php" title="includes.hpp" alt="" coords="301,80,396,107"/>
<area shape="rect" id="node3" href="../../da/d2a/a00086.php" title="Clock.hpp" alt="" coords="5,304,87,331"/>
<area shape="rect" id="node24" href="../../db/dab/a00089.php" title="ConsoleTable.hpp" alt="" coords="56,229,183,256"/>
<area shape="rect" id="node25" href="../../d4/d7d/a00093.php" title="Date.hpp" alt="" coords="135,155,210,181"/>
<area shape="rect" id="node27" href="../../d5/d1e/a00103.php" title="IOConfig.hpp" alt="" coords="297,304,395,331"/>
<area shape="rect" id="node28" href="../../dd/d6d/a00111.php" title="Path.hpp" alt="" coords="386,155,461,181"/>
<area shape="rect" id="node33" href="../../d2/da3/a00115.php" title="PathfindingException.hpp" alt="" coords="485,155,655,181"/>
<area shape="rect" id="node34" href="../../df/dc8/a00122.php" title="Referenced.hpp" alt="" coords="549,379,663,405"/>
<area shape="rect" id="node35" href="../../d1/d88/a00128.php" title="Threadable.hpp" alt="" coords="688,379,799,405"/>
<area shape="rect" id="node39" href="../../d9/d47/a00129.php" title="Time.hpp" alt="" coords="235,155,311,181"/>
<area shape="rect" id="node4" href="../../d9/d77/a00095.php" title="defines.hpp" alt="" coords="401,528,491,555"/>
<area shape="rect" id="node5" href="../../d1/dc1/a00092.php" title="cryptage.hpp" alt="" coords="288,603,385,629"/>
<area shape="rect" id="node22" href="../../d7/d70/a00106.php" title="Map.hpp" alt="" coords="410,603,482,629"/>
<area shape="rect" id="node23" href="../../d5/deb/a00132.php" title="Tree.hpp" alt="" coords="507,603,580,629"/>
<area shape="rect" id="node6" href="../../d2/d1f/a00083.php" title="C++.hpp" alt="" coords="409,677,483,704"/>
<area shape="rect" id="node7" href="../../d9/dec/a00090.php" title="Contraption.hpp" alt="" coords="342,752,457,779"/>
<area shape="rect" id="node21" href="../../d4/d3a/a00101.php" title="Identifier.hpp" alt="" coords="441,1125,539,1152"/>
<area shape="rect" id="node8" href="../../d1/d84/a00097.php" title="Entity.hpp" alt="" coords="232,827,313,853"/>
<area shape="rect" id="node19" href="../../d4/d81/a00110.php" title="Object.hpp" alt="" coords="365,827,450,853"/>
<area shape="rect" id="node9" href="../../d0/d61/a00100.php" title="Hostile.hpp" alt="" coords="121,901,209,928"/>
<area shape="rect" id="node16" href="../../d5/d5b/a00135.php" title="Vegetal.hpp" alt="" coords="227,976,318,1003"/>
<area shape="rect" id="node10" href="../../d6/d2c/a00072.php" title="Animal.hpp" alt="" coords="105,976,192,1003"/>
<area shape="rect" id="node11" href="../../d1/d6e/a00073.php" title="Ant.hpp" alt="" coords="105,1051,171,1077"/>
<area shape="rect" id="node12" href="../../d9/df8/a00096.php" title="Entities.hpp" alt="" coords="322,1125,413,1152"/>
<area shape="rect" id="node13" href="../../df/d6a/a00119.php" title="PlayerAbstraction.hpp" alt="" coords="296,1200,447,1227"/>
<area shape="rect" id="node14" href="../../d8/d87/a00118.php" title="Player.hpp" alt="" coords="387,1275,471,1301"/>
<area shape="rect" id="node15" href="../../df/d5d/a00084.php" title="C++Entities.hpp" alt="" coords="370,1349,487,1376"/>
<area shape="rect" id="node17" href="../../d1/dd6/a00108.php" title="Mushroom.hpp" alt="" coords="196,1051,304,1077"/>
<area shape="rect" id="node18" href="../../d9/d4b/a00117.php" title="Plant.hpp" alt="" coords="329,1051,406,1077"/>
<area shape="rect" id="node20" href="../../dc/dfe/a00125.php" title="Stone.hpp" alt="" coords="371,901,452,928"/>
<area shape="rect" id="node26" href="../../dc/d54/a00094.php" title="DateTime.hpp" alt="" coords="207,229,311,256"/>
<area shape="rect" id="node29" href="../../d4/d3e/a00116.php" title="PathfindingProblem.hpp" alt="" coords="395,229,555,256"/>
<area shape="rect" id="node30" href="../../db/d57/a00112.php" title="Pathfinding.hpp" alt="" coords="419,304,531,331"/>
<area shape="rect" id="node31" href="../../d8/d17/a00114.php" title="PathfindingDijkstra.hpp" alt="" coords="367,379,525,405"/>
<area shape="rect" id="node32" href="../../d3/d00/a00113.php" title="PathfindingAlgorithms.hpp" alt="" coords="359,453,533,480"/>
<area shape="rect" id="node36" href="../../db/db6/a00074.php" title="Args.hpp" alt="" coords="609,453,683,480"/>
<area shape="rect" id="node37" href="../../d1/d09/a00077.php" title="bdd.hpp" alt="" coords="708,453,776,480"/>
<area shape="rect" id="node38" href="../../d7/d06/a00131.php" title="Timer.hpp" alt="" coords="801,453,881,480"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:dd/d1b/a00015"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a49144605ea2f1f8a9463ae309c293628"><td class="memItemLeft" align="right" valign="top">std::time_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a49144605ea2f1f8a9463ae309c293628">mcd::getSec</a> ()</td></tr>
<tr class="memdesc:a49144605ea2f1f8a9463ae309c293628"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the number of seconds since the Epoch.  <a href="../../dd/d1b/a00015.php#a49144605ea2f1f8a9463ae309c293628">More...</a><br /></td></tr>
<tr class="separator:a49144605ea2f1f8a9463ae309c293628"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac4573282fe9cf6a0af8de786baaf6456"><td class="memItemLeft" align="right" valign="top">std::chrono::milliseconds&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#ac4573282fe9cf6a0af8de786baaf6456">mcd::getMilli</a> ()</td></tr>
<tr class="memdesc:ac4573282fe9cf6a0af8de786baaf6456"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the milliseconds since the Epoch.  <a href="../../dd/d1b/a00015.php#ac4573282fe9cf6a0af8de786baaf6456">More...</a><br /></td></tr>
<tr class="separator:ac4573282fe9cf6a0af8de786baaf6456"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0003c12a7cc73a35e488f59ad14770bf"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a0003c12a7cc73a35e488f59ad14770bf">mcd::sleep</a> (size_t duration)</td></tr>
<tr class="memdesc:a0003c12a7cc73a35e488f59ad14770bf"><td class="mdescLeft">&#160;</td><td class="mdescRight">Sleep the thread during <em>duration</em> seconds.  <a href="../../dd/d1b/a00015.php#a0003c12a7cc73a35e488f59ad14770bf">More...</a><br /></td></tr>
<tr class="separator:a0003c12a7cc73a35e488f59ad14770bf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a30ed8e5c290433011b9855598cfc050a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a30ed8e5c290433011b9855598cfc050a">mcd::milliSleep</a> (size_t duration)</td></tr>
<tr class="memdesc:a30ed8e5c290433011b9855598cfc050a"><td class="mdescLeft">&#160;</td><td class="mdescRight">Sleep the thread during <em>duration</em> milliseconds.  <a href="../../dd/d1b/a00015.php#a30ed8e5c290433011b9855598cfc050a">More...</a><br /></td></tr>
<tr class="separator:a30ed8e5c290433011b9855598cfc050a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a773d8ead6e35e10f86f4285f3f79ecb9"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a773d8ead6e35e10f86f4285f3f79ecb9">mcd::microSleep</a> (size_t duration)</td></tr>
<tr class="memdesc:a773d8ead6e35e10f86f4285f3f79ecb9"><td class="mdescLeft">&#160;</td><td class="mdescRight">Sleep the thread during <em>duration</em> microseconds.  <a href="../../dd/d1b/a00015.php#a773d8ead6e35e10f86f4285f3f79ecb9">More...</a><br /></td></tr>
<tr class="separator:a773d8ead6e35e10f86f4285f3f79ecb9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5b2e0c30451ea35d0cc5eb9badea5be0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a5b2e0c30451ea35d0cc5eb9badea5be0">mcd::nanoSleep</a> (size_t duration)</td></tr>
<tr class="memdesc:a5b2e0c30451ea35d0cc5eb9badea5be0"><td class="mdescLeft">&#160;</td><td class="mdescRight">Sleep the thread during <em>duration</em> nanoseconds.  <a href="../../dd/d1b/a00015.php#a5b2e0c30451ea35d0cc5eb9badea5be0">More...</a><br /></td></tr>
<tr class="separator:a5b2e0c30451ea35d0cc5eb9badea5be0"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d6/db3/a00130.php">timeFunctions.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
