<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Class Index</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Fri Sep 27 2019 01:33:45 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('classes.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Class Index</div>  </div>
</div><!--header-->
<div class="contents">
<div class="qindex"><a class="qindex" href="#letter_a">a</a>&#160;|&#160;<a class="qindex" href="#letter_b">b</a>&#160;|&#160;<a class="qindex" href="#letter_c">c</a>&#160;|&#160;<a class="qindex" href="#letter_d">d</a>&#160;|&#160;<a class="qindex" href="#letter_e">e</a>&#160;|&#160;<a class="qindex" href="#letter_f">f</a>&#160;|&#160;<a class="qindex" href="#letter_h">h</a>&#160;|&#160;<a class="qindex" href="#letter_i">i</a>&#160;|&#160;<a class="qindex" href="#letter_m">m</a>&#160;|&#160;<a class="qindex" href="#letter_n">n</a>&#160;|&#160;<a class="qindex" href="#letter_o">o</a>&#160;|&#160;<a class="qindex" href="#letter_p">p</a>&#160;|&#160;<a class="qindex" href="#letter_q">q</a>&#160;|&#160;<a class="qindex" href="#letter_r">r</a>&#160;|&#160;<a class="qindex" href="#letter_s">s</a>&#160;|&#160;<a class="qindex" href="#letter_t">t</a>&#160;|&#160;<a class="qindex" href="#letter_v">v</a>&#160;|&#160;<a class="qindex" href="#letter_w">w</a></div>
<table class="classindex">
<tr><td rowspan="2" valign="bottom"><a name="letter_a"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;a&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="d7/d16/a00930.php">DateTime</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d6/da7/a00822.php">is_quatuor</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d4/dd0/a00994.php">Pathfinding</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d6/d17/a00778.php">stack</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td rowspan="2" valign="bottom"><a name="letter_e"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;e&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="d9/daf/a00830.php">is_smatch</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d9/d9a/a00998.php">PathfindingDijkstra</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d4/d56/a01042.php">Stone</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="d4/d13/a00766.php">Animal</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="dd/db2/a00866.php">is_special_struct</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d2/dd5/a01002.php">PathfindingException</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_t"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;t&#160;&#160;</div></td></tr></table>
</td></tr>
<tr><td valign="top"><a class="el" href="d0/d7e/a00770.php">Ant</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d5/d54/a00938.php">Entity</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="da/d90/a00826.php">is_string</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d3/d7b/a00986.php">PathfindingNode</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="d3/dee/a00774.php">Arguments</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_f"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;f&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="de/d02/a01026.php">is_thread_ptr</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="dc/d81/a01006.php">PathfindingProblem</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d3/daf/a00790.php">t_queue</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td rowspan="2" valign="bottom"><a name="letter_b"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;b&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="d3/d60/a00818.php">is_trio</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d0/d2b/a01010.php">Plant</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="da/d96/a00782.php">t_stack</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="df/d12/a00942.php">Fraction</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d4/dfd/a00810.php">is_vector</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d0/d56/a01014.php">Player</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="da/d17/a01046.php">Threadable</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="d5/d12/a00794.php">Big</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_h"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;h&#160;&#160;</div></td></tr></table>
</td><td rowspan="2" valign="bottom"><a name="letter_m"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;m&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="d3/d08/a01018.php">PlayerAbstraction</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="dc/dfa/a00894.php">ThreadCout</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="df/d24/a00217.php#de/d79/a00798">Binary</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d7/df7/a01074.php">Point</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d7/d46/a00890.php">ThreadEndlCout</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="d5/dcd/a00802.php">Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="dc/d0a/a00850.php">has_istream_operator</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d2/d6e/a00966.php">Map</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="de/d41/a01030.php">PureVirtual</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d9/d8e/a01050.php">Time</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td rowspan="2" valign="bottom"><a name="letter_c"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;c&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="d0/d11/a00842.php">has_ostream_operator</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="df/d24/a00217.php#df/d88/a00962">MapMove</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_q"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;q&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="dd/d57/a01054.php">Timer</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="d2/dc7/a00838.php">has_size_method</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d0/daf/a00970.php">Matrix</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d4/d8a/a01062.php">Tree</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="d4/d12/a00910.php">Cesar</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="da/d40/a00946.php">Hostile</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="df/dce/a00974.php">Mushroom</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="df/d24/a00217.php#d5/d67/a01070">quatuor</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="df/d24/a00217.php#d0/dfb/a01066">trio</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="da/d98/a00870.php">Clock</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_i"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;i&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="d0/ddf/a00918.php">MyCrypt</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d0/d7d/a00786.php">queue</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_v"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;v&#160;&#160;</div></td></tr></table>
</td></tr>
<tr><td valign="top"><a class="el" href="d3/d50/a00882.php">Cls</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_n"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;n&#160;&#160;</div></td></tr></table>
</td><td rowspan="2" valign="bottom"><a name="letter_r"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;r&#160;&#160;</div></td></tr></table>
</td></tr>
<tr><td valign="top"><a class="el" href="df/d2a/a00874.php">Color</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="df/d39/a00950.php">Identifier</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="db/dba/a01078.php">vector</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="d2/dab/a00886.php">ConsoleCursor</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d3/dca/a00954.php">IOConfig</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="df/d24/a00217.php#d5/d4c/a01058">Node</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="de/d91/a01034.php">Referenced</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="dd/df1/a01082.php">Vegetal</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="d2/d79/a00898.php">ConsoleTable</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d0/dad/a00806.php">is_array</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d2/ddd/a00978.php">NotCopyable</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d5/d69/a00878.php">Reinit</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_w"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;w&#160;&#160;</div></td></tr></table>
</td></tr>
<tr><td valign="top"><a class="el" href="d5/dd3/a00902.php">Contraption</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d9/d02/a00834.php">is_duration</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_o"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;o&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="d4/dbc/a01038.php">RNG</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="df/d24/a00217.php#d0/df0/a00934">ContraptionAttr</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d1/dd8/a01022.php">is_minded_ptr</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="dd/dcf/a00922.php">RSA</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="df/d24/a00217.php#df/d9c/a00958">WorldDimensions</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td></tr>
<tr><td valign="top"><a class="el" href="da/dd8/a00906.php">Crypto</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="dc/d41/a00862.php">is_object</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d1/d7a/a00982.php">Object</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_s"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;s&#160;&#160;</div></td></tr></table>
</td><td></td></tr>
<tr><td rowspan="2" valign="bottom"><a name="letter_d"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;d&#160;&#160;</div></td></tr></table>
</td><td valign="top"><a class="el" href="da/d71/a00814.php">is_pair</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td rowspan="2" valign="bottom"><a name="letter_p"></a><table border="0" cellspacing="0" cellpadding="0"><tr><td><div class="ah">&#160;&#160;p&#160;&#160;</div></td></tr></table>
</td><td></td></tr>
<tr><td valign="top"><a class="el" href="d0/d66/a00858.php">is_printable</a> (<a class="el" href="dc/d9a/a00218.php">mcd::Check</a>)&#160;&#160;&#160;</td><td valign="top"><a class="el" href="d3/dd1/a00914.php">SHA2</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td></td></tr>
<tr><td valign="top"><a class="el" href="d8/d38/a00926.php">Date</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td></td><td valign="top"><a class="el" href="dd/d7a/a00990.php">Path</a> (<a class="el" href="df/d24/a00217.php">mcd</a>)&#160;&#160;&#160;</td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td><td></td></tr>
</table>
<div class="qindex"><a class="qindex" href="#letter_a">a</a>&#160;|&#160;<a class="qindex" href="#letter_b">b</a>&#160;|&#160;<a class="qindex" href="#letter_c">c</a>&#160;|&#160;<a class="qindex" href="#letter_d">d</a>&#160;|&#160;<a class="qindex" href="#letter_e">e</a>&#160;|&#160;<a class="qindex" href="#letter_f">f</a>&#160;|&#160;<a class="qindex" href="#letter_h">h</a>&#160;|&#160;<a class="qindex" href="#letter_i">i</a>&#160;|&#160;<a class="qindex" href="#letter_m">m</a>&#160;|&#160;<a class="qindex" href="#letter_n">n</a>&#160;|&#160;<a class="qindex" href="#letter_o">o</a>&#160;|&#160;<a class="qindex" href="#letter_p">p</a>&#160;|&#160;<a class="qindex" href="#letter_q">q</a>&#160;|&#160;<a class="qindex" href="#letter_r">r</a>&#160;|&#160;<a class="qindex" href="#letter_s">s</a>&#160;|&#160;<a class="qindex" href="#letter_t">t</a>&#160;|&#160;<a class="qindex" href="#letter_v">v</a>&#160;|&#160;<a class="qindex" href="#letter_w">w</a></div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
