<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: Class Members - Functions</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.1.1</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Nov 15 2020 11:00:16 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('functions_func_o.php',''); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_o"></a>- o -</h3><ul>
<li>Object()
: <a class="el" href="df/d10/a01357.php#ad332f3a57527a6ede1be2e18b65615a5">mcd::Object</a>
</li>
<li>onCompare()
: <a class="el" href="d5/df9/a01441.php#a279d0472004ed9618dde58fcfd6bb508">mcd::Tree&lt; T &gt;</a>
</li>
<li>onDelete()
: <a class="el" href="d5/df9/a01441.php#ad9cda4b45c11828381cde08fa48ae94d">mcd::Tree&lt; T &gt;</a>
</li>
<li>operator bool()
: <a class="el" href="d9/d17/a01129.php#ac482f8c9f482ce76ed197faf07d24617">mcd::Big</a>
</li>
<li>operator double()
: <a class="el" href="dc/dd5/a01293.php#a285e38748cb55302c43feab8fa4a29f5">mcd::Fraction</a>
</li>
<li>operator std::string()
: <a class="el" href="d9/d17/a01129.php#a638fbd4ccaffb7b432c7c78d2f510134">mcd::Big</a>
</li>
<li>operator T()
: <a class="el" href="d9/d17/a01129.php#a42a1a05e756cde973a62bede71473069">mcd::Big</a>
</li>
<li>operator!=()
: <a class="el" href="dc/dd5/a01293.php#a9803ec99dc9da6df50c872a281a10c14">mcd::Fraction</a>
</li>
<li>operator%()
: <a class="el" href="d6/d6e/a01137.php#a5e868f4d94de157b5dc9686169759c25">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#a619d937a957bc1f2516066ebb3501951">mcd::Fraction</a>
</li>
<li>operator%=()
: <a class="el" href="d9/d17/a01129.php#a078be418a37b709c8124ec69cfd66836">mcd::Big</a>
, <a class="el" href="d6/d6e/a01137.php#ab9c7ac190008adce96818f231a7f1b29">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#a7b6753a02a790ffbb75c36920237167c">mcd::Fraction</a>
</li>
<li>operator&amp;()
: <a class="el" href="d6/d6e/a01137.php#ab5d91a8250d4c61551dd6a12087ec4e9">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
</li>
<li>operator&amp;=()
: <a class="el" href="d6/d6e/a01137.php#a860b1e9436a7aa4474fa873eebf1ba18">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="da/df7/a01457.php#acef3e5f0cf617a16de3d05045f6a21ed">mcd::vector&lt; C &gt;</a>
</li>
<li>operator()()
: <a class="el" href="dd/de4/a01121.php#ab411af4c628ae6ed469f78119eb99de4">mcd::Assert</a>
, <a class="el" href="d3/d07/a01241.php#ad5d2436f989665365b5da4dd154c07bd">mcd::Console::SetPrecision</a>
, <a class="el" href="dc/d2a/a01333.php#a1809056415a86a4627e0cad3bbb0b3b0">mcd::Map</a>
, <a class="el" href="db/dec/a01337.php#a895533c348847ed307cafe3d85c8ebf9">mcd::Matrix&lt; C &gt;</a>
, <a class="el" href="d7/d68/a01413.php#a8b84a9dc967e1210738e3a8bba43e4a4">mcd::RND&lt; T, U &gt;</a>
</li>
<li>operator*()
: <a class="el" href="d6/d6e/a01137.php#ac075fbd59e6455aebe1bf83227741501">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#aece90dc9d246328147f02da505af1050">mcd::Fraction</a>
, <a class="el" href="db/dec/a01337.php#a957d2d9f14651524380e8157f9b5c81e">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator*=()
: <a class="el" href="d9/d17/a01129.php#aee0004ba93bf9b5e84bc6069b2e70330">mcd::Big</a>
, <a class="el" href="d6/d6e/a01137.php#aca12b38947b6b62909b8fea33b3f31c1">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#aae423fa04b3025e509901155241b5402">mcd::Fraction</a>
, <a class="el" href="db/dec/a01337.php#a5a6d6beaad0043a80248e0c794b35b41">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator+()
: <a class="el" href="d6/d6e/a01137.php#a96aabebb693a050eec49429233f55998">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#a0897ad5e88848032ff6570bd83ddbef7">mcd::Fraction</a>
, <a class="el" href="db/dec/a01337.php#a4e98d6c2cc727cfb4aa0e4fdded9b076">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator++()
: <a class="el" href="dc/dd5/a01293.php#af066abb5b8fe5db0e0c4ce7d125f0c5e">mcd::Fraction</a>
</li>
<li>operator+=()
: <a class="el" href="d9/d17/a01129.php#a71c734bca411504941a7a5a611b8e285">mcd::Big</a>
, <a class="el" href="d6/d6e/a01137.php#a968c3515ac59bc3455944f89db13fcb0">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#a76f6e7a0b34f33d8d53bc993b7c0ac89">mcd::Fraction</a>
, <a class="el" href="db/dec/a01337.php#a726c8287d0230d12145c7817a48370ae">mcd::Matrix&lt; C &gt;</a>
, <a class="el" href="de/df6/a01141.php#a749b7cda25492926ad8bffcbf9d79c3e">mcd::natural::Cell</a>
, <a class="el" href="de/d04/a01209.php#af78f3653fd09e326bf53699b972329d3">mcd::natural::Chromosome</a>
, <a class="el" href="da/df7/a01457.php#a0ac9b9f19baf217c291e37a190b3e68c">mcd::vector&lt; C &gt;</a>
</li>
<li>operator-()
: <a class="el" href="d6/d6e/a01137.php#a1334dd26328e22ce50e91de36dc69dfa">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#a7a16f5b2182b2752cfbef72018e7636e">mcd::Fraction</a>
, <a class="el" href="db/dec/a01337.php#ac4c11fb6b3b07324760b321fbb1d8133">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator--()
: <a class="el" href="dc/dd5/a01293.php#a34e188b2c7100e21fe387855ca963f52">mcd::Fraction</a>
</li>
<li>operator-=()
: <a class="el" href="d9/d17/a01129.php#aa11404d0af642fa7e89fc484445200d5">mcd::Big</a>
, <a class="el" href="d6/d6e/a01137.php#a0a6198f933e2d8f262467aa5171baf7a">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#a455683f59112555055fc6c5686a9621a">mcd::Fraction</a>
, <a class="el" href="db/dec/a01337.php#a502cfc9cc8f10aa5ca5a5e1194932ad0">mcd::Matrix&lt; C &gt;</a>
, <a class="el" href="da/df7/a01457.php#a78502b560831d092c0eaaca67e79d4f4">mcd::vector&lt; C &gt;</a>
</li>
<li>operator/()
: <a class="el" href="d6/d6e/a01137.php#a502c702e99d1b1e97e72fae39b1063a8">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#a0ffeec4d80502f0173a03d7b3aa361db">mcd::Fraction</a>
, <a class="el" href="db/dec/a01337.php#a0d321172c9d51e8dd372711d3780e348">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator/=()
: <a class="el" href="d9/d17/a01129.php#aed2dc1aa4bd20abbe2c48aefe115b57d">mcd::Big</a>
, <a class="el" href="d6/d6e/a01137.php#a1a3d5135edf9681af40cc8e917e29b15">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="dc/dd5/a01293.php#a4942772dfaef8d5158163f7fcca98b57">mcd::Fraction</a>
, <a class="el" href="db/dec/a01337.php#afe90a761f6005ead4652574b71e40221">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator&lt;()
: <a class="el" href="dc/dd5/a01293.php#a4c0588f44c0f24a7cb2fe0d1a4c05ad5">mcd::Fraction</a>
</li>
<li>operator&lt;&lt;()
: <a class="el" href="d6/d6e/a01137.php#a31f62f20ead58385f3c19590d69e095f">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
</li>
<li>operator&lt;&lt;=()
: <a class="el" href="d6/d6e/a01137.php#a6a6b170313bb013e4108470677750f03">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
</li>
<li>operator&lt;=()
: <a class="el" href="dc/dd5/a01293.php#add6d3ff26c1c87e2d645ad37e751bdac">mcd::Fraction</a>
</li>
<li>operator=()
: <a class="el" href="d9/d17/a01129.php#adc8b04536591da50d9c9342a5eccaf42">mcd::Big</a>
, <a class="el" href="d9/dda/a01289.php#ab86ac60ef49f2bf978faa24588b32ced">mcd::exception</a>
, <a class="el" href="de/d90/a01313.php#ac2afe8da3954c9e84cc97674a0194d03">mcd::Json</a>
, <a class="el" href="d9/dae/a01453.php#aeac533b3e4edb1f24bd947e0a96bb5c4">mcd::Point</a>
, <a class="el" href="db/df2/a01425.php#aede63b72f054d20e35d22153af8313c8">mcd::Threadable&lt; C &gt;</a>
, <a class="el" href="da/df7/a01457.php#a2a215cad8226c8f949ff27fcd0e606b8">mcd::vector&lt; C &gt;</a>
</li>
<li>operator==()
: <a class="el" href="dc/dd5/a01293.php#a300ed85793b7aece141599c82524f8d9">mcd::Fraction</a>
</li>
<li>operator&gt;()
: <a class="el" href="dc/dd5/a01293.php#a5160d78b6f8e8269aacac56fb50346df">mcd::Fraction</a>
</li>
<li>operator&gt;=()
: <a class="el" href="dc/dd5/a01293.php#ac4dcbd6c3961244afb7bbcb90c5b01da">mcd::Fraction</a>
</li>
<li>operator&gt;&gt;()
: <a class="el" href="d6/d6e/a01137.php#a0024cd90341cbd89270738b791011d01">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
</li>
<li>operator&gt;&gt;=()
: <a class="el" href="d6/d6e/a01137.php#a8a8d08b67d142a871bdbf2d2d6b6b02a">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
</li>
<li>operator[]()
: <a class="el" href="d1/dfa/a01097.php#ac56d872fc98d66350596b44230f927fe">mcd::Arguments</a>
, <a class="el" href="de/d90/a01313.php#af146512243e74e908084f7751a8ffdf4">mcd::Json</a>
</li>
<li>operator^()
: <a class="el" href="d6/d6e/a01137.php#afec0277f6214fd493039d940cc6bf5c7">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
</li>
<li>operator^=()
: <a class="el" href="d6/d6e/a01137.php#a69b1bdfd8d4c0ff3727cdab70e086349">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="da/df7/a01457.php#a5bccad40e32efad3b685320434e65201">mcd::vector&lt; C &gt;</a>
</li>
<li>operator|()
: <a class="el" href="d6/d6e/a01137.php#adc6ba7b8a523f0cdaabb5fd70451fcf8">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
</li>
<li>operator|=()
: <a class="el" href="d6/d6e/a01137.php#a94f4f75fd082e9e4f06f1bab865ea79d">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="da/df7/a01457.php#acf021f04fbc720705d300f638b8f2de1">mcd::vector&lt; C &gt;</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
