<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Class Members - Functions</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Thu Sep 26 2019 11:50:16 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_func_o.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_o"></a>- o -</h3><ul>
<li>Object()
: <a class="el" href="d7/dd4/a00968.php#ad332f3a57527a6ede1be2e18b65615a5">mcd::Object</a>
</li>
<li>onCompare()
: <a class="el" href="d5/de7/a01048.php#a279d0472004ed9618dde58fcfd6bb508">mcd::Tree&lt; T &gt;</a>
</li>
<li>onDelete()
: <a class="el" href="d5/de7/a01048.php#ad9cda4b45c11828381cde08fa48ae94d">mcd::Tree&lt; T &gt;</a>
</li>
<li>operator bool()
: <a class="el" href="df/d0c/a00788.php#ac482f8c9f482ce76ed197faf07d24617">mcd::Big</a>
</li>
<li>operator double()
: <a class="el" href="dd/d38/a00928.php#a285e38748cb55302c43feab8fa4a29f5">mcd::Fraction</a>
</li>
<li>operator std::string()
: <a class="el" href="df/d0c/a00788.php#a638fbd4ccaffb7b432c7c78d2f510134">mcd::Big</a>
</li>
<li>operator T()
: <a class="el" href="df/d0c/a00788.php#a42a1a05e756cde973a62bede71473069">mcd::Big</a>
</li>
<li>operator!=()
: <a class="el" href="dd/d38/a00928.php#a728b8777d909549030d50032783761dc">mcd::Fraction</a>
</li>
<li>operator%()
: <a class="el" href="dd/d38/a00928.php#a619d937a957bc1f2516066ebb3501951">mcd::Fraction</a>
</li>
<li>operator%=()
: <a class="el" href="df/d0c/a00788.php#a078be418a37b709c8124ec69cfd66836">mcd::Big</a>
, <a class="el" href="dd/d38/a00928.php#a7b6753a02a790ffbb75c36920237167c">mcd::Fraction</a>
</li>
<li>operator()()
: <a class="el" href="de/d49/a00952.php#a105197d7158b9387782b28583c6c07ba">mcd::Map</a>
, <a class="el" href="d3/de5/a00956.php#a895533c348847ed307cafe3d85c8ebf9">mcd::Matrix&lt; C &gt;</a>
, <a class="el" href="d4/dc5/a01024.php#a717048eaee5dc829e132237026beaecc">mcd::RNG&lt; T, U &gt;</a>
</li>
<li>operator*()
: <a class="el" href="dd/d38/a00928.php#aece90dc9d246328147f02da505af1050">mcd::Fraction</a>
, <a class="el" href="d3/de5/a00956.php#a61b1b866f822f492dd94f0178de09f0e">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator*=()
: <a class="el" href="df/d0c/a00788.php#aee0004ba93bf9b5e84bc6069b2e70330">mcd::Big</a>
, <a class="el" href="dd/d38/a00928.php#aae423fa04b3025e509901155241b5402">mcd::Fraction</a>
, <a class="el" href="d3/de5/a00956.php#a035e71a534c66ed739cdafccb5abc09b">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator+()
: <a class="el" href="dd/d38/a00928.php#a0897ad5e88848032ff6570bd83ddbef7">mcd::Fraction</a>
, <a class="el" href="d3/de5/a00956.php#ac2adb934f2c26b12d6b5f5981c0e4d7a">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator++()
: <a class="el" href="dd/d38/a00928.php#af066abb5b8fe5db0e0c4ce7d125f0c5e">mcd::Fraction</a>
</li>
<li>operator+=()
: <a class="el" href="df/d0c/a00788.php#a71c734bca411504941a7a5a611b8e285">mcd::Big</a>
, <a class="el" href="dd/d38/a00928.php#a76f6e7a0b34f33d8d53bc993b7c0ac89">mcd::Fraction</a>
, <a class="el" href="d3/de5/a00956.php#ab65365129992bf5a53b62e3bd3955135">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator-()
: <a class="el" href="dd/d38/a00928.php#a7a16f5b2182b2752cfbef72018e7636e">mcd::Fraction</a>
, <a class="el" href="d3/de5/a00956.php#acff8e20e80d55f14e4ef611dc1c9b8ce">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator--()
: <a class="el" href="dd/d38/a00928.php#a34e188b2c7100e21fe387855ca963f52">mcd::Fraction</a>
</li>
<li>operator-=()
: <a class="el" href="df/d0c/a00788.php#aa11404d0af642fa7e89fc484445200d5">mcd::Big</a>
, <a class="el" href="dd/d38/a00928.php#a53b141f48ecc61069385e16cf51524dc">mcd::Fraction</a>
, <a class="el" href="d3/de5/a00956.php#a8c4a74722881f5fdb1a1135b36808f47">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator/()
: <a class="el" href="dd/d38/a00928.php#a0ffeec4d80502f0173a03d7b3aa361db">mcd::Fraction</a>
, <a class="el" href="d3/de5/a00956.php#aead70f5313e4a9a9c39321d41c2c3d10">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator/=()
: <a class="el" href="df/d0c/a00788.php#aed2dc1aa4bd20abbe2c48aefe115b57d">mcd::Big</a>
, <a class="el" href="dd/d38/a00928.php#a4942772dfaef8d5158163f7fcca98b57">mcd::Fraction</a>
, <a class="el" href="d3/de5/a00956.php#a8f1be652fdf748cc826d30cbb96745f0">mcd::Matrix&lt; C &gt;</a>
</li>
<li>operator&lt;()
: <a class="el" href="dd/d38/a00928.php#a4c0588f44c0f24a7cb2fe0d1a4c05ad5">mcd::Fraction</a>
</li>
<li>operator&lt;=()
: <a class="el" href="dd/d38/a00928.php#ac1e8c0cf1fdef5dd32409c5d0b660fb1">mcd::Fraction</a>
</li>
<li>operator=()
: <a class="el" href="df/d0c/a00788.php#adc8b04536591da50d9c9342a5eccaf42">mcd::Big</a>
, <a class="el" href="d5/d16/a01060.php#a6ebbd086a808f7fb8bd49bda00b8df12">mcd::Point</a>
, <a class="el" href="df/d89/a01032.php#aede63b72f054d20e35d22153af8313c8">mcd::Threadable&lt; C &gt;</a>
</li>
<li>operator==()
: <a class="el" href="dd/d38/a00928.php#a986f1f323f69858991a54320af44b6a5">mcd::Fraction</a>
</li>
<li>operator&gt;()
: <a class="el" href="dd/d38/a00928.php#a379d98c2c6ae1962fc2089b599fc48df">mcd::Fraction</a>
</li>
<li>operator&gt;=()
: <a class="el" href="dd/d38/a00928.php#ac4dcbd6c3961244afb7bbcb90c5b01da">mcd::Fraction</a>
</li>
<li>operator[]()
: <a class="el" href="d8/d20/a00768.php#ae401cb47faea064ac04133ea929c0f94">mcd::Arguments</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
