<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: Class Members - Related Functions</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.1.1</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Fri Nov 13 2020 12:37:29 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('functions_rela.php',''); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_c"></a>- c -</h3><ul>
<li>Cls
: <a class="el" href="da/d19/a01217.php#a37c42c3a0b8af325e746f536a6a51305">mcd::Console::Color</a>
</li>
</ul>


<h3><a id="index_g"></a>- g -</h3><ul>
<li>GaussJordan
: <a class="el" href="db/dec/a01337.php#a9b0f04cced69a887b46bddde8e3f3c0a">mcd::Matrix&lt; C &gt;</a>
</li>
</ul>


<h3><a id="index_m"></a>- m -</h3><ul>
<li>mod
: <a class="el" href="d9/d17/a01129.php#a2ed0b910c5ed7ec9875836082c63baa8">mcd::Big</a>
</li>
</ul>


<h3><a id="index_n"></a>- n -</h3><ul>
<li>nroot
: <a class="el" href="d9/d17/a01129.php#a21b8fc95f6ce377054c153aa5f1e871c">mcd::Big</a>
</li>
</ul>


<h3><a id="index_o"></a>- o -</h3><ul>
<li>operator!
: <a class="el" href="d9/d17/a01129.php#aaeca4e372966fe2b3b857d52880ca210">mcd::Big</a>
</li>
<li>operator!=
: <a class="el" href="d9/d17/a01129.php#ad9c55799e64051a79feb72642bacc2bd">mcd::Big</a>
, <a class="el" href="dc/dd5/a01293.php#a189801f68196f20f1c7c7f7580a6ec52">mcd::Fraction</a>
, <a class="el" href="d9/dae/a01453.php#a56d3ecc223a30b7947a8a5e3776083e3">mcd::Point</a>
</li>
<li>operator%
: <a class="el" href="d9/d17/a01129.php#a8082f5075921a15bedfa304ddc5f0bfa">mcd::Big</a>
</li>
<li>operator&amp;
: <a class="el" href="da/df7/a01457.php#a1552117c5c07498294173619e4ca5836">mcd::vector&lt; C &gt;</a>
</li>
<li>operator*
: <a class="el" href="d9/d17/a01129.php#aef65b2815526a32f3da7094648cb5ef7">mcd::Big</a>
</li>
<li>operator+
: <a class="el" href="d9/d17/a01129.php#ad475b8459ee2ea450eecbc0b2a49f221">mcd::Big</a>
, <a class="el" href="de/df6/a01141.php#a27089d4be7e4f07bf6c1943c59b3bf47">mcd::natural::Cell</a>
, <a class="el" href="de/d04/a01209.php#abed91ce31a251621eff0ec618c9d95e2">mcd::natural::Chromosome</a>
, <a class="el" href="da/df7/a01457.php#a8f261f2319c479f4e714b269bbbbdfa9">mcd::vector&lt; C &gt;</a>
</li>
<li>operator++
: <a class="el" href="d9/d17/a01129.php#a561b68f0811a35c5af315d6b52f8c858">mcd::Big</a>
</li>
<li>operator-
: <a class="el" href="d9/d17/a01129.php#a8d411571b65ece2daacc12f0293850e8">mcd::Big</a>
, <a class="el" href="da/df7/a01457.php#aee068ab7887e20606e98299c3671c34a">mcd::vector&lt; C &gt;</a>
</li>
<li>operator--
: <a class="el" href="d9/d17/a01129.php#a5226a81d618e406ae59842011efff7f0">mcd::Big</a>
</li>
<li>operator/
: <a class="el" href="d9/d17/a01129.php#aa0213bc63f03a5db6ec4d081b9320a96">mcd::Big</a>
</li>
<li>operator&lt;
: <a class="el" href="d9/d17/a01129.php#a9c625348272715ed4dad2c1420fb5bd0">mcd::Big</a>
, <a class="el" href="de/d85/a01273.php#a900297f0a1d5018e0c30d2e8fa6a99c6">mcd::Date</a>
, <a class="el" href="d2/d1d/a01277.php#aaec41bb6ed721384b089c34fd87e0085">mcd::DateTime</a>
, <a class="el" href="d2/d1f/a01361.php#accb5b160fd3f52084b8b83c8dddaae93">mcd::PathfindingNode</a>
, <a class="el" href="d1/d3b/a01429.php#a2176bf97f6b18969bb71b7c3f2e56234">mcd::Time</a>
</li>
<li>operator&lt;&lt;
: <a class="el" href="d9/d17/a01129.php#a6d1ae6342e0dd6f689535b21fd46a023">mcd::Big</a>
, <a class="el" href="d6/d6e/a01137.php#acd2465f87f784cedc37718af0bf50d17">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="da/d19/a01217.php#a84513fec989f2f817d2b1c5e6989450e">mcd::Console::Color</a>
, <a class="el" href="d3/d07/a01241.php#a5a120231654267de5f32512a83c99521">mcd::Console::SetPrecision</a>
, <a class="el" href="dc/dab/a01237.php#a8b27881bbb3b1a50ddf821d8ce62e4d6">mcd::Console::ThreadCout</a>
, <a class="el" href="d1/d31/a01245.php#af23c547bfa2b35d582a6922d425d02f5">mcd::ConsoleTable</a>
, <a class="el" href="d3/d7b/a01249.php#a763a20bdd6cf99e565f2516d1c4bb161">mcd::Contraption</a>
, <a class="el" href="de/d85/a01273.php#a1862604492a841a6b98e1a3061d95b96">mcd::Date</a>
, <a class="el" href="d2/d1d/a01277.php#af57470a685eee50ced503a3ab380e9ba">mcd::DateTime</a>
, <a class="el" href="dc/dd5/a01293.php#a9313ed58249557fab9c0b6ab5e5f977f">mcd::Fraction</a>
, <a class="el" href="de/d90/a01313.php#a6b1400a312593beec3776b4f998a7419">mcd::Json</a>
, <a class="el" href="db/dec/a01337.php#a9a3710d279e209fbff51b625690ef630">mcd::Matrix&lt; C &gt;</a>
, <a class="el" href="de/df6/a01141.php#a3b03e2ae2aae5a47673ad2bdb55375ce">mcd::natural::Cell</a>
, <a class="el" href="de/d04/a01209.php#a76b305eaa6cc1a513e64de3459e3b550">mcd::natural::Chromosome</a>
, <a class="el" href="dc/d8c/a01297.php#aadb0dff1f1d91e1b0b2c7a382de48eb8">mcd::natural::Gene</a>
, <a class="el" href="d9/dae/a01453.php#a55681886ec7c5d7c0210fa0611bc84ea">mcd::Point</a>
, <a class="el" href="d1/d3b/a01429.php#aa153c7e397eda8644c840a97f6036c5b">mcd::Time</a>
, <a class="el" href="da/df7/a01457.php#a809579a337d6d0419a28bff79eb2597b">mcd::vector&lt; C &gt;</a>
</li>
<li>operator&lt;=
: <a class="el" href="d9/d17/a01129.php#a74e55e1a85a44b255d0f8e1158e02658">mcd::Big</a>
, <a class="el" href="dc/dd5/a01293.php#addda863096fc0bcbe756cc01fd80521f">mcd::Fraction</a>
</li>
<li>operator==
: <a class="el" href="d9/d17/a01129.php#a5eed09966f2142f9d979e7be4643c06a">mcd::Big</a>
, <a class="el" href="de/d85/a01273.php#a9cfaaa2dd5867578b32c02fd8bc16339">mcd::Date</a>
, <a class="el" href="d2/d1d/a01277.php#a15ab62ed982a1d04015c4e94597e225e">mcd::DateTime</a>
, <a class="el" href="de/d90/a01313.php#a03e32be5b88c0a40797b0ed39c9bdcba">mcd::Json</a>
, <a class="el" href="db/dec/a01337.php#a9114b65a5cd73102b02f5ede2c290177">mcd::Matrix&lt; C &gt;</a>
, <a class="el" href="de/df6/a01141.php#a368f58787c40f58441c7eea56a420a82">mcd::natural::Cell</a>
, <a class="el" href="de/d04/a01209.php#a1803f44b93c73c5cf0f3d8204eac3c9e">mcd::natural::Chromosome</a>
, <a class="el" href="dc/d8c/a01297.php#abfba7cb01e60aeda7477a3b504d4ed57">mcd::natural::Gene</a>
, <a class="el" href="d2/d1f/a01361.php#af8e324237235cd148492d82eadf94e0c">mcd::PathfindingNode</a>
, <a class="el" href="d9/dae/a01453.php#a177528c8a1eee37fcda25a89084b8ed6">mcd::Point</a>
, <a class="el" href="d1/d3b/a01429.php#a7f236759032a4630990af05bd6c8530b">mcd::Time</a>
</li>
<li>operator&gt;
: <a class="el" href="d9/d17/a01129.php#ac75c3d550acaece7444e1d3373e0ced6">mcd::Big</a>
, <a class="el" href="dc/dd5/a01293.php#a2efd99f639b6f6ca4b13c7733a3f2a55">mcd::Fraction</a>
</li>
<li>operator&gt;=
: <a class="el" href="d9/d17/a01129.php#adf83d734f0c4b777bb675bf327996987">mcd::Big</a>
, <a class="el" href="dc/dd5/a01293.php#a63aeeec7f8e00c70aa489ba2d3c0ef4c">mcd::Fraction</a>
</li>
<li>operator&gt;&gt;
: <a class="el" href="d9/d17/a01129.php#a91ce80d3959e1d2a891e58c940c8631b">mcd::Big</a>
, <a class="el" href="de/df6/a01141.php#a4e8b664ca85bee0d335569bc95a513e8">mcd::natural::Cell</a>
, <a class="el" href="de/d04/a01209.php#a9a437c818c1b78544066972a94410efc">mcd::natural::Chromosome</a>
, <a class="el" href="dc/d8c/a01297.php#a2614d14b993a651c047de4bf36f7aef2">mcd::natural::Gene</a>
, <a class="el" href="da/df7/a01457.php#a3b06b20625099b2c7cdd5ac2c7290558">mcd::vector&lt; C &gt;</a>
</li>
<li>operator^
: <a class="el" href="da/df7/a01457.php#af87e40dfdbf6844cacdd3fc5873018b0">mcd::vector&lt; C &gt;</a>
</li>
<li>operator|
: <a class="el" href="da/df7/a01457.php#a1db1d552fd452960ac62c3d796c0649a">mcd::vector&lt; C &gt;</a>
</li>
</ul>


<h3><a id="index_p"></a>- p -</h3><ul>
<li>pgcd
: <a class="el" href="d9/d17/a01129.php#aa6a7af66a5c239b2b46979e998c43679">mcd::Big</a>
</li>
<li>pow
: <a class="el" href="d9/d17/a01129.php#a9d40406ec9457a1565a2b0c60585ae9b">mcd::Big</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
