<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: Class Members - Functions</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.2.2</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Nov 15 2020 20:32:44 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('functions_func_t.php',''); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_t"></a>- t -</h3><ul>
<li>t_queue()
: <a class="el" href="d6/d40/a01114.php#a6113ab263c40412573cb17961892e4eb">mcd::t_queue&lt; T, Container &gt;</a>
</li>
<li>t_stack()
: <a class="el" href="da/d4e/a01106.php#aa4c2b6ebb0b904372919f1c9d0e8a7fa">mcd::t_stack&lt; T, Container &gt;</a>
</li>
<li>testPath()
: <a class="el" href="d4/dd1/a01334.php#ada7c31df9004ebb9b494f09a6a4a224a">mcd::Map</a>
</li>
<li>Threadable()
: <a class="el" href="dc/de6/a01426.php#a04bdb4a894312f6671680c2f103b8a63">mcd::Threadable&lt; C &gt;</a>
</li>
<li>ThreadCout()
: <a class="el" href="d8/ddf/a01238.php#a0ab22efba01da7bd7a61446936294cca">mcd::console::ThreadCout</a>
</li>
<li>ThreadEndlCout()
: <a class="el" href="d6/d1e/a01234.php#a428f6ae4ecd881bbbb2db0c317f4d210">mcd::console::ThreadEndlCout</a>
</li>
<li>Time()
: <a class="el" href="d8/dd0/a01430.php#ac802213e9ca41cc731f14619534e0249">mcd::Time</a>
</li>
<li>Timer()
: <a class="el" href="d1/de7/a01434.php#ae2847ca8c851863418d57e80e972095a">mcd::Timer</a>
</li>
<li>top()
: <a class="el" href="da/df6/a01454.php#afd57961d22ce89d783303c0fbbdc4f83">mcd::Point</a>
, <a class="el" href="da/d4e/a01106.php#a527628a84ec81233f4e475f986e9d10d">mcd::t_stack&lt; T, Container &gt;</a>
</li>
<li>tos()
: <a class="el" href="d2/d4d/a01338.php#adbfa246182cc089300f95cf1610a99ef">mcd::Matrix&lt; C &gt;</a>
</li>
<li>transform()
: <a class="el" href="d3/d53/a01262.php#a74c404cd90d7d9331818f2eea6f1f7d2">mcd::SHA2</a>
</li>
<li>transposed()
: <a class="el" href="d2/d4d/a01338.php#a942e3d418da2bacad3193d82411e2cfc">mcd::Matrix&lt; C &gt;</a>
</li>
<li>Tree()
: <a class="el" href="d0/de2/a01442.php#a93774d1792effab8a46379c6781729f0">mcd::Tree&lt; T &gt;</a>
</li>
<li>turn()
: <a class="el" href="da/d73/a01090.php#a74240288a6b9d0ae3ec2407805bc8c62">mcd::entites::Animal</a>
</li>
<li>turnLeft()
: <a class="el" href="d4/d22/a01250.php#af62a631783e20d0805d813d9fbe9a093">mcd::entites::Contraption</a>
</li>
<li>turnRight()
: <a class="el" href="d4/d22/a01250.php#adc8d2f50785c37a414b5906999c8a3e0">mcd::entites::Contraption</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
