<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Class Members - Functions</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Fri Sep 6 2019 18:14:51 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_func_o.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_o"></a>- o -</h3><ul>
<li>Object()
: <a class="el" href="d1/db0/a00945.php#ad332f3a57527a6ede1be2e18b65615a5">mcd::Object</a>
</li>
<li>onCompare()
: <a class="el" href="db/d23/a01025.php#a279d0472004ed9618dde58fcfd6bb508">mcd::Tree&lt; T &gt;</a>
</li>
<li>onDelete()
: <a class="el" href="db/d23/a01025.php#ad9cda4b45c11828381cde08fa48ae94d">mcd::Tree&lt; T &gt;</a>
</li>
<li>operator std::string()
: <a class="el" href="d8/dba/a00773.php#a638fbd4ccaffb7b432c7c78d2f510134">mcd::Big</a>
</li>
<li>operator%=()
: <a class="el" href="d8/dba/a00773.php#a078be418a37b709c8124ec69cfd66836">mcd::Big</a>
</li>
<li>operator()()
: <a class="el" href="d0/d5b/a00933.php#a1809056415a86a4627e0cad3bbb0b3b0">mcd::Map</a>
, <a class="el" href="df/d59/a01001.php#a717048eaee5dc829e132237026beaecc">mcd::RNG&lt; T, U &gt;</a>
</li>
<li>operator*=()
: <a class="el" href="d8/dba/a00773.php#aee0004ba93bf9b5e84bc6069b2e70330">mcd::Big</a>
</li>
<li>operator+=()
: <a class="el" href="d8/dba/a00773.php#a71c734bca411504941a7a5a611b8e285">mcd::Big</a>
</li>
<li>operator-=()
: <a class="el" href="d8/dba/a00773.php#aa11404d0af642fa7e89fc484445200d5">mcd::Big</a>
</li>
<li>operator/=()
: <a class="el" href="d8/dba/a00773.php#aed2dc1aa4bd20abbe2c48aefe115b57d">mcd::Big</a>
</li>
<li>operator=()
: <a class="el" href="d8/dba/a00773.php#adc8b04536591da50d9c9342a5eccaf42">mcd::Big</a>
, <a class="el" href="d2/d41/a01037.php#a220f83e0ebfaa9b2884530cfcac6f6df">mcd::Point</a>
</li>
<li>operator[]()
: <a class="el" href="dc/dd0/a00753.php#a3afcd48b173c2c0f17c74a99b3a6b413">mcd::Arguments</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
