<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: Class Members - Functions</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.2.2</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Nov 15 2020 20:32:44 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('functions_func.php',''); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_a"></a>- a -</h3><ul>
<li>add()
: <a class="el" href="d5/d17/a01098.php#a0d178470f50f3a3f12b2dab7aa40f004">mcd::Arguments</a>
, <a class="el" href="d0/de2/a01442.php#a20ba766efa9e94d90d156432d6f101b1">mcd::Tree&lt; T &gt;</a>
</li>
<li>addColors()
: <a class="el" href="d8/d15/a01218.php#a39d1e3b3618a86c29866bd90855bfc8f">mcd::console::Color</a>
</li>
<li>addPosition()
: <a class="el" href="d4/d22/a01250.php#a19d6e2cdd63fe936b58298d215319527">mcd::entites::Contraption</a>
</li>
<li>addProg()
: <a class="el" href="d5/d17/a01098.php#a1eabf4c8408ded2b8deca24d99fd3234">mcd::Arguments</a>
</li>
<li>addSuite()
: <a class="el" href="d1/df4/a01422.php#a071aa854651614bcd81581eb26b5cd20">mcd::tests::Test</a>
</li>
<li>addTest()
: <a class="el" href="d1/df4/a01422.php#a9b581c6619cbb7660c0c0d509a4a979d">mcd::tests::Test</a>
</li>
<li>addThrow()
: <a class="el" href="d1/df4/a01422.php#abfd0b19e1a6b68854276138b66f0b757">mcd::tests::Test</a>
</li>
<li>Animal()
: <a class="el" href="da/d73/a01090.php#a36ed3fa0cc86391119065cdc1fd10c10">mcd::entites::Animal</a>
</li>
<li>Ant()
: <a class="el" href="d6/dea/a01094.php#aa5ae8e8d1c69d88652d032bab0ee6590">mcd::entites::Ant</a>
</li>
<li>anyObstacle()
: <a class="el" href="da/d73/a01090.php#a368f50a5960e814706f04ab441318911">mcd::entites::Animal</a>
</li>
<li>applyForEach()
: <a class="el" href="d0/de2/a01442.php#aa1c0e2b0a15c31c48ed5cade92c4ae3d">mcd::Tree&lt; T &gt;</a>
</li>
<li>Arguments()
: <a class="el" href="d5/d17/a01098.php#ac6c3e24abf9d442d2a01b601ad3a0968">mcd::Arguments</a>
</li>
<li>Arrived()
: <a class="el" href="db/d74/a01378.php#a9fcff7a44db764decbb680479144b97b">mcd::PathfindingException</a>
</li>
<li>asc()
: <a class="el" href="d0/de2/a01442.php#aaf42d9cae430064e1b52b8cd3e57ee42">mcd::Tree&lt; T &gt;</a>
</li>
<li>Assert()
: <a class="el" href="db/d32/a01122.php#ad4dd96d96703a8dd5efcd62ee8d3a78d">mcd::Assert</a>
</li>
<li>AssertionException()
: <a class="el" href="db/d1e/a01126.php#ad93f95c8923581b9ce4e3d28d63a243e">mcd::AssertionException</a>
</li>
<li>attack()
: <a class="el" href="da/d73/a01090.php#a9b36d22d0275ba7c2aaedb031bf7d630">mcd::entites::Animal</a>
, <a class="el" href="dc/de0/a01302.php#ab05e964095ba05b2f3030b506146149a">mcd::entites::Hostile</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
