<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Class Members - Functions</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Thu Mar 26 2020 23:11:06 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('functions_func_g.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_g"></a>- g -</h3><ul>
<li>Gene()
: <a class="el" href="df/dbc/a01004.php#afac2f9fde459a7a311c2a19078f0cc95">mcd::natural::Gene</a>
</li>
<li>get()
: <a class="el" href="d9/dbb/a00852.php#ac47df1759fc5e2a1c2b4113401fc3ee9">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="d2/d4c/a00984.php#a8573428b5d4557473120c24e1e52d543">mcd::Date</a>
, <a class="el" href="d6/d48/a00988.php#a7b25df777f0b2b3ac2396538eb3ca028">mcd::DateTime</a>
, <a class="el" href="df/d89/a01032.php#a04a6f229a4697e8945922ed23b52f7d6">mcd::Map</a>
, <a class="el" href="d8/d1c/a00824.php#a148295001e6effa1aa1217af766e021f">mcd::queue&lt; T, Container &gt;</a>
, <a class="el" href="d7/d60/a00816.php#ac779733da952e8cfda80b14655a07172">mcd::stack&lt; T, Container &gt;</a>
, <a class="el" href="d0/dc8/a01124.php#af9360f3323012f2572ffb3f8924fca62">mcd::Time</a>
</li>
<li>getA()
: <a class="el" href="dd/d11/a00960.php#a580eafa58a93d9ab4264c4cbac2f4167">mcd::Contraption</a>
</li>
<li>getAge()
: <a class="el" href="d3/daa/a00996.php#adc41605613a8d9420f9e9b7d5d1693c9">mcd::Entity</a>
</li>
<li>getAttributes()
: <a class="el" href="dd/d11/a00960.php#aa36a1788770d7667d8a2848ff1e3f0c6">mcd::Contraption</a>
</li>
<li>getCaste()
: <a class="el" href="d7/dc8/a00808.php#aefe83b0ef881a901834a3dc32f60fa10">mcd::Ant</a>
</li>
<li>getDamages()
: <a class="el" href="d3/daa/a00996.php#a7bf4a1bb07d7a688bd2ea4c446aa6070">mcd::Entity</a>
</li>
<li>getElapsed()
: <a class="el" href="dd/d38/a00928.php#a47ce94671d48c1f42862771174c86810">mcd::Clock</a>
</li>
<li>getErrorCode()
: <a class="el" href="d6/d6a/a01072.php#a922e8cbd5025f4f17e45889055df165c">mcd::PathfindingException</a>
</li>
<li>getExperience()
: <a class="el" href="da/db7/a01088.php#af4b6c4845dcc12c9feed1910e7de9334">mcd::PlayerAbstraction&lt; PlayerParent &gt;</a>
</li>
<li>getExperienceMax()
: <a class="el" href="da/db7/a01088.php#a3d9f0332994725fceb7f785fd83e1802">mcd::PlayerAbstraction&lt; PlayerParent &gt;</a>
</li>
<li>getFood()
: <a class="el" href="d1/dd1/a00804.php#aa200ce00d14dc675aed8467ca0fa8760">mcd::Animal</a>
</li>
<li>getFoodMax()
: <a class="el" href="d1/dd1/a00804.php#abc229075f9f07b49f7baa041ec4c6efc">mcd::Animal</a>
</li>
<li>getH()
: <a class="el" href="dd/d11/a00960.php#aec81012bc23935e626500734007d5fb5">mcd::Contraption</a>
, <a class="el" href="df/d89/a01032.php#a846e20ddb36e52abe1975bfd7f47bb62">mcd::Map</a>
</li>
<li>getId()
: <a class="el" href="d4/d45/a01012.php#abc0c02ec636a63cf2086e6e98f194b63">mcd::Identifier</a>
</li>
<li>getIdentity()
: <a class="el" href="d8/d79/a01036.php#aac5e5ab03fe97f3deb3f56b34b638638">mcd::Matrix&lt; C &gt;</a>
</li>
<li>getLeftCount()
: <a class="el" href="d1/dae/a01136.php#a634efe609117c9533707b9f30bd0c488">mcd::Tree&lt; T &gt;</a>
</li>
<li>getLevel()
: <a class="el" href="dd/d11/a00960.php#a2f6cf40462b5dba5f7743c83cc2389f1">mcd::Contraption</a>
</li>
<li>getLife()
: <a class="el" href="d3/daa/a00996.php#a90c6ecc6d1eb5f75555d350061e45851">mcd::Entity</a>
</li>
<li>getLifeMax()
: <a class="el" href="d3/daa/a00996.php#adbc4c4d4900f96af54a931cedf1d4c7b">mcd::Entity</a>
</li>
<li>getMail()
: <a class="el" href="da/db7/a01088.php#ada35a68939571761734d82bf83e6c634">mcd::PlayerAbstraction&lt; PlayerParent &gt;</a>
</li>
<li>getMap()
: <a class="el" href="dd/d11/a00960.php#a393c4ec6fd375809fbcf1cfeab44ed25">mcd::Contraption</a>
</li>
<li>getPassword()
: <a class="el" href="d4/d45/a01012.php#a0dcb443f68200102b855f77878754af9">mcd::Identifier</a>
</li>
<li>getPath()
: <a class="el" href="d9/db3/a01064.php#ac59e95d415c520941c5bac355537df7f">mcd::Pathfinding</a>
</li>
<li>getPosition()
: <a class="el" href="dd/d11/a00960.php#ac95da2f760e8ba07a54ac849c5a3307f">mcd::Contraption</a>
</li>
<li>getPrivate()
: <a class="el" href="db/d20/a00980.php#ac38c1c5dff307a8dd9ce9c00b8df8b87">mcd::RSA</a>
</li>
<li>getProblem()
: <a class="el" href="df/d89/a01032.php#ab798c2d9fb3e6b25abaef7926b8a0abb">mcd::Map</a>
</li>
<li>getPublic()
: <a class="el" href="db/d20/a00980.php#a7fdf2f24700983208b6bfab8df8ef911">mcd::RSA</a>
</li>
<li>getReborn()
: <a class="el" href="d3/daa/a00996.php#ad15b39d3c89a220d3a612bf7bcc8e3a9">mcd::Entity</a>
</li>
<li>getRegen()
: <a class="el" href="d3/daa/a00996.php#a89b212594457755f67a4cb98f8c1218b">mcd::Entity</a>
</li>
<li>getRelativeZ()
: <a class="el" href="d1/dd1/a00804.php#a2ce9aecbe210f893028b8e9ad44a2b7b">mcd::Animal</a>
, <a class="el" href="dd/d11/a00960.php#a20dee618b85a3f841921a534bd5dfd37">mcd::Contraption</a>
</li>
<li>getResistance()
: <a class="el" href="d3/daa/a00996.php#af381c01c6bea9908472377489ad6b4c0">mcd::Entity</a>
</li>
<li>getRightCount()
: <a class="el" href="d1/dae/a01136.php#ada7f6fc4dba1856a8aae67983ba5544b">mcd::Tree&lt; T &gt;</a>
</li>
<li>getSize()
: <a class="el" href="df/d89/a01032.php#adc4f78a75dbf140919d939985c209cbb">mcd::Map</a>
</li>
<li>getSpecialAttack()
: <a class="el" href="d1/dd1/a00804.php#a5a18d838394f7eca74b2c169a6ba945b">mcd::Animal</a>
</li>
<li>getSpecies()
: <a class="el" href="d1/dd1/a00804.php#ade580e646ec547804f21a73ee944552c">mcd::Animal</a>
</li>
<li>getSpeed()
: <a class="el" href="d1/dd1/a00804.php#acaa526abac4337a8be4836b0c99a9f9b">mcd::Animal</a>
</li>
<li>getStart()
: <a class="el" href="dd/d38/a00928.php#a276d9d978a8670e8354cac2b589c60ce">mcd::Clock</a>
, <a class="el" href="d9/d12/a01128.php#a5ce92c00f251ba4ee94fc8224a9ccbc7">mcd::Timer</a>
</li>
<li>getStone()
: <a class="el" href="d7/dc8/a00808.php#aba7dfff3a965c52127afa152a66a32fa">mcd::Ant</a>
</li>
<li>getStoneMax()
: <a class="el" href="d7/dc8/a00808.php#a3c53c4e13e45a9432c2aba52c98edce3">mcd::Ant</a>
</li>
<li>getStrength()
: <a class="el" href="dd/dac/a01008.php#a6301018ead1f9778a74dc6d4b8e1daff">mcd::Hostile</a>
</li>
<li>getTarget()
: <a class="el" href="dd/dac/a01008.php#a13299f1f64259b76ddf0a43dd97a4864">mcd::Hostile</a>
</li>
<li>getTimeActReborn()
: <a class="el" href="d3/daa/a00996.php#abca030f9d81cbba5aa08ac6c55aaf06b">mcd::Entity</a>
</li>
<li>getTimeActRegen()
: <a class="el" href="d3/daa/a00996.php#acf9d27e7d1cb3d983f407905e95bcc43">mcd::Entity</a>
</li>
<li>getTimePrecReborn()
: <a class="el" href="d3/daa/a00996.php#a88b90ea88f999bc11a2e07fdf1de1020">mcd::Entity</a>
</li>
<li>getTimePrecRegen()
: <a class="el" href="d3/daa/a00996.php#a5ad008ea31a40fad735680b4bdfb249e">mcd::Entity</a>
</li>
<li>getUsername()
: <a class="el" href="d4/d45/a01012.php#a6108c8a63af7595ff4d9a4f2ad868b1e">mcd::Identifier</a>
</li>
<li>getW()
: <a class="el" href="dd/d11/a00960.php#ad12fd1c5a207f169edc619e09a5a969f">mcd::Contraption</a>
, <a class="el" href="df/d89/a01032.php#ad4e66e9116fc7b785e4e0bbfd93dbf3d">mcd::Map</a>
</li>
<li>getX()
: <a class="el" href="dd/d11/a00960.php#a6e7d791e4289bd253a357be80f8131ee">mcd::Contraption</a>
</li>
<li>getY()
: <a class="el" href="dd/d11/a00960.php#a153124dd434c08a943f60d7b43c2ffab">mcd::Contraption</a>
</li>
<li>getZ()
: <a class="el" href="dd/d11/a00960.php#a6ac6575807535f3d9aeb251ce3cceaed">mcd::Contraption</a>
</li>
<li>goBot()
: <a class="el" href="d1/dd1/a00804.php#aec9e7e9161766fa70a0f7e0f7dbd09f1">mcd::Animal</a>
</li>
<li>goLeft()
: <a class="el" href="d1/dd1/a00804.php#aa26f06d52070e9976a972d49c11723c1">mcd::Animal</a>
</li>
<li>goRight()
: <a class="el" href="d1/dd1/a00804.php#ad3ce2b65cecda053e43eac7421224088">mcd::Animal</a>
</li>
<li>goTo()
: <a class="el" href="d9/dce/a00944.php#a191575f00626575e84455dfae871f502">mcd::ConsoleCursor</a>
</li>
<li>goTop()
: <a class="el" href="d1/dd1/a00804.php#ac70088d58528c2bb5a3bd30bf176f2ea">mcd::Animal</a>
</li>
<li>grow()
: <a class="el" href="d3/daa/a00996.php#a4cae69f657ab66bdcc7b78accbb836a9">mcd::Entity</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
