<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: Class Members - Functions</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.2.2</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Nov 15 2020 20:32:44 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('functions_func_g.php',''); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_g"></a>- g -</h3><ul>
<li>Gene()
: <a class="el" href="d4/d34/a01298.php#afac2f9fde459a7a311c2a19078f0cc95">mcd::natural::Gene</a>
</li>
<li>get()
: <a class="el" href="d0/d39/a01138.php#ac47df1759fc5e2a1c2b4113401fc3ee9">mcd::Binary&lt; T, typename std::enable_if_t&lt; std::is_arithmetic&lt; T &gt;::value, void &gt; &gt;</a>
, <a class="el" href="de/d33/a01274.php#a8573428b5d4557473120c24e1e52d543">mcd::Date</a>
, <a class="el" href="d4/d10/a01278.php#a7b25df777f0b2b3ac2396538eb3ca028">mcd::DateTime</a>
, <a class="el" href="d9/de6/a01314.php#a915790021b9c9f20ac2ea225baecf489">mcd::Json</a>
, <a class="el" href="d4/dd1/a01334.php#a04a6f229a4697e8945922ed23b52f7d6">mcd::Map</a>
, <a class="el" href="d1/d3d/a01110.php#a148295001e6effa1aa1217af766e021f">mcd::queue&lt; T, Container &gt;</a>
, <a class="el" href="d4/da7/a01102.php#ac779733da952e8cfda80b14655a07172">mcd::stack&lt; T, Container &gt;</a>
, <a class="el" href="d8/dd0/a01430.php#af9360f3323012f2572ffb3f8924fca62">mcd::Time</a>
</li>
<li>getA()
: <a class="el" href="d4/d22/a01250.php#a6c98244da0afe4b7602dcd5edd7b530f">mcd::entites::Contraption</a>
</li>
<li>getAge()
: <a class="el" href="d0/d00/a01286.php#aedba70a2669386e9fc6327fb75672776">mcd::entites::Entity</a>
</li>
<li>getAttributes()
: <a class="el" href="d4/d22/a01250.php#abb45e93f32e13f62ad461772b427b8cd">mcd::entites::Contraption</a>
</li>
<li>getCaste()
: <a class="el" href="d6/dea/a01094.php#acd3dc84820f7a0f7afc1ee3b2f38c505">mcd::entites::Ant</a>
</li>
<li>getDamages()
: <a class="el" href="d0/d00/a01286.php#a6a230aac6046298818ae3bbd03b1890f">mcd::entites::Entity</a>
</li>
<li>getElapsed()
: <a class="el" href="d5/d32/a01214.php#a47ce94671d48c1f42862771174c86810">mcd::Clock</a>
</li>
<li>getErrorCode()
: <a class="el" href="db/d74/a01378.php#a922e8cbd5025f4f17e45889055df165c">mcd::PathfindingException</a>
</li>
<li>getExperience()
: <a class="el" href="d6/d2f/a01394.php#a9e6e7cb33567b77cf06fb17b622dab93">mcd::entites::PlayerAbstraction&lt; PlayerParent &gt;</a>
</li>
<li>getExperienceMax()
: <a class="el" href="d6/d2f/a01394.php#a0dae7daec87f344c41179d80f3535bd0">mcd::entites::PlayerAbstraction&lt; PlayerParent &gt;</a>
</li>
<li>getFood()
: <a class="el" href="da/d73/a01090.php#a4190a20f09f5176937e2a59682b4a19d">mcd::entites::Animal</a>
</li>
<li>getFoodMax()
: <a class="el" href="da/d73/a01090.php#ad60b1da4704fce7dbdbdbb0c46425663">mcd::entites::Animal</a>
</li>
<li>getH()
: <a class="el" href="d4/d22/a01250.php#afc770f2e74e14cf3725700b93d785db9">mcd::entites::Contraption</a>
, <a class="el" href="d4/dd1/a01334.php#a846e20ddb36e52abe1975bfd7f47bb62">mcd::Map</a>
</li>
<li>getId()
: <a class="el" href="d7/d8c/a01306.php#abc0c02ec636a63cf2086e6e98f194b63">mcd::Identifier</a>
</li>
<li>getIdentity()
: <a class="el" href="d2/d4d/a01338.php#aac5e5ab03fe97f3deb3f56b34b638638">mcd::Matrix&lt; C &gt;</a>
</li>
<li>getLeftCount()
: <a class="el" href="d0/de2/a01442.php#a634efe609117c9533707b9f30bd0c488">mcd::Tree&lt; T &gt;</a>
</li>
<li>getLevel()
: <a class="el" href="d4/d22/a01250.php#a0c6389dbf2aca432ff7446686553002c">mcd::entites::Contraption</a>
</li>
<li>getLife()
: <a class="el" href="d0/d00/a01286.php#a551318af54ec2c3b8e373f03820341f1">mcd::entites::Entity</a>
</li>
<li>getLifeMax()
: <a class="el" href="d0/d00/a01286.php#ab41291fd22c20b3c7e68981658e7ff78">mcd::entites::Entity</a>
</li>
<li>getMail()
: <a class="el" href="d6/d2f/a01394.php#ac73e50383e85f5543aa8f1c204c06682">mcd::entites::PlayerAbstraction&lt; PlayerParent &gt;</a>
</li>
<li>getMap()
: <a class="el" href="d4/d22/a01250.php#af18b7804d0a5c1ae3456a2469d4e3ebb">mcd::entites::Contraption</a>
</li>
<li>getPassword()
: <a class="el" href="d7/d8c/a01306.php#a0dcb443f68200102b855f77878754af9">mcd::Identifier</a>
</li>
<li>getPath()
: <a class="el" href="d8/dbe/a01370.php#ac59e95d415c520941c5bac355537df7f">mcd::Pathfinding</a>
</li>
<li>getPosition()
: <a class="el" href="d4/d22/a01250.php#a2daee570979e9136e02f1cf4e63d154f">mcd::entites::Contraption</a>
</li>
<li>getPrivate()
: <a class="el" href="da/d00/a01270.php#ac38c1c5dff307a8dd9ce9c00b8df8b87">mcd::RSA</a>
</li>
<li>getProblem()
: <a class="el" href="d4/dd1/a01334.php#ab798c2d9fb3e6b25abaef7926b8a0abb">mcd::Map</a>
</li>
<li>getPublic()
: <a class="el" href="da/d00/a01270.php#a7fdf2f24700983208b6bfab8df8ef911">mcd::RSA</a>
</li>
<li>getReborn()
: <a class="el" href="d0/d00/a01286.php#a12bbd901d42aabc341024d768c2d7d05">mcd::entites::Entity</a>
</li>
<li>getRegen()
: <a class="el" href="d0/d00/a01286.php#a4636a18f042c12c33927629b03a3b89d">mcd::entites::Entity</a>
</li>
<li>getRelativeZ()
: <a class="el" href="da/d73/a01090.php#ae21b811a5410982f98fb3c1b400f3d3b">mcd::entites::Animal</a>
, <a class="el" href="d4/d22/a01250.php#a743ad51105fef3bef1b12c86aeefe04d">mcd::entites::Contraption</a>
</li>
<li>getResistance()
: <a class="el" href="d0/d00/a01286.php#a66797468a0b0e40672f5f06a224bb852">mcd::entites::Entity</a>
</li>
<li>getRightCount()
: <a class="el" href="d0/de2/a01442.php#ada7f6fc4dba1856a8aae67983ba5544b">mcd::Tree&lt; T &gt;</a>
</li>
<li>getSize()
: <a class="el" href="d4/dd1/a01334.php#adc4f78a75dbf140919d939985c209cbb">mcd::Map</a>
</li>
<li>getSpecialAttack()
: <a class="el" href="da/d73/a01090.php#ab6a4f73b3dcafa29c630474586a0a5f3">mcd::entites::Animal</a>
</li>
<li>getSpecies()
: <a class="el" href="da/d73/a01090.php#abbbf07f112e4b68cc8c52ee2a3574cf3">mcd::entites::Animal</a>
</li>
<li>getSpeed()
: <a class="el" href="da/d73/a01090.php#afa208e3d986b8cde1890492bca1192a2">mcd::entites::Animal</a>
</li>
<li>getStart()
: <a class="el" href="d5/d32/a01214.php#a276d9d978a8670e8354cac2b589c60ce">mcd::Clock</a>
, <a class="el" href="d1/de7/a01434.php#a5ce92c00f251ba4ee94fc8224a9ccbc7">mcd::Timer</a>
</li>
<li>getStone()
: <a class="el" href="d6/dea/a01094.php#a55739652a457b863e65efe5d1e58394a">mcd::entites::Ant</a>
</li>
<li>getStoneMax()
: <a class="el" href="d6/dea/a01094.php#a85102063fe39a47b725af66fc4e21bee">mcd::entites::Ant</a>
</li>
<li>getStrength()
: <a class="el" href="dc/de0/a01302.php#a1e36f9947b0464f4661313d18224c9f9">mcd::entites::Hostile</a>
</li>
<li>getTarget()
: <a class="el" href="dc/de0/a01302.php#a8adeff4efa60e976a3deab87b7b7ed37">mcd::entites::Hostile</a>
</li>
<li>getTimeActReborn()
: <a class="el" href="d0/d00/a01286.php#a4a7ecf8329598824ce185f12b1156b2d">mcd::entites::Entity</a>
</li>
<li>getTimeActRegen()
: <a class="el" href="d0/d00/a01286.php#a25a05843f2ed7bc3ef3fd69f95919f34">mcd::entites::Entity</a>
</li>
<li>getTimePrecReborn()
: <a class="el" href="d0/d00/a01286.php#a1a51289ad8c76425931f16cc0747367c">mcd::entites::Entity</a>
</li>
<li>getTimePrecRegen()
: <a class="el" href="d0/d00/a01286.php#a5b0e11613b619f1d7d13005eda17730c">mcd::entites::Entity</a>
</li>
<li>getUsername()
: <a class="el" href="d7/d8c/a01306.php#a6108c8a63af7595ff4d9a4f2ad868b1e">mcd::Identifier</a>
</li>
<li>getW()
: <a class="el" href="d4/d22/a01250.php#ab06c5a3b852a6783442615f691310406">mcd::entites::Contraption</a>
, <a class="el" href="d4/dd1/a01334.php#ad4e66e9116fc7b785e4e0bbfd93dbf3d">mcd::Map</a>
</li>
<li>getX()
: <a class="el" href="d4/d22/a01250.php#a637ef114b8d306e9d686c193315ceeca">mcd::entites::Contraption</a>
</li>
<li>getY()
: <a class="el" href="d4/d22/a01250.php#aaaa0e642e0c71837795a27b3f4c7494a">mcd::entites::Contraption</a>
</li>
<li>getZ()
: <a class="el" href="d4/d22/a01250.php#ae685cec408982719291a83ec1144b8fd">mcd::entites::Contraption</a>
</li>
<li>goBot()
: <a class="el" href="da/d73/a01090.php#a7d3d6d0a5400c1007e87006a2621318e">mcd::entites::Animal</a>
</li>
<li>goLeft()
: <a class="el" href="da/d73/a01090.php#a54a446a1e8ca5ae324cd4e549557af12">mcd::entites::Animal</a>
</li>
<li>goRight()
: <a class="el" href="da/d73/a01090.php#abd82e64df62eb44cb1f8f5169442a0f9">mcd::entites::Animal</a>
</li>
<li>goTo()
: <a class="el" href="d0/d58/a01230.php#a935cee462520735116a963b3df85c5d4">mcd::console::Cursor</a>
</li>
<li>goTop()
: <a class="el" href="da/d73/a01090.php#a1c657ac9863517201e908b01c4bb5b08">mcd::entites::Animal</a>
</li>
<li>grow()
: <a class="el" href="d0/d00/a01286.php#a66af9df86b4be6708e01d3030ccf9df9">mcd::entites::Entity</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
