<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Class Hierarchy</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Fri Sep 6 2019 16:09:07 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('hierarchy.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Class Hierarchy</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">
<p><a href="inherits.php">Go to the graphical class hierarchy</a></p>
This inheritance list is sorted roughly, but not completely, alphabetically:</div><div class="directory">
<div class="levels">[detail level <span onclick="javascript:toggleLevel(1);">1</span><span onclick="javascript:toggleLevel(2);">2</span><span onclick="javascript:toggleLevel(3);">3</span><span onclick="javascript:toggleLevel(4);">4</span><span onclick="javascript:toggleLevel(5);">5</span>]</div><table class="directory">
<tr id="row_0_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dc/dd0/a00753.php" target="_self">mcd::Arguments</a></td><td class="desc">A class to manage the arguments </td></tr>
<tr id="row_1_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d8/dba/a00773.php" target="_self">mcd::Big</a></td><td class="desc">A new huge arithmetic variable </td></tr>
<tr id="row_2_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d5/dac/a00841.php" target="_self">mcd::Clock</a></td><td class="desc">A clock to measure the elapsed time </td></tr>
<tr id="row_3_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_3_" class="arrow" onclick="toggleFolder('3_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/dcf/a00845.php" target="_self">mcd::Color</a></td><td class="desc">Change the text color in the console </td></tr>
<tr id="row_3_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="db/deb/a00853.php" target="_self">mcd::Cls</a></td><td class="desc">Clear the console </td></tr>
<tr id="row_3_1_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="de/d37/a00849.php" target="_self">mcd::Reinit</a></td><td class="desc"><a class="el" href="de/d37/a00849.php" title="Reinit the color in the console. ">Reinit</a> the color in the console </td></tr>
<tr id="row_4_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d3/db2/a00869.php" target="_self">mcd::ConsoleTable</a></td><td class="desc">A class to print a table in the console </td></tr>
<tr id="row_5_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_5_" class="arrow" onclick="toggleFolder('5_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d9/d22/a00873.php" target="_self">mcd::Contraption</a></td><td class="desc">A contraption </td></tr>
<tr id="row_5_0_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_5_0_" class="arrow" onclick="toggleFolder('5_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="de/dc3/a00909.php" target="_self">mcd::Entity</a></td><td class="desc">An entity </td></tr>
<tr id="row_5_0_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_5_0_0_" class="arrow" onclick="toggleFolder('5_0_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d1/d79/a00745.php" target="_self">mcd::Animal</a></td><td class="desc">An animal </td></tr>
<tr id="row_5_0_0_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d5/de8/a00749.php" target="_self">mcd::Ant</a></td><td class="desc">An ant </td></tr>
<tr id="row_5_0_1_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_5_0_1_" class="arrow" onclick="toggleFolder('5_0_1_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d1/d83/a01041.php" target="_self">mcd::Vegetal</a></td><td class="desc">A vegetal </td></tr>
<tr id="row_5_0_1_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="de/db9/a00937.php" target="_self">mcd::Mushroom</a></td><td class="desc">A mushroom </td></tr>
<tr id="row_5_0_1_1_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d3/da5/a00973.php" target="_self">mcd::Plant</a></td><td class="desc">A plant </td></tr>
<tr id="row_5_1_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_5_1_" class="arrow" onclick="toggleFolder('5_1_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d1/db0/a00945.php" target="_self">mcd::Object</a></td><td class="desc">An object </td></tr>
<tr id="row_5_1_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/d06/a01005.php" target="_self">mcd::Stone</a></td><td class="desc">A stone </td></tr>
<tr id="row_6_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/ded/a00196.php#da/d5b/a00905" target="_self">mcd::ContraptionAttr</a></td><td class="desc">A struct to define <b><a class="el" href="d9/d22/a00873.php" title="A contraption. ">Contraption</a></b> attributes </td></tr>
<tr id="row_7_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_7_" class="arrow" onclick="toggleFolder('7_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="de/d01/a00897.php" target="_self">mcd::Date</a></td><td class="desc">A class to play with dates </td></tr>
<tr id="row_7_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d0/dac/a00901.php" target="_self">mcd::DateTime</a></td><td class="desc">A class to play with dates and times </td></tr>
<tr id="row_8_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_8_" class="arrow" onclick="toggleFolder('8_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>std::exception</b></td><td class="desc">STL class </td></tr>
<tr id="row_8_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d3/dcd/a00965.php" target="_self">mcd::PathfindingException</a></td><td class="desc">All exceptions that could be thrown by the pathfinding algorithm </td></tr>
<tr id="row_9_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d6/d8b/a00821.php" target="_self">mcd::Check::has_istream_operator&lt; T &gt;</a></td><td class="desc">A template class to test if T has an istream operator </td></tr>
<tr id="row_10_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="de/d9d/a00813.php" target="_self">mcd::Check::has_ostream_operator&lt; T &gt;</a></td><td class="desc">A template class to test if T has an ostream operator </td></tr>
<tr id="row_11_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dd/d7e/a00809.php" target="_self">mcd::Check::has_size_method&lt; T &gt;</a></td><td class="desc">Verify if an object has a size method </td></tr>
<tr id="row_12_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_12_" class="arrow" onclick="toggleFolder('12_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d9/dfb/a00913.php" target="_self">mcd::Hostile</a></td><td class="desc">A class to derivate from when the thing can attack </td></tr>
<tr id="row_12_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d1/d79/a00745.php" target="_self">mcd::Animal</a></td><td class="desc">An animal </td></tr>
<tr id="row_13_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_13_" class="arrow" onclick="toggleFolder('13_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d4/ddc/a00917.php" target="_self">mcd::Identifier</a></td><td class="desc">A class to store some identify datas </td></tr>
<tr id="row_13_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d5/d6c/a00977.php" target="_self">mcd::Player&lt; PlayerParent &gt;</a></td><td class="desc">A player that can be a child from any class </td></tr>
<tr id="row_14_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dd/d7a/a00921.php" target="_self">mcd::IOConfig</a></td><td class="desc">A class to configure inputs and outputs </td></tr>
<tr id="row_15_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_15_" class="arrow" onclick="toggleFolder('15_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>std::ios_base</b></td><td class="desc">STL class </td></tr>
<tr id="row_15_0_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_15_0_" class="arrow" onclick="toggleFolder('15_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>std::basic_ios&lt; Char &gt;</b></td><td class="desc">STL class </td></tr>
<tr id="row_15_0_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_15_0_0_" class="arrow" onclick="toggleFolder('15_0_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>std::basic_ostream&lt; Char &gt;</b></td><td class="desc">STL class </td></tr>
<tr id="row_15_0_0_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span id="arr_15_0_0_0_" class="arrow" onclick="toggleFolder('15_0_0_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>std::ostream</b></td><td class="desc">STL class </td></tr>
<tr id="row_15_0_0_0_0_"><td class="entry"><span style="width:80px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dd/d7b/a00865.php" target="_self">mcd::ThreadCout</a></td><td class="desc">A class to use std::cout thread safe </td></tr>
<tr id="row_16_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d2/d02/a00777.php" target="_self">mcd::Check::is_array&lt; T &gt;</a></td><td class="desc">A template class to test if T is an array, a vector or a map </td></tr>
<tr id="row_17_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/dff/a00805.php" target="_self">mcd::Check::is_duration&lt; T &gt;</a></td><td class="desc">A template class to test if T is a chrono::duration </td></tr>
<tr id="row_18_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="da/deb/a00985.php" target="_self">mcd::Check::is_minded_ptr&lt; T &gt;</a></td><td class="desc">A template class to test if T is a std::shared_ptr, a std::unique_ptr or a std::weak_ptr </td></tr>
<tr id="row_19_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dc/d6e/a00833.php" target="_self">mcd::Check::is_object&lt; T &gt;</a></td><td class="desc">A template class to test if T is an unknown object </td></tr>
<tr id="row_20_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d3/d00/a00785.php" target="_self">mcd::Check::is_pair&lt; T &gt;</a></td><td class="desc">A template class to test if T is a std::pair </td></tr>
<tr id="row_21_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d1/dea/a00829.php" target="_self">mcd::Check::is_printable&lt; T &gt;</a></td><td class="desc">A template class to test if T is printable </td></tr>
<tr id="row_22_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d4/dd7/a00793.php" target="_self">mcd::Check::is_quatuor&lt; T &gt;</a></td><td class="desc">A template class to test if T is a std::pair </td></tr>
<tr id="row_23_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/d0a/a00801.php" target="_self">mcd::Check::is_smatch&lt; T &gt;</a></td><td class="desc">A template class to test if T is a string regex match </td></tr>
<tr id="row_24_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d1/de6/a00837.php" target="_self">mcd::Check::is_special_struct&lt; T &gt;</a></td><td class="desc">A template class to test if T is a special struct </td></tr>
<tr id="row_25_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="da/db8/a00797.php" target="_self">mcd::Check::is_string&lt; T &gt;</a></td><td class="desc">A template class to test if T is a std::string </td></tr>
<tr id="row_26_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d4/d95/a00989.php" target="_self">mcd::Check::is_thread_ptr&lt; T &gt;</a></td><td class="desc">A template class to test if T is a std::shared_ptr&lt;std::thread&gt;, a std::unique_ptr&lt;std::thread&gt;, a std::weak_ptr&lt;std::thread&gt; or a std::thread* </td></tr>
<tr id="row_27_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d8/d7d/a00789.php" target="_self">mcd::Check::is_trio&lt; T &gt;</a></td><td class="desc">A template class to test if T is a std::pair </td></tr>
<tr id="row_28_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d6/d86/a00781.php" target="_self">mcd::Check::is_vector&lt; T &gt;</a></td><td class="desc">A template class to test if T is a vector </td></tr>
<tr id="row_29_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d0/d5b/a00933.php" target="_self">mcd::Map</a></td><td class="desc">A class to manage a map and that implement some pathfinding algorithms </td></tr>
<tr id="row_30_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/ded/a00196.php#dc/d92/a00929" target="_self">mcd::MapMove</a></td><td class="desc">A struct to know informations about th movement of something in the map </td></tr>
<tr id="row_31_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/ded/a00196.php#d5/dfb/a01021" target="_self">mcd::Node&lt; T &gt;</a></td><td class="desc">A struct to define a node for the tree </td></tr>
<tr id="row_32_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_32_" class="arrow" onclick="toggleFolder('32_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d6/dad/a00941.php" target="_self">mcd::NotCopyable</a></td><td class="desc">A class to let some other not to be copyable </td></tr>
<tr id="row_32_0_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_32_0_" class="arrow" onclick="toggleFolder('32_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d1/de7/a00877.php" target="_self">mcd::Crypto</a></td><td class="desc">A class to be the parent for every crypt class </td></tr>
<tr id="row_32_0_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="df/d41/a00881.php" target="_self">mcd::Cesar</a></td><td class="desc">A class to use the cesar algorithm for encryption </td></tr>
<tr id="row_32_0_1_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="de/dc8/a00889.php" target="_self">mcd::MyCrypt</a></td><td class="desc">A class to use the <a class="el" href="dc/d2c/a00893.php" title="A class to use the RSA algorithm for encryption. ">RSA</a> algorithm for encryption </td></tr>
<tr id="row_32_0_2_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dc/d2c/a00893.php" target="_self">mcd::RSA</a></td><td class="desc">A class to use the <a class="el" href="dc/d2c/a00893.php" title="A class to use the RSA algorithm for encryption. ">RSA</a> algorithm for encryption </td></tr>
<tr id="row_32_0_3_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="db/d18/a00885.php" target="_self">mcd::SHA2</a></td><td class="desc">An implementation of sha256 encryption </td></tr>
<tr id="row_33_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d5/da3/a00953.php" target="_self">mcd::Path</a></td><td class="desc">A class to manage a path computed by the map </td></tr>
<tr id="row_34_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_34_" class="arrow" onclick="toggleFolder('34_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d1/df7/a00957.php" target="_self">mcd::Pathfinding</a></td><td class="desc">A class to implement some pathfinding algorithms </td></tr>
<tr id="row_34_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="da/d45/a00961.php" target="_self">mcd::PathfindingDijkstra</a></td><td class="desc">An implementation of the Dijkstra algorithm </td></tr>
<tr id="row_35_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="df/dc6/a00949.php" target="_self">mcd::PathfindingNode</a></td><td class="desc">A node for the path </td></tr>
<tr id="row_36_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/dfd/a00969.php" target="_self">mcd::PathfindingProblem</a></td><td class="desc">A class to group every pathfinding problems in one way to use it </td></tr>
<tr id="row_37_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_37_" class="arrow" onclick="toggleFolder('37_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>PlayerParent</b></td><td class="desc"></td></tr>
<tr id="row_37_0_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_37_0_" class="arrow" onclick="toggleFolder('37_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dd/d24/a00981.php" target="_self">mcd::PlayerAbstraction&lt; PlayerParent &gt;</a></td><td class="desc">A player that can be a child from any class </td></tr>
<tr id="row_37_0_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d5/d6c/a00977.php" target="_self">mcd::Player&lt; PlayerParent &gt;</a></td><td class="desc">A player that can be a child from any class </td></tr>
<tr id="row_38_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d2/d41/a01037.php" target="_self">mcd::Point</a></td><td class="desc">A struct to define a point in space </td></tr>
<tr id="row_39_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_39_" class="arrow" onclick="toggleFolder('39_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="da/d0a/a00993.php" target="_self">mcd::PureVirtual</a></td><td class="desc">A class to make some other to be abstract class </td></tr>
<tr id="row_39_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d0/d82/a00857.php" target="_self">mcd::ConsoleCursor</a></td><td class="desc">A class to play with the cursor in the console </td></tr>
<tr id="row_40_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/ded/a00196.php#d2/d57/a01033" target="_self">mcd::quatuor&lt; T, U, V, W &gt;</a></td><td class="desc">A container for four values </td></tr>
<tr id="row_41_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_41_" class="arrow" onclick="toggleFolder('41_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>std::queue&lt; T &gt;</b></td><td class="desc">STL class </td></tr>
<tr id="row_41_0_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_41_0_" class="arrow" onclick="toggleFolder('41_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dc/de2/a00765.php" target="_self">mcd::queue&lt; T, Container &gt;</a></td><td class="desc">An implementation of std::queue </td></tr>
<tr id="row_41_0_0_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dd/d51/a00769.php" target="_self">mcd::t_queue&lt; T, Container &gt;</a></td><td class="desc">An thread-safe implementation of queue </td></tr>
<tr id="row_42_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d0/d28/a00997.php" target="_self">mcd::Referenced&lt; C &gt;</a></td><td class="desc">A class to have a reference to the class' pointer </td></tr>
<tr id="row_43_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="df/d59/a01001.php" target="_self">mcd::RNG&lt; T, U &gt;</a></td><td class="desc">A class to simplify the use of random </td></tr>
<tr id="row_44_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_44_" class="arrow" onclick="toggleFolder('44_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><b>std::stack&lt; T &gt;</b></td><td class="desc">STL class </td></tr>
<tr id="row_44_0_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_44_0_" class="arrow" onclick="toggleFolder('44_0_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d3/d95/a00757.php" target="_self">mcd::stack&lt; T, Container &gt;</a></td><td class="desc">An implementation of std::stack </td></tr>
<tr id="row_44_0_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d3/d4f/a00761.php" target="_self">mcd::t_stack&lt; T, Container &gt;</a></td><td class="desc">An thread-safe implementation of stack </td></tr>
<tr id="row_45_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/ded/a01009.php" target="_self">mcd::Threadable&lt; C &gt;</a></td><td class="desc">A class to let another one to be threadable with update() member in a thread </td></tr>
<tr id="row_46_"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_46_" class="arrow" onclick="toggleFolder('46_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/ded/a01009.php" target="_self">mcd::Threadable&lt; Timer &gt;</a></td><td class="desc"></td></tr>
<tr id="row_46_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d3/ded/a01017.php" target="_self">mcd::Timer</a></td><td class="desc">A timer to do something at the end </td></tr>
<tr id="row_47_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="dd/dd5/a00861.php" target="_self">mcd::ThreadEndlCout</a></td><td class="desc">A class to use std::endl in <a class="el" href="dd/d7b/a00865.php" title="A class to use std::cout thread safe. ">ThreadCout</a> </td></tr>
<tr id="row_48_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_48_" class="arrow" onclick="toggleFolder('48_')">&#9660;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/d59/a01013.php" target="_self">mcd::Time</a></td><td class="desc">A class to play with dates </td></tr>
<tr id="row_48_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d0/dac/a00901.php" target="_self">mcd::DateTime</a></td><td class="desc">A class to play with dates and times </td></tr>
<tr id="row_49_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="db/d23/a01025.php" target="_self">mcd::Tree&lt; T &gt;</a></td><td class="desc">A class to manage a binary tree </td></tr>
<tr id="row_50_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/ded/a00196.php#d0/daa/a01029" target="_self">mcd::trio&lt; T, U, V &gt;</a></td><td class="desc">A container for three values </td></tr>
<tr id="row_51_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span class="icona"><span class="icon">C</span></span><a class="el" href="d7/ded/a00196.php#dc/d36/a00925" target="_self">mcd::WorldDimensions</a></td><td class="desc">An object to group the dimensions of the world </td></tr>
</table>
</div><!-- directory -->
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
