<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: Class Hierarchy</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.1.1</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Nov 1 2020 19:28:20 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('hierarchy.php',''); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Class Hierarchy</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">
<p><a href="hierarchy.php">Go to the textual class hierarchy</a></p>
</div><table border="0" cellspacing="10" cellpadding="0">
<tr><td><img src="inherit_graph_0.png" border="0" usemap="#amcd_1_1Arguments" alt=""/>
<map name="mcd_1_1Arguments" id="mcd_1_1Arguments">
<area shape="rect" href="d2/d20/a01096.php" title="A class to manage the arguments." alt="" coords="5,5,124,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_1.png" border="0" usemap="#amcd_1_1Assert" alt=""/>
<map name="mcd_1_1Assert" id="mcd_1_1Assert">
<area shape="rect" href="dc/d51/a01120.php" title="My assert&#39;s implementation." alt="" coords="5,5,99,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_2.png" border="0" usemap="#amcd_1_1AssertionLocationStruct" alt=""/>
<map name="mcd_1_1AssertionLocationStruct" id="mcd_1_1AssertionLocationStruct">
<area shape="rect" href="db/d12/a00268.php#d4/dc5/a01116" title=" " alt="" coords="5,5,200,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_3.png" border="0" usemap="#amcd_1_1Big" alt=""/>
<map name="mcd_1_1Big" id="mcd_1_1Big">
<area shape="rect" href="d9/d12/a01128.php" title="A new huge arithmetic variable." alt="" coords="5,5,80,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_4.png" border="0" usemap="#amcd_1_1Binary_3_01T_00_01Enable_01_4" alt=""/>
<map name="mcd_1_1Binary_3_01T_00_01Enable_01_4" id="mcd_1_1Binary_3_01T_00_01Enable_01_4">
<area shape="rect" href="db/d12/a00268.php#d6/de6/a01132" title="A class to manage binary values easily." alt="" coords="5,5,176,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_5.png" border="0" usemap="#amcd_1_1Binary_3_01T_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic_3_01T_01_4_1_1value_00_01void_01_4_01_4" alt=""/>
<map name="mcd_1_1Binary_3_01T_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic_3_01T_01_4_1_1value_00_01void_01_4_01_4" id="mcd_1_1Binary_3_01T_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic_3_01T_01_4_1_1value_00_01void_01_4_01_4">
<area shape="rect" href="d1/dae/a01136.php" title=" " alt="" coords="5,5,184,76"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_6.png" border="0" usemap="#amcd_1_1Check_1_1has__istream__operator_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1has__istream__operator_3_01T_01_4" id="mcd_1_1Check_1_1has__istream__operator_3_01T_01_4">
<area shape="rect" href="d6/d97/a01188.php" title="A template class to test if T has an istream operator." alt="" coords="5,5,177,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_7.png" border="0" usemap="#amcd_1_1Check_1_1has__ostream__operator_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1has__ostream__operator_3_01T_01_4" id="mcd_1_1Check_1_1has__ostream__operator_3_01T_01_4">
<area shape="rect" href="dd/d75/a01180.php" title="A template class to test if T has an ostream operator." alt="" coords="5,5,181,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_8.png" border="0" usemap="#amcd_1_1Check_1_1has__size__method_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1has__size__method_3_01T_01_4" id="mcd_1_1Check_1_1has__size__method_3_01T_01_4">
<area shape="rect" href="d3/d32/a01176.php" title="Verify if an object has a size method." alt="" coords="5,5,159,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_9.png" border="0" usemap="#amcd_1_1Check_1_1is__array_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__array_3_01T_01_4" id="mcd_1_1Check_1_1is__array_3_01T_01_4">
<area shape="rect" href="db/d17/a01148.php" title="A template class to test if T is an array, a vector or a map." alt="" coords="5,5,184,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_10.png" border="0" usemap="#amcd_1_1Check_1_1is__duration_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__duration_3_01T_01_4" id="mcd_1_1Check_1_1is__duration_3_01T_01_4">
<area shape="rect" href="d6/db6/a01172.php" title="A template class to test if T is a chrono::duration." alt="" coords="5,5,201,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_11.png" border="0" usemap="#amcd_1_1Check_1_1is__minded__ptr_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__minded__ptr_3_01T_01_4" id="mcd_1_1Check_1_1is__minded__ptr_3_01T_01_4">
<area shape="rect" href="d9/d45/a01396.php" title="A template class to test if T is a std::shared_ptr, a std::unique_ptr or a std::weak_ptr." alt="" coords="5,5,165,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_12.png" border="0" usemap="#amcd_1_1Check_1_1is__object_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__object_3_01T_01_4" id="mcd_1_1Check_1_1is__object_3_01T_01_4">
<area shape="rect" href="dc/dcc/a01200.php" title="A template class to test if T is an unknown object." alt="" coords="5,5,191,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_13.png" border="0" usemap="#amcd_1_1Check_1_1is__pair_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__pair_3_01T_01_4" id="mcd_1_1Check_1_1is__pair_3_01T_01_4">
<area shape="rect" href="d9/d97/a01152.php" title="A template class to test if T is a std::pair." alt="" coords="5,5,176,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_14.png" border="0" usemap="#amcd_1_1Check_1_1is__printable_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__printable_3_01T_01_4" id="mcd_1_1Check_1_1is__printable_3_01T_01_4">
<area shape="rect" href="d2/d22/a01196.php" title="A template class to test if T is printable." alt="" coords="5,5,204,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_15.png" border="0" usemap="#amcd_1_1Check_1_1is__quatuor_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__quatuor_3_01T_01_4" id="mcd_1_1Check_1_1is__quatuor_3_01T_01_4">
<area shape="rect" href="da/d20/a01160.php" title="A template class to test if T is a std::pair." alt="" coords="5,5,199,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_16.png" border="0" usemap="#amcd_1_1Check_1_1is__smatch_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__smatch_3_01T_01_4" id="mcd_1_1Check_1_1is__smatch_3_01T_01_4">
<area shape="rect" href="d4/da6/a01168.php" title="A template class to test if T is a string regex match." alt="" coords="5,5,199,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_17.png" border="0" usemap="#amcd_1_1Check_1_1is__special__struct_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__special__struct_3_01T_01_4" id="mcd_1_1Check_1_1is__special__struct_3_01T_01_4">
<area shape="rect" href="d7/d5a/a01204.php" title="A template class to test if T is a special struct." alt="" coords="5,5,164,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_18.png" border="0" usemap="#amcd_1_1Check_1_1is__string_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__string_3_01T_01_4" id="mcd_1_1Check_1_1is__string_3_01T_01_4">
<area shape="rect" href="d2/dd2/a01164.php" title="A template class to test if T is a std::string." alt="" coords="5,5,188,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_19.png" border="0" usemap="#amcd_1_1Check_1_1is__thread__ptr_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__thread__ptr_3_01T_01_4" id="mcd_1_1Check_1_1is__thread__ptr_3_01T_01_4">
<area shape="rect" href="dc/d35/a01400.php" title="A template class to test if T is a std::shared_ptr&lt;thread&gt;, a std::unique_ptr&lt;thread&gt;,..." alt="" coords="5,5,160,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_20.png" border="0" usemap="#amcd_1_1Check_1_1is__trio_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__trio_3_01T_01_4" id="mcd_1_1Check_1_1is__trio_3_01T_01_4">
<area shape="rect" href="d9/d42/a01156.php" title="A template class to test if T is a std::pair." alt="" coords="5,5,173,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_21.png" border="0" usemap="#amcd_1_1Check_1_1is__vector_3_01T_01_4" alt=""/>
<map name="mcd_1_1Check_1_1is__vector_3_01T_01_4" id="mcd_1_1Check_1_1is__vector_3_01T_01_4">
<area shape="rect" href="db/d51/a01144.php" title="A template class to test if T is a vector." alt="" coords="5,5,192,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_22.png" border="0" usemap="#amcd_1_1Clock" alt=""/>
<map name="mcd_1_1Clock" id="mcd_1_1Clock">
<area shape="rect" href="dc/db6/a01212.php" title="A clock to measure the elapsed time." alt="" coords="5,5,95,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_23.png" border="0" usemap="#amcd_1_1Color" alt=""/>
<map name="mcd_1_1Color" id="mcd_1_1Color">
<area shape="rect" href="d8/df3/a01216.php" title="Change the text color in the console." alt="" coords="5,31,92,57"/>
<area shape="rect" href="d8/d8e/a01224.php" title="Clear the console." alt="" coords="147,5,222,32"/>
<area shape="rect" href="db/d42/a01220.php" title="Reinit the color in the console." alt="" coords="140,56,229,83"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_24.png" border="0" usemap="#amcd_1_1ConsoleTable" alt=""/>
<map name="mcd_1_1ConsoleTable" id="mcd_1_1ConsoleTable">
<area shape="rect" href="d4/dd5/a01244.php" title="A class to print a table in the console." alt="" coords="5,5,140,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_25.png" border="0" usemap="#amcd_1_1ContraptionAttr" alt=""/>
<map name="mcd_1_1ContraptionAttr" id="mcd_1_1ContraptionAttr">
<area shape="rect" href="db/d12/a00268.php#d8/d0d/a01280" title="A struct to define Contraption attributes." alt="" coords="5,5,148,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_26.png" border="0" usemap="#amcd_1_1exception" alt=""/>
<map name="mcd_1_1exception" id="mcd_1_1exception">
<area shape="rect" title="STL class." alt="" coords="5,81,109,108"/>
<area shape="rect" href="d7/d8d/a01288.php" title="A class to call custom exceptions." alt="" coords="157,81,268,108"/>
<area shape="rect" href="d0/dc8/a01124.php" title="An exception thrown by my assert&#39;s implementation." alt="" coords="321,5,489,32"/>
<area shape="rect" href="d4/d49/a01316.php" title="A class to throw Json exceptions." alt="" coords="335,56,476,83"/>
<area shape="rect" href="d7/d51/a01340.php" title="A class to throw some exceptions for a Matrix instance." alt="" coords="331,107,480,133"/>
<area shape="rect" href="d2/d29/a01376.php" title="All exceptions that could be thrown by the pathfinding algorithm." alt="" coords="316,157,495,184"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_27.png" border="0" usemap="#amcd_1_1Fraction" alt=""/>
<map name="mcd_1_1Fraction" id="mcd_1_1Fraction">
<area shape="rect" href="d8/d7a/a01292.php" title="A class to manage fractions." alt="" coords="5,5,108,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_28.png" border="0" usemap="#amcd_1_1Hostile" alt=""/>
<map name="mcd_1_1Hostile" id="mcd_1_1Hostile">
<area shape="rect" href="da/de0/a01248.php" title="A contraption." alt="" coords="5,81,128,108"/>
<area shape="rect" href="dd/d18/a01284.php" title="An entity." alt="" coords="179,56,269,83"/>
<area shape="rect" href="d2/d3f/a01356.php" title="An object." alt="" coords="177,107,271,133"/>
<area shape="rect" href="da/db7/a01088.php" title="An animal." alt="" coords="322,5,417,32"/>
<area shape="rect" href="d2/d2f/a01460.php" title="A vegetal." alt="" coords="320,56,419,83"/>
<area shape="rect" href="de/d9c/a01092.php" title="An ant." alt="" coords="487,5,562,32"/>
<area shape="rect" href="dc/d54/a01344.php" title="A mushroom." alt="" coords="467,56,583,83"/>
<area shape="rect" href="d7/dde/a01384.php" title="A plant." alt="" coords="482,107,567,133"/>
<area shape="rect" href="d5/dec/a01416.php" title="A stone." alt="" coords="325,107,414,133"/>
<area shape="rect" href="d8/dc5/a01300.php" title="A class to derivate from when the thing can attack." alt="" coords="176,5,272,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_29.png" border="0" usemap="#amcd_1_1IOConfig" alt=""/>
<map name="mcd_1_1IOConfig" id="mcd_1_1IOConfig">
<area shape="rect" href="d1/d56/a01308.php" title="A class to configure inputs and outputs." alt="" coords="5,5,112,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_30.png" border="0" usemap="#amcd_1_1Json" alt=""/>
<map name="mcd_1_1Json" id="mcd_1_1Json">
<area shape="rect" href="d7/d41/a01312.php" title="A class to manage Json formatted data." alt="" coords="5,5,88,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_31.png" border="0" usemap="#amcd_1_1Logger" alt=""/>
<map name="mcd_1_1Logger" id="mcd_1_1Logger">
<area shape="rect" href="df/dec/a01320.php" title="A class to log some messages." alt="" coords="5,5,100,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_32.png" border="0" usemap="#amcd_1_1Map" alt=""/>
<map name="mcd_1_1Map" id="mcd_1_1Map">
<area shape="rect" href="d9/d45/a01332.php" title="A class to manage a map and that implement some pathfinding algorithms." alt="" coords="5,5,85,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_33.png" border="0" usemap="#amcd_1_1MapMove" alt=""/>
<map name="mcd_1_1MapMove" id="mcd_1_1MapMove">
<area shape="rect" href="db/d12/a00268.php#dc/dd9/a01328" title="A struct to know informations about th movement of something in the map." alt="" coords="5,5,117,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_34.png" border="0" usemap="#amcd_1_1Matrix_3_01C_01_4" alt=""/>
<map name="mcd_1_1Matrix_3_01C_01_4" id="mcd_1_1Matrix_3_01C_01_4">
<area shape="rect" href="df/d93/a01336.php" title="A class to represent matrix." alt="" coords="5,5,131,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_35.png" border="0" usemap="#amcd_1_1natural_1_1Cell" alt=""/>
<map name="mcd_1_1natural_1_1Cell" id="mcd_1_1natural_1_1Cell">
<area shape="rect" href="dc/d64/a01140.php" title="A cell with chromosomes." alt="" coords="5,5,131,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_36.png" border="0" usemap="#amcd_1_1natural_1_1Chromosome" alt=""/>
<map name="mcd_1_1natural_1_1Chromosome" id="mcd_1_1natural_1_1Chromosome">
<area shape="rect" href="d9/d31/a01208.php" title="A double group of genes." alt="" coords="5,5,185,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_37.png" border="0" usemap="#amcd_1_1natural_1_1Gene" alt=""/>
<map name="mcd_1_1natural_1_1Gene" id="mcd_1_1natural_1_1Gene">
<area shape="rect" href="d4/d64/a01296.php" title="A gene that represent a caracteristic." alt="" coords="5,5,139,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_38.png" border="0" usemap="#amcd_1_1Node_3_01T_01_4" alt=""/>
<map name="mcd_1_1Node_3_01T_01_4" id="mcd_1_1Node_3_01T_01_4">
<area shape="rect" href="db/d12/a00268.php#dc/d85/a01436" title="A struct to define a node for the tree." alt="" coords="5,5,124,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_39.png" border="0" usemap="#amcd_1_1NotCopyable" alt=""/>
<map name="mcd_1_1NotCopyable" id="mcd_1_1NotCopyable">
<area shape="rect" href="d7/d57/a01348.php" title="A class to let some other not to be copyable." alt="" coords="5,81,136,108"/>
<area shape="rect" href="d0/d33/a01252.php" title="A class to be the parent for every crypt class." alt="" coords="184,81,279,108"/>
<area shape="rect" href="d6/d0f/a01256.php" title="A class to use the cesar algorithm for encryption." alt="" coords="334,5,425,32"/>
<area shape="rect" href="d3/d51/a01264.php" title="A class to test a homemade algorithm for encryption." alt="" coords="327,56,432,83"/>
<area shape="rect" href="dc/dd9/a01268.php" title="A class to use the RSA algorithm for encryption." alt="" coords="338,107,421,133"/>
<area shape="rect" href="d7/da3/a01260.php" title="An implementation of sha256 encryption." alt="" coords="334,157,425,184"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_40.png" border="0" usemap="#amcd_1_1NotInstantiable" alt=""/>
<map name="mcd_1_1NotInstantiable" id="mcd_1_1NotInstantiable">
<area shape="rect" href="d0/d85/a01352.php" title="Let a class being only an abstract class." alt="" coords="5,5,148,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_41.png" border="0" usemap="#amcd_1_1Path" alt=""/>
<map name="mcd_1_1Path" id="mcd_1_1Path">
<area shape="rect" href="de/d1f/a01364.php" title="A class to manage a path computed by the map." alt="" coords="5,5,88,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_42.png" border="0" usemap="#amcd_1_1Pathfinding" alt=""/>
<map name="mcd_1_1Pathfinding" id="mcd_1_1Pathfinding">
<area shape="rect" href="dd/d0c/a01368.php" title="A class to implement some pathfinding algorithms." alt="" coords="5,5,125,32"/>
<area shape="rect" href="df/d0b/a01372.php" title="An implementation of the Dijkstra algorithm." alt="" coords="173,5,339,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_43.png" border="0" usemap="#amcd_1_1PathfindingNode" alt=""/>
<map name="mcd_1_1PathfindingNode" id="mcd_1_1PathfindingNode">
<area shape="rect" href="d9/d79/a01360.php" title="A node for the path." alt="" coords="5,5,156,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_44.png" border="0" usemap="#amcd_1_1PathfindingProblem" alt=""/>
<map name="mcd_1_1PathfindingProblem" id="mcd_1_1PathfindingProblem">
<area shape="rect" href="dd/d6d/a01380.php" title="A class to group every pathfinding problems in one way to use it." alt="" coords="5,5,173,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_45.png" border="0" usemap="#amcd_1_1PlayerAbstraction_3_01PlayerParent_01_4" alt=""/>
<map name="mcd_1_1PlayerAbstraction_3_01PlayerParent_01_4" id="mcd_1_1PlayerAbstraction_3_01PlayerParent_01_4">
<area shape="rect" href="d6/dae/a01304.php" title="A class to store some identify datas." alt="" coords="177,5,283,32"/>
<area shape="rect" href="d0/d36/a01388.php" title="A player that can be a child from any class." alt="" coords="357,35,548,61"/>
<area shape="rect" title=" " alt="" coords="5,64,103,91"/>
<area shape="rect" href="d1/dcc/a01392.php" title="A player that can be a child from any class." alt="" coords="151,57,309,98"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_46.png" border="0" usemap="#amcd_1_1Point" alt=""/>
<map name="mcd_1_1Point" id="mcd_1_1Point">
<area shape="rect" href="dd/d1c/a01452.php" title="A struct to define a point in space." alt="" coords="5,5,91,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_47.png" border="0" usemap="#amcd_1_1PureVirtual" alt=""/>
<map name="mcd_1_1PureVirtual" id="mcd_1_1PureVirtual">
<area shape="rect" href="d2/d82/a01404.php" title="A class to make some other to be abstract class." alt="" coords="5,5,124,32"/>
<area shape="rect" href="de/d16/a01228.php" title="A class to play with the cursor in the console." alt="" coords="172,5,315,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_48.png" border="0" usemap="#amcd_1_1quatuor_3_01T_00_01U_00_01V_00_01W_01_4" alt=""/>
<map name="mcd_1_1quatuor_3_01T_00_01U_00_01V_00_01W_01_4" id="mcd_1_1quatuor_3_01T_00_01U_00_01V_00_01W_01_4">
<area shape="rect" href="db/d12/a00268.php#dd/d08/a01448" title="A container for four values." alt="" coords="5,5,144,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_49.png" border="0" usemap="#amcd_1_1queue_3_01T_00_01Container_01_4" alt=""/>
<map name="mcd_1_1queue_3_01T_00_01Container_01_4" id="mcd_1_1queue_3_01T_00_01Container_01_4">
<area shape="rect" title="STL class." alt="" coords="5,35,120,61"/>
<area shape="rect" href="d2/dd7/a01108.php" title="An implementation of std::queue." alt="" coords="168,5,352,32"/>
<area shape="rect" href="d2/dd7/a01108.php" title=" " alt="" coords="193,57,327,98"/>
<area shape="rect" href="d0/d39/a01112.php" title="An thread&#45;safe implementation of queue." alt="" coords="400,64,595,91"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_50.png" border="0" usemap="#amcd_1_1Referenced_3_01C_01_4" alt=""/>
<map name="mcd_1_1Referenced_3_01C_01_4" id="mcd_1_1Referenced_3_01C_01_4">
<area shape="rect" href="df/d84/a01408.php" title="A class to have a reference to the class&#39; pointer." alt="" coords="5,5,161,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_51.png" border="0" usemap="#amcd_1_1RNG_3_01T_00_01U_01_4" alt=""/>
<map name="mcd_1_1RNG_3_01T_00_01U_01_4" id="mcd_1_1RNG_3_01T_00_01U_01_4">
<area shape="rect" href="dc/d10/a01412.php" title="A class to simplify the use of random." alt="" coords="5,5,139,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_52.png" border="0" usemap="#amcd_1_1SetPrecision" alt=""/>
<map name="mcd_1_1SetPrecision" id="mcd_1_1SetPrecision">
<area shape="rect" href="d5/d6e/a01240.php" title="Change the precision of a std::ostream and save the default value." alt="" coords="5,5,135,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_53.png" border="0" usemap="#amcd_1_1stack_3_01T_00_01Container_01_4" alt=""/>
<map name="mcd_1_1stack_3_01T_00_01Container_01_4" id="mcd_1_1stack_3_01T_00_01Container_01_4">
<area shape="rect" title="STL class." alt="" coords="5,35,117,61"/>
<area shape="rect" href="d3/dbd/a01100.php" title="An implementation of std::stack." alt="" coords="165,5,347,32"/>
<area shape="rect" href="d3/dbd/a01100.php" title=" " alt="" coords="191,57,321,98"/>
<area shape="rect" href="dd/dcb/a01104.php" title="An thread&#45;safe implementation of stack." alt="" coords="395,64,587,91"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_54.png" border="0" usemap="#amcd_1_1Tests_1_1Test" alt=""/>
<map name="mcd_1_1Tests_1_1Test" id="mcd_1_1Tests_1_1Test">
<area shape="rect" href="d0/d05/a01420.php" title="A static class to test code." alt="" coords="5,5,125,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_55.png" border="0" usemap="#amcd_1_1Threadable_3_01C_01_4" alt=""/>
<map name="mcd_1_1Threadable_3_01C_01_4" id="mcd_1_1Threadable_3_01C_01_4">
<area shape="rect" href="d5/da5/a01424.php" title="A class to let another one to be threadable with update() member in a thread." alt="" coords="5,5,159,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_56.png" border="0" usemap="#amcd_1_1Threadable_3_01Timer_01_4" alt=""/>
<map name="mcd_1_1Threadable_3_01Timer_01_4" id="mcd_1_1Threadable_3_01Timer_01_4">
<area shape="rect" href="d5/da5/a01424.php" title=" " alt="" coords="5,5,181,32"/>
<area shape="rect" href="db/dff/a01432.php" title="A timer to do something at the end." alt="" coords="229,5,317,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_57.png" border="0" usemap="#amcd_1_1ThreadCout" alt=""/>
<map name="mcd_1_1ThreadCout" id="mcd_1_1ThreadCout">
<area shape="rect" title="STL class." alt="" coords="5,13,105,39"/>
<area shape="rect" title="STL class." alt="" coords="153,13,308,39"/>
<area shape="rect" title="STL class." alt="" coords="356,5,489,47"/>
<area shape="rect" title="STL class." alt="" coords="537,13,632,39"/>
<area shape="rect" href="d8/d2b/a01236.php" title="A class to use std::cout thread safe." alt="" coords="680,13,803,39"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_58.png" border="0" usemap="#amcd_1_1ThreadEndlCout" alt=""/>
<map name="mcd_1_1ThreadEndlCout" id="mcd_1_1ThreadEndlCout">
<area shape="rect" href="d0/d67/a01232.php" title="A class to use std::endl in ThreadCout." alt="" coords="5,5,155,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_59.png" border="0" usemap="#amcd_1_1Time" alt=""/>
<map name="mcd_1_1Time" id="mcd_1_1Time">
<area shape="rect" href="d4/d0e/a01272.php" title="A class to play with dates." alt="" coords="6,5,89,32"/>
<area shape="rect" href="d5/d37/a01276.php" title="A class to play with dates and times." alt="" coords="137,31,249,57"/>
<area shape="rect" href="d2/db1/a01428.php" title="A class to play with dates." alt="" coords="5,56,89,83"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_60.png" border="0" usemap="#amcd_1_1Tree_3_01T_01_4" alt=""/>
<map name="mcd_1_1Tree_3_01T_01_4" id="mcd_1_1Tree_3_01T_01_4">
<area shape="rect" href="df/d31/a01440.php" title="A class to manage a binary tree." alt="" coords="5,5,119,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_61.png" border="0" usemap="#amcd_1_1trio_3_01T_00_01U_00_01V_01_4" alt=""/>
<map name="mcd_1_1trio_3_01T_00_01U_00_01V_01_4" id="mcd_1_1trio_3_01T_00_01U_00_01V_01_4">
<area shape="rect" href="db/d12/a00268.php#d7/d32/a01444" title="A container for three values." alt="" coords="5,5,144,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_62.png" border="0" usemap="#amcd_1_1vector_3_01C_01_4" alt=""/>
<map name="mcd_1_1vector_3_01C_01_4" id="mcd_1_1vector_3_01C_01_4">
<area shape="rect" title="STL class." alt="" coords="5,5,121,32"/>
<area shape="rect" href="d4/d98/a01456.php" title="Add some features to std::vector." alt="" coords="169,5,295,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_63.png" border="0" usemap="#amcd_1_1WorldDimensions" alt=""/>
<map name="mcd_1_1WorldDimensions" id="mcd_1_1WorldDimensions">
<area shape="rect" href="db/d12/a00268.php#d5/d53/a01324" title="An object to group the dimensions of the world." alt="" coords="5,5,163,32"/>
</map>
</td></tr>
</table>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
