<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Namespace Members</title>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="dynsections.js"></script>
		<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
		<link href="doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Thu Nov 14 2019 13:45:02 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('namespacemembers_func.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_a"></a>- a -</h3><ul>
<li>abs()
: <a class="el" href="da/d2e/a00238.php#a50868f33f43952d24f8449e883d3fd99">mcd</a>
</li>
<li>array1Dto2D()
: <a class="el" href="da/d2e/a00238.php#a040a2aa0625adc9f13e6568d906a20a2">mcd</a>
</li>
<li>array2Dto1D()
: <a class="el" href="da/d2e/a00238.php#af1c42a8b9412d2afa3b486c5e629f752">mcd</a>
</li>
</ul>


<h3><a id="index_c"></a>- c -</h3><ul>
<li>collidesC()
: <a class="el" href="da/d2e/a00238.php#ace8a4328114062b56cf578ad92df821f">mcd</a>
</li>
<li>collidesPC()
: <a class="el" href="da/d2e/a00238.php#ae694a8102421f25c163a0ef7a9e903e2">mcd</a>
</li>
<li>collidesPR()
: <a class="el" href="da/d2e/a00238.php#a3c001118da32a4466802e0b378af661b">mcd</a>
</li>
<li>collidesR()
: <a class="el" href="da/d2e/a00238.php#ab43dbb509e6ac3b52cd7767a1fb6bdaa">mcd</a>
</li>
<li>collidesRC()
: <a class="el" href="da/d2e/a00238.php#adbb1b1f3a194f48bab3af872f65b9757">mcd</a>
</li>
<li>contains()
: <a class="el" href="da/d2e/a00238.php#ad53bf266a5db5dc112e71ebe3c78946e">mcd</a>
</li>
<li>count()
: <a class="el" href="da/d2e/a00238.php#a95be8eb46f76298e1218183421d13825">mcd</a>
</li>
</ul>


<h3><a id="index_d"></a>- d -</h3><ul>
<li>decimalPart()
: <a class="el" href="da/d2e/a00238.php#a0598b7abd7e7441f6553f1b486053945">mcd</a>
</li>
<li>deletePtr()
: <a class="el" href="da/d2e/a00238.php#ad32e282421be0e66b0288fe7634ad183">mcd</a>
</li>
<li>dist()
: <a class="el" href="da/d2e/a00238.php#a4d75f23c9b03fd2c56324895d0ff3c58">mcd</a>
</li>
<li>dsigmoide()
: <a class="el" href="da/d2e/a00238.php#a9042d2e8e9a6311b4260c6f376f4072c">mcd</a>
</li>
</ul>


<h3><a id="index_e"></a>- e -</h3><ul>
<li>error_log()
: <a class="el" href="da/d2e/a00238.php#a1a14f66f0c6eba0c77338364977658e1">mcd</a>
</li>
<li>eucl()
: <a class="el" href="da/d2e/a00238.php#a10764d50321a1ff81cc7cd4a9f7e42bc">mcd</a>
</li>
<li>exec()
: <a class="el" href="da/d2e/a00238.php#a0d72a06346182146581ff63f2fa70580">mcd</a>
</li>
</ul>


<h3><a id="index_f"></a>- f -</h3><ul>
<li>fileExists()
: <a class="el" href="da/d2e/a00238.php#ae44c2e346da18a7424d97535fb654448">mcd</a>
</li>
<li>fileFormat()
: <a class="el" href="da/d2e/a00238.php#aada88379a63c49987a295485391aa192">mcd</a>
</li>
<li>fromBigVal()
: <a class="el" href="da/d2e/a00238.php#aea3616a95b7e00c3c401fe7f5d907ba8">mcd</a>
</li>
</ul>


<h3><a id="index_g"></a>- g -</h3><ul>
<li>getall()
: <a class="el" href="da/d2e/a00238.php#ad903ee1a5cdf033a289168423cc0cf46">mcd</a>
</li>
<li>getFileSize()
: <a class="el" href="da/d2e/a00238.php#a97dfa91f19b9e2175dddbf65285663a2">mcd</a>
</li>
<li>getlines()
: <a class="el" href="da/d2e/a00238.php#a1dd313ef15241c8adf795cbcc5c77048">mcd</a>
</li>
<li>getMilli()
: <a class="el" href="da/d2e/a00238.php#ac4573282fe9cf6a0af8de786baaf6456">mcd</a>
</li>
<li>getSec()
: <a class="el" href="da/d2e/a00238.php#a49144605ea2f1f8a9463ae309c293628">mcd</a>
</li>
<li>getType()
: <a class="el" href="da/d2e/a00238.php#aad6c9253e2099a49d163fad90ef6f5f5">mcd</a>
</li>
</ul>


<h3><a id="index_i"></a>- i -</h3><ul>
<li>implode()
: <a class="el" href="da/d2e/a00238.php#ad751f3d04e342cbe86c561683c3bd99c">mcd</a>
</li>
<li>info_log()
: <a class="el" href="da/d2e/a00238.php#af0b4fd6390d33edc9719d42b26f6e29f">mcd</a>
</li>
<li>invmod()
: <a class="el" href="da/d2e/a00238.php#a6f68c011df46f54833bbda0ac9de04e2">mcd</a>
</li>
<li>isDivisor()
: <a class="el" href="da/d2e/a00238.php#a23f629777bd39a54b33491cb1223da01">mcd</a>
</li>
<li>isLuhn()
: <a class="el" href="da/d2e/a00238.php#ab001b84d20c0fffe59c7a55ed872d300">mcd</a>
</li>
<li>isNumber()
: <a class="el" href="da/d2e/a00238.php#a6a0096efe278298f80c641af617dd216">mcd</a>
</li>
<li>isPrime()
: <a class="el" href="da/d2e/a00238.php#ad3913978376bb08e036a7bf0b21d6b50">mcd</a>
</li>
<li>isPrintable()
: <a class="el" href="d9/d21/a00240.php#a13e84a38884d860a4854bdd4a031d218">mcd::Check</a>
</li>
</ul>


<h3><a id="index_l"></a>- l -</h3><ul>
<li>log2p()
: <a class="el" href="da/d2e/a00238.php#a69d6be0b9d139073dda5e708c76dccdd">mcd</a>
</li>
<li>lowercase()
: <a class="el" href="da/d2e/a00238.php#a0c6d83e8654926ceebd7777a9ada0652">mcd</a>
</li>
<li>luhn()
: <a class="el" href="da/d2e/a00238.php#a176933d706495ddff7385a68319e7169">mcd</a>
</li>
</ul>


<h3><a id="index_m"></a>- m -</h3><ul>
<li>max()
: <a class="el" href="da/d2e/a00238.php#a50e5370a188b7230c0dce47cc746f533">mcd</a>
</li>
<li>microSleep()
: <a class="el" href="da/d2e/a00238.php#a773d8ead6e35e10f86f4285f3f79ecb9">mcd</a>
</li>
<li>milliSleep()
: <a class="el" href="da/d2e/a00238.php#a30ed8e5c290433011b9855598cfc050a">mcd</a>
</li>
<li>min()
: <a class="el" href="da/d2e/a00238.php#abc683613235e8674b000071c25747728">mcd</a>
</li>
<li>mod()
: <a class="el" href="da/d2e/a00238.php#af44c5ff8cc0a054f720ed177e7e44265">mcd</a>
</li>
</ul>


<h3><a id="index_n"></a>- n -</h3><ul>
<li>nanoSleep()
: <a class="el" href="da/d2e/a00238.php#a5b2e0c30451ea35d0cc5eb9badea5be0">mcd</a>
</li>
</ul>


<h3><a id="index_o"></a>- o -</h3><ul>
<li>operator!=()
: <a class="el" href="da/d2e/a00238.php#a8106aa588d48c9fbed5e30e22fd55f76">mcd</a>
</li>
<li>operator+()
: <a class="el" href="da/d2e/a00238.php#a68941be2cb0a91ce0a75b0992c772e19">mcd</a>
</li>
<li>operator++()
: <a class="el" href="da/d2e/a00238.php#a164a9c100a128e971c6becd38fe7db82">mcd</a>
</li>
<li>operator-()
: <a class="el" href="da/d2e/a00238.php#aa34a809adea5c0391ccc070f4b6fac4b">mcd</a>
</li>
<li>operator--()
: <a class="el" href="da/d2e/a00238.php#a69988c1c7ee2ad5814c297f749588e78">mcd</a>
</li>
<li>operator&lt;()
: <a class="el" href="da/d2e/a00238.php#ab3a0bfd8107f1a0512e3daccbe8ec32a">mcd</a>
</li>
<li>operator&lt;&lt;()
: <a class="el" href="da/d2e/a00238.php#a0e76ac5c4df82149886b58edcfc7090a">mcd</a>
</li>
<li>operator&lt;=()
: <a class="el" href="da/d2e/a00238.php#a35feb7b77517c8a067a4f631d0c01903">mcd</a>
</li>
<li>operator==()
: <a class="el" href="da/d2e/a00238.php#a49c8e33d55da52fabdb3f09f2fd3e5b2">mcd</a>
</li>
<li>operator&gt;()
: <a class="el" href="da/d2e/a00238.php#ae8c157fea2d3cba9a23a3ff2878cc08e">mcd</a>
</li>
<li>operator&gt;=()
: <a class="el" href="da/d2e/a00238.php#a83c8849718e8a8532282e6f1c80ceca0">mcd</a>
</li>
</ul>


<h3><a id="index_p"></a>- p -</h3><ul>
<li>pgcd()
: <a class="el" href="da/d2e/a00238.php#a0f3f4e24615446479ff59ce15ce61cde">mcd</a>
</li>
<li>ppcm()
: <a class="el" href="da/d2e/a00238.php#ad6ca3061a339d883c257105bd831efd1">mcd</a>
</li>
<li>print_all()
: <a class="el" href="da/d2e/a00238.php#a5996fcf8097a903a5461a6035ff0f98d">mcd</a>
</li>
<li>print_r()
: <a class="el" href="da/d2e/a00238.php#a0029a835651d350c925a43fd718ab590">mcd</a>
</li>
<li>printable()
: <a class="el" href="d9/d21/a00240.php#ab0b2e96bd3f31d823dad478c5f54abf1">mcd::Check</a>
</li>
<li>printSize()
: <a class="el" href="da/d2e/a00238.php#a5046a9dfac4629babcb20cf7b914415e">mcd</a>
</li>
<li>printType()
: <a class="el" href="da/d2e/a00238.php#a2bb83762638ce787815f3699d67faa92">mcd</a>
</li>
<li>ProjectionSurSegment()
: <a class="el" href="da/d2e/a00238.php#af6f9411fa8041c4f9f81519deeba4a0a">mcd</a>
</li>
</ul>


<h3><a id="index_r"></a>- r -</h3><ul>
<li>randStr()
: <a class="el" href="da/d2e/a00238.php#a1ddd069f38e7407563a5d8e763d7dc90">mcd</a>
</li>
<li>ref()
: <a class="el" href="da/d2e/a00238.php#a25c5de928e67bd9c01f720f39329f04c">mcd</a>
</li>
<li>removeAccents()
: <a class="el" href="da/d2e/a00238.php#a685af449d029b7793f497633bbafbcbb">mcd</a>
</li>
<li>replace()
: <a class="el" href="da/d2e/a00238.php#ae61cb7564bc3b0ccbcad0b991b74635d">mcd</a>
</li>
<li>rewrite()
: <a class="el" href="da/d2e/a00238.php#a4462e6059998aa718e92fd11fd9747e8">mcd</a>
</li>
<li>rngRange()
: <a class="el" href="da/d2e/a00238.php#a95489209bc34099d9508c0e22a279bb0">mcd</a>
</li>
<li>round()
: <a class="el" href="da/d2e/a00238.php#a7e1c88cc52e517f309354a546e78f403">mcd</a>
</li>
</ul>


<h3><a id="index_s"></a>- s -</h3><ul>
<li>servLog()
: <a class="el" href="da/d2e/a00238.php#abcc09c3d97d72792032b5615d41aa1c5">mcd</a>
</li>
<li>setlines()
: <a class="el" href="da/d2e/a00238.php#a08a1c8da74e7ca2634c1a2a4f4a3ac9d">mcd</a>
</li>
<li>sigmoide()
: <a class="el" href="da/d2e/a00238.php#a2d67b0e24c6216a693a903f5bc8c31a0">mcd</a>
</li>
<li>sleep()
: <a class="el" href="da/d2e/a00238.php#a0003c12a7cc73a35e488f59ad14770bf">mcd</a>
</li>
<li>sleep_for()
: <a class="el" href="d0/d27/a00239.php#aaa5ef673c6390db3486b12d03a64f8f5">mcd::this_thread</a>
</li>
<li>sortAsc()
: <a class="el" href="da/d2e/a00238.php#a0a1aa5f89ff57aa7dc4e6d136c9c315f">mcd</a>
</li>
<li>sortDesc()
: <a class="el" href="da/d2e/a00238.php#a45ad9c2ac4a373fdad27e51c1c741d76">mcd</a>
</li>
<li>split()
: <a class="el" href="da/d2e/a00238.php#a3f5effb1d0789a63d9c71c5549f3eacf">mcd</a>
</li>
<li>sq()
: <a class="el" href="da/d2e/a00238.php#a31eb09e89b0015d54768c4510e59c780">mcd</a>
</li>
<li>sqrt()
: <a class="el" href="da/d2e/a00238.php#ae3a712e4de66375b1a188fa464c968e2">mcd</a>
</li>
</ul>


<h3><a id="index_t"></a>- t -</h3><ul>
<li>tob()
: <a class="el" href="da/d2e/a00238.php#a7b322c51a82629ed6b2325f2f938eae3">mcd</a>
</li>
<li>toBigVal()
: <a class="el" href="da/d2e/a00238.php#a66e560b6579bb202abdcee37283121a0">mcd</a>
</li>
<li>tod()
: <a class="el" href="da/d2e/a00238.php#a3c6193ba2e9669603892d2508cbc6668">mcd</a>
</li>
<li>tof()
: <a class="el" href="da/d2e/a00238.php#a6ed92c0cecb59861393802ac313a2b0f">mcd</a>
</li>
<li>toi()
: <a class="el" href="da/d2e/a00238.php#a476d57ae34f933a4192553496ec91208">mcd</a>
</li>
<li>tomilli()
: <a class="el" href="da/d2e/a00238.php#a71458bb6c1d0939bd975cdf25e864599">mcd</a>
</li>
<li>tos()
: <a class="el" href="da/d2e/a00238.php#ae057a7c5042a3cacb444199a2b6b7598">mcd</a>
</li>
<li>tosh()
: <a class="el" href="da/d2e/a00238.php#adfea444e2cb8e428b7c9604d77076ad1">mcd</a>
</li>
<li>tost()
: <a class="el" href="da/d2e/a00238.php#a917e4be62e6930b138038ae16ebc7904">mcd</a>
</li>
<li>tou()
: <a class="el" href="da/d2e/a00238.php#a818831d2e74dbfa3be2150c38a9afa31">mcd</a>
</li>
<li>tov()
: <a class="el" href="da/d2e/a00238.php#a21f9e69f4ccff705b65007a1ac7063ef">mcd</a>
</li>
<li>treeAscSorter()
: <a class="el" href="da/d2e/a00238.php#aa17a2314efb86933584ae451318a17da">mcd</a>
</li>
<li>treeDescSorter()
: <a class="el" href="da/d2e/a00238.php#a1865ef6e7eed9ac5fa5b177b3f8dd1e9">mcd</a>
</li>
<li>trim()
: <a class="el" href="da/d2e/a00238.php#aa97708c3c4ad49b7e60d30c66bfad80a">mcd</a>
</li>
</ul>


<h3><a id="index_u"></a>- u -</h3><ul>
<li>uppercase()
: <a class="el" href="da/d2e/a00238.php#a334e09619932c4b2c193abe4fc9c3306">mcd</a>
</li>
</ul>


<h3><a id="index_w"></a>- w -</h3><ul>
<li>warning_log()
: <a class="el" href="da/d2e/a00238.php#ac625de83fcace96567aecd1363297776">mcd</a>
</li>
<li>wholePart()
: <a class="el" href="da/d2e/a00238.php#af9443ebf71fe196006831fe344a09f13">mcd</a>
</li>
</ul>


<h3><a id="index_y"></a>- y -</h3><ul>
<li>yield()
: <a class="el" href="d0/d27/a00239.php#a3a711ec2f858ee16756d8619224624ee">mcd::this_thread</a>
</li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
