<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Player.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Thu Sep 26 2019 21:18:11 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d3/df8/a00155.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">Player.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d6/db8/a00158.php">C++/PlayerAbstraction.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d1/dc1/a00092.php">C++/Identifier.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Player.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/d34/a00156.png" border="0" usemap="#Player_8hpp" alt=""/></div>
<map name="Player_8hpp" id="Player_8hpp">
<area shape="rect" id="node2" href="../../d6/db8/a00158.php" title="C++/PlayerAbstraction.hpp" alt="" coords="361,80,541,107"/>
<area shape="rect" id="node98" href="../../d1/dc1/a00092.php" title="C++/Identifier.hpp" alt="" coords="562,155,689,181"/>
<area shape="rect" id="node3" href="../../db/db6/a00074.php" title="C++/Entities.hpp" alt="" coords="381,155,502,181"/>
<area shape="rect" id="node4" href="../../d5/de9/a00176.php" title="C++/Stone.hpp" alt="" coords="514,229,625,256"/>
<area shape="rect" id="node91" href="../../d7/d9a/a00152.php" title="C++/Plant.hpp" alt="" coords="99,229,205,256"/>
<area shape="rect" id="node94" href="../../dc/dfe/a00125.php" title="C++/Mushroom.hpp" alt="" coords="229,229,368,256"/>
<area shape="rect" id="node95" href="../../dd/dad/a00005.php" title="C++/Ant.hpp" alt="" coords="393,229,490,256"/>
<area shape="rect" id="node5" href="../../d7/d06/a00131.php" title="C++/Object.hpp" alt="" coords="511,379,625,405"/>
<area shape="rect" id="node6" href="../../d9/d2e/a00056.php" title="C++/Contraption.hpp" alt="" coords="481,528,625,555"/>
<area shape="rect" id="node7" href="../../d4/d8c/a00035.php" title="C++/C++.hpp" alt="" coords="557,603,659,629"/>
<area shape="rect" id="node8" href="../../df/d03/a00062.php" title="C++/cryptage.hpp" alt="" coords="406,677,533,704"/>
<area shape="rect" id="node89" href="../../de/db1/a00197.php" title="C++/Tree.hpp" alt="" coords="557,677,659,704"/>
<area shape="rect" id="node90" href="../../d0/dc2/a00104.php" title="C++/Map.hpp" alt="" coords="683,677,786,704"/>
<area shape="rect" id="node9" href="../../d0/d89/a00071.php" title="C++/defines.hpp" alt="" coords="549,752,667,779"/>
<area shape="rect" id="node10" href="../../dc/d57/a00194.php" title="C++/Timer.hpp" alt="" coords="207,827,318,853"/>
<area shape="rect" id="node75" href="../../d4/dee/a00008.php" title="C++/Args.hpp" alt="" coords="343,827,447,853"/>
<area shape="rect" id="node76" href="../../da/d24/a00068.php" title="C++/DateTime.hpp" alt="" coords="417,1051,551,1077"/>
<area shape="rect" id="node79" href="../../d5/df9/a00044.php" title="C++/Clock.hpp" alt="" coords="522,976,633,1003"/>
<area shape="rect" id="node80" href="../../dc/dee/a00053.php" title="C++/ConsoleTable.hpp" alt="" coords="588,901,745,928"/>
<area shape="rect" id="node81" href="../../dc/de6/a00167.php" title="C++/Referenced.hpp" alt="" coords="708,976,852,1003"/>
<area shape="rect" id="node82" href="../../d5/db1/a00140.php" title="C++/PathfindingAlgorithms.hpp" alt="" coords="831,827,1035,853"/>
<area shape="rect" id="node88" href="../../d1/d44/a00098.php" title="C++/IOConfig.hpp" alt="" coords="1059,1051,1189,1077"/>
<area shape="rect" id="node11" href="../../de/df3/a00185.php" title="C++/Threadable.hpp" alt="" coords="237,901,379,928"/>
<area shape="rect" id="node12" href="../../d9/d77/a00095.php" title="C++/includes.hpp" alt="" coords="608,1200,733,1227"/>
<area shape="rect" id="node13" href="../../d9/dd0/a00191.php" title="C++/timeFunctions.hpp" alt="" coords="201,1275,359,1301"/>
<area shape="rect" id="node69" href="../../d1/d88/a00128.php" title="C++/NotCopyable.hpp" alt="" coords="383,1275,537,1301"/>
<area shape="rect" id="node15" href="../../db/dd9/a00179.php" title="C++/string.hpp" alt="" coords="279,1349,388,1376"/>
<area shape="rect" id="node17" href="../../d7/d25/a00182.php" title="C++/system.hpp" alt="" coords="205,1424,325,1451"/>
<area shape="rect" id="node66" href="../../d5/dcb/a00170.php" title="C++/RNG.hpp" alt="" coords="349,1424,456,1451"/>
<area shape="rect" id="node68" href="../../d4/d3a/a00101.php" title="C++/macro.hpp" alt="" coords="481,1424,594,1451"/>
<area shape="rect" id="node18" href="../../da/dec/a00080.php" title="C++/errors.hpp" alt="" coords="210,1499,321,1525"/>
<area shape="rect" id="node19" href="../../d5/de0/a00050.php" title="C++/console.hpp" alt="" coords="136,1573,259,1600"/>
<area shape="rect" id="node64" href="../../d2/d1f/a00083.php" title="C++/files.hpp" alt="" coords="283,1573,384,1600"/>
<area shape="rect" id="node20" href="../../d3/d8b/a00059.php" title="C++/convert.hpp" alt="" coords="147,1648,267,1675"/>
<area shape="rect" id="node22" href="../../da/d45/a00011.php" title="C++/array.hpp" alt="" coords="213,1723,320,1749"/>
<area shape="rect" id="node24" href="../../dd/d32/a00041.php" title="C++/check.hpp" alt="" coords="211,1797,323,1824"/>
<area shape="rect" id="node63" href="../../d7/d3f/a00173.php" title="C++/sorting.hpp" alt="" coords="361,1797,477,1824"/>
<area shape="rect" id="node28" href="../../d2/de7/a00014.php" title="C++/arraysIncludes.hpp" alt="" coords="408,1872,571,1899"/>
<area shape="rect" id="node57" href="../../d6/d2d/a00047.php" title="C++/collides.hpp" alt="" coords="262,1872,383,1899"/>
<area shape="rect" id="node35" href="../../d6/d7d/a00161.php" title="C++/pointers.hpp" alt="" coords="569,2245,692,2272"/>
<area shape="rect" id="node38" href="../../d3/db1/a00200.php" title="C++/types.hpp" alt="" coords="684,2320,793,2347"/>
<area shape="rect" id="node40" href="../../d4/d51/a00017.php" title="Big.hpp" alt="" coords="649,2395,716,2421"/>
<area shape="rect" id="node55" href="../../db/ddf/a00164.php" title="PureVirtual.hpp" alt="" coords="741,2395,851,2421"/>
<area shape="rect" id="node56" href="../../de/d79/a00203.php" title="UsefullDefines.hpp" alt="" coords="876,2395,1009,2421"/>
<area shape="rect" id="node51" href="../../d3/d52/a00023.php" title="C++/Big_Constructor.hpp" alt="" coords="975,2469,1145,2496"/>
<area shape="rect" id="node52" href="../../d5/d16/a00029.php" title="C++/Big_Operator.hpp" alt="" coords="1170,2469,1323,2496"/>
<area shape="rect" id="node53" href="../../db/db2/a00020.php" title="C++/Big_Comparison.hpp" alt="" coords="1348,2469,1521,2496"/>
<area shape="rect" id="node54" href="../../d6/d5b/a00026.php" title="C++/Big_Maths.hpp" alt="" coords="1545,2469,1684,2496"/>
<area shape="rect" id="node58" href="../../d4/d81/a00110.php" title="C++/Matrix.hpp" alt="" coords="86,1947,199,1973"/>
<area shape="rect" id="node59" href="../../da/d2a/a00086.php" title="C++/Fraction.hpp" alt="" coords="279,2021,403,2048"/>
<area shape="rect" id="node60" href="../../df/d98/a00107.php" title="C++/maths.hpp" alt="" coords="285,2096,398,2123"/>
<area shape="rect" id="node61" href="../../dc/d87/a00032.php" title="C++/Binary.hpp" alt="" coords="527,2171,641,2197"/>
<area shape="rect" id="node77" href="../../de/de1/a00065.php" title="C++/Date.hpp" alt="" coords="477,1125,582,1152"/>
<area shape="rect" id="node78" href="../../da/d15/a00188.php" title="C++/Time.hpp" alt="" coords="345,1125,452,1152"/>
<area shape="rect" id="node83" href="../../d7/dce/a00143.php" title="C++/PathfindingDijkstra.hpp" alt="" coords="851,901,1037,928"/>
<area shape="rect" id="node84" href="../../d2/df5/a00137.php" title="C++/Pathfinding.hpp" alt="" coords="877,976,1019,1003"/>
<area shape="rect" id="node85" href="../../da/d1e/a00149.php" title="C++/PathfindingProblem.hpp" alt="" coords="845,1051,1035,1077"/>
<area shape="rect" id="node86" href="../../d9/db6/a00146.php" title="C++/PathfindingException.hpp" alt="" coords="887,1125,1087,1152"/>
<area shape="rect" id="node87" href="../../de/d76/a00134.php" title="C++/Path.hpp" alt="" coords="759,1125,863,1152"/>
<area shape="rect" id="node92" href="../../d5/df1/a00206.php" title="C++/Vegetal.hpp" alt="" coords="237,304,358,331"/>
<area shape="rect" id="node93" href="../../d1/d09/a00077.php" title="C++/Entity.hpp" alt="" coords="371,453,482,480"/>
<area shape="rect" id="node96" href="../../d7/d46/a00002.php" title="C++/Animal.hpp" alt="" coords="383,304,500,331"/>
<area shape="rect" id="node97" href="../../db/dab/a00089.php" title="C++/Hostile.hpp" alt="" coords="367,379,486,405"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/db7/a00157.png" border="0" usemap="#Player_8hppdep" alt=""/></div>
<map name="Player_8hppdep" id="Player_8hppdep">
<area shape="rect" id="node2" href="../../d8/d41/a00038.php" title="C++Entities.hpp" alt="" coords="5,80,123,107"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d6/d36/a01011.php">mcd::Player&lt; PlayerParent &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A player that can be a child from any class.  <a href="../../d6/d36/a01011.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:d3/dd1/a00214"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d3/dd1/a00214.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : August, 17 2018 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d3/df8/a00155.php">Player.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
