<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: Player.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Apr 28 2019 10:54:58 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d8/d87/a00118.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">Player.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../df/d6a/a00119.php">C++/PlayerAbstraction.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/d3a/a00101.php">C++/Identifier.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Player.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/dc2/a00228.png" border="0" usemap="#Player_8hpp" alt=""/></div>
<map name="Player_8hpp" id="Player_8hpp">
<area shape="rect" id="node2" href="../../df/d6a/a00119.php" title="C++/PlayerAbstraction.hpp" alt="" coords="643,80,823,107"/>
<area shape="rect" id="node99" href="../../d4/d3a/a00101.php" title="C++/Identifier.hpp" alt="" coords="826,155,953,181"/>
<area shape="rect" id="node3" href="../../d9/df8/a00096.php" title="C++/Entities.hpp" alt="" coords="645,155,766,181"/>
<area shape="rect" id="node4" href="../../dc/dfe/a00125.php" title="C++/Stone.hpp" alt="" coords="778,229,889,256"/>
<area shape="rect" id="node92" href="../../d9/d4b/a00117.php" title="C++/Plant.hpp" alt="" coords="363,229,469,256"/>
<area shape="rect" id="node95" href="../../d1/dd6/a00108.php" title="C++/Mushroom.hpp" alt="" coords="493,229,632,256"/>
<area shape="rect" id="node96" href="../../d1/d6e/a00073.php" title="C++/Ant.hpp" alt="" coords="657,229,754,256"/>
<area shape="rect" id="node5" href="../../d4/d81/a00110.php" title="C++/Object.hpp" alt="" coords="775,379,889,405"/>
<area shape="rect" id="node6" href="../../d9/dec/a00090.php" title="C++/Contraption.hpp" alt="" coords="745,528,889,555"/>
<area shape="rect" id="node7" href="../../d2/d1f/a00083.php" title="C++/C++.hpp" alt="" coords="821,603,923,629"/>
<area shape="rect" id="node8" href="../../d1/dc1/a00092.php" title="C++/cryptage.hpp" alt="" coords="670,677,797,704"/>
<area shape="rect" id="node90" href="../../d5/deb/a00132.php" title="C++/Tree.hpp" alt="" coords="821,677,923,704"/>
<area shape="rect" id="node91" href="../../d7/d70/a00106.php" title="C++/Map.hpp" alt="" coords="947,677,1050,704"/>
<area shape="rect" id="node9" href="../../d9/d77/a00095.php" title="C++/defines.hpp" alt="" coords="813,752,931,779"/>
<area shape="rect" id="node10" href="../../d7/d06/a00131.php" title="C++/Timer.hpp" alt="" coords="49,827,159,853"/>
<area shape="rect" id="node71" href="../../d1/d09/a00077.php" title="C++/bdd.hpp" alt="" coords="476,827,575,853"/>
<area shape="rect" id="node76" href="../../db/db6/a00074.php" title="C++/Args.hpp" alt="" coords="293,827,397,853"/>
<area shape="rect" id="node77" href="../../dc/d54/a00094.php" title="C++/DateTime.hpp" alt="" coords="683,1051,818,1077"/>
<area shape="rect" id="node80" href="../../da/d2a/a00086.php" title="C++/Clock.hpp" alt="" coords="789,976,899,1003"/>
<area shape="rect" id="node81" href="../../db/dab/a00089.php" title="C++/ConsoleTable.hpp" alt="" coords="924,976,1081,1003"/>
<area shape="rect" id="node82" href="../../df/dc8/a00122.php" title="C++/Referenced.hpp" alt="" coords="987,1051,1131,1077"/>
<area shape="rect" id="node83" href="../../d3/d00/a00113.php" title="C++/PathfindingAlgorithms.hpp" alt="" coords="1157,827,1361,853"/>
<area shape="rect" id="node89" href="../../d5/d1e/a00103.php" title="C++/IOConfig.hpp" alt="" coords="1343,976,1473,1003"/>
<area shape="rect" id="node11" href="../../d1/d88/a00128.php" title="C++/Threadable.hpp" alt="" coords="5,901,147,928"/>
<area shape="rect" id="node12" href="../../d9/dcc/a00102.php" title="C++/includes.hpp" alt="" coords="887,1200,1012,1227"/>
<area shape="rect" id="node13" href="../../d6/db3/a00130.php" title="C++/timeFunctions.hpp" alt="" coords="479,1275,638,1301"/>
<area shape="rect" id="node65" href="../../dd/d42/a00109.php" title="C++/NotCopyable.hpp" alt="" coords="662,1275,815,1301"/>
<area shape="rect" id="node15" href="../../d7/d12/a00126.php" title="C++/string.hpp" alt="" coords="557,1349,667,1376"/>
<area shape="rect" id="node17" href="../../df/dcd/a00127.php" title="C++/system.hpp" alt="" coords="484,1424,604,1451"/>
<area shape="rect" id="node62" href="../../de/d36/a00123.php" title="C++/RNG.hpp" alt="" coords="628,1424,735,1451"/>
<area shape="rect" id="node64" href="../../d0/dc2/a00104.php" title="C++/macro.hpp" alt="" coords="759,1424,873,1451"/>
<area shape="rect" id="node18" href="../../d1/d44/a00098.php" title="C++/errors.hpp" alt="" coords="489,1499,599,1525"/>
<area shape="rect" id="node19" href="../../db/ddf/a00088.php" title="C++/console.hpp" alt="" coords="415,1573,537,1600"/>
<area shape="rect" id="node60" href="../../da/d74/a00099.php" title="C++/files.hpp" alt="" coords="561,1573,663,1600"/>
<area shape="rect" id="node20" href="../../da/d82/a00091.php" title="C++/convert.hpp" alt="" coords="425,1648,545,1675"/>
<area shape="rect" id="node22" href="../../d9/da5/a00075.php" title="C++/array.hpp" alt="" coords="492,1723,599,1749"/>
<area shape="rect" id="node24" href="../../df/d13/a00085.php" title="C++/check.hpp" alt="" coords="489,1797,601,1824"/>
<area shape="rect" id="node59" href="../../da/d72/a00124.php" title="C++/sorting.hpp" alt="" coords="695,1797,811,1824"/>
<area shape="rect" id="node28" href="../../db/df8/a00076.php" title="C++/arraysIncludes.hpp" alt="" coords="708,1872,871,1899"/>
<area shape="rect" id="node57" href="../../d1/d1e/a00087.php" title="C++/collides.hpp" alt="" coords="562,1872,683,1899"/>
<area shape="rect" id="node35" href="../../d4/d98/a00120.php" title="C++/pointers.hpp" alt="" coords="673,2021,796,2048"/>
<area shape="rect" id="node38" href="../../d0/de8/a00133.php" title="C++/types.hpp" alt="" coords="788,2096,897,2123"/>
<area shape="rect" id="node40" href="../../d9/da4/a00078.php" title="Big.hpp" alt="" coords="753,2171,820,2197"/>
<area shape="rect" id="node55" href="../../d8/dfa/a00121.php" title="PureVirtual.hpp" alt="" coords="845,2171,955,2197"/>
<area shape="rect" id="node56" href="../../de/d76/a00134.php" title="UsefullDefines.hpp" alt="" coords="980,2171,1113,2197"/>
<area shape="rect" id="node51" href="../../da/dec/a00080.php" title="C++/Big_Constructor.hpp" alt="" coords="1080,2245,1251,2272"/>
<area shape="rect" id="node52" href="../../d4/d63/a00082.php" title="C++/Big_Operator.hpp" alt="" coords="1275,2245,1429,2272"/>
<area shape="rect" id="node53" href="../../d1/d51/a00079.php" title="C++/Big_Comparison.hpp" alt="" coords="1453,2245,1627,2272"/>
<area shape="rect" id="node54" href="../../d8/d53/a00081.php" title="C++/Big_Maths.hpp" alt="" coords="1651,2245,1789,2272"/>
<area shape="rect" id="node58" href="../../df/d98/a00107.php" title="C++/maths.hpp" alt="" coords="387,1947,501,1973"/>
<area shape="rect" id="node78" href="../../d4/d7d/a00093.php" title="C++/Date.hpp" alt="" coords="755,1125,861,1152"/>
<area shape="rect" id="node79" href="../../d9/d47/a00129.php" title="C++/Time.hpp" alt="" coords="624,1125,731,1152"/>
<area shape="rect" id="node84" href="../../d8/d17/a00114.php" title="C++/PathfindingDijkstra.hpp" alt="" coords="1160,901,1347,928"/>
<area shape="rect" id="node85" href="../../db/d57/a00112.php" title="C++/Pathfinding.hpp" alt="" coords="1177,976,1319,1003"/>
<area shape="rect" id="node86" href="../../d4/d3e/a00116.php" title="C++/PathfindingProblem.hpp" alt="" coords="1155,1051,1346,1077"/>
<area shape="rect" id="node87" href="../../d2/da3/a00115.php" title="C++/PathfindingException.hpp" alt="" coords="1165,1125,1365,1152"/>
<area shape="rect" id="node88" href="../../dd/d6d/a00111.php" title="C++/Path.hpp" alt="" coords="1037,1125,1141,1152"/>
<area shape="rect" id="node93" href="../../d5/d5b/a00135.php" title="C++/Vegetal.hpp" alt="" coords="501,304,622,331"/>
<area shape="rect" id="node94" href="../../d1/d84/a00097.php" title="C++/Entity.hpp" alt="" coords="635,453,746,480"/>
<area shape="rect" id="node97" href="../../d6/d2c/a00072.php" title="C++/Animal.hpp" alt="" coords="647,304,764,331"/>
<area shape="rect" id="node98" href="../../d0/d61/a00100.php" title="C++/Hostile.hpp" alt="" coords="631,379,750,405"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/d2d/a00229.png" border="0" usemap="#Player_8hppdep" alt=""/></div>
<map name="Player_8hppdep" id="Player_8hppdep">
<area shape="rect" id="node2" href="../../df/d5d/a00084.php" title="C++Entities.hpp" alt="" coords="5,80,123,107"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php">mcd::Player&lt; PlayerParent &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A player that can be a child from any class.  <a href="../../d2/d79/a00051.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:dd/d1b/a00015"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : August, 17 2018 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d8/d87/a00118.php">Player.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
