<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: Contraption.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">1.6.2.3</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Mon Nov 16 2020 10:12:13 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('d0/d89/a00071.php','../../'); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">Contraption.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../dd/d32/a00041.php">C++.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Contraption.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d6/d2c/a00072.png" border="0" usemap="#aContraption_8hpp" alt=""/></div>
<map name="Contraption_8hpp" id="Contraption_8hpp">
<area shape="rect" title=" " alt="" coords="766,5,881,32"/>
<area shape="rect" href="../../dd/d32/a00041.php" title=" " alt="" coords="787,80,860,107"/>
<area shape="rect" href="../../d5/de0/a00050.php" title=" " alt="" coords="687,155,757,181"/>
<area shape="rect" href="../../d1/d88/a00128.php" title=" " alt="" coords="781,229,866,256"/>
<area shape="rect" href="../../d6/de1/a00233.php" title=" " alt="" coords="863,304,935,331"/>
<area shape="rect" href="../../d9/d2e/a00056.php" title=" " alt="" coords="631,229,757,256"/>
<area shape="rect" href="../../df/d98/a00107.php" title=" " alt="" coords="681,304,760,331"/>
<area shape="rect" href="../../d6/d2d/a00047.php" title=" " alt="" coords="780,379,867,405"/>
<area shape="rect" href="../../d4/d51/a00017.php" title=" " alt="" coords="643,453,729,480"/>
<area shape="rect" href="../../df/dc8/a00122.php" title=" " alt="" coords="786,453,861,480"/>
<area shape="rect" href="../../d1/d09/a00077.php" title=" " alt="" coords="915,528,1012,555"/>
<area shape="rect" href="../../db/db2/a00020.php" title=" " alt="" coords="573,528,733,555"/>
<area shape="rect" href="../../da/d2a/a00086.php" title=" " alt="" coords="779,603,868,629"/>
<area shape="rect" href="../../d6/d22/a00245.php" title=" " alt="" coords="532,677,611,704"/>
<area shape="rect" href="../../d4/dee/a00008.php" title=" " alt="" coords="635,677,710,704"/>
<area shape="rect" href="../../d3/d8b/a00059.php" title=" " alt="" coords="653,827,735,853"/>
<area shape="rect" href="../../da/d24/a00068.php" title=" " alt="" coords="681,901,808,928"/>
<area shape="rect" href="../../d2/d1f/a00083.php" title=" " alt="" coords="797,976,901,1003"/>
<area shape="rect" href="../../df/d6a/a00119.php" title=" " alt="" coords="886,752,985,779"/>
<area shape="rect" href="../../d5/db1/a00140.php" title=" " alt="" coords="999,677,1071,704"/>
<area shape="rect" href="../../dd/dc1/a00212.php" title=" " alt="" coords="1214,827,1329,853"/>
<area shape="rect" href="../../d7/d40/a00236.php" title=" " alt="" coords="535,752,645,779"/>
<area shape="rect" href="../../d4/d3e/a00116.php" title=" " alt="" coords="820,1125,915,1152"/>
<area shape="rect" href="../../dc/de6/a00167.php" title=" " alt="" coords="339,1200,462,1227"/>
<area shape="rect" href="../../d5/dcb/a00170.php" title=" " alt="" coords="487,1200,621,1227"/>
<area shape="rect" href="../../d2/dc8/a00242.php" title=" " alt="" coords="645,1200,775,1227"/>
<area shape="rect" title=" " alt="" coords="799,1200,861,1227"/>
<area shape="rect" title=" " alt="" coords="885,1200,924,1227"/>
<area shape="rect" title=" " alt="" coords="948,1200,1011,1227"/>
<area shape="rect" title=" " alt="" coords="1035,1200,1089,1227"/>
<area shape="rect" title=" " alt="" coords="1113,1200,1163,1227"/>
<area shape="rect" href="../../d9/d01/a00227.php" title="Used to replace strptime function when compiling for Windows." alt="" coords="623,1275,703,1301"/>
<area shape="rect" title=" " alt="" coords="728,1275,783,1301"/>
<area shape="rect" href="../../d5/ddf/a00224.php" title=" " alt="" coords="609,1349,718,1376"/>
<area shape="rect" title=" " alt="" coords="493,1424,549,1451"/>
<area shape="rect" href="../../d3/dd5/a00215.php" title=" " alt="" coords="573,1424,650,1451"/>
<area shape="rect" href="../../d2/df5/a00137.php" title=" " alt="" coords="674,1424,757,1451"/>
<area shape="rect" href="../../d1/da8/a00230.php" title=" " alt="" coords="781,1424,871,1451"/>
<area shape="rect" title=" " alt="" coords="579,1499,644,1525"/>
<area shape="rect" href="../../d9/d77/a00095.php" title=" " alt="" coords="786,1499,866,1525"/>
<area shape="rect" href="../../de/de1/a00065.php" title=" " alt="" coords="728,1573,820,1600"/>
<area shape="rect" href="../../d4/d3a/a00101.php" title=" " alt="" coords="844,1573,915,1600"/>
<area shape="rect" href="../../db/db6/a00074.php" title=" " alt="" coords="730,1648,821,1675"/>
<area shape="rect" title=" " alt="" coords="683,1723,766,1749"/>
<area shape="rect" href="../../da/d45/a00011.php" title=" " alt="" coords="790,1723,865,1749"/>
<area shape="rect" href="../../dc/dee/a00053.php" title=" " alt="" coords="841,1797,923,1824"/>
<area shape="rect" href="../../dc/d9a/a00218.php" title=" " alt="" coords="729,1797,816,1824"/>
<area shape="rect" href="../../df/d03/a00062.php" title=" " alt="" coords="1034,1872,1125,1899"/>
<area shape="rect" href="../../d9/d39/a00257.php" title=" " alt="" coords="731,1872,814,1899"/>
<area shape="rect" title=" " alt="" coords="845,1872,906,1899"/>
<area shape="rect" title=" " alt="" coords="930,1872,999,1899"/>
<area shape="rect" href="../../d9/db6/a00146.php" title=" " alt="" coords="1043,1947,1126,1973"/>
<area shape="rect" href="../../d0/dc2/a00104.php" title=" " alt="" coords="1180,2021,1275,2048"/>
<area shape="rect" href="../../d6/d7d/a00161.php" title=" " alt="" coords="1014,2021,1155,2048"/>
<area shape="rect" href="../../d7/dce/a00143.php" title=" " alt="" coords="1065,2096,1147,2123"/>
<area shape="rect" title=" " alt="" coords="1194,2096,1261,2123"/>
<area shape="rect" href="../../d8/d41/a00038.php" title=" " alt="" coords="1062,2171,1145,2197"/>
<area shape="rect" href="../../d5/df1/a00206.php" title=" " alt="" coords="701,2245,794,2272"/>
<area shape="rect" href="../../d3/d1a/a00251.php" title=" " alt="" coords="615,2320,693,2347"/>
<area shape="rect" title=" " alt="" coords="718,2320,777,2347"/>
<area shape="rect" title=" " alt="" coords="801,2320,859,2347"/>
<area shape="rect" href="../../d3/d52/a00023.php" title=" " alt="" coords="371,2395,438,2421"/>
<area shape="rect" href="../../d3/de5/a00209.php" title=" " alt="" coords="483,2395,593,2421"/>
<area shape="rect" href="../../dd/dd7/a00248.php" title=" " alt="" coords="617,2395,691,2421"/>
<area shape="rect" href="../../d7/d03/a00254.php" title=" " alt="" coords="715,2395,849,2421"/>
<area shape="rect" title=" " alt="" coords="873,2395,941,2421"/>
<area shape="rect" href="../../d7/d06/a00131.php" title=" " alt="" coords="618,2469,730,2496"/>
<area shape="rect" href="../../d6/d5b/a00026.php" title=" " alt="" coords="451,2469,593,2496"/>
<area shape="rect" href="../../d5/d16/a00029.php" title=" " alt="" coords="5,2469,145,2496"/>
<area shape="rect" href="../../dc/d87/a00032.php" title=" " alt="" coords="170,2469,279,2496"/>
<area shape="rect" href="../../d4/d8c/a00035.php" title=" " alt="" coords="303,2469,426,2496"/>
<area shape="rect" href="../../d5/de9/a00176.php" title=" " alt="" coords="614,2544,734,2571"/>
<area shape="rect" title=" " alt="" coords="583,2619,651,2645"/>
<area shape="rect" href="../../de/d76/a00134.php" title=" " alt="" coords="675,2619,791,2645"/>
<area shape="rect" title=" " alt="" coords="246,2693,321,2720"/>
<area shape="rect" title=" " alt="" coords="345,2693,403,2720"/>
<area shape="rect" title=" " alt="" coords="428,2693,507,2720"/>
<area shape="rect" title=" " alt="" coords="531,2693,603,2720"/>
<area shape="rect" title=" " alt="" coords="628,2693,675,2720"/>
<area shape="rect" title=" " alt="" coords="699,2693,767,2720"/>
<area shape="rect" title=" " alt="" coords="791,2693,845,2720"/>
<area shape="rect" title=" " alt="" coords="870,2693,939,2720"/>
<area shape="rect" title=" " alt="" coords="964,2693,1019,2720"/>
<area shape="rect" title=" " alt="" coords="1043,2693,1097,2720"/>
<area shape="rect" title=" " alt="" coords="1121,2693,1179,2720"/>
<area shape="rect" href="../../d1/d44/a00098.php" title=" " alt="" coords="937,2096,1040,2123"/>
<area shape="rect" title=" " alt="" coords="953,2171,1032,2197"/>
<area shape="rect" title=" " alt="" coords="851,2171,929,2197"/>
<area shape="rect" href="../../d2/de7/a00014.php" title=" " alt="" coords="700,1947,832,1973"/>
<area shape="rect" title=" " alt="" coords="449,2021,560,2048"/>
<area shape="rect" title=" " alt="" coords="585,2021,689,2048"/>
<area shape="rect" title=" " alt="" coords="713,2021,763,2048"/>
<area shape="rect" title=" " alt="" coords="788,2021,845,2048"/>
<area shape="rect" title=" " alt="" coords="870,2021,910,2048"/>
<area shape="rect" title=" " alt="" coords="935,2021,989,2048"/>
<area shape="rect" title=" " alt="" coords="846,1648,913,1675"/>
<area shape="rect" href="../../da/dec/a00080.php" title=" " alt="" coords="830,1051,905,1077"/>
<area shape="rect" href="../../d0/d27/a00239.php" title=" " alt="" coords="729,1051,805,1077"/>
<area shape="rect" href="../../de/df3/a00185.php" title=" " alt="" coords="1009,752,1184,779"/>
<area shape="rect" href="../../da/d15/a00188.php" title=" " alt="" coords="1018,827,1175,853"/>
<area shape="rect" href="../../d7/d25/a00182.php" title=" " alt="" coords="1041,901,1153,928"/>
<area shape="rect" href="../../dc/d57/a00194.php" title=" " alt="" coords="1017,976,1177,1003"/>
<area shape="rect" href="../../db/dd9/a00179.php" title=" " alt="" coords="1174,1051,1249,1077"/>
<area shape="rect" href="../../d9/dd0/a00191.php" title=" " alt="" coords="979,1051,1150,1077"/>
<area shape="rect" href="../../dc/dfe/a00125.php" title=" " alt="" coords="757,528,890,555"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d6e/a00073.png" border="0" usemap="#aContraption_8hppdep" alt=""/></div>
<map name="Contraption_8hppdep" id="Contraption_8hppdep">
<area shape="rect" title=" " alt="" coords="163,5,278,32"/>
<area shape="rect" href="../../d1/dc1/a00092.php" title=" " alt="" coords="128,80,207,107"/>
<area shape="rect" href="../../d7/d3f/a00173.php" title=" " alt="" coords="253,80,338,107"/>
<area shape="rect" href="../../d4/d81/a00110.php" title=" " alt="" coords="26,155,114,181"/>
<area shape="rect" href="../../dd/dd7/a00260.php" title=" " alt="" coords="122,229,213,256"/>
<area shape="rect" href="../../d7/d46/a00002.php" title=" " alt="" coords="5,229,92,256"/>
<area shape="rect" href="../../dd/dad/a00005.php" title=" " alt="" coords="10,304,77,331"/>
<area shape="rect" href="../../db/dab/a00089.php" title=" " alt="" coords="169,379,259,405"/>
<area shape="rect" href="../../de/d79/a00203.php" title=" " alt="" coords="139,453,289,480"/>
<area shape="rect" href="../../d3/db1/a00200.php" title=" " alt="" coords="173,528,255,555"/>
<area shape="rect" href="../../d5/df9/a00044.php" title=" " alt="" coords="155,603,273,629"/>
<area shape="rect" href="../../db/ddf/a00164.php" title=" " alt="" coords="101,304,209,331"/>
<area shape="rect" href="../../de/db1/a00197.php" title=" " alt="" coords="234,304,311,331"/>
<area shape="rect" href="../../dd/d52/a00221.php" title=" " alt="" coords="297,155,379,181"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d22/a01250.php">mcd::entities::Contraption</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A contraption.  <a href="../../d4/d22/a01250.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:db/d12/a00268"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/d12/a00268.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:d5/d42/a00269"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d42/a00269.php">mcd::entities</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : August, 17 2018 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_1788504ec76a4dda5464562bc560d0b5.php">C++Tests</a></li><li class="navelem"><a class="el" href="../../dir_2e741febc7df97747a68d36c1b3be5f0.php">C++</a></li><li class="navelem"><a class="el" href="../../dir_220287e732b97f08f66e5f221c69df74.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_75b0389167f46f79a101ef8c4434cec4.php">C++</a></li><li class="navelem"><a class="el" href="../../d0/d89/a00071.php">Contraption.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
