<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: Member List</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Fri Aug 17 2018 08:52:49 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.php"><span>Classes</span></a></li>
      <li><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="../../inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d1/d7c/a00003.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Animal Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../d1/d7c/a00003.php">Animal</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d52/a00023.php#af02c6d8b3c66c3a39bcc25834c056a13">_attacked</a></td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d52/a00023.php#a26c8c210acfd1799e332632291a5c7bf">_attackedSpec</a></td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a313bebfa2599d68722ade04f390b029d">_direction</a></td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a0d2501ac69dd25d63ed6639628363929">_movedD</a></td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a70befa3d7b85575b27a3fa276db9c53c">_movedL</a></td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#afa2426068213d1d292562a4c182ad532">_movedR</a></td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#ae7d422979c02938b0281af141105b90e">_movedU</a></td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#ab65c9d9be118c3db43e459ed9bf1a409">_obstacle</a></td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d52/a00023.php#a4240de82415d660b569700289d4ab229">_target</a></td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a6cbb52b9ef8ee0ffba677c79290da3a5">addPosition</a>(double64_t x, double64_t y, double64_t z=0)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a46fa459910827becd0cc0463f260d4e0">Animal</a>(Map *map=nullptr, Point pt={0, 0, 0}, ContraptionAttr attr={0, 0, 0})</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a3106b384960dd889ce599eed9d2b61d9">anyObstacle</a>()</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#aea47bc43468e85f59c2a9ff1a3e64887">attack</a>(Entity *target=nullptr)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#ad9fd8916f14ba954f4f98911e34a6d99">collides</a>(Contraption &amp;other)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#ade814dc70fcbf6685e6359420e7cf860">collides</a>(Contraption *other=nullptr)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a7c8528d1910eceb027dc77313ff04f82">collidesCircle</a>(Contraption &amp;other, double64_t radius)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a8fcfc90b1a8a95be2a412e3a16d06080">collidesCircle</a>(Contraption *other=nullptr, double64_t radius=0)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#aab6124c1e2241cf9491eb0dcc9c7d482">collidesRect</a>(Contraption &amp;other)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#ac5b0737fd290c4d632536c632bd57030">collidesRect</a>(Contraption *other=nullptr)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#ac80a221d48732cc349d5ccef1e4ad319">Contraption</a>(Map *map=nullptr, Point pt={0, 0, 0}, ContraptionAttr attr={0, 0, 0})</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a8eb01833b85eafedca05d504d7be006b">Entity</a>(Map *map=nullptr, Point pt={0, 0, 0}, ContraptionAttr attr={0, 0, 0})</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a8078072bd826e3494d66a82ebf21754e">getA</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a907885ca909c1ade2931811a7624e951">getAge</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a9993ab6cac0ce33ea91485965572cba9">getAttributes</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#ad0653e9bdc90c0ab8acef1be05efce3a">getDamages</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a29ad24536b14f4396ef9ca68351990b2">getFood</a>() const </td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a321c21c10a79de7d2e3db3ebb18d3112">getFoodMax</a>() const </td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a9719243bd6cfcc7b4aaea3aa1623d6c9">getH</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a3b6d4a5f2d520dfa5e58afe5b421a126">getLevel</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a843bba45a013ce45e4a649929f409b56">getLife</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#ab351874b4b68b1035be7957f6ed2e4e8">getLifeMax</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a3ca9a1e5aff93640d295576af62b7202">getMap</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#abc9cc2cd7e06c45e4c0edf96f405bae2">getPosition</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#adf095b7cd0850ad96bcbb1bb1cbe7b24">getReborn</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#ab2fc34a05a50d5d404929fa53a735f1a">getRegen</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#adc94897c67603ad2c6ce5c9ba0614c8a">getRelativeZ</a>(Contraption &amp;obj)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#ad0d3807f039d7c2fce9ae6722deec07f">getResistance</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#af7d494388300a7c6e47d0f0fb8bf6397">getSpecialAttack</a>() const </td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a49bb6b51a6d4213beaee878ca25075bc">getSpecies</a>() const </td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#aff675d03512504a49f4a0ddd7bb8c9e9">getSpeed</a>() const </td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d52/a00023.php#a6638a0b137f65027609f912855903de5">getStrength</a>() const </td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d52/a00023.php#ae9646e71bc0ee3240492aa98060e4942">getTarget</a>() const </td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#ac14585a9954f864b05bde1b7a2e0975d">getTimeActReborn</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#ac9685b66dbbba69d3c81f670fdd6baf9">getTimeActRegen</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a25d537178d3ac843cbd76503716b265c">getTimePrecReborn</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a1872def40f5d4ac2849fc882a1b7ba26">getTimePrecRegen</a>() const </td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a797f24e736a2d9fb49324219ce5ff493">getW</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a8e37d9aa83c5a7074a73b0629c92bca9">getX</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a384fbc78faf68407ed47efc23608801d">getY</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a9718691fe70bd1855414ccf74a23f995">getZ</a>() const </td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#acab06880e7336633b3d89bdbfbdbb4c8">goBot</a>()</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#aa260b234c8945347a33c1b35649bdf0b">goLeft</a>()</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#ac08f32231f137ed194a34b487b2f8db1">goRight</a>()</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#af284d102e5bc1de273df697bec76c2e8">goTop</a>()</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a0c839621027ac7ae02197923acd45fbd">grow</a>()</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a93315b1cb45e07b0dc90ef4ec0c9b841">hit</a>(double64_t damages)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d52/a00023.php#ab5ee3eebdea8943c1cb6ebd1b875bbf1">Hostile</a>()</td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d52/a00023.php#a7ad578b926f0be7cf84ee0f45665fa1f">hurt</a>(Entity *target=nullptr)</td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a07c40f873879cc72d0fc94a0831b955a">move</a>()</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a6e209ff2a9d0bf3a73d10baabadcb3b9">move</a>(Direction dir)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a1a3cd3d34d5b78e1e5cda26d9851969f">printInfos</a>(std::ostream &amp;stream) const override</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#aac3b312b278f4e56cd4806ec3b8b1760">sender</a>(std::string, vector_str)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#adc32e0091645e3ff58587b3915680d81">setA</a>(double64_t angle)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#ae056e9174c2d1ee5951a563c768a464e">setAge</a>(double64_t age)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a3e221cb1cdd414d2d06492b575ec7120">setAttributes</a>(ContraptionAttr attr)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a6f32609c67a5031667bca0160cc3c4b0">setAttributes</a>(double64_t w, double64_t h, double64_t angle=0)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#aeb718662f5c4e3437abe9ae0fd587ec2">setDamages</a>(double64_t damages)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a720eeec8fd6c5b657841eba6c3c6a0ed">setFood</a>(const double64_t food)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#ad1e0e8a5c102b2bd95f0c133eec09a89">setFoodMax</a>(const double64_t foodMax)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a7efde486fe106d3878755b9db1127d88">setH</a>(double64_t h)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#ae9131d3133c67c22f8692d4bd806187e">setLevel</a>(size_t level)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#ae705f808d00581dbd148d7d0a2015f0f">setLife</a>(double64_t life)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a0d88e87317d6f003471fcf52808a4a25">setMap</a>(Map *map)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a05facc668dcb27c1bab72118aa5bafe7">setPosition</a>(Point pt)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a4bfbd30624b084959f42291f2702a723">setPosition</a>(double64_t x, double64_t y, double64_t z=0)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a8b9e1b5c58f90b500b38831ea31097d6">setReborn</a>(const double64_t reborn)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a70109aa6875a5fec64dac1c3dd16fc57">setRegen</a>(const double64_t regen)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#ad9df076222196073068633c61793e179">setResistance</a>(double64_t resistance)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#acd3a1a440f7f4f0553235f0ed106b7f8">setSpecialAttack</a>(const std::string specialAttack)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#aacbfd4edeec5da6823f8f64d615aa23e">setSpecies</a>(const std::string species)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a3bf3dd87882f3422298ccfb32f2a12f1">setSpeed</a>(double64_t speed)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d52/a00023.php#ad73dc2a20264e3fe8d51d5263c8e3722">setStrength</a>(double64_t strength)</td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d52/a00023.php#ab2f44509aba02128b145f53b45ae3d6e">setTarget</a>(Entity *target)</td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a8a1ca1cc53f552ae915d5b1231de314b">setTimeActReborn</a>(const double64_t time)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a088f9230879d772e7872041c451f5dba">setTimeActRegen</a>(const double64_t time)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a4c4e2d9aa3604323ed24e1411c0dec8c">setTimePrecReborn</a>(const double64_t time)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a40f87ea4a2290bed71e15b318123008d">setTimePrecRegen</a>(const double64_t time)</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a1102b32324b755d0fa4ed68a4fbbff72">setW</a>(double64_t w)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a33238305b6740a899553d139d2c6f522">setX</a>(double64_t x)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a42e1a00e1ad5acaa84121a8e86cd4d02">setY</a>(double64_t y)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#ad6f7d1d6ad29714e30947ca89a4812a0">setZ</a>(double64_t z)</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a1500edfc376853144d9390429134dc63">turn</a>(double64_t na)</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#ab69fdcd66f63e0a038a4006d43ecb9b6">turnLeft</a>()</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d2/de7/a00014.php#a20f271c846ea0c8bc96c618616a260ba">turnRight</a>()</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d52/a00023.php#a4b91ff7920ded02f9662134608f11d6f">untarget</a>()</td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d1/d7c/a00003.php#a16d8b7f94611cc65f5cdb58cc105527b">~Animal</a>()</td><td class="entry"><a class="el" href="../../d1/d7c/a00003.php">Animal</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d2/de7/a00014.php#acfdea93e7835722a3b211ba2b8dd1463">~Contraption</a>()</td><td class="entry"><a class="el" href="../../d2/de7/a00014.php">Contraption</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../dd/da2/a00019.php#a588098978eea6a3486b7361605ff3f0f">~Entity</a>()</td><td class="entry"><a class="el" href="../../dd/da2/a00019.php">Entity</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d52/a00023.php#af1c3ba743ce0c9b50d501fb86f4127f8">~Hostile</a>()</td><td class="entry"><a class="el" href="../../d3/d52/a00023.php">Hostile</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
