<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.11"/>
		<title>C++: Map.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Sun Apr 28 2019 10:54:58 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="../../pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="../../namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="../../annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="../../files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../files.php"><span>File&#160;List</span></a></li>
      <li><a href="../../globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d7/d70/a00106.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a> &#124;
<a href="#typedef-members">Typedefs</a> &#124;
<a href="#enum-members">Enumerations</a>  </div>
  <div class="headertitle">
<div class="title">Map.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d9/d77/a00095.php">C++/defines.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Map.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/d13/a00205.png" border="0" usemap="#Map_8hpp" alt=""/></div>
<map name="Map_8hpp" id="Map_8hpp">
<area shape="rect" id="node2" href="../../d9/d77/a00095.php" title="C++/defines.hpp" alt="" coords="813,80,931,107"/>
<area shape="rect" id="node3" href="../../d7/d06/a00131.php" title="C++/Timer.hpp" alt="" coords="49,155,159,181"/>
<area shape="rect" id="node64" href="../../d1/d09/a00077.php" title="C++/bdd.hpp" alt="" coords="476,155,575,181"/>
<area shape="rect" id="node69" href="../../db/db6/a00074.php" title="C++/Args.hpp" alt="" coords="293,155,397,181"/>
<area shape="rect" id="node70" href="../../dc/d54/a00094.php" title="C++/DateTime.hpp" alt="" coords="683,379,818,405"/>
<area shape="rect" id="node73" href="../../da/d2a/a00086.php" title="C++/Clock.hpp" alt="" coords="789,304,899,331"/>
<area shape="rect" id="node74" href="../../db/dab/a00089.php" title="C++/ConsoleTable.hpp" alt="" coords="924,304,1081,331"/>
<area shape="rect" id="node75" href="../../df/dc8/a00122.php" title="C++/Referenced.hpp" alt="" coords="989,379,1133,405"/>
<area shape="rect" id="node76" href="../../d3/d00/a00113.php" title="C++/PathfindingAlgorithms.hpp" alt="" coords="1157,155,1361,181"/>
<area shape="rect" id="node82" href="../../d5/d1e/a00103.php" title="C++/IOConfig.hpp" alt="" coords="1346,304,1475,331"/>
<area shape="rect" id="node4" href="../../d1/d88/a00128.php" title="C++/Threadable.hpp" alt="" coords="5,229,147,256"/>
<area shape="rect" id="node5" href="../../d9/dcc/a00102.php" title="C++/includes.hpp" alt="" coords="889,528,1015,555"/>
<area shape="rect" id="node6" href="../../d6/db3/a00130.php" title="C++/timeFunctions.hpp" alt="" coords="482,603,641,629"/>
<area shape="rect" id="node58" href="../../dd/d42/a00109.php" title="C++/NotCopyable.hpp" alt="" coords="665,603,818,629"/>
<area shape="rect" id="node8" href="../../d7/d12/a00126.php" title="C++/string.hpp" alt="" coords="560,677,669,704"/>
<area shape="rect" id="node10" href="../../df/dcd/a00127.php" title="C++/system.hpp" alt="" coords="487,752,607,779"/>
<area shape="rect" id="node55" href="../../de/d36/a00123.php" title="C++/RNG.hpp" alt="" coords="631,752,737,779"/>
<area shape="rect" id="node57" href="../../d0/dc2/a00104.php" title="C++/macro.hpp" alt="" coords="762,752,875,779"/>
<area shape="rect" id="node11" href="../../d1/d44/a00098.php" title="C++/errors.hpp" alt="" coords="491,827,602,853"/>
<area shape="rect" id="node12" href="../../db/ddf/a00088.php" title="C++/console.hpp" alt="" coords="417,901,540,928"/>
<area shape="rect" id="node53" href="../../da/d74/a00099.php" title="C++/files.hpp" alt="" coords="564,901,665,928"/>
<area shape="rect" id="node13" href="../../da/d82/a00091.php" title="C++/convert.hpp" alt="" coords="428,976,548,1003"/>
<area shape="rect" id="node15" href="../../d9/da5/a00075.php" title="C++/array.hpp" alt="" coords="495,1051,601,1077"/>
<area shape="rect" id="node17" href="../../df/d13/a00085.php" title="C++/check.hpp" alt="" coords="492,1125,604,1152"/>
<area shape="rect" id="node52" href="../../da/d72/a00124.php" title="C++/sorting.hpp" alt="" coords="698,1125,814,1152"/>
<area shape="rect" id="node21" href="../../db/df8/a00076.php" title="C++/arraysIncludes.hpp" alt="" coords="711,1200,873,1227"/>
<area shape="rect" id="node50" href="../../d1/d1e/a00087.php" title="C++/collides.hpp" alt="" coords="565,1200,686,1227"/>
<area shape="rect" id="node28" href="../../d4/d98/a00120.php" title="C++/pointers.hpp" alt="" coords="676,1349,799,1376"/>
<area shape="rect" id="node31" href="../../d0/de8/a00133.php" title="C++/types.hpp" alt="" coords="791,1424,900,1451"/>
<area shape="rect" id="node33" href="../../d9/da4/a00078.php" title="Big.hpp" alt="" coords="756,1499,823,1525"/>
<area shape="rect" id="node48" href="../../d8/dfa/a00121.php" title="PureVirtual.hpp" alt="" coords="847,1499,958,1525"/>
<area shape="rect" id="node49" href="../../de/d76/a00134.php" title="UsefullDefines.hpp" alt="" coords="983,1499,1116,1525"/>
<area shape="rect" id="node44" href="../../da/dec/a00080.php" title="C++/Big_Constructor.hpp" alt="" coords="1083,1573,1253,1600"/>
<area shape="rect" id="node45" href="../../d4/d63/a00082.php" title="C++/Big_Operator.hpp" alt="" coords="1278,1573,1431,1600"/>
<area shape="rect" id="node46" href="../../d1/d51/a00079.php" title="C++/Big_Comparison.hpp" alt="" coords="1456,1573,1629,1600"/>
<area shape="rect" id="node47" href="../../d8/d53/a00081.php" title="C++/Big_Maths.hpp" alt="" coords="1653,1573,1792,1600"/>
<area shape="rect" id="node51" href="../../df/d98/a00107.php" title="C++/maths.hpp" alt="" coords="390,1275,503,1301"/>
<area shape="rect" id="node71" href="../../d4/d7d/a00093.php" title="C++/Date.hpp" alt="" coords="758,453,863,480"/>
<area shape="rect" id="node72" href="../../d9/d47/a00129.php" title="C++/Time.hpp" alt="" coords="627,453,733,480"/>
<area shape="rect" id="node77" href="../../d8/d17/a00114.php" title="C++/PathfindingDijkstra.hpp" alt="" coords="1161,229,1348,256"/>
<area shape="rect" id="node78" href="../../db/d57/a00112.php" title="C++/Pathfinding.hpp" alt="" coords="1179,304,1322,331"/>
<area shape="rect" id="node79" href="../../d4/d3e/a00116.php" title="C++/PathfindingProblem.hpp" alt="" coords="1158,379,1349,405"/>
<area shape="rect" id="node80" href="../../d2/da3/a00115.php" title="C++/PathfindingException.hpp" alt="" coords="1168,453,1368,480"/>
<area shape="rect" id="node81" href="../../dd/d6d/a00111.php" title="C++/Path.hpp" alt="" coords="1040,453,1144,480"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/df1/a00206.png" border="0" usemap="#Map_8hppdep" alt=""/></div>
<map name="Map_8hppdep" id="Map_8hppdep">
<area shape="rect" id="node2" href="../../d2/d1f/a00083.php" title="C++.hpp" alt="" coords="310,80,383,107"/>
<area shape="rect" id="node3" href="../../d9/dec/a00090.php" title="Contraption.hpp" alt="" coords="243,155,357,181"/>
<area shape="rect" id="node17" href="../../d4/d3a/a00101.php" title="Identifier.hpp" alt="" coords="342,528,439,555"/>
<area shape="rect" id="node4" href="../../d1/d84/a00097.php" title="Entity.hpp" alt="" coords="135,229,217,256"/>
<area shape="rect" id="node15" href="../../d4/d81/a00110.php" title="Object.hpp" alt="" coords="265,229,351,256"/>
<area shape="rect" id="node5" href="../../d0/d61/a00100.php" title="Hostile.hpp" alt="" coords="23,304,111,331"/>
<area shape="rect" id="node12" href="../../d5/d5b/a00135.php" title="Vegetal.hpp" alt="" coords="131,379,221,405"/>
<area shape="rect" id="node6" href="../../d6/d2c/a00072.php" title="Animal.hpp" alt="" coords="7,379,94,405"/>
<area shape="rect" id="node7" href="../../d1/d6e/a00073.php" title="Ant.hpp" alt="" coords="5,453,72,480"/>
<area shape="rect" id="node8" href="../../d9/df8/a00096.php" title="Entities.hpp" alt="" coords="223,528,313,555"/>
<area shape="rect" id="node9" href="../../df/d6a/a00119.php" title="PlayerAbstraction.hpp" alt="" coords="197,603,347,629"/>
<area shape="rect" id="node10" href="../../d8/d87/a00118.php" title="Player.hpp" alt="" coords="287,677,371,704"/>
<area shape="rect" id="node11" href="../../df/d5d/a00084.php" title="C++Entities.hpp" alt="" coords="271,752,388,779"/>
<area shape="rect" id="node13" href="../../d1/dd6/a00108.php" title="Mushroom.hpp" alt="" coords="97,453,205,480"/>
<area shape="rect" id="node14" href="../../d9/d4b/a00117.php" title="Plant.hpp" alt="" coords="229,453,307,480"/>
<area shape="rect" id="node16" href="../../dc/dfe/a00125.php" title="Stone.hpp" alt="" coords="271,304,353,331"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:d7/dce/a00143"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#d7/dce/a00143">mcd::WorldDimensions</a></td></tr>
<tr class="memdesc:d7/dce/a00143"><td class="mdescLeft">&#160;</td><td class="mdescRight">An object to group the dimensions of the world.  <a href="../../dd/d1b/a00015.php#d7/dce/a00143">More...</a><br /></td></tr>
<tr class="separator:d7/dce/a00143"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:de/d14/a00139"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#de/d14/a00139">mcd::MapMove</a></td></tr>
<tr class="memdesc:de/d14/a00139"><td class="mdescLeft">&#160;</td><td class="mdescRight">A struct to know informations about th movement of something in the map.  <a href="../../dd/d1b/a00015.php#de/d14/a00139">More...</a><br /></td></tr>
<tr class="separator:de/d14/a00139"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d3/de7/a00039.php">mcd::Map</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A class to manage a map and that implement some pathfinding algorithms.  <a href="../../d3/de7/a00039.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:dd/d1b/a00015"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="typedef-members"></a>
Typedefs</h2></td></tr>
<tr class="memitem:a626eae05d907e09e182c9772e1aa04e6"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a626eae05d907e09e182c9772e1aa04e6">mcd::MapLine</a> = std::vector&lt; Tile &gt;</td></tr>
<tr class="separator:a626eae05d907e09e182c9772e1aa04e6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4da80d0816a366662f2bd5bd8740af79"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a4da80d0816a366662f2bd5bd8740af79">mcd::MapArray</a> = std::vector&lt; MapLine &gt;</td></tr>
<tr class="separator:a4da80d0816a366662f2bd5bd8740af79"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="enum-members"></a>
Enumerations</h2></td></tr>
<tr class="memitem:a7350be9df9566241dfb80071a89f9ede"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dd/d1b/a00015.php#a7350be9df9566241dfb80071a89f9ede">mcd::Tile</a> { <a class="el" href="../../dd/d1b/a00015.php#ae3ee27656d8eb6e8a09407841cd00898ab50339a10e1de285ac99d4c3990b8693">mcd::NONE</a> = 0, 
<a class="el" href="../../dd/d1b/a00015.php#a7350be9df9566241dfb80071a89f9edea2399122c182da0d5946e2937bb73edf2">mcd::Tile::OBSTACLE</a>, 
<a class="el" href="../../dd/d1b/a00015.php#a7350be9df9566241dfb80071a89f9edeadedcb56e75fe1488e20865e0ea36d0b9">mcd::Tile::GROUND</a>, 
<a class="el" href="../../dd/d1b/a00015.php#a7350be9df9566241dfb80071a89f9edeabb1ca97ec761fc37101737ba0aa2e7c5">mcd::Tile::ERROR</a>
 }<tr class="memdesc:a7350be9df9566241dfb80071a89f9ede"><td class="mdescLeft">&#160;</td><td class="mdescRight">Tiles of the map.  <a href="../../dd/d1b/a00015.php#a7350be9df9566241dfb80071a89f9ede">More...</a><br /></td></tr>
</td></tr>
<tr class="separator:a7350be9df9566241dfb80071a89f9ede"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Created : July, 29 2018 14:27:51 </dd>
<dd>
Last modification : August, 16 2018 </dd></dl>
</div><hr/><h2 class="groupheader">Class Documentation</h2>
<a name="d7/dce/a00143" id="d7/dce/a00143"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">struct mcd::WorldDimensions</td>
        </tr>
      </table>
</div><div class="memdoc">
<div class="textblock"><p>An object to group the dimensions of the world. </p>
</div><table class="fieldtable">
<tr><th colspan="3">Class Members</th></tr>
<tr><td class="fieldtype">
<a class="anchor" id="abe35d460277b28d79aa0261fd58b89da"></a>size_t</td>
<td class="fieldname">
h</td>
<td class="fielddoc">
</td></tr>
<tr><td class="fieldtype">
<a class="anchor" id="a5e12726e58baa05036bc160c31d08016"></a>size_t</td>
<td class="fieldname">
w</td>
<td class="fielddoc">
</td></tr>
<tr><td class="fieldtype">
<a class="anchor" id="a6e818e561922fa511658e15bec5fa55d"></a>size_t</td>
<td class="fieldname">
z</td>
<td class="fielddoc">
</td></tr>
</table>

</div>
</div>
<a name="de/d14/a00139" id="de/d14/a00139"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">struct mcd::MapMove</td>
        </tr>
      </table>
</div><div class="memdoc">
<div class="textblock"><p>A struct to know informations about th movement of something in the map. </p>
</div><table class="fieldtable">
<tr><th colspan="3">Class Members</th></tr>
<tr><td class="fieldtype">
<a class="anchor" id="a2f707d77cfeffb93eceecea7c25a7cc6"></a>bool</td>
<td class="fieldname">
end</td>
<td class="fielddoc">
</td></tr>
<tr><td class="fieldtype">
<a class="anchor" id="a61ee478b9a87acbd0fb2299f867a1bea"></a>bool</td>
<td class="fieldname">
next</td>
<td class="fielddoc">
</td></tr>
</table>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d7/d70/a00106.php">Map.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
