<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.20"/>
		<title>C++: Member List</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">4.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Tue Oct 27 2020 18:49:23 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(document).ready(function(){initNavTree('d9/de6/a01314.php','../../'); initResizable(); });
/* @license-end */
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">mcd::Logger Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a25d94050e8e7f91c7e1f02ddc2af8e95ad58a475f585716dda86e2e0af0570cec">All</a> enum value</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a25d94050e8e7f91c7e1f02ddc2af8e95a8a3e3b4dccd41544fac18f0f339ba68e">Debug</a> enum value</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a25d94050e8e7f91c7e1f02ddc2af8e95a98b026269a3081d4a4801bc7418e1d47">Error</a> enum value</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a25d94050e8e7f91c7e1f02ddc2af8e95a3b0278ed2e63ab59b05883c3943c73cf">Fatal</a> enum value</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a25d94050e8e7f91c7e1f02ddc2af8e95ae7888eab8f157c2bc53e24557f2a8458">Info</a> enum value</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d9/de6/a01314.php#ab549f25e73c47afaff922b59cda6ccc4">init</a>(const std::string &amp;logConfigFile)</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a365030ec32e6af40c6c53a53ff5163f4">isEnabled</a>(Level level)</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d9/de6/a01314.php#ad8527d935f1fa6c697d792a8f72276e4">isInit</a>() const</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a25d94050e8e7f91c7e1f02ddc2af8e95">Level</a> enum name</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a2cb99172e98a89e45fdcb9b394eea99e">log</a>(Level level, int line, const std::string &amp;file, Args... args)</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a189cdd6486b23632d014a2e795ed8e13">Logger</a>()</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a25d94050e8e7f91c7e1f02ddc2af8e95a0bab71bd19d6bf8a3e85aaf73e41814a">Off</a> enum value</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a9351097884f74c914c92bd982e70d159">reset</a>(std::string file, int line)</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a25d94050e8e7f91c7e1f02ddc2af8e95a97b60120ff602c7d5050124927962f79">Warn</a> enum value</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/de6/a01314.php#a9b43e0ba2ab53c8a6758b20d3f828f96">~Logger</a>()</td><td class="entry"><a class="el" href="../../d9/de6/a01314.php">mcd::Logger</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
