<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: Stone.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Thu Sep 26 2019 21:18:11 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/de9/a00176.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">Stone.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../d7/d06/a00131.php">C++/Object.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Stone.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/d4c/a00177.png" border="0" usemap="#Stone_8hpp" alt=""/></div>
<map name="Stone_8hpp" id="Stone_8hpp">
<area shape="rect" id="node2" href="../../d7/d06/a00131.php" title="C++/Object.hpp" alt="" coords="551,80,665,107"/>
<area shape="rect" id="node3" href="../../d9/d2e/a00056.php" title="C++/Contraption.hpp" alt="" coords="536,155,680,181"/>
<area shape="rect" id="node4" href="../../d4/d8c/a00035.php" title="C++/C++.hpp" alt="" coords="557,229,659,256"/>
<area shape="rect" id="node5" href="../../df/d03/a00062.php" title="C++/cryptage.hpp" alt="" coords="406,304,533,331"/>
<area shape="rect" id="node86" href="../../de/db1/a00197.php" title="C++/Tree.hpp" alt="" coords="557,304,659,331"/>
<area shape="rect" id="node87" href="../../d0/dc2/a00104.php" title="C++/Map.hpp" alt="" coords="683,304,786,331"/>
<area shape="rect" id="node6" href="../../d0/d89/a00071.php" title="C++/defines.hpp" alt="" coords="549,379,667,405"/>
<area shape="rect" id="node7" href="../../dc/d57/a00194.php" title="C++/Timer.hpp" alt="" coords="207,453,318,480"/>
<area shape="rect" id="node72" href="../../d4/dee/a00008.php" title="C++/Args.hpp" alt="" coords="343,453,447,480"/>
<area shape="rect" id="node73" href="../../da/d24/a00068.php" title="C++/DateTime.hpp" alt="" coords="417,677,551,704"/>
<area shape="rect" id="node76" href="../../d5/df9/a00044.php" title="C++/Clock.hpp" alt="" coords="522,603,633,629"/>
<area shape="rect" id="node77" href="../../dc/dee/a00053.php" title="C++/ConsoleTable.hpp" alt="" coords="588,528,745,555"/>
<area shape="rect" id="node78" href="../../dc/de6/a00167.php" title="C++/Referenced.hpp" alt="" coords="708,603,852,629"/>
<area shape="rect" id="node79" href="../../d5/db1/a00140.php" title="C++/PathfindingAlgorithms.hpp" alt="" coords="825,453,1029,480"/>
<area shape="rect" id="node85" href="../../d1/d44/a00098.php" title="C++/IOConfig.hpp" alt="" coords="1059,677,1189,704"/>
<area shape="rect" id="node8" href="../../de/df3/a00185.php" title="C++/Threadable.hpp" alt="" coords="237,528,379,555"/>
<area shape="rect" id="node9" href="../../d9/d77/a00095.php" title="C++/includes.hpp" alt="" coords="608,827,733,853"/>
<area shape="rect" id="node10" href="../../d9/dd0/a00191.php" title="C++/timeFunctions.hpp" alt="" coords="201,901,359,928"/>
<area shape="rect" id="node66" href="../../d1/d88/a00128.php" title="C++/NotCopyable.hpp" alt="" coords="383,901,537,928"/>
<area shape="rect" id="node12" href="../../db/dd9/a00179.php" title="C++/string.hpp" alt="" coords="279,976,388,1003"/>
<area shape="rect" id="node14" href="../../d7/d25/a00182.php" title="C++/system.hpp" alt="" coords="205,1051,325,1077"/>
<area shape="rect" id="node63" href="../../d5/dcb/a00170.php" title="C++/RNG.hpp" alt="" coords="349,1051,456,1077"/>
<area shape="rect" id="node65" href="../../d4/d3a/a00101.php" title="C++/macro.hpp" alt="" coords="481,1051,594,1077"/>
<area shape="rect" id="node15" href="../../da/dec/a00080.php" title="C++/errors.hpp" alt="" coords="210,1125,321,1152"/>
<area shape="rect" id="node16" href="../../d5/de0/a00050.php" title="C++/console.hpp" alt="" coords="136,1200,259,1227"/>
<area shape="rect" id="node61" href="../../d2/d1f/a00083.php" title="C++/files.hpp" alt="" coords="283,1200,384,1227"/>
<area shape="rect" id="node17" href="../../d3/d8b/a00059.php" title="C++/convert.hpp" alt="" coords="147,1275,267,1301"/>
<area shape="rect" id="node19" href="../../da/d45/a00011.php" title="C++/array.hpp" alt="" coords="213,1349,320,1376"/>
<area shape="rect" id="node21" href="../../dd/d32/a00041.php" title="C++/check.hpp" alt="" coords="211,1424,323,1451"/>
<area shape="rect" id="node60" href="../../d7/d3f/a00173.php" title="C++/sorting.hpp" alt="" coords="390,1424,506,1451"/>
<area shape="rect" id="node25" href="../../d2/de7/a00014.php" title="C++/arraysIncludes.hpp" alt="" coords="408,1499,571,1525"/>
<area shape="rect" id="node54" href="../../d6/d2d/a00047.php" title="C++/collides.hpp" alt="" coords="262,1499,383,1525"/>
<area shape="rect" id="node32" href="../../d6/d7d/a00161.php" title="C++/pointers.hpp" alt="" coords="569,1872,692,1899"/>
<area shape="rect" id="node35" href="../../d3/db1/a00200.php" title="C++/types.hpp" alt="" coords="684,1947,793,1973"/>
<area shape="rect" id="node37" href="../../d4/d51/a00017.php" title="Big.hpp" alt="" coords="648,2021,715,2048"/>
<area shape="rect" id="node52" href="../../db/ddf/a00164.php" title="PureVirtual.hpp" alt="" coords="739,2021,850,2048"/>
<area shape="rect" id="node53" href="../../de/d79/a00203.php" title="UsefullDefines.hpp" alt="" coords="875,2021,1008,2048"/>
<area shape="rect" id="node48" href="../../d3/d52/a00023.php" title="C++/Big_Constructor.hpp" alt="" coords="975,2096,1145,2123"/>
<area shape="rect" id="node49" href="../../d5/d16/a00029.php" title="C++/Big_Operator.hpp" alt="" coords="1170,2096,1323,2123"/>
<area shape="rect" id="node50" href="../../db/db2/a00020.php" title="C++/Big_Comparison.hpp" alt="" coords="1348,2096,1521,2123"/>
<area shape="rect" id="node51" href="../../d6/d5b/a00026.php" title="C++/Big_Maths.hpp" alt="" coords="1545,2096,1684,2123"/>
<area shape="rect" id="node55" href="../../d4/d81/a00110.php" title="C++/Matrix.hpp" alt="" coords="86,1573,199,1600"/>
<area shape="rect" id="node56" href="../../da/d2a/a00086.php" title="C++/Fraction.hpp" alt="" coords="279,1648,403,1675"/>
<area shape="rect" id="node57" href="../../df/d98/a00107.php" title="C++/maths.hpp" alt="" coords="285,1723,398,1749"/>
<area shape="rect" id="node58" href="../../dc/d87/a00032.php" title="C++/Binary.hpp" alt="" coords="527,1797,641,1824"/>
<area shape="rect" id="node74" href="../../de/de1/a00065.php" title="C++/Date.hpp" alt="" coords="477,752,582,779"/>
<area shape="rect" id="node75" href="../../da/d15/a00188.php" title="C++/Time.hpp" alt="" coords="345,752,452,779"/>
<area shape="rect" id="node80" href="../../d7/dce/a00143.php" title="C++/PathfindingDijkstra.hpp" alt="" coords="844,528,1031,555"/>
<area shape="rect" id="node81" href="../../d2/df5/a00137.php" title="C++/Pathfinding.hpp" alt="" coords="877,603,1019,629"/>
<area shape="rect" id="node82" href="../../da/d1e/a00149.php" title="C++/PathfindingProblem.hpp" alt="" coords="845,677,1035,704"/>
<area shape="rect" id="node83" href="../../d9/db6/a00146.php" title="C++/PathfindingException.hpp" alt="" coords="887,752,1087,779"/>
<area shape="rect" id="node84" href="../../de/d76/a00134.php" title="C++/Path.hpp" alt="" coords="759,752,863,779"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d90/a00178.png" border="0" usemap="#Stone_8hppdep" alt=""/></div>
<map name="Stone_8hppdep" id="Stone_8hppdep">
<area shape="rect" id="node2" href="../../db/db6/a00074.php" title="Entities.hpp" alt="" coords="35,80,126,107"/>
<area shape="rect" id="node3" href="../../d6/db8/a00158.php" title="PlayerAbstraction.hpp" alt="" coords="5,155,156,181"/>
<area shape="rect" id="node4" href="../../d3/df8/a00155.php" title="Player.hpp" alt="" coords="39,229,123,256"/>
<area shape="rect" id="node5" href="../../d8/d41/a00038.php" title="C++Entities.hpp" alt="" coords="22,304,139,331"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d21/a01039.php">mcd::Stone</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A stone.  <a href="../../df/d21/a01039.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:d3/dd1/a00214"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d3/dd1/a00214.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : August, 17 2018 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d5/de9/a00176.php">Stone.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
