<!-- HTML header for doxygen 1.8.11-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
		<meta name="generator" content="Doxygen 1.8.13"/>
		<title>C++: PlayerAbstraction.hpp File Reference</title>
		<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="../../jquery.js"></script>
		<script type="text/javascript" src="../../dynsections.js"></script>
		<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
		<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
		<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
		<link href="../../doxystyle.css" rel="stylesheet" type="text/css"/>
	</head>
	<body>
		<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
			<div id="titlearea">
				<table cellspacing="0" cellpadding="0">
					<tbody>
						<tr style="height: 56px;">
							<td id="projectalign" style="padding-left: 0.5em;">
								<div id="projectname">C++
									&#160;<span id="projectnumber">2.0</span>
								</div>
								<div id="projectbrief">My own C++ features</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<?php
				$text = "Generated on Thu Nov 14 2019 13:45:02 for C++ by";
				$text = substr($text, 0, sizeof($text) - 4);
				$tmp = substr($text, 17);
				$tmp = substr($tmp, 0, strpos($tmp, " for"));
				$lastModif = date("l jS \of F Y \a\\t H:i:s", strtotime($tmp));
			?>
		<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/de9/a00176.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">PlayerAbstraction.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="../../da/dec/a00080.php">C++/Entities.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for PlayerAbstraction.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/d4c/a00177.png" border="0" usemap="#PlayerAbstraction_8hpp" alt=""/></div>
<map name="PlayerAbstraction_8hpp" id="PlayerAbstraction_8hpp">
<area shape="rect" id="node2" href="../../da/dec/a00080.php" title="C++/Entities.hpp" alt="" coords="825,80,946,107"/>
<area shape="rect" id="node3" href="../../dc/d57/a00194.php" title="C++/Stone.hpp" alt="" coords="623,155,734,181"/>
<area shape="rect" id="node99" href="../../d5/dcb/a00170.php" title="C++/Plant.hpp" alt="" coords="759,155,865,181"/>
<area shape="rect" id="node102" href="../../d2/df5/a00137.php" title="C++/Mushroom.hpp" alt="" coords="889,155,1028,181"/>
<area shape="rect" id="node103" href="../../dd/dad/a00005.php" title="C++/Ant.hpp" alt="" coords="1053,155,1150,181"/>
<area shape="rect" id="node4" href="../../d9/db6/a00146.php" title="C++/Object.hpp" alt="" coords="685,304,800,331"/>
<area shape="rect" id="node5" href="../../df/d03/a00062.php" title="C++/Contraption.hpp" alt="" coords="717,453,861,480"/>
<area shape="rect" id="node6" href="../../dd/d32/a00041.php" title="C++/C++.hpp" alt="" coords="738,528,841,555"/>
<area shape="rect" id="node7" href="../../da/d24/a00068.php" title="C++/cryptage.hpp" alt="" coords="630,677,757,704"/>
<area shape="rect" id="node96" href="../../df/d98/a00107.php" title="C++/Logger.hpp" alt="" coords="731,603,847,629"/>
<area shape="rect" id="node97" href="../../d4/d51/a00017.php" title="C++/Assert.hpp" alt="" coords="872,603,987,629"/>
<area shape="rect" id="node8" href="../../d1/d09/a00077.php" title="C++/defines.hpp" alt="" coords="735,752,854,779"/>
<area shape="rect" id="node9" href="../../d3/dd5/a00215.php" title="C++/Timer.hpp" alt="" coords="367,827,478,853"/>
<area shape="rect" id="node81" href="../../d4/dee/a00008.php" title="C++/Args.hpp" alt="" coords="503,827,607,853"/>
<area shape="rect" id="node82" href="../../db/db6/a00074.php" title="C++/DateTime.hpp" alt="" coords="577,1125,711,1152"/>
<area shape="rect" id="node85" href="../../d5/de0/a00050.php" title="C++/Clock.hpp" alt="" coords="682,976,793,1003"/>
<area shape="rect" id="node86" href="../../d3/d8b/a00059.php" title="C++/ConsoleTable.hpp" alt="" coords="752,1051,909,1077"/>
<area shape="rect" id="node87" href="../../de/df3/a00185.php" title="C++/Referenced.hpp" alt="" coords="868,901,1012,928"/>
<area shape="rect" id="node88" href="../../d0/dc2/a00104.php" title="C++/IOConfig.hpp" alt="" coords="985,976,1114,1003"/>
<area shape="rect" id="node89" href="../../d4/d3e/a00116.php" title="C++/Map.hpp" alt="" coords="1123,827,1226,853"/>
<area shape="rect" id="node10" href="../../d5/df1/a00206.php" title="C++/Threadable.hpp" alt="" coords="383,901,524,928"/>
<area shape="rect" id="node11" href="../../d4/d3a/a00101.php" title="C++/includes.hpp" alt="" coords="768,1275,893,1301"/>
<area shape="rect" id="node12" href="../../d5/db1/a00140.php" title="C++/NotCopyable.hpp" alt="" coords="211,1349,365,1376"/>
<area shape="rect" id="node13" href="../../d7/dce/a00143.php" title="C++/NotInstantiable.hpp" alt="" coords="389,1349,555,1376"/>
<area shape="rect" id="node14" href="../../dd/dc1/a00212.php" title="C++/timeFunctions.hpp" alt="" coords="579,1349,738,1376"/>
<area shape="rect" id="node16" href="../../d3/db1/a00200.php" title="Used to replace strptime function when compiling for Windows. " alt="" coords="657,1424,767,1451"/>
<area shape="rect" id="node17" href="../../de/db1/a00197.php" title="C++/string.hpp" alt="" coords="657,1499,767,1525"/>
<area shape="rect" id="node19" href="../../de/d79/a00203.php" title="C++/system.hpp" alt="" coords="584,1573,704,1600"/>
<area shape="rect" id="node73" href="../../da/d15/a00188.php" title="C++/RNG.hpp" alt="" coords="728,1573,835,1600"/>
<area shape="rect" id="node75" href="../../d3/d00/a00113.php" title="C++/macro.hpp" alt="" coords="859,1573,973,1600"/>
<area shape="rect" id="node20" href="../../da/d2a/a00086.php" title="C++/errors.hpp" alt="" coords="589,1648,699,1675"/>
<area shape="rect" id="node21" href="../../d9/d2e/a00056.php" title="C++/console.hpp" alt="" coords="515,1723,637,1749"/>
<area shape="rect" id="node71" href="../../db/dab/a00089.php" title="C++/files.hpp" alt="" coords="661,1723,763,1749"/>
<area shape="rect" id="node22" href="../../de/de1/a00065.php" title="C++/convert.hpp" alt="" coords="525,1797,645,1824"/>
<area shape="rect" id="node24" href="../../da/d45/a00011.php" title="C++/array.hpp" alt="" coords="592,1872,699,1899"/>
<area shape="rect" id="node26" href="../../d6/d2d/a00047.php" title="C++/check.hpp" alt="" coords="589,1947,701,1973"/>
<area shape="rect" id="node70" href="../../d9/dd0/a00191.php" title="C++/sorting.hpp" alt="" coords="727,1947,843,1973"/>
<area shape="rect" id="node29" href="../../d9/d01/a00227.php" title="C++/vector.hpp" alt="" coords="730,2021,843,2048"/>
<area shape="rect" id="node64" href="../../dc/dee/a00053.php" title="C++/collides.hpp" alt="" coords="585,2021,706,2048"/>
<area shape="rect" id="node30" href="../../d2/de7/a00014.php" title="C++/arraysIncludes.hpp" alt="" coords="751,2096,913,2123"/>
<area shape="rect" id="node37" href="../../db/dd9/a00179.php" title="C++/pointers.hpp" alt="" coords="713,2395,836,2421"/>
<area shape="rect" id="node38" href="../../dd/d52/a00221.php" title="C++/types.hpp" alt="" coords="612,2469,721,2496"/>
<area shape="rect" id="node40" href="../../d3/d52/a00023.php" title="Big.hpp" alt="" coords="633,2544,700,2571"/>
<area shape="rect" id="node59" href="../../dc/d9a/a00218.php" title="C++/Tree.hpp" alt="" coords="506,2544,609,2571"/>
<area shape="rect" id="node60" href="../../d7/d25/a00182.php" title="PureVirtual.hpp" alt="" coords="725,2544,835,2571"/>
<area shape="rect" id="node61" href="../../d5/ddf/a00224.php" title="UsefullDefines.hpp" alt="" coords="860,2544,993,2571"/>
<area shape="rect" id="node41" href="../../da/d1e/a00149.php" title="C++/OsDetection.hpp" alt="" coords="322,2619,473,2645"/>
<area shape="rect" id="node55" href="../../d5/d16/a00029.php" title="C++/Big_Constructor.hpp" alt="" coords="1035,2619,1205,2645"/>
<area shape="rect" id="node56" href="../../d4/d8c/a00035.php" title="C++/Big_Operator.hpp" alt="" coords="497,2619,650,2645"/>
<area shape="rect" id="node57" href="../../d6/d5b/a00026.php" title="C++/Big_Comparison.hpp" alt="" coords="675,2619,848,2645"/>
<area shape="rect" id="node58" href="../../dc/d87/a00032.php" title="C++/Big_Maths.hpp" alt="" coords="872,2619,1011,2645"/>
<area shape="rect" id="node43" href="../../d4/d81/a00110.php" title="C++/lowIncludes.hpp" alt="" coords="391,2693,537,2720"/>
<area shape="rect" id="node65" href="../../df/dc8/a00122.php" title="C++/Matrix.hpp" alt="" coords="494,2096,607,2123"/>
<area shape="rect" id="node66" href="../../d1/dc1/a00092.php" title="C++/Fraction.hpp" alt="" coords="419,2171,543,2197"/>
<area shape="rect" id="node67" href="../../df/d6a/a00119.php" title="C++/maths.hpp" alt="" coords="425,2245,538,2272"/>
<area shape="rect" id="node68" href="../../d8/d41/a00038.php" title="C++/Binary.hpp" alt="" coords="671,2320,785,2347"/>
<area shape="rect" id="node83" href="../../d0/d89/a00071.php" title="C++/Date.hpp" alt="" coords="622,1200,727,1227"/>
<area shape="rect" id="node84" href="../../d3/de5/a00209.php" title="C++/Time.hpp" alt="" coords="491,1200,597,1227"/>
<area shape="rect" id="node90" href="../../d6/db8/a00158.php" title="C++/PathfindingAlgorithms.hpp" alt="" coords="1109,901,1313,928"/>
<area shape="rect" id="node91" href="../../d6/d7d/a00161.php" title="C++/PathfindingDijkstra.hpp" alt="" coords="1139,976,1325,1003"/>
<area shape="rect" id="node92" href="../../d3/df8/a00155.php" title="C++/Pathfinding.hpp" alt="" coords="1161,1051,1303,1077"/>
<area shape="rect" id="node93" href="../../dc/de6/a00167.php" title="C++/PathfindingProblem.hpp" alt="" coords="1137,1125,1327,1152"/>
<area shape="rect" id="node94" href="../../db/ddf/a00164.php" title="C++/PathfindingException.hpp" alt="" coords="1163,1200,1363,1227"/>
<area shape="rect" id="node95" href="../../d7/d9a/a00152.php" title="C++/Path.hpp" alt="" coords="1035,1200,1139,1227"/>
<area shape="rect" id="node98" href="../../db/db2/a00020.php" title="C++/AssertionException.hpp" alt="" coords="833,677,1023,704"/>
<area shape="rect" id="node100" href="../../d1/da8/a00230.php" title="C++/Vegetal.hpp" alt="" coords="787,229,909,256"/>
<area shape="rect" id="node101" href="../../d2/d1f/a00083.php" title="C++/Entity.hpp" alt="" coords="793,379,903,405"/>
<area shape="rect" id="node104" href="../../d7/d46/a00002.php" title="C++/Animal.hpp" alt="" coords="1005,229,1123,256"/>
<area shape="rect" id="node105" href="../../d9/d77/a00095.php" title="C++/Hostile.hpp" alt="" coords="945,304,1063,331"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d90/a00178.png" border="0" usemap="#PlayerAbstraction_8hppdep" alt=""/></div>
<map name="PlayerAbstraction_8hppdep" id="PlayerAbstraction_8hppdep">
<area shape="rect" id="node2" href="../../d7/d3f/a00173.php" title="Player.hpp" alt="" coords="39,80,123,107"/>
<area shape="rect" id="node3" href="../../d5/df9/a00044.php" title="C++Entities.hpp" alt="" coords="22,155,139,181"/>
</map>
</div>
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d16/a01060.php">mcd::PlayerAbstraction&lt; PlayerParent &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A player that can be a child from any class.  <a href="../../d5/d16/a01060.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:da/d2e/a00238"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d2e/a00238.php">mcd</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>Last modification : September, 26 2019 </dd></dl>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.11-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
	<ul>
		<li class="navelem"><a class="el" href="../../dir_bfccd401955b95cf8c75461437045ac0.php">inc</a></li><li class="navelem"><a class="el" href="../../dir_2ce2ad1ea5ded593884489da6d66e532.php">C++</a></li><li class="navelem"><a class="el" href="../../d5/de9/a00176.php">PlayerAbstraction.hpp</a></li>
		<li class="footer">
			<?php
				echo $text;
			?>
		</li>
	</ul>
</div>
</body>
</html>
